ProdIND/ProdPrograms/force-app/main/default/objects/Customer_Dedupe_Response__c/Customer_Dedupe_Response__c.object-meta.xml
<CustomObject>
    <label>Customer Dedupe Response</label>
    <nameField>
        <displayFormat>CDR-{000000}</displayFormat>
        <label>Customer Dedupe Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Dedupe Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Customer_Dedupe_Response__c/fields/CIC_No__c.field-meta.xml
<CustomField>
    <fullName>CIC_No__c</fullName>
    <label>CIC No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/IND_ExternalDedupeStatusAPIRequest.cls
public class IND_ExternalDedupeStatusAPIRequest extends ParentAPIRequest{
    public  String CIC_No = '';
    public IND_ExternalDedupeStatusAPIRequest(Customer_Dedupe_Response__c cdr, String loanAppId){
        this.CIC_No = cdr.CIC_No__c;
        validate(System.Label.DedupeStatus);
    }   

    public override boolean validate(String serviceName){
        if(String.isBlank(this.CIC_No)){
          throw new IND_Exception(System.Label.CICNo);
        }
        return true;
    }

    public override Map<String,String> getHttpRequestHeaders(){
        //Map to store HTTP request header data
        Map<String,String> requestHeaderMap = Utilities.getHeaders();
        return requestHeaderMap;
        //requestheadermap is used to fetch the request from client
    }
}