ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/Deal_Number__c.object-meta.xml
<CustomObject>
    <description>The custom object created for Deal Number generation</description>
    <label>Deal Number</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <formula>DNField1__c  +  DNField2__c  +  ProductCode__c  +  DNField3__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal Number</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Request</fullName>
            </value>
            <value>
                <fullName>RC Upload</fullName>
            </value>
            <value>
                <fullName>Business Payment Details</fullName>
            </value>
            <value>
                <fullName>Insurance Details</fullName>
            </value>
            <value>
                <fullName>New/Used Vehicle Details</fullName>
            </value>
            <value>
                <fullName>Beneficiary Details</fullName>
            </value>
            <value>
                <fullName>Key Fact Statement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Seller&apos;s Passbook</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Bank Statement</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Cancel Cheque</fullName>
            </value>
            <value>
                <fullName>Driving Licence</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Voter Id</fullName>
            </value>
            <value>
                <fullName>Form 60</fullName>
            </value>
            <value>
                <fullName>Customer Image</fullName>
            </value>
            <value>
                <fullName>Aadhaar</fullName>
            </value>
            <value>
                <fullName>Vehicle Images</fullName>
            </value>
            <value>
                <fullName>RC Document</fullName>
            </value>
            <value>
                <fullName>SPR</fullName>
            </value>
            <value>
                <fullName>APR</fullName>
            </value>
            <value>
                <fullName>Electronic Bill</fullName>
                <label>Electricity Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Water Bill</fullName>
                <label>Water Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Vehicle Insurance Policy</fullName>
            </value>
            <value>
                <fullName>Vehicle Image</fullName>
            </value>
            <value>
                <fullName>Bank Statement</fullName>
            </value>
            <value>
                <fullName>Insurance Policy Doc</fullName>
            </value>
            <value>
                <fullName>Valuation Report</fullName>
            </value>
            <value>
                <fullName>Office FI</fullName>
            </value>
            <value>
                <fullName>Land Photo</fullName>
            </value>
            <value>
                <fullName>Patta Document</fullName>
            </value>
            <value>
                <fullName>Rent Agreement/Reciept</fullName>
            </value>
            <value>
                <fullName>Pension Document</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Engine Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Chassis Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Selfie with Vehicle-uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Post Payments Request RC</fullName>
            </value>
            <value>
                <fullName>RC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/is_Active__c.field-meta.xml
<CustomField>
    <fullName>is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Opportunity_Relation__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Relation__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>Vehicle_Detail__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/LoanDisbursementDetails__c/LoanDisbursementDetails__c.object-meta.xml
<CustomObject>
    <label>LoanDisbursementDetails</label>
    <nameField>
        <label>LoanDisbursementDetails  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LoanDisbursementDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/LoanDisbursementDetails__c/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Number</label>
    <referenceTo>Deal_Number__c</referenceTo>
    <relationshipLabel>LoanDisbursementDetails</relationshipLabel>
    <relationshipName>LoanDisbursementDetails</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/LoanDisbursementDetails__c/fields/Parent_Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Parent_Loan_Application__c</fullName>
    <label>Parent Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>LoanDisbursementDetails</relationshipLabel>
    <relationshipName>LoanDisbursementDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/LoanDisbursementDetails__c/fields/RC_Document__c.field-meta.xml
<CustomField>
    <fullName>RC_Document__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RC Document</label>
    <referenceTo>Documents__c</referenceTo>
    <relationshipLabel>LoanDisbursementDetails (RC Document)</relationshipLabel>
    <relationshipName>LoanDisbursementDetails1</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/LoanDisbursementDetails__c/fields/Registration_Format__c.field-meta.xml
<CustomField>
    <fullName>Registration_Format__c</fullName>
    <label>Registration Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Old</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/LoanDisbursementDetails__c/fields/Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Registration_Number__c</fullName>
    <label>Registration Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/LoanDisbursementDetails__c/fields/Registration_Owner_Nam__c.field-meta.xml
<CustomField>
    <fullName>Registration_Owner_Nam__c</fullName>
    <label>Registration Owner Nam</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <description>IndusInd deal number</description>
    <label>Deal Number</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Parent_Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Parent_Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Revoked parent application</description>
    <label>Parent Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Payment_Request_Generation_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request_Generation_Date__c</fullName>
    <label>Payment Request Generation Date</label>
    <type>DateTime</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/Vehicle_Detail__c.object-meta.xml
<CustomObject>
    <label>Vehicle Detail</label>
    <nameField>
        <displayFormat>VD-{00000}</displayFormat>
        <label>Vehicle Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Number</label>
    <referenceTo>Deal_Number__c</referenceTo>
    <relationshipLabel>Vehicle Details</relationshipLabel>
    <relationshipName>Vehicle_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <description>Vehicle Insurance and Vehicle Valuation data</description>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Vehicle_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Vehicle_type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_type__c</fullName>
    <label>Vehicle type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/classes/GenericUploadController.cls
public with sharing class GenericUploadController {

    @AuraEnabled
    public static Opportunity checkPaymentRequest(string loanApplicationId, String dealId){
        try {
            if(loanApplicationId != null) {
            List<Opportunity> oppList = [Select Id , Payment_Request_Generation_Date__c,(Select id from Vehicle_Details__r WHERE Deal_Number__c =: dealId) FROM Opportunity where Id =: loanApplicationId];
                if(oppList.size()>0){
                    return oppList[0];
                }
                
            }
            return null;
        } catch( Exception e) {
            ErrorLoggerUtil.logErrorEvent('GenericUploadController', 'checkPaymentRequest', '', e);
            throw new AuraHandledException(e.getMessage());
        }
    }

    /*
    * @Method Name: getRelatedFileByRecordId
    * @Created by:  Kruthi Nadig
    * @description: to get version data of file
    * @Param:       String contentversion Id
    */
    @AuraEnabled
    public static string getRelatedFileByRecordId(string contentVersionId) {
        ContentVersion conv = [Select Id,versionData from ContentVersion where Id = :contentVersionId];
        return EncodingUtil.base64Encode(conv.versionData);
    }
    
    /*
    * @Method Name: checkRCDocument
    * @Created by:  Kruthi Nadig
    * @description: to check if RC Document already exists
    * @Param:       String Loan Application Id, String Applicant Id
    */
    @AuraEnabled
    public static String checkRCDocument(string loanApplicationId,string applicantId, String dealId){
        if(loanApplicationId != NULL){
            Opportunity oppObj = [Select Id,Vehicle_Type__c, Product_Type__c from Opportunity Where Id=:loanApplicationId];
            string docName;
            if(oppObj.Vehicle_Type__c == 'New'){
                docName = 'RC';
            }else if(oppObj.Vehicle_Type__c == 'Used' || oppObj.Vehicle_Type__c == 'Refinance'){
                docName = 'Post Payments Request RC';
            }
            list<Documents__c> doclist = new list<Documents__c>();
            if(oppObj.Product_Type__c == System.Label.Tractor){
                List<Vehicle_Detail__c> VehicleLst = [SELECT Id FROM Vehicle_Detail__c WHERE Deal_Number__c =: dealId WITH SECURITY_ENFORCED];
                doclist = [SELECT Id 
                            FROM Documents__c 
                            WHERE Document_Type__c = :docName AND Opportunity_Relation__c = :loanApplicationId AND Applicant__c =:applicantId AND Is_Active__c = true AND Vehicle_Detail__c =: VehicleLst[0].Id
                            WITH SECURITY_ENFORCED];
            }else{
                doclist = [SELECT Id 
                            FROM Documents__c 
                            WHERE Document_Type__c = :docName AND Opportunity_Relation__c = :loanApplicationId AND Applicant__c =:applicantId AND Is_Active__c = true 
                            WITH SECURITY_ENFORCED];
            }

            if(!doclist.isEmpty()) {
                List<ContentDocumentLink> contentDocumentLinkList = new List<ContentDocumentLink>();
                contentDocumentLinkList =[SELECT id, contentdocumentid, linkedentity.name, linkedentityid FROM ContentDocumentLink WHERE linkedentityid =: doclist[0].Id ];
                if(contentDocumentLinkList.isEmpty()){
                    return null;
                }else{
                    return doclist[0].Id;
                }
            } else {
                return null;
            }
        }else{
            return null;
        }
    }

    /*
    * @Method Name: clearRCDocument
    * @Created by:  Kruthi Nadig
    * @description: clear the values in RC
    * @Param:       String Loan Disbursement Id
    */
    @AuraEnabled
    public static void clearRCDocument(string loanDisbursementId){
        try {
            if(loanDisbursementId != null) {
            update new LoanDisbursementDetails__c(Id=loanDisbursementId,Registration_Date__c=null,Registration_Format__c='',Registration_Number__c='',Registration_Owner_Nam__c='',RC_Document__c=null);
            }
        } catch( Exception e) {
            ErrorLoggerUtil.logErrorEvent('GenericUploadController', 'clearRCDocument', '', e);
            throw new AuraHandledException(e.getMessage());
        }
    }

    /*
    * @Method Name: fetchDisbursementRecord
    * @Created by:  Kruthi Nadig
    * @description: to fetch disbursement recordId
    * @Param:       String Loan Application Id, String Applicant Id
    */
    @AuraEnabled
    public static LoanDisbursementDetails__c fetchDisbursementRecord(string loanApplicationId,string applicantId, String dealId){
        try {
            Opportunity oppRec = [SELECT Id, Product_Type__c FROM Opportunity WHERE Id =:loanApplicationId WITH SECURITY_ENFORCED];
            list<LoanDisbursementDetails__c> disbList = new list<LoanDisbursementDetails__c>();
            if(oppRec.Product_Type__c == System.Label.Tractor){
                disbList = [SELECT Id,Parent_Loan_Application__r.Vehicle_Type__c 
                                FROM LoanDisbursementDetails__c 
                                WHERE Parent_Loan_Application__c = :loanApplicationId AND Deal_Number__c =: dealId
                                WITH SECURITY_ENFORCED];
            }else{
                disbList = [SELECT Id,Parent_Loan_Application__r.Vehicle_Type__c 
                                FROM LoanDisbursementDetails__c 
                                WHERE Parent_Loan_Application__c = :loanApplicationId 
                                WITH SECURITY_ENFORCED];
            }
            if(!disbList.isEmpty()) {
                return disbList[0];
            } else {
                return null;
            }
        } catch( Exception e) {
            ErrorLoggerUtil.logErrorEvent('GenericUploadController', 'fetchDisbursementRecord', '', e);
            throw new AuraHandledException(e.getMessage());
        }
    }

    /*
    * @Method Name: deleteContentDocument
    * @Created by:  Kruthi Nadig
    * @description: to delete the content document
    * @Param:       String - Document ID
    */
    @AuraEnabled
    public static String deleteContentDocument(String docIds){
        try{
            ContentDocumentLink conLink = [SELECT ContentDocumentId FROM ContentDocumentLink WHERE Id=:docIds WITH SECURITY_ENFORCED];
            delete new ContentDocument(Id = conLink.ContentDocumentId);
            if(Test.isRunningTest())
            {
                throw new AuraHandledException(System.Label.ExceptionMessage);
            }
            return 'SUCCESS';
           
        }
        catch(Exception e){
            ErrorLoggerUtil.logErrorEvent('GenericUploadController', 'deleteContentDocument', '', e);
            throw new AuraHandledException(e.getMessage());
        }
    }

    /*
    * @Method Name: createOtherDocument
    * @Created by:  Kruthi Nadig
    * @description: to create a Document object for 'Other documents'
    * @Param:       String - Document Type
    * @Param:       String - current Vehicle Record ID
    * @Param:       String - Loan Applicant ID
    * @Return:      String - loanApplication ID
    */
	@AuraEnabled
    public static string createOtherDocument(String docType,String vehicleDetailId,String applicantId,String loanApplicationId){
         try {  
                string leadNo;
                list<Documents__c> docUpdList = new list<Documents__c>();
                ID otherDocRecordTypeId = Schema.SObjectType.Documents__c.getRecordTypeInfosByName().get('Other Documents').getRecordTypeId();
                if(loanApplicationId!=null ){
                   list<Opportunity> loanApp= [Select Name from Opportunity where Id =: loanApplicationId WITH SECURITY_ENFORCED];
                   if(!loanApp.isEmpty()) {
                       leadNo = loanApp[0].Name;
                       //Deactivate existing Document, if any                      
                       for(Documents__c doc : [Select Id from Documents__c where Document_Type__c = :docType and Opportunity_Relation__c = :loanApplicationId and Applicant__c =:applicantId and Vehicle_Detail__c =: vehicleDetailId WITH SECURITY_ENFORCED]) {
                            doc.is_Active__c = false;
                            docUpdList.add(doc);
                       }
                   }
                   if(!docUpdList.isEmpty()) {
                        update docUpdList;
                   }   
                   Documents__c docObject= new Documents__c(Name = docType+' '+leadNo,Vehicle_Detail__c=vehicleDetailId,Applicant__c=applicantId,Opportunity_Relation__c=loanApplicationId,Document_Type__c=docType,is_Active__c = true);
                    System.debug('docObject'+docObject);
                   docObject.RecordTypeId = otherDocRecordTypeId;
                   if (Schema.sObjectType.Documents__c.isCreateable()){
                    	insert docObject;
                   }
                   if(Test.isRunningTest())
                   {
                      throw new AuraHandledException(System.Label.ExceptionMessage);
                   }
                   return docObject.Id;
                }
                 return null;
              } catch(Exception e){
                    ErrorLoggerUtil.logErrorEvent('GenericUploadController', 'createOtherDocument ', System.Label.Apex, e);
            		throw new AuraHandledException(e.getMessage() + ' ' + e.getStackTraceString());  
              }

    }

    /*
    * @Method Name: changeFilename
    * @Created by:  Kruthi Nadig
    * @description: to change the file name
    * @Param:       String - contentDocumentId
    */
	@AuraEnabled
    public static void changeFilename(string contentDocId,string fname) {
         ContentDocument conDoc = [select id,Title from ContentDocument where Id=:contentDocId]; // Getting files from Parent record 
        conDoc.Title = fname;  
        try{  
        update conDoc;  
        }  
        catch(Exception e){  
            ErrorLoggerUtil.logErrorEvent('GenericUploadController', 'changeFilename ', System.Label.Apex, e);
            throw new AuraHandledException(e.getMessage() + ' ' + e.getStackTraceString());
        }  
    }
    
     
    /*
    * @Method Name: getContentVersion
    * @Created by:  Poonam Tilokani
    * @description: to get content version
    * @Param:       String - contentDocumentId
    */
    
     @AuraEnabled
    public static List<ContentVersion> getContentVersion(String conDocId){
        try{
            List<ContentVersion> conVerList = [SELECT Id, VersionData, FileType, Title, FileExtension,IsLatest, 
                                                     ContentDocumentId, ContentDocument.FileType
                                                    FROM   ContentVersion 
                                                    WHERE  ContentDocumentId =: conDocId and IsLatest = true];
            if(conVerList.size()>0){
                return conVerList;
            }
            return null;
            
        }catch(Exception e){
            ErrorLoggerUtil.logErrorEvent('GenericUploadController', 'getContentVersion', System.Label.Apex, e);
            throw new IND_Exception(e.getMessage()); 
        }
    }
    /*
    * @Method Name: getProfileName
    * @Created by:  Poonam Tilokani
    * @description: to get profile name
    * @Param:       String - Loan application Id
    */
    @AuraEnabled
    public static Boolean getProfileName(String loanApplicationId){
        try{                   
            User Usr =[SELECT Id,profileId,profile.name,userType FROM User WHERE Id = : UserInfo.getUserId()];
            if(Usr.userType == 'PowerPartner'){
                return true;
            }else{
                return false;
            }
        }
        catch(Exception e){
            ErrorLoggerUtil.logErrorEvent('GenericUploadController', 'getProfileName', System.Label.Apex, e);
            throw new IND_Exception(e.getMessage()); 
        }
    }

    /*
    * @Method Name: fetchLoanApplicationSubStage
    * @Created by:  Gaurav Rawat
    * @description: to fetch the loan application sub stage
    * @Param:       String - Loan application Id
    */
    @AuraEnabled
    public static Boolean fetchLoanApplicationSubStage(String loanApplicationId){
        Boolean isSubStageRC = false;
        try{
            List<Opportunity> oppList = new List<Opportunity>([SELECT Id,Sub_Stage__c FROM Opportunity WHERE Id = : loanApplicationId WITH SECURITY_ENFORCED LIMIT 1]);
            for(Opportunity opp : oppList){
                if(opp.Sub_Stage__c == System.Label.RC_Disbursement_Substage){
                    isSubStageRC = true;
                }
            }
            return isSubStageRC;
        }
        catch(Exception e){
            ErrorLoggerUtil.logErrorEvent('GenericUploadController', 'fetchLoanApplicationSubStage', System.Label.Apex, e, loanApplicationId);
            throw new IND_Exception(e.getMessage()); 
        }
    }
    @AuraEnabled
    public static void otherFilesDeleted(string contentDocId, String documentId){
        try{
            if(documentId != null && contentDocId != null){
               List<ContentDocumentLink> conLinkList = [Select Id,ContentDocumentId,LinkedEntityId from ContentDocumentLink where LinkedEntityId =: documentId AND ContentDocumentId !=: contentDocId ];
               if(conLinkList.size()>0){
                   delete conLinkList;
               }
                    
            }

        }catch(Exception e){
            ErrorLoggerUtil.logErrorEvent('GenericUploadController', 'otherFilesDeleted ', System.Label.Apex, e);
            throw new AuraHandledException(e.getMessage() + ' ' + e.getStackTraceString());
        }
    }
}