ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/Final_Term__c.object-meta.xml
<CustomObject>
    <description>To store Final term module data.</description>
    <label>Final Term</label>
    <nameField>
        <displayFormat>FT-{000000}</displayFormat>
        <label>Final Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan_Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Final_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Referrer_Ben_Code__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Ben_Code__c</fullName>
    <label>Referrer Ben Code</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Referrer_Name__c.field-meta.xml
<CustomField>
    <fullName>Referrer_Name__c</fullName>
    <label>Referrer Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/classes/DSA_Batch_DisbursedLead.cls
public class DSA_Batch_DisbursedLead implements Database.Batchable<sObject>{
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        string FTQuery='SELECT Id, Name, Referrer_Ben_Code__c, Referrer_Name__c, Loan_Application__c  FROM Final_Term__c Where Referrer_Ben_Code__c !=null';
        return Database.getQueryLocator(FTQuery);
    }
    public void execute(Database.BatchableContext bc, List<Final_Term__c> LoanData){
        // process each batch of records
        Set<String> Bencode =new Set<String>();
        Map<Id,String> OppANDBencode =new Map<Id,String>();
        List<OpportunityShare> lstOpp = new List<OpportunityShare>();
        try{
            for(Final_Term__c ft : LoanData){
                Bencode.add(ft.Referrer_Ben_Code__c);
                OppANDBencode.put(ft.Loan_Application__c,ft.Referrer_Ben_Code__c);
            }
            system.debug('OppANDBencode-->'+JSON.serializePretty(OppANDBencode));
            List<User> DSAUser = [Select Id, name, employeenumber,Profile.Name from User where employeenumber IN: Bencode AND Profile.Name='DSA Community User'];
            system.debug('DSAUser-->'+JSON.serializePretty(DSAUser));
            for(Id loanid: OppANDBencode.keySet()){
                for(User u : DSAUser){
                    if(OppANDBencode.get(loanid) == u.employeenumber){
                        OpportunityShare ObjOppSh = new OpportunityShare();
                        ObjOppSh.OpportunityId = loanid;
                        ObjOppSh.UserOrGroupId = u.Id;
                        ObjOppSh.OpportunityAccessLevel = 'Edit';
                        ObjOppSh.RowCause= 'Manual';
                        lstOpp.add(ObjOppSh);
                    }
                }
            }
            
            insert lstOpp;
        }
        catch (Exception e) {
            ErrorLoggerUtil.logErrorEvent('DSA_Batch_DisbursedLead', 'execute', 'Apex', e);
        }
    }
    public void finish(Database.BatchableContext bc){
        
    }
    
}