ProdIND/ProdPrograms/force-app/main/default/objects/DealNumber_Setting__mdt/DealNumber_Setting__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata created for Deal Number generation</description>
    <label>Deal Number</label>
    <pluralLabel>Deal Numbers</pluralLabel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/DealNumber_Setting__mdt/fields/MDNField2__c.field-meta.xml
<CustomField>
    <fullName>MDNField2__c</fullName>
    <description>MDNField2</description>
    <label>MDNField2</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/Maker_Id__c.field-meta.xml
<CustomField>
    <fullName>Maker_Id__c</fullName>
    <label>Maker Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC - Copy/force-app/main/default/classes/CustomMetadataUtilsTest.cls
@isTest
public class CustomMetadataUtilsTest {
    
    @isTest
    public static void verifyCreateCustomMetadata(){
        //create user
        Profile p = [SELECT Id FROM Profile WHERE Name='IBL CVO'];
        User u = new User(Alias = 'standt2', Email='standarduser2@testorg.com',MobilePhone = '9999999999',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,Maker_Id__c='12',IsActive = true,
                          TimeZoneSidKey='America/Los_Angeles',UserName='test1_userprod123@indusbank.com');
        insert u;
        System.runAs(u) 
        {
            Map<String, Object> metadataFieldValueMap = new  Map<String, Object>();
            metadataFieldValueMap.put('MDNField2__c', '9');
            CustomMetadataUtils.createCustomMetadata('DealNumber_Setting__mdt', 'Deal Number', metadataFieldValueMap);
            CustomMetadataUtils.updateCustomMetadata('DealNumber_Setting__mdt', 'Deal_Number', 'Deal Number', metadataFieldValueMap);
            System.assert(metadataFieldValueMap != null);
        }
    }
}