ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Application_Consent_Received__c.field-meta.xml
<CustomField>
    <fullName>Application_Consent_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Application Consent Received</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Application_Consent_SMS_Sent_Time__c.field-meta.xml
<CustomField>
    <fullName>Application_Consent_SMS_Sent_Time__c</fullName>
    <label>Application Consent Received Time</label>
    <type>DateTime</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Application_Form_SMS_Sent__c.field-meta.xml
<CustomField>
    <fullName>Application_Form_SMS_Sent__c</fullName>
    <label>Application Form SMS Sent</label>
    <type>DateTime</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Consent_Received__c.field-meta.xml
<CustomField>
    <fullName>Consent_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Consent Received</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Consent_Sent__c.field-meta.xml
<CustomField>
    <fullName>Consent_Sent__c</fullName>
    <label>Consent Sent</label>
    <type>DateTime</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Insurance_Consent_OTP_Time__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Consent_OTP_Time__c</fullName>
    <label>Insurance Consent OTP Time</label>
    <type>DateTime</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Insurance_Consent_Received__c.field-meta.xml
<CustomField>
    <fullName>Insurance_Consent_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Insurance Consent Received?</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Insurance_consent_sent_on__c.field-meta.xml
<CustomField>
    <fullName>Insurance_consent_sent_on__c</fullName>
    <label>Insurance Consent Received Time</label>
    <type>DateTime</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/ApplicantConsentHandler.cls
public class ApplicantConsentHandler {
    public static void updateConsentReceived(List<Applicant__c> newApplicants, List<Applicant__c> oldApplicants) {
        List<Applicant__c> applicantsToUpdate = new List<Applicant__c>();

        for (Integer i = 0; i < newApplicants.size(); i++) {
            Applicant__c newApplicant = newApplicants[i];
            Applicant__c oldApplicant = oldApplicants[i];

            if ((newApplicant.Consent_Sent__c != null && oldApplicant.Consent_Sent__c == null) || (newApplicant.Consent_Sent__c != oldApplicant.Consent_Sent__c)) {
                Applicant__c updatedApplicant = new Applicant__c(Id = newApplicant.Id);
                updatedApplicant.Consent_Received__c = true; // Update the flag
                applicantsToUpdate.add(updatedApplicant);
            }
            if ((newApplicant.Application_Form_SMS_Sent__c != null && oldApplicant.Application_Form_SMS_Sent__c == null) || (newApplicant.Application_Form_SMS_Sent__c != oldApplicant.Application_Form_SMS_Sent__c)) {
                Applicant__c applicationConsent = new Applicant__c(Id = newApplicant.Id);
                applicationConsent.Application_Consent_Received__c = true; 
                applicationConsent.Application_Consent_SMS_Sent_Time__c = DateTime.now();
                applicantsToUpdate.add(applicationConsent);
            }
            if ((newApplicant.Insurance_Consent_OTP_Time__c != null && oldApplicant.Insurance_Consent_OTP_Time__c == null) || (newApplicant.Insurance_Consent_OTP_Time__c  != oldApplicant.Insurance_Consent_OTP_Time__c) ) {
                Applicant__c applicationConsentInsurance = new Applicant__c(Id = newApplicant.Id);
                applicationConsentInsurance.Insurance_Consent_Received__c = true; 
                applicationConsentInsurance.Insurance_consent_sent_on__c = DateTime.now();
                applicantsToUpdate.add(applicationConsentInsurance);
            }
            
        }

        if (!applicantsToUpdate.isEmpty()) {
            update applicantsToUpdate;
        }
    }
}