ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Consent_Received__c.field-meta.xml
<CustomField>
    <fullName>Consent_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Consent Received</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Consent_Sent__c.field-meta.xml
<CustomField>
    <fullName>Consent_Sent__c</fullName>
    <label>Consent Sent</label>
    <type>DateTime</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/OTP_for_borrower__c.field-meta.xml
<CustomField>
    <fullName>OTP_for_borrower__c</fullName>
    <label>OTP for borrower</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Register_for_WhatsApp_Banking__c.field-meta.xml
<CustomField>
    <fullName>Register_for_WhatsApp_Banking__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Register for WhatsApp Banking</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Consent_Received__c.field-meta.xml
<CustomField>
    <fullName>Consent_Received__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Consent Received</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Consent_Sent__c.field-meta.xml
<CustomField>
    <fullName>Consent_Sent__c</fullName>
    <label>Consent Sent</label>
    <type>DateTime</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/OTP_for_borrower__c.field-meta.xml
<CustomField>
    <fullName>OTP_for_borrower__c</fullName>
    <label>OTP for borrower</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/VfPageContent__mdt/VfPageContent__mdt.object-meta.xml
<CustomObject>
    <label>VfPageContent</label>
    <pluralLabel>VfPageContent</pluralLabel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/VfPageContent__mdt/fields/WspNotRegistered__c.field-meta.xml
<CustomField>
    <fullName>WspNotRegistered__c</fullName>
    <label>WspNotRegistered</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/VfPageContent__mdt/fields/WspRegisteredContent__c.field-meta.xml
<CustomField>
    <fullName>WspRegisteredContent__c</fullName>
    <label>WspRegisteredContent</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/DateTimeHandleTest.cls
/**
* @author Ruchi Jain
* @company Persistent Systems
* @description A  Test class for the DateTimeHandle class
* Inputs: None
* History:
* 27/10/2021 Ruchi Jain
*/
@isTest
public class DateTimeHandleTest {
    
    @testSetup static void setup() {
         Account testAccount = TestDataUtility.createTestAccount(true);
            
            Opportunity oppObj = TestDataUtility.createTestOpportunity(false);
            oppObj.AccountId = testAccount.Id;
            insert oppObj;
         Applicant__c applicantObj = TestDataUtility.createTestApplicant(false);
            applicantObj.Opportunity__c= oppObj.Id;
            applicantObj.Consent_Received__c=true;
        	applicantObj.OTP_for_borrower__c='19333';
            applicantObj.Consent_Sent__c=DateTime.valueOf(DateTime.now().getTime()-4);
            insert applicantObj;
         Applicant__c applicantObj1 = TestDataUtility.createTestApplicant(false);
            applicantObj1.Opportunity__c= oppObj.Id;
            applicantObj1.Consent_Received__c=false;
        	applicantObj1.OTP_for_borrower__c='19393';
            applicantObj1.Register_for_WhatsApp_Banking__c=true;
            applicantObj1.Consent_Sent__c=DateTime.valueOf(DateTime.now().getTime()-27248698);
            insert applicantObj1;
    }
    
    //Test method enableCheckboxTest 
    @isTest
    static  void enableCheckboxTest() {
        try{
            Applicant__c app=[Select Id,OTP_for_borrower__c from Applicant__c limit 1];
            app.Register_for_WhatsApp_Banking__c = true;
            update app;
            PageReference testPage = Page.AcceptConsent; 
            Test.setCurrentPage(testPage);
            testPage.getParameters().put('id', String.valueOf(app.Id));
            testPage.getParameters().put('otp', String.valueOf(app.OTP_for_borrower__c));
            
            ApexPages.StandardController stdSetController = new ApexPages.StandardController(app);
            
            Test.startTest();
            DateTimeHandle ext = new DateTimeHandle(stdSetController); 
            ext.enableCheckbox();
            
            system.assertEquals(true,app.Consent_Received__c);
            Test.stopTest();
        }Catch(Exception e){
            system.assertEquals('Script-thrown exception', e.getMessage());
        }
        
        
    }
    
   @isTest
    static  void dosentenableCheckboxTest() {
        try{
           Applicant__c app=[Select Id,Consent_Sent__c,OTP_for_borrower__c from Applicant__c where Consent_Received__c=false  limit 1];
            system.debug('time'+(app.Consent_Sent__c.getTime())/60000);
            PageReference testPage = Page.AcceptConsent; 
            Test.setCurrentPage(testPage);
            testPage.getParameters().put('id', String.valueOf(app.Id));
            testPage.getParameters().put('otp', String.valueOf(app.OTP_for_borrower__c));

            
            ApexPages.StandardController stdSetController = new ApexPages.StandardController(app);
            
            Test.startTest();
            DateTimeHandle ext = new DateTimeHandle(stdSetController); 
            ext.vfMetadata = [select id,WspNotRegistered__c,WspRegisteredContent__c from VfPageContent__mdt where Label ='BodyContent'];
            ext.enableCheckbox();
            Test.stopTest();
            
            system.assertEquals(false,app.Consent_Received__c);
        }Catch(Exception e){
            system.assertEquals('Script-thrown exception', e.getMessage());
        }
        
    }
}