ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Lead_Number__c.field-meta.xml
<CustomField>
    <fullName>Lead_Number__c</fullName>
    <formula>Opportunity__r.Lead_number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Id</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Lead_number__c.field-meta.xml
<CustomField>
    <fullName>Lead_number__c</fullName>
    <label>Lead Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC - Copy/force-app/main/default/classes/IND_EmailServiceService_Test.cls
/*------------------------------------------------------------
Author:        Satyam More
Company:       Persistent Systems
Description:   Test class created to validate the IND_EmailServiceRequest IND_EmailServiceService IND_EmailServiceResponse class
History
Date            Author              Comments
-------------------------------------------------------------
03-01-2022      Satyam More       Created
------------------------------------------------------------*/
@isTest(SeeAllData=false)
public class IND_EmailServiceService_Test {
@isTest
    public static void testEmailServiceService(){
        
        try{   
            
            Opportunity opp = TestDataUtility.createTestOpportunityforRunEmiEngineApi(false);
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            Applicant__c applicant = TestDataUtility.createTestApplicant(false);
            applicant.Opportunity__c=opp.Id;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
            
            String emailService = '{"leadId":"'+opp.Lead_number__c+'" ,"emailTo":"satyam_more@persistent.com", "emailCC":"bhushan_charde@persistent.com", "emailSubject":"Test Email Service API", "emailBody":"Test Email Service API"}';
            
            Continuation con = (Continuation)IntegrationEngine.doEmailServiceCallout(emailService);
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('{"JData":"bmvHXB5/b59ltoDPA8dwPKjM9zW1GwK5fvqA5/8G5nhh0w0E1I+3oTmH6qu4bRWV2ZIKywha3ogGCQMc2PCp/haQEVQHkfdJYPSxjfd2DnM95cSKzj+Wu/SxWkUr0je1ZpGONr41Yd1JTq5juubLNw=="}');
            response.setStatusCode(200);
            
            String continuationLabel = IntegrationEngine.continuationLabel;
            List<String> labels = new List<String>{continuationLabel};
            Object continuationState= IntegrationEngine.continuationState;
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            String emailServiceResponse= (String)IntegrationEngine.processEmailServiceResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
            String responseExpected ='{"body":null,"response":{"status":"SUCCESS","respDesc":"Email-Sent","content":["Email Sent Successfully!"]}}';
            System.assertEquals(responseExpected, emailServiceResponse, 'SUCCESS');
            
        } catch(Exception ex){
            System.assertEquals(ex.getMessage(),'Script-thrown exception', 'Exception');
        }
    }
    
    @isTest
    public static void testEmailServiceService2(){
        
        try{   
            
            Opportunity opp = TestDataUtility.createTestOpportunityforRunEmiEngineApi(false);
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            Applicant__c applicant = TestDataUtility.createTestApplicant(false);
            applicant.Opportunity__c=opp.Id;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
            
            String emailService = '{"leadId":"" ,"emailTo":"satyam_more@persistent.com", "emailCC":"bhushan_charde@persistent.com", "emailSubject":"Test Email Service API", "emailBody":"Test Email Service API"}';
            
            Continuation con = (Continuation)IntegrationEngine.doEmailServiceCallout(emailService);
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('{"JData":"bmvHXB5/b59ltoDPA8dwPKjM9zW1GwK5fvqA5/8G5nhh0w0E1I+3oTmH6qu4bRWV2ZIKywha3ogGCQMc2PCp/haQEVQHkfdJYPSxjfd2DnM95cSKzj+Wu/SxWkUr0je1ZpGONr41Yd1JTq5juubLNw=="}');
            response.setStatusCode(200);
            
            String continuationLabel = IntegrationEngine.continuationLabel;
            List<String> labels = new List<String>{continuationLabel};
            Object continuationState= IntegrationEngine.continuationState;
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            String emailServiceResponse= (String)IntegrationEngine.processEmailServiceResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
            String responseExpected ='{"body":null,"response":{"status":"SUCCESS","respDesc":"Email-Sent","content":["Email Sent Successfully!"]}}';
            System.assertEquals(responseExpected, emailServiceResponse, 'SUCCESS');
            
        } catch(Exception ex){
            System.assertEquals(ex.getMessage(),System.Label.LeadId, 'Exception');
        }
    }
    
    @isTest
    public static void testEmailServiceService3(){
        
        try{   
            
            Opportunity opp = TestDataUtility.createTestOpportunityforRunEmiEngineApi(false);
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            Applicant__c applicant = TestDataUtility.createTestApplicant(false);
            applicant.Opportunity__c=opp.Id;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
            
            String emailService = '{"leadId":"'+opp.Lead_number__c+'" ,"emailTo":"", "emailCC":"bhushan_charde@persistent.com", "emailSubject":"Test Email Service API", "emailBody":"Test Email Service API"}';
            
            Continuation con = (Continuation)IntegrationEngine.doEmailServiceCallout(emailService);
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('{"JData":"bmvHXB5/b59ltoDPA8dwPKjM9zW1GwK5fvqA5/8G5nhh0w0E1I+3oTmH6qu4bRWV2ZIKywha3ogGCQMc2PCp/haQEVQHkfdJYPSxjfd2DnM95cSKzj+Wu/SxWkUr0je1ZpGONr41Yd1JTq5juubLNw=="}');
            response.setStatusCode(200);
            
            String continuationLabel = IntegrationEngine.continuationLabel;
            List<String> labels = new List<String>{continuationLabel};
            Object continuationState= IntegrationEngine.continuationState;
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            String emailServiceResponse= (String)IntegrationEngine.processEmailServiceResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
            String responseExpected ='{"body":null,"response":{"status":"SUCCESS","respDesc":"Email-Sent","content":["Email Sent Successfully!"]}}';
            System.assertEquals(responseExpected, emailServiceResponse, 'SUCCESS');
            
        } catch(Exception ex){
            System.assertEquals(ex.getMessage(),System.Label.Email, 'Exception');
        }
    }
    
    @isTest
    public static void testEmailServiceService4(){
        
        try{   
            
            Opportunity opp = TestDataUtility.createTestOpportunityforRunEmiEngineApi(false);
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            Applicant__c applicant = TestDataUtility.createTestApplicant(false);
            applicant.Opportunity__c=opp.Id;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
            
            String emailService = '{"leadId":"'+opp.Lead_number__c+'" ,"emailTo":"satyam_more@persistent.com", "emailCC":"", "emailSubject":"Test Email Service API", "emailBody":"Test Email Service API"}';
            
            Continuation con = (Continuation)IntegrationEngine.doEmailServiceCallout(emailService);
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('{"JData":"bmvHXB5/b59ltoDPA8dwPKjM9zW1GwK5fvqA5/8G5nhh0w0E1I+3oTmH6qu4bRWV2ZIKywha3ogGCQMc2PCp/haQEVQHkfdJYPSxjfd2DnM95cSKzj+Wu/SxWkUr0je1ZpGONr41Yd1JTq5juubLNw=="}');
            response.setStatusCode(200);
            
            String continuationLabel = IntegrationEngine.continuationLabel;
            List<String> labels = new List<String>{continuationLabel};
            Object continuationState= IntegrationEngine.continuationState;
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            String emailServiceResponse= (String)IntegrationEngine.processEmailServiceResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
            String responseExpected ='{"body":null,"response":{"status":"SUCCESS","respDesc":"Email-Sent","content":["Email Sent Successfully!"]}}';
            System.assertEquals(responseExpected, emailServiceResponse, 'SUCCESS');
            
        } catch(Exception ex){
            System.assertEquals(ex.getMessage(),System.Label.Email, 'Exception');
        }
    }
    
    @isTest
    public static void testEmailServiceService5(){
        
        try{   
            
            Opportunity opp = TestDataUtility.createTestOpportunityforRunEmiEngineApi(false);
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            Applicant__c applicant = TestDataUtility.createTestApplicant(false);
            applicant.Opportunity__c=opp.Id;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
            
            String emailService = '{"leadId":"'+opp.Lead_number__c+'" ,"emailTo":"satyam_more@persistent.com", "emailCC":"bhushan_charde@persistent.com", "emailSubject":"", "emailBody":"Test Email Service API"}';
            
            Continuation con = (Continuation)IntegrationEngine.doEmailServiceCallout(emailService);
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('{"JData":"bmvHXB5/b59ltoDPA8dwPKjM9zW1GwK5fvqA5/8G5nhh0w0E1I+3oTmH6qu4bRWV2ZIKywha3ogGCQMc2PCp/haQEVQHkfdJYPSxjfd2DnM95cSKzj+Wu/SxWkUr0je1ZpGONr41Yd1JTq5juubLNw=="}');
            response.setStatusCode(200);
            
            String continuationLabel = IntegrationEngine.continuationLabel;
            List<String> labels = new List<String>{continuationLabel};
            Object continuationState= IntegrationEngine.continuationState;
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            String emailServiceResponse= (String)IntegrationEngine.processEmailServiceResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
            String responseExpected ='{"body":null,"response":{"status":"SUCCESS","respDesc":"Email-Sent","content":["Email Sent Successfully!"]}}';
            System.assertEquals(responseExpected, emailServiceResponse, 'SUCCESS');
            
        } catch(Exception ex){
            System.assertEquals(ex.getMessage(),System.Label.EmailSubject, 'Exception');
        }
    }
    
    @isTest
    public static void testEmailServiceService6(){
        
        try{   
            
            Opportunity opp = TestDataUtility.createTestOpportunityforRunEmiEngineApi(false);
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            Applicant__c applicant = TestDataUtility.createTestApplicant(false);
            applicant.Opportunity__c=opp.Id;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
            
            String emailService = '{"leadId":"'+opp.Lead_number__c+'" ,"emailTo":"satyam_more@persistent.com", "emailCC":"bhushan_charde@persistent.com", "emailSubject":"Test Email Service API", "emailBody":""}';
            
            Continuation con = (Continuation)IntegrationEngine.doEmailServiceCallout(emailService);
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('{"JData":"bmvHXB5/b59ltoDPA8dwPKjM9zW1GwK5fvqA5/8G5nhh0w0E1I+3oTmH6qu4bRWV2ZIKywha3ogGCQMc2PCp/haQEVQHkfdJYPSxjfd2DnM95cSKzj+Wu/SxWkUr0je1ZpGONr41Yd1JTq5juubLNw=="}');
            response.setStatusCode(200);
            
            String continuationLabel = IntegrationEngine.continuationLabel;
            List<String> labels = new List<String>{continuationLabel};
            Object continuationState= IntegrationEngine.continuationState;
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            String emailServiceResponse= (String)IntegrationEngine.processEmailServiceResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
            String responseExpected ='{"body":null,"response":{"status":"SUCCESS","respDesc":"Email-Sent","content":["Email Sent Successfully!"]}}';
            System.assertEquals(responseExpected, emailServiceResponse, 'SUCCESS');
            
        } catch(Exception ex){
            System.assertEquals(ex.getMessage(),System.Label.EmailBody, 'Exception');
        }
    }
    
    @isTest
    public static void testEmailServiceService7(){
        
        try{   
            
            Opportunity opp = TestDataUtility.createTestOpportunityforRunEmiEngineApi(false);
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            Applicant__c applicant = TestDataUtility.createTestApplicant(false);
            applicant.Opportunity__c=opp.Id;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
            
            String emailService = '{"leadId":"'+opp.Lead_number__c+'" ,"emailTo":"satyam_more@persistent.com", "emailCC":"bhushan_charde@persistent.com", "emailSubject":"Test Email Service API", "emailBody":"Test Email Service API"}';
            
            Continuation con = (Continuation)IntegrationEngine.doEmailServiceCallout(emailService);
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('{"JData":"bmvHXB5/b59ltoDPA8dwPKjM9zW1GwK5fvqA5/8G5nhh0w0E1I+3oTmH6qu4bRWV2ZIKywha3ogGCQMc2PCp/haQEVQHkfdJYPSxjfd2DnM95cSKzj+Wu/SxWkUr0je1ZpGONr41Yd1JTq5juubLNw=="}');
            response.setStatusCode(500);
            
            String continuationLabel = IntegrationEngine.continuationLabel;
            List<String> labels = new List<String>{continuationLabel};
            Object continuationState= IntegrationEngine.continuationState;
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            String emailServiceResponse= (String)IntegrationEngine.processEmailServiceResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
            String responseExpected ='{"body":null,"response":{"status":"SUCCESS","respDesc":"Email-Sent","content":["Email Sent Successfully!"]}}';
            System.assertEquals(responseExpected, emailServiceResponse, 'SUCCESS');
            
        } catch(Exception ex){
            System.assertEquals(ex.getMessage(),'No Response Found.', 'Exception');
        }
    }
}