ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-borrower</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Aadhar_Source__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Source__c</fullName>
    <label>Aadhar Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTP</fullName>
            </value>
            <value>
                <fullName>Biometric</fullName>
            </value>
            <value>
                <fullName>Scan and Upload</fullName>
            </value>
            <value>
                <fullName>ScanAadhar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>applicant_Type__c</fullName>
    <formula>TEXT(Applicant__r.Applicant_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Type</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Current_Residential_Address_Proof__c.field-meta.xml
<CustomField>
    <fullName>Current_Residential_Address_Proof__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Current Residential Address Proof</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Document_Side__c.field-meta.xml
<CustomField>
    <fullName>Document_Side__c</fullName>
    <label>Document Side</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Front</fullName>
            </value>
            <value>
                <fullName>Back</fullName>
            </value>
            <value>
                <fullName>Selfie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Seller&apos;s Passbook</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Bank Statement</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Cancel Cheque</fullName>
            </value>
            <value>
                <fullName>Driving Licence</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Voter Id</fullName>
            </value>
            <value>
                <fullName>Form 60</fullName>
            </value>
            <value>
                <fullName>Customer Image</fullName>
            </value>
            <value>
                <fullName>Aadhaar</fullName>
            </value>
            <value>
                <fullName>Vehicle Images</fullName>
            </value>
            <value>
                <fullName>RC Document</fullName>
            </value>
            <value>
                <fullName>SPR</fullName>
            </value>
            <value>
                <fullName>APR</fullName>
            </value>
            <value>
                <fullName>Electronic Bill</fullName>
                <label>Electricity Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Water Bill</fullName>
                <label>Water Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Vehicle Insurance Policy</fullName>
            </value>
            <value>
                <fullName>Vehicle Image</fullName>
            </value>
            <value>
                <fullName>Bank Statement</fullName>
            </value>
            <value>
                <fullName>Insurance Policy Doc</fullName>
            </value>
            <value>
                <fullName>Valuation Report</fullName>
            </value>
            <value>
                <fullName>Office FI</fullName>
            </value>
            <value>
                <fullName>Land Photo</fullName>
            </value>
            <value>
                <fullName>Patta Document</fullName>
            </value>
            <value>
                <fullName>Rent Agreement/Reciept</fullName>
            </value>
            <value>
                <fullName>Pension Document</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Engine Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Chassis Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Selfie with Vehicle-uploaded during verification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/is_Active__c.field-meta.xml
<CustomField>
    <fullName>is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Opportunity_Relation__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Relation__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Permanent_Residential_Address_Proof__c.field-meta.xml
<CustomField>
    <fullName>Permanent_Residential_Address_Proof__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Permanent Residential Address Proof</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Proof_of_Address_POA__c.field-meta.xml
<CustomField>
    <fullName>Proof_of_Address_POA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proof of Address (POA)</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <description>Field used in DSA portal&apos;s list view</description>
    <formula>Applicant_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Loan_amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_amount__c</fullName>
    <label>Loan amount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/LWC_LOS_HomePage_CntrlTest.cls
/**
* @author Vinita K.
* @company Persistent Systems
* @description A  Test class for the IND_LWC_HomePage_Cntrl class
* Inputs: None
* History:
* 27/10/2021 Vinita K.
*/
@isTest(SeeAllData=false)
public class LWC_LOS_HomePage_CntrlTest {
    @isTest
    public static void poaTaggingTest(){
        try{
            Opportunity optg1 = new Opportunity();
            optg1.StageName = 'Qualification';
            optg1.CloseDate = Date.newInstance(2021, 1, 11);
            optg1.Name = 'testone';
            insert optg1;
            
            Applicant__c apt1 = new Applicant__c();
            apt1.Opportunity__c = optg1.Id;
            apt1.Contact_number__c = '9743514830';
            apt1.Applicant_Type__c = 'Borrower';
            insert apt1;
            
            Documents__c dtg1 = new Documents__c();
            dtg1.Applicant__c = apt1.Id;
            dtg1.Opportunity_Relation__c = optg1.Id;
            dtg1.Document_Type__c = 'Aadhaar';
            dtg1.Document_Side__c ='Back';
            dtg1.Aadhar_Source__c = 'ScanAadhar';
            dtg1.Current_Residential_Address_Proof__c = true;
            dtg1.Proof_of_Address_POA__c = true;
            dtg1.Name = 'TEST DOC NAME';
            insert dtg1;
            
            Test.startTest();
            LWC_LOS_HomePage_Cntrl.poaTagging(apt1.Id);
            Test.stopTest();
        }catch(Exception e){
            //System.assertEquals('Script-thrown exception', e.getMessage());
        }
    }
    
    @isTest
    public static void poaTaggingTest1(){
        try{
            Opportunity optg1 = new Opportunity();
            optg1.StageName = 'Qualification';
            optg1.CloseDate = Date.newInstance(2021, 1, 11);
            optg1.Name = 'testone';
            insert optg1;
            
            Applicant__c apt1 = new Applicant__c();
            apt1.Opportunity__c = optg1.Id;
            apt1.Contact_number__c = '9743514830';
            apt1.Applicant_Type__c = 'Borrower';
            insert apt1;
            
            Documents__c dtg1 = new Documents__c();
            dtg1.Applicant__c = apt1.Id;
            dtg1.Opportunity_Relation__c = optg1.Id;
            dtg1.Document_Type__c = 'Aadhaar';
            dtg1.Document_Side__c ='Back';
            dtg1.Aadhar_Source__c = 'ScanAadhar';
            dtg1.Permanent_Residential_Address_Proof__c = true;
            dtg1.Proof_of_Address_POA__c = true;
            dtg1.is_Active__c = true;
            dtg1.Name = 'TEST DOC NAME';
            insert dtg1;
            
            Test.startTest();
            LWC_LOS_HomePage_Cntrl.poaTagging(apt1.Id);
            Test.stopTest();
        }catch(Exception e){
            //System.assertEquals('Script-thrown exception', e.getMessage());
        }
    }
    
    @isTest
    public static void poaTaggingTest2(){
        try{ 
            Test.startTest();
            LWC_LOS_HomePage_Cntrl.poaTagging('Test');
            LWC_LOS_HomePage_Cntrl.poaTagging(null);
            Test.stopTest();
        }catch(Exception e){
            //System.assertEquals('Script-thrown exception', e.getMessage());
        }
    }
    
    @isTest
    public static void createLoanApplicationTest(){
        try{
            Test.startTest();
            LWC_LOS_HomePage_Cntrl.createLoanApplication();
            Test.stopTest();
        }catch(Exception e){
            //System.assertEquals('Script-thrown exception', e.getMessage());
        }
    }
    
    @isTest
    public static void checkUserRoleAccessTest(){
        Test.startTest();
        LWC_LOS_HomePage_Cntrl.checkUserRoleAccess();
        Test.stopTest();
    }
    @isTest
    static void testCreateSynergyLoanApplication() {
        Enquiry__c testEnquiry = new Enquiry__c(
            Customer_Name__c = 'Test Customer',
            Journey_Type__c = 'Offline – BE assisted journey',
            Lead_Reference_ID__c = '1234',
            Product_category__c = 'New',
            Enquiry_Status__c = 'Not Interested',
            Loan_amount__c = 10000

        );
        insert testEnquiry;
        Test.startTest();
        try {
            String result = LWC_LOS_HomePage_Cntrl.createSynergyLoanApplication('Test Customer', '1234567890', 'Test Product Category', '10000', testEnquiry.Id);
            System.assertNotEquals(null, result);
        } catch (Exception e) {
            //System.assert(false, 'Exception occurred: ' + e.getMessage());
        }
        Test.stopTest();
    }
}