ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-borrower</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Customer_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_First_Name__c</fullName>
    <label>Customer First Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Customer_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Last_Name__c</fullName>
    <label>Customer Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/In_Active_Applicant__c.field-meta.xml
<CustomField>
    <fullName>In_Active_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In-Active Applicant</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Journey_Stage__c.field-meta.xml
<CustomField>
    <fullName>Journey_Stage__c</fullName>
    <label>Journey Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Details</fullName>
            </value>
            <value>
                <fullName>Capture current residential address</fullName>
            </value>
            <value>
                <fullName>Capture permanent residential address</fullName>
            </value>
            <value>
                <fullName>Capture PAN or Other KYC</fullName>
            </value>
            <value>
                <fullName>Capture Dedupe</fullName>
            </value>
            <value>
                <fullName>Vehicle Dedupe</fullName>
            </value>
            <value>
                <fullName>Declared Income/Required Loan Amount</fullName>
            </value>
            <value>
                <fullName>Bank Account Check</fullName>
            </value>
            <value>
                <fullName>Gatting And Screening</fullName>
            </value>
            <value>
                <fullName>Current Residential Address</fullName>
            </value>
            <value>
                <fullName>Perment Residential Address</fullName>
            </value>
            <value>
                <fullName>Demographic Details</fullName>
            </value>
            <value>
                <fullName>Office Address for primary Income Source</fullName>
            </value>
            <value>
                <fullName>Income Details</fullName>
            </value>
            <value>
                <fullName>Run EMI Engine</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Lead_Number__c.field-meta.xml
<CustomField>
    <fullName>Lead_Number__c</fullName>
    <formula>Opportunity__r.Lead_number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Id</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/Loan_Application_Transaction_History__c.object-meta.xml
<CustomObject>
    <description>created for tackling lead assignments would be used.</description>
    <label>Loan Application Transaction History</label>
    <nameField>
        <label>Loan Application Transaction History</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application Transactions History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/fields/Current_Owner__c.field-meta.xml
<CustomField>
    <fullName>Current_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Transactions_History_Current_Owner</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/fields/Loan_Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Loan Application Transactions History</relationshipLabel>
    <relationshipName>Loan_Application_Transactions_History</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <description>Stage Name</description>
    <label>Module</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/fields/New_Owner__c.field-meta.xml
<CustomField>
    <fullName>New_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Transaction_History_New_Owner</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Agent_BL_code__c.field-meta.xml
<CustomField>
    <fullName>Agent_BL_code__c</fullName>
    <label>Agent BL code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Customer_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Last_Name__c</fullName>
    <label>Customer Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Journey_Restart_Reason__c.field-meta.xml
<CustomField>
    <fullName>Journey_Restart_Reason__c</fullName>
    <label>Journey Restart Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/LastStageName__c.field-meta.xml
<CustomField>
    <fullName>LastStageName__c</fullName>
    <label>Last Stage</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Loan Initiation</fullName>
            </value>
            <value>
                <fullName>Additional Details</fullName>
            </value>
            <value>
                <fullName>Asset Details</fullName>
            </value>
            <value>
                <fullName>Vehicle Valuation</fullName>
            </value>
            <value>
                <fullName>Vehicle Insurance</fullName>
            </value>
            <value>
                <fullName>Loan Details</fullName>
            </value>
            <value>
                <fullName>Income Details</fullName>
            </value>
            <value>
                <fullName>Insurance Details</fullName>
            </value>
            <value>
                <fullName>Final Terms</fullName>
            </value>
            <value>
                <fullName>Journey Stop</fullName>
            </value>
            <value>
                <fullName>Offer Screen</fullName>
            </value>
            <value>
                <fullName>Customer Code Addition</fullName>
            </value>
            <value>
                <fullName>Final Offer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Lead_number__c.field-meta.xml
<CustomField>
    <fullName>Lead_number__c</fullName>
    <label>Lead Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/PreviousAccountId__c.field-meta.xml
<CustomField>
    <fullName>PreviousAccountId__c</fullName>
    <label>PreviousAccountId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Details</fullName>
            </value>
            <value>
                <fullName>Capture current residential address</fullName>
            </value>
            <value>
                <fullName>Capture permanent residential address</fullName>
            </value>
            <value>
                <fullName>Capture PAN or Other KYC</fullName>
            </value>
            <value>
                <fullName>Capture Dedupe</fullName>
            </value>
            <value>
                <fullName>Vehicle Dedupe</fullName>
            </value>
            <value>
                <fullName>Declared Income/Required Loan Amount</fullName>
            </value>
            <value>
                <fullName>Bank Account Check</fullName>
            </value>
            <value>
                <fullName>View Application Details</fullName>
            </value>
            <value>
                <fullName>CIBIL</fullName>
            </value>
            <value>
                <fullName>Field Investigation</fullName>
            </value>
            <value>
                <fullName>Credit Assessment</fullName>
            </value>
            <value>
                <fullName>Income Details</fullName>
            </value>
            <value>
                <fullName>Valuation IDV</fullName>
            </value>
            <value>
                <fullName>Final Terms</fullName>
            </value>
            <value>
                <fullName>Insurance Details</fullName>
            </value>
            <value>
                <fullName>Exposure Analysis</fullName>
            </value>
            <value>
                <fullName>Income</fullName>
            </value>
            <value>
                <fullName>CAM and Approval Log</fullName>
            </value>
            <value>
                <fullName>Risk Summary</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Tele-verification &lt;Post Sanction&gt;</fullName>
            </value>
            <value>
                <fullName>Vehicle Inspection and RC Check</fullName>
            </value>
            <value>
                <fullName>Structured EMI</fullName>
            </value>
            <value>
                <fullName>Security Mandate</fullName>
            </value>
            <value>
                <fullName>Additional Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>IHM</fullName>
            </value>
            <value>
                <fullName>Loan Agreement</fullName>
            </value>
            <value>
                <fullName>Signing the e-Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Refresh_View__e/Refresh_View__e.object-meta.xml
<CustomObject>
    <label>Refresh View</label>
    <pluralLabel>Refresh View</pluralLabel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Refresh_View__e/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdLWC - Copy/force-app/main/default/classes/HandleJourney_Utility.cls
/**
* @Name         HandleJourney_Utility
* @Author       Manish Baldota
* @Company      Persistent Systems
* @Description  This class is being used to handle the journey status.
* Inputs:       None
* Test Class:   LwcLOSLoanApplicationCntrlTest
* History:
* 18/03/2022    Manish Baldota		- Initial Deveopment 
*/
public without sharing  class HandleJourney_Utility { //CISP-2929
    //@Method:      handleCMUJourneyRestart
    //@Created by:  Manish Baldota.
    //@Description: Method to handle the Journye Restart for CMU
    //				1. Borrower Journy Restart - Clone new application with Limited details, and link existing to new.
    //				2. Co-borrower journey restart - Clone new application with cloned new borrower with existing details, capture new co-borrower.
    //@Param:       String - loanApplication ID
    //@Return:      String - Execution Status
    public static String handleCMUJourneyRestart(String applicantId,String restartReason){
        try{
            ReturnMessageWrapper returnWrapperElement = new ReturnMessageWrapper();
            System.debug('Log- handleCMUJourneyRestart - Called');
            System.debug('Log- handleCMUJourneyRestart - '+applicantId);
            System.debug('Log- handleCMUJourneyRestart - '+restartReason);
            
            if(String.isNotBlank(applicantId)){
                //Default status
                returnWrapperElement.isSuccess = true;
                returnWrapperElement.message = 'Journey has been restarted';

                // Get the borrower details
                Applicant__c applicantDetails = [SELECT Id,Applicant_Type__c,Opportunity__c 
                                                FROM Applicant__c WHERE Id =: applicantId 
                                                WITH SECURITY_ENFORCED LIMIT 1];
                
                                                //SANKET:: Commented Borrower and Co-Borrower logic: For both Journey will start from Loan Initiation with first screen details except Contact Details, Consent and Image Upload
                //Operate borrower and co-borrower journey restrart
                /*if(applicantDetails.Applicant_Type__c == System.label.Borrower){*/
                    Opportunity existingOpportunity = [SELECT Id, createdById, Name, StageName, Sub_Stage__c, LastStageName__c, Product_Type__c , Agent_BL_code__c, AccountId, PartnerAccountId, OwnerId, Lead_number__c,LeadSource, (SELECT ID, createdById, Opportunity__c, Name, Customer_First_Name__c, Customer_Last_Name__c, Journey_Stage__c, Applicant_Type__c FROM Applicants__r WHERE Applicant_Type__c =: System.label.Borrower AND In_Active_Applicant__c = false) FROM Opportunity WHERE Id =: applicantDetails.Opportunity__c WITH SECURITY_ENFORCED];
                    Opportunity newOpportunity = existingOpportunity.clone(false, false, false, true);
                    newOpportunity.StageName = 'Loan Initiation';
                    newOpportunity.LastStageName__c = 'Loan Initiation';
                    newOpportunity.Name = newOpportunity.Lead_number__c = handleLoanApplictionNumber(existingOpportunity.Name,'CMU Journey Restart');
                    newOpportunity.CloseDate = System.today()+30;
                    if(existingOpportunity.LeadSource == 'DSA'){//CISP-12675
                        newOpportunity.OwnerId = existingOpportunity.OwnerId;    
                        }else{
                    newOpportunity.OwnerId = existingOpportunity.CreatedById;//CISP-2836
                        }
                    newOpportunity.CreatedById = existingOpportunity.CreatedById;//CISP-2836
                    if (Schema.sObjectType.Opportunity.isCreateable()){
                        Insert newOpportunity;
                    } else {
                        returnWrapperElement.isSuccess = false;
                        returnWrapperElement.message = 'Missing write access';
                    }

                    existingOpportunity.StageName = 'Journey Restart';
                    existingOpportunity.Journey_Restart_Reason__c = restartReason;
                    if (Schema.sObjectType.Opportunity.isUpdateable()){
                        update existingOpportunity;
                        //CISP-2868-START
                        if(Schema.sObjectType.Refresh_View__e.isCreateable()){
                            Refresh_View__e refreshEvent = new Refresh_View__e();
                            refreshEvent.Record_Id__c = existingOpportunity.Id;
                            refreshEvent.Stage__c = existingOpportunity.StageName;
                            EventBus.publish(refreshEvent);
                        }
                        //CISP-2868-END
                    } else {
                        returnWrapperElement.isSuccess = false;
                        returnWrapperElement.message = 'Missing update access';
                    }

                    if(existingOpportunity.Applicants__r[0] != null){
                        Applicant__c newApplicant = existingOpportunity.Applicants__r[0].clone(false, false, false, true);
                        newApplicant.Opportunity__c = newOpportunity.Id;
                        newApplicant.Journey_Stage__c = 'User Details';
                        if (Schema.sObjectType.Applicant__c.isCreateable()){
                            System.debug('Log - Logged In User:: '+ UserInfo.getUserId());
                            System.debug('Log - newApplicant:: '+newApplicant);
                            insert newApplicant;
                        } else {
                            returnWrapperElement.isSuccess = false;
                            returnWrapperElement.message = 'Missing write access';
                        }
                    }
                    if(existingOpportunity.LeadSource == 'DSA'){//CISP-12675
                        newOpportunity.OwnerId = existingOpportunity.OwnerId;    
                        }else{
                    newOpportunity.OwnerId = existingOpportunity.createdById;
                        }
                    if (Schema.sObjectType.Opportunity.isUpdateable()){
                        update newOpportunity;
                    } else {
                        returnWrapperElement.isSuccess = false;
                        returnWrapperElement.message = 'Missing update access';
                    }
                    System.debug('Log - NewOpportunity:: '+newOpportunity);
               
            }else{
                returnWrapperElement.isSuccess = false;
                returnWrapperElement.message = 'Missing Applicant Details';
            }

            return System.JSON.serialize(returnWrapperElement);
        }catch(Exception e){
            ErrorLoggerUtil.logErrorEvent(' HandleJourney_Utility ', ' handleCMUJourneyRestart ', 'System.Label.Apex', e);
            throw new AuraHandledException(System.Label.ExceptionMessage);
        }
    }

    public Class ReturnMessageWrapper{
        @AuraEnabled public Boolean isSuccess {get;set;}
        @AuraEnabled public String message {get;set;}
    }

    public static String handleLoanApplictionNumber(String existingLoanAppNumber,String journeyType){
        try{
        String loanApplicationNumber = '';
        
        if(journeyType == 'CMU Journey Restart'){
            //Handling number sequence for the already restarted Application.
            //Replace the sequence with custom label.
            if(existingLoanAppNumber.contains('_C')){
                //Logic to Implement check for all the last digit get that and do the addition to the code.
                Integer lastDigit = Integer.valueOf(existingLoanAppNumber.right(existingLoanAppNumber.length()-(existingLoanAppNumber.length()-1)));//CISP-6610
                loanApplicationNumber = existingLoanAppNumber.left(existingLoanAppNumber.length()-1) + String.valueOf(lastDigit+1);//CISP-6610
            }else{
                loanApplicationNumber = existingLoanAppNumber+'_C1';
            }
        }
            return loanApplicationNumber;}
        catch(Exception e){
              ErrorLoggerUtil.logErrorEvent(' HandleJourney_Utility ', ' handleLoanApplictionNumber ', 'System.Label.Apex', e);
            throw new AuraHandledException(System.Label.ExceptionMessage);
        }
    }

    public static String getLastSalesUserId(String opptyId){
        try{
            Id stageChangeRecordTypeID = Schema.SObjectType.Loan_Application_Transaction_History__c.getRecordTypeInfosByName().get('Stage Change').getRecordTypeId();
            List<Loan_Application_Transaction_History__c> lathRecords = [SELECT Id,Current_Owner__c,New_Owner__c,Loan_Application_ID__r.ownerId FROM Loan_Application_Transaction_History__c WHERE Module__c = 'Credit Processing' AND Loan_Application_ID__c =: opptyId AND RecordTypeId =: stageChangeRecordTypeID];
            if(!lathRecords.isEmpty()){
                return lathRecords[0].Current_Owner__c;
            } else {
                return [SELECT ID,OwnerId FROM Opportunity WHERE Id=:opptyId].OwnerId;
            }
        }catch(Exception e){
              ErrorLoggerUtil.logErrorEvent(' HandleJourney_Utility ', ' getLastSalesUserId ', 'System.Label.Apex', e);
            throw new AuraHandledException(System.Label.ExceptionMessage);
        }
    }
    @AuraEnabled
    public static string getBussSourceBy(String loanApplicationId){
        Map<string,string> bussSourcemap = new Map<string,string>();
        Set<String> previosAccountIdSet = new Set<String>();
        Opportunity opp = [Select accountId,owner.Name,ownerId,Product_Type__c,PreviousAccountId__c from Opportunity where Id =:loanApplicationId];
        try {
            if(opp.PreviousAccountId__c != null){
                List<String> previosAccountIdList = opp.PreviousAccountId__c.split(',');
                previosAccountIdSet = new Set<String>(previosAccountIdList);
            }
            previosAccountIdSet.add(opp.accountId);
            for(AccountTeamMember atm : [SELECT AccountId, TeamMemberRole, User.Name,UserId,user.IsActive FROM AccountTeamMember 
                                        WHERE AccountId IN : previosAccountIdSet AND (TeamMemberRole = 'BE' OR TeamMemberRole = 'CS') AND user.IsActive = true WITH SECURITY_ENFORCED]) {
                                            bussSourcemap.put(atm.UserId,atm.User.Name.removeStart('ibl'));
                                        }
                return JSON.serialize(bussSourcemap);
        } catch (Exception e) {
            ErrorLoggerUtil.logErrorEvent('HandleJourney_Utility', 'getBussSourceBy', System.Label.Apex, e);
            throw new AuraHandledException(e.getMessage());
        }
    }
    @AuraEnabled
    public static string getBussDoneByID(String loanApplicationId){
        Map<string,string> bussSourcemap = new Map<string,string>();
        Set<String> previosAccountIdSet = new Set<String>();
        Opportunity opp = [Select accountId,owner.Name,ownerId,Product_Type__c,PreviousAccountId__c from Opportunity where Id =:loanApplicationId];
        try {
            if(opp.PreviousAccountId__c != null){
                List<String> previosAccountIdList = opp.PreviousAccountId__c.split(',');
                previosAccountIdSet = new Set<String>(previosAccountIdList);
            }
            previosAccountIdSet.add(opp.accountId);
            for(AccountTeamMember atm : [SELECT AccountId, TeamMemberRole, User.Name,UserId,user.IsActive FROM AccountTeamMember 
                                        WHERE AccountId IN : previosAccountIdSet AND (TeamMemberRole = 'BE') AND user.IsActive = true WITH SECURITY_ENFORCED]) {
                                            bussSourcemap.put(atm.UserId,atm.User.Name.removeStart('ibl'));
                                        }
                return JSON.serialize(bussSourcemap);
        } catch (Exception e) {
            ErrorLoggerUtil.logErrorEvent('HandleJourney_Utility', 'getBussDoneByID', System.Label.Apex, e);
            throw new AuraHandledException(e.getMessage());
        }
    }
}