ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-borrower</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Scorecard_Decision__c.field-meta.xml
<CustomField>
    <fullName>Scorecard_Decision__c</fullName>
    <label>Scorecard Decision</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>applicant_Type__c</fullName>
    <formula>TEXT(Applicant__r.Applicant_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Type</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Income_Details__c.field-meta.xml
<CustomField>
    <fullName>Income_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Income Details</label>
    <referenceTo>Income_Details__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>Vehicle_Detail__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Existing_EMI__c/Existing_EMI__c.object-meta.xml
<CustomObject>
    <label>Existing EMI</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Existing EMI Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Existing EMIs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Field_Investigation__c/Field_Investigation__c.object-meta.xml
<CustomObject>
    <label>Field Investigation</label>
    <nameField>
        <displayFormat>FI-{00000}</displayFormat>
        <label>Field Investigation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Income_Details__c/Income_Details__c.object-meta.xml
<CustomObject>
    <label>Income Details</label>
    <nameField>
        <label>Income Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Income Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Income_Details__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Income_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Lead_Genaration_Metadata__mdt/Lead_Genaration_Metadata__mdt.object-meta.xml
<CustomObject>
    <label>Lead Genaration Metadata</label>
    <pluralLabel>Lead Genaration Metadatas</pluralLabel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Lead_Genaration_Metadata__mdt/fields/FieldSetName__c.field-meta.xml
<CustomField>
    <fullName>FieldSetName__c</fullName>
    <label>FieldSetName</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Lead_Genaration_Metadata__mdt/fields/Module_Name__c.field-meta.xml
<CustomField>
    <fullName>Module_Name__c</fullName>
    <label>Module Name</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Lead_Genaration_Metadata__mdt/fields/Object__c.field-meta.xml
<CustomField>
    <fullName>Object__c</fullName>
    <label>Object</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Lead_Genaration_Metadata__mdt/fields/UpdateOrDeactivateOperation__c.field-meta.xml
<CustomField>
    <fullName>UpdateOrDeactivateOperation__c</fullName>
    <label>UpdateOrDeactivateOperation</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/Loan_Application_Transaction_History__c.object-meta.xml
<CustomObject>
    <description>created for tackling lead assignments would be used.</description>
    <label>Loan Application Transaction History</label>
    <nameField>
        <label>Loan Application Transaction History</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application Transactions History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/fields/Assignment_status__c.field-meta.xml
<CustomField>
    <fullName>Assignment_status__c</fullName>
    <label>Assignment status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/fields/Loan_Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Loan Application Transactions History</relationshipLabel>
    <relationshipName>Loan_Application_Transactions_History</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <description>Stage Name</description>
    <label>Module</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/fields/Module_Name__c.field-meta.xml
<CustomField>
    <fullName>Module_Name__c</fullName>
    <label>Module Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Additional Details</fullName>
            </value>
            <value>
                <fullName>Asset Details</fullName>
            </value>
            <value>
                <fullName>Vehicle Insurance</fullName>
            </value>
            <value>
                <fullName>Vehicle Valuation</fullName>
            </value>
            <value>
                <fullName>Loan Details</fullName>
            </value>
            <value>
                <fullName>Income Details</fullName>
            </value>
            <value>
                <fullName>Final Terms</fullName>
            </value>
            <value>
                <fullName>Insurance Details</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>Post Sanction Checks and Documentation</fullName>
            </value>
            <value>
                <fullName>Disbursement Request Preparation</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Needs Analysis</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Loan Initiation</fullName>
            </value>
            <value>
                <fullName>Prospecting</fullName>
            </value>
            <value>
                <fullName>Offer Screen</fullName>
            </value>
            <value>
                <fullName>Existing EMI</fullName>
            </value>
            <value>
                <fullName>Credit Processing</fullName>
            </value>
            <value>
                <fullName>Additional Customer Details</fullName>
                <isActive>false</isActive>
                <label>Additional Customer Details</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/fields/New_Owner__c.field-meta.xml
<CustomField>
    <fullName>New_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Transaction_History_New_Owner</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/OpportunityTeamMember/fields/Assign_To__c.field-meta.xml
<CustomField>
    <fullName>Assign_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Will be used to display lookup to user</description>
    <label>Assign To</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please select user to be assigned to this module.</errorMessage>
        <filterItems>
            <field>$User.Product_Type__c</field>
            <operation>equals</operation>
            <valueField>User.Product_Type__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunity_Team</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/Maker_Id__c.field-meta.xml
<CustomField>
    <fullName>Maker_Id__c</fullName>
    <label>Maker Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/Vehicle_Detail__c.object-meta.xml
<CustomObject>
    <label>Vehicle Detail</label>
    <nameField>
        <displayFormat>VD-{00000}</displayFormat>
        <label>Vehicle Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/OEM_Dealer__c.field-meta.xml
<CustomField>
    <fullName>OEM_Dealer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OEM Dealer</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/classes/Recall_applicationTest.cls
@isTest
public class Recall_applicationTest {
    
    @isTest
    public static void reaclltranferedApplictaionTest(){
        Opportunity opra1 = new Opportunity();
        opra1.StageName = 'Vehicle insurance';
        opra1.CloseDate = Date.newInstance(2021, 1, 11);
        opra1.Name = 'testone';
        insert opra1;
        
        Vehicle_Detail__c  vehicleDetail =  TestDataUtility.createTestVehicleDetailForIbb(false, opra1);
        vehicleDetail.OEM_Dealer__c = false;
        insert vehicleDetail;
        
        Lead_Genaration_Metadata__mdt lgm1 = [SELECT id,MasterLabel,FieldSetName__c,Object__c,UpdateOrDeactivateOperation__c FROM Lead_Genaration_Metadata__mdt WHERE UpdateOrDeactivateOperation__c = 'Update' limit 1];
        
        Loan_Application_Transaction_History__c lth1 = new Loan_Application_Transaction_History__c();
        lth1.Loan_Application_ID__c = opra1.Id;
        lth1.Assignment_status__c = 'Pending';
        lth1.Module_Name__c = opra1.StageName;
        lth1.New_Owner__c = UserInfo.getUserId();
        lth1.RecordTypeId = Schema.SObjectType.Loan_Application_Transaction_History__c.getRecordTypeInfosByName().get('Lead Assignment').getRecordTypeId();
        upsert lth1;
        
        OpportunityTeamMember optm2 = new OpportunityTeamMember();
        optm2.OpportunityId = opra1.Id;
        optm2.UserId = lth1.New_Owner__c;
        optm2.TeamMemberRole = 'BE';
      //  optm2.Assign_To__c = null;
        insert optm2;
        
        Test.startTest();
        Boolean result = Recall_application.reaclltranferedApplictaion(opra1.Id);
      //  System.assert(result);
        Test.stopTest();
    }
    
    
    
    @isTest
    public static void getUpdateTest(){        
        Opportunity opra2 = new Opportunity();
        opra2.StageName = 'Vehicle insurance';
        opra2.CloseDate = Date.newInstance(2021, 1, 11); 
        opra2.Name = 'testone';
        insert opra2;
        
        Applicant__c applicant = TestDataUtility.createTestApplicantForSMS(false);
        applicant.Opportunity__c = opra2.Id;
        applicant.Applicant_Type__c  = null;
        applicant.Scorecard_Decision__c = 'Red';
        insert applicant;
        
        Vehicle_Detail__c  vehicleDetail =  TestDataUtility.createTestVehicleDetailForIbb(false, opra2);
        vehicleDetail.OEM_Dealer__c = true;
        insert vehicleDetail;
        
        Test.startTest();
        Boolean result = Recall_application.getUpdate('LA_VehicleInsurancePurgeFields', 'Vehicle_Detail__c', opra2.Id);
        Recall_application.getUpdate('LA_VehicleInsurancePurgeFields', 'Income_Details__c', opra2.Id);
        Recall_application.getUpdate('LA_VehicleInsurancePurgeFields', 'Opportunity', opra2.Id);
        Recall_application.getUpdate('LA_VehicleInsurancePurgeFields', 'Applicant__c', opra2.Id);
        System.assert(result);
        Test.stopTest();
    }
    
    @isTest
    public static void getDecivateTest(){
        Opportunity opra2 = new Opportunity();
        opra2.StageName = 'Vehicle insurance';
        opra2.CloseDate = Date.newInstance(2021, 1, 11);
        opra2.Name = 'testone';
        insert opra2;
        
        Vehicle_Detail__c  vehicleDetail =  TestDataUtility.createTestVehicleDetailForIbb(false, opra2);
        vehicleDetail.OEM_Dealer__c = false;
        insert vehicleDetail;
        
        Test.startTest();
        Boolean result = Recall_application.getDecivate('Vehicle_Detail__c', opra2.Id);
        Recall_application.getDecivate('Field_Investigation__c', opra2.Id);
        Recall_application.getDecivate('Income_Details__c', opra2.Id);
        Recall_application.getDecivate('Existing_EMI__c', opra2.Id);
        Recall_application.getDecivate('Documents__c', opra2.Id);
        System.assert(result);
        Test.stopTest();
    }
    
    
    
    
    
    
    
    
    
    
  
     @isTest
    public static void getUserRoleTest(){
        
            Profile p = [SELECT Id FROM Profile WHERE Name='CMU'];
            system.debug('p'+ p);
            User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
                              EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                              LocaleSidKey='en_US', ProfileId = p.Id,Maker_Id__c = '1001',
                              TimeZoneSidKey='America/Los_Angeles',
                              MobilePhone = '9701498575',
                              UserName='standarduser4@testorg.com.psdev1');
            insert u; 
             System.runAs(u) 
            {
            Account au1 = new Account();
            au1.Name = 'test';
            au1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
            insert au1;
        
            Opportunity opp = TestDataUtility.createTestOpportunity(false);
            opp.AccountId = au1.Id;
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
        
            AccountTeamMember atm2 = new AccountTeamMember();
            atm2.AccountId = opp.AccountId;
		    atm2.TeamMemberRole = 'BE';
            atm2.UserId = u.Id;
            insert atm2;
        
            Test.startTest();
                  Recall_application.getUserRole(u.Id,opp.Id);
            Test.stopTest();
            }
    }
    
    @isTest
    public static void checkLoanApplicationTransactionHistoryTest(){
         Opportunity opks1 = new Opportunity();
                opks1.StageName = 'Qualification';
                opks1.CloseDate = Date.newInstance(2021, 1, 11);
                opks1.Name = 'testone';
                insert opks1;
            
                Loan_Application_Transaction_History__c lth1 = new Loan_Application_Transaction_History__c();
                lth1.Loan_Application_ID__c = opks1.Id;
                lth1.Module_Name__c = 'FI';
                insert lth1;
        
                Test.startTest();
                       Recall_application.checkLoanApplicationTransactionHistory(opks1.Id,lth1.Module__c);
                Test.stopTest();
    }
    
     @isTest
    public static void checkLoanApplicationTransactionHistoryTest1(){
         Opportunity opks1 = new Opportunity();
                opks1.StageName = 'Qualification';
                opks1.CloseDate = Date.newInstance(2021, 1, 11);
                opks1.Name = 'testone';
                insert opks1;
            
                Loan_Application_Transaction_History__c lth1 = new Loan_Application_Transaction_History__c();
                lth1.Loan_Application_ID__c = opks1.Id;
                lth1.Module_Name__c = 'FI';
                lth1.Assignment_status__c = 'Pending';
                lth1.RecordTypeId = Schema.SObjectType.Loan_Application_Transaction_History__c.getRecordTypeInfosByName().get('Lead Assignment' ).getRecordTypeId();
                insert lth1;
        
                Test.startTest();
                       Recall_application.checkLoanApplicationTransactionHistory(opks1.Id,lth1.Module_Name__c);
                Test.stopTest();
    }
    
}