ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Lead_Number__c.field-meta.xml
<CustomField>
    <fullName>Lead_Number__c</fullName>
    <formula>Opportunity__r.Lead_number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Id</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Income_Details__c/Income_Details__c.object-meta.xml
<CustomObject>
    <label>Income Details</label>
    <nameField>
        <label>Income Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Income Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Income_Details__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Income_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Income_Details__c/fields/Capture_GST_Method__c.field-meta.xml
<CustomField>
    <fullName>Capture_GST_Method__c</fullName>
    <label>Capture GST Method</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Online via link</fullName>
            </value>
            <value>
                <fullName>Upload online via link</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Lead_number__c.field-meta.xml
<CustomField>
    <fullName>Lead_number__c</fullName>
    <label>Lead Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/IND_PerfiosGSTReportRequest.cls
/*------------------------------------------------------------
Author:        Bhushan Charde
Company:       Persistent Systems
Description:   This class is wrapper class for the Perfios GST Report API request 
Test Class:     
History
Date            Author              Comments
-------------------------------------------------------------
12-23-2021      Bhushan Charde       Created
------------------------------------------------------------*/
public class IND_PerfiosGSTReportRequest extends ParentAPIRequest {
    
	public final string type {get;set;}
    public final string PerfiosTransactionId {get;set;}
    public final string maker_Id     {get;set;}
    public final string lead_Id 	   {get;set;}
    public final string reportFormat {get;set;}
    
    
    // @Method:      IND_PerfiosGSTReportRequest
    // @Created by:  Bhushan Charde 
    // @Description: Contructor to initialize the details
    // @Param:       Object applicant Record
    // @Return:      ''
    public IND_PerfiosGSTReportRequest(Applicant__c app){  
        //currently hardcode Id's has been passed these will be changed at the time of handshaking.
        this.type = 'GSTOnline';
        this.PerfiosTransactionId = 'PGVCGESPRWJWATY40UAJ6';  
        this.Lead_Id = app.Opportunity__r.Lead_number__c;  
        this.Maker_Id = IntegrationUtilities.getMakerId();
        this.reportFormat= 'xlsx';
        
        validate(System.Label.GSTReport);
    } 
    
    // @Method:      IND_PerfiosGSTReportRequest
    // @Created by:  Bhushan Charde 
    // @Description: Contructor to initialize the details
    // @Param:       Object applicant Record
    // @Return:      ''
    public IND_PerfiosGSTReportRequest(Income_Details__c app, Opportunity opty, String perfiosId, String reportFormat){  
        this.type = app.Capture_GST_Method__c != null && app.Capture_GST_Method__c == 'Online via link'?'GSTOnline': app.Capture_GST_Method__c == 'Upload online via link'?'GSTUpload' : '';
        this.PerfiosTransactionId = perfiosId;
        this.Lead_Id = opty.Lead_number__c;  
        this.Maker_Id = '1001';//IntegrationUtilities.getMakerId();
        this.reportFormat= reportFormat;
    }  
    
    // @Method:      getHttpRequestHeaders
    // @Created by:  Bhushan Charde 
    // @Description: Method to get the HTTP request header data
    // @Param:       ''
    // @Return:      Header required to callout the service.
    public override Map<String,String> getHttpRequestHeaders(){    
        Map<String,String> requestHeaderMap = Utilities.getHeaders();
        return requestHeaderMap;
    }
    
    // @Method:      validate
    // @Created by:  Bhushan Charde 
    // @Description: Method to validate the required input details
    // @Param:       Service name
    // @Return:      True - If all the validations are passed.
   
    public override boolean validate(String serviceName){
        
        if(String.isBlank(this.PerfiosTransactionId)){
            throw new IND_Exception(System.Label.perfiosTransactionErrorId);
        }
        if(String.isBlank(this.Lead_Id)){
            throw new IND_Exception(System.Label.Lead_IDError);
        }        
        if(String.isBlank(this.Maker_Id)){
            throw new IND_Exception(System.Label.Maker_IdError);
        }
        
        return true;
    }
}