ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-borrower</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Code__c</fullName>
    <label>Customer Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Customer_Code__c/Customer_Code__c.object-meta.xml
<CustomObject>
    <label>Customer Code</label>
    <nameField>
        <label>Customer  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Customer_Code__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant_Delete</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Customer_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Customer_Code__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Customer_Codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Code__c</fullName>
    <label>Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Loan_amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_amount__c</fullName>
    <label>Loan amount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Total_Funded_premium_amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Funded_premium_amount__c</fullName>
    <label>Total Funded premium amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Details_Retry_Attempt__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Details_Retry_Attempt__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Vehicle Details Retry Attempt</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Sub_Category__c</fullName>
    <label>Vehicle Sub-Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC - Copy/force-app/main/default/classes/IND_LWC_StpChecksCntrlTest1.cls
@isTest
public class IND_LWC_StpChecksCntrlTest1 {  
    
  /*  public static Opportunity testOpportunityNewData(){
        Opportunity opsc1 = new Opportunity();
            opsc1.StageName = 'Qualification';
            opsc1.CloseDate = Date.newInstance(2022, 1, 11);
            opsc1.Name = 'testone';
            opsc1.Vehicle_Type__c = 'New';
            opsc1.Product_Type__c = 'Two Wheeler';
        insert opsc1;
        return opsc1;
    }
    
    public static Opportunity testOpportunityUsedData(){
        Opportunity opsc1 = new Opportunity();
            opsc1.StageName = 'Qualification';
            opsc1.CloseDate = Date.newInstance(2022, 1, 11);
            opsc1.Name = 'testone';
            opsc1.Vehicle_Type__c = 'Used';
            opsc1.Product_Type__c = 'Two Wheeler';
        insert opsc1;
        return opsc1;
    }
    
    public static Applicant__c testApplicantData(){
        Opportunity opsc2 = testOpportunityNewData();
        Applicant__c apsc2 = new Applicant__c();
            apsc2.Opportunity__c = opsc2.Id;
            apsc2.Contact_number__c = '9743514830';
            apsc2.Applicant_Type__c = 'Borrower';
        insert apsc2;
        return apsc2;
    }
    
    public static Customer_Code__c testCustomerCodeData(){
        Opportunity opsc2 = testOpportunityNewData();
        Customer_Code__c cust = new Customer_Code__c();
            cust.Name='newcust';
            cust.Loan_Application__c = opsc2.Id;
            insert cust;
        return cust;
    }
   Test3---
            Opportunity opsc2 = new Opportunity();
            opsc2.StageName = 'Qualification';
            opsc2.CloseDate = Date.newInstance(2022, 1, 11);
            opsc2.Name = 'testone';
            opsc2.Product_Type__c = 'Passenger Vehicles';
            opsc2.Loan_amount__c = '6000000';
             opsc2.Vehicle_Details_Retry_Attempt__c=1;
            opsc2.Vehicle_Type__c = 'used';
            insert opsc2;

	Test4--- 
            Opportunity opsc1 = new Opportunity();
            opsc1.StageName = 'Qualification';
            opsc1.CloseDate = Date.newInstance(2022, 1, 11);
            opsc1.Name = 'testone';
            opsc1.Vehicle_Type__c = 'New';
            opsc1.Product_Type__c = 'Two Wheeler';
            insert opsc1;
	Test6---
		 
     Opportunity opsc2 = new Opportunity();
            opsc2.StageName = 'Qualification';
            opsc2.CloseDate = Date.newInstance(2022, 1, 11);
            opsc2.Name = 'testone';
          //  opsc1.Vehicle_Type__c = 'New';
            opsc2.Product_Type__c = 'Passenger Vehicles';
            opsc2.Loan_amount__c = '6000000';
             opsc2.Vehicle_Details_Retry_Attempt__c=1;
            opsc2.Vehicle_Type__c = 'used';
            insert opsc2;
       
            
*/  
    /* test7-- 
         Opportunity opsc2 = new Opportunity();
            opsc2.StageName = 'Qualification';
            opsc2.CloseDate = Date.newInstance(2022, 1, 11);
            opsc2.Name = 'testone';
            opsc2.Vehicle_Type__c = 'New';
            opsc2.Product_Type__c = 'Passenger Vehicles';
            opsc2.Loan_amount__c = '6000000';
            opsc2.Vehicle_Details_Retry_Attempt__c = 1;
        	opsc2.Total_Funded_premium_amount__c = 40000 ; 
  
            insert opsc2;
        */
    /*Test 6 ---
     Opportunity opsc2 = new Opportunity();
            opsc2.StageName = 'Qualification';
            opsc2.CloseDate = Date.newInstance(2022, 1, 11);
            opsc2.Name = 'testone';
          //  opsc1.Vehicle_Type__c = 'New';
            opsc2.Product_Type__c = 'Passenger Vehicles';
            opsc2.Loan_amount__c = '6000000';
             opsc2.Vehicle_Details_Retry_Attempt__c=1;
            opsc2.Vehicle_Type__c = 'used';
            insert opsc2;
       */
      /* Test5---
        Opportunity opsc2 = new Opportunity();
            opsc2.StageName = 'Qualification';
            opsc2.CloseDate = Date.newInstance(2022, 1, 11);
            opsc2.Name = 'testone';
            opsc2.Product_Type__c = 'Passenger Vehicles';
            opsc2.Loan_amount__c = '6000000';
            opsc2.Vehicle_Details_Retry_Attempt__c=1;
            opsc2.Vehicle_Type__c = 'used';
            insert opsc2;
*/	
       /*Test2---
            Opportunity opsc2 = new Opportunity();
            opsc2.StageName = 'Qualification';
            opsc2.CloseDate = Date.newInstance(2022, 1, 11);
            opsc2.Name = 'testone';
            opsc2.Vehicle_Type__c = 'Used';
            opsc2.Product_Type__c = 'Two Wheeler';
            opsc2.Loan_amount__c = '6000000';
            opsc2.Vehicle_Sub_Category__c = 'UEB';
            insert opsc2;
            */
     		
}