ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Disposition__c.field-meta.xml
<CustomField>
    <fullName>Disposition__c</fullName>
    <label>Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pre-mature leads</fullName>
            </value>
            <value>
                <fullName>Not Interested</fullName>
            </value>
            <value>
                <fullName>Warm leads - call back</fullName>
            </value>
            <value>
                <fullName>Deferred leads - call back</fullName>
            </value>
            <value>
                <fullName>Completed leads</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Sub_Disposition__c.field-meta.xml
<CustomField>
    <fullName>Sub_Disposition__c</fullName>
    <label>Sub-Disposition</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Disposition__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agent not available/rejected</fullName>
            </value>
            <value>
                <fullName>Customer not available</fullName>
            </value>
            <value>
                <fullName>Car not needed</fullName>
            </value>
            <value>
                <fullName>Car needed no finance</fullName>
            </value>
            <value>
                <fullName>Car finance not needed from IBL</fullName>
            </value>
            <value>
                <fullName>Deal closed somewhere else</fullName>
            </value>
            <value>
                <fullName>Customer to be called back later</fullName>
            </value>
            <value>
                <fullName>Customer to complete journey on his own</fullName>
            </value>
            <value>
                <fullName>Customer disconnected the call without talking</fullName>
            </value>
            <value>
                <fullName>Car not finalised yet</fullName>
            </value>
            <value>
                <fullName>Car finalised but buy/finance later</fullName>
            </value>
            <value>
                <fullName>Other reason (Free-text mandatory)</fullName>
            </value>
            <value>
                <fullName>Customer completed the process</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/ConVox_Configuration__c/ConVox_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>ConVox Configuration</label>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdLWC - Copy/force-app/main/default/classes/conVoxAPIHandlerTest.cls
/*------------------------------------------------------------
Author:        Haarika Chodisetti
Company:       Salesforce
Description:   This class is to test methods of conVoxAPIHandler
History
Date            Author              Comments
-------------------------------------------------------------
16-08-2022      Haarika Chodisetti         Created
------------------------------------------------------------*/
@isTest
public with sharing class conVoxAPIHandlerTest {
    /*
     * @Method:      conVoxAPIHandlerTest
     * @Created by:  Haarika Chodisetti
     * @Description: Tests all methods of conVoxAPIHandler with the help of CTIMockHttpClass
     * @Param:       
     * @Return:  void   
     History
     Date            Author              Comments
     -------------------------------------------------------------
     16-08-2022      Haarika Chodisetti         Created
     ------------------------------------------------------------*/
    @isTest static void conVoxAPIHandlerTest1() {
        Opportunity opp = TestDataUtility.createTestOpportunity(true);
        Applicant__c app = TestDataUtility.createTestApplicantService(true, opp);
        app.Disposition__c = IntegrationConstants.DISPOSITION_NOT_INTERESTED;
        app.Sub_Disposition__c = IntegrationConstants.SUB_DISPOSITION_CAR_NOT_NEEDED;
        update app;
        Opportunity opp1 = TestDataUtility.createTestOpportunity1(true);
        Applicant__c app1 = TestDataUtility.createTestApplicantService(true, opp);
        app1.Disposition__c = IntegrationConstants.DISPOSITION_NOT_INTERESTED;
        app1.Sub_Disposition__c = IntegrationConstants.SUB_DISPOSITION_CAR_NOT_NEEDED;
        update app1;
        ConVox_Configuration__c configValues = ConVox_Configuration__c.getInstance();
        configValues.EndPoint__c = IntegrationConstants.CONVOX_END_POINT;
        upsert configValues; 
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, New CTIMockHttpClass());        
        conVoxAPIHandler.callApi(IntegrationConstants.CONVOX_DATAUPLOAD,app.Contact_number__c,app.Id);
        conVoxAPIHandler.callApi(IntegrationConstants.CONVOX_DELETELEAD,null, null);
        Test.stopTest();
    }
}