ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-borrower</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Aadhar_Source__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Source__c</fullName>
    <label>Aadhar Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTP</fullName>
            </value>
            <value>
                <fullName>Biometric</fullName>
            </value>
            <value>
                <fullName>Scan and Upload</fullName>
            </value>
            <value>
                <fullName>ScanAadhar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>applicant_Type__c</fullName>
    <formula>TEXT(Applicant__r.Applicant_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Type</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Document_Side__c.field-meta.xml
<CustomField>
    <fullName>Document_Side__c</fullName>
    <label>Document Side</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Front</fullName>
            </value>
            <value>
                <fullName>Back</fullName>
            </value>
            <value>
                <fullName>Selfie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Seller&apos;s Passbook</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Bank Statement</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Cancel Cheque</fullName>
            </value>
            <value>
                <fullName>Driving Licence</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Voter Id</fullName>
            </value>
            <value>
                <fullName>Form 60</fullName>
            </value>
            <value>
                <fullName>Customer Image</fullName>
            </value>
            <value>
                <fullName>Aadhaar</fullName>
            </value>
            <value>
                <fullName>Vehicle Images</fullName>
            </value>
            <value>
                <fullName>RC Document</fullName>
            </value>
            <value>
                <fullName>SPR</fullName>
            </value>
            <value>
                <fullName>APR</fullName>
            </value>
            <value>
                <fullName>Electronic Bill</fullName>
                <label>Electricity Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Water Bill</fullName>
                <label>Water Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Vehicle Insurance Policy</fullName>
            </value>
            <value>
                <fullName>Vehicle Image</fullName>
            </value>
            <value>
                <fullName>Bank Statement</fullName>
            </value>
            <value>
                <fullName>Insurance Policy Doc</fullName>
            </value>
            <value>
                <fullName>Valuation Report</fullName>
            </value>
            <value>
                <fullName>Office FI</fullName>
            </value>
            <value>
                <fullName>Land Photo</fullName>
            </value>
            <value>
                <fullName>Patta Document</fullName>
            </value>
            <value>
                <fullName>Rent Agreement/Reciept</fullName>
            </value>
            <value>
                <fullName>Pension Document</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Engine Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Chassis Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Selfie with Vehicle-uploaded during verification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/KYC_name__c.field-meta.xml
<CustomField>
    <fullName>KYC_name__c</fullName>
    <label>KYC name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Opportunity_Relation__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Relation__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>Vehicle_Detail__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/Final_Term__c.object-meta.xml
<CustomObject>
    <description>To store Final term module data.</description>
    <label>Final Term</label>
    <nameField>
        <displayFormat>FT-{000000}</displayFormat>
        <label>Final Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/CRM_IRR__c.field-meta.xml
<CustomField>
    <fullName>CRM_IRR__c</fullName>
    <label>Offer engine CRM IRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/EMI_Amount__c.field-meta.xml
<CustomField>
    <fullName>EMI_Amount__c</fullName>
    <label>Offer engine EMI Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Holiday_period__c.field-meta.xml
<CustomField>
    <fullName>Holiday_period__c</fullName>
    <label>Holiday period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>150</fullName>
            </value>
            <value>
                <fullName>180</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan_Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Final_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>Vehicle_Detail__c</referenceTo>
    <relationshipLabel>Final Terms</relationshipLabel>
    <relationshipName>Final_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <label>Base Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Ben_Code__c.field-meta.xml
<CustomField>
    <fullName>Ben_Code__c</fullName>
    <label>Ben Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/CRM_IRR__c.field-meta.xml
<CustomField>
    <fullName>CRM_IRR__c</fullName>
    <label>CRM IRR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/EMI_Amount__c.field-meta.xml
<CustomField>
    <fullName>EMI_Amount__c</fullName>
    <label>EMI Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Holiday_period__c.field-meta.xml
<CustomField>
    <fullName>Holiday_period__c</fullName>
    <label>Holiday period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/Vehicle_Detail__c.object-meta.xml
<CustomObject>
    <label>Vehicle Detail</label>
    <nameField>
        <displayFormat>VD-{00000}</displayFormat>
        <label>Vehicle Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Base_Price__c.field-meta.xml
<CustomField>
    <fullName>Base_Price__c</fullName>
    <label>Base Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Ben_Code__c.field-meta.xml
<CustomField>
    <fullName>Ben_Code__c</fullName>
    <label>Ben Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Insurance_expiring_within_60_days__c.field-meta.xml
<CustomField>
    <fullName>Insurance_expiring_within_60_days__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Insurance expiring within 60 days</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <description>Vehicle Insurance and Vehicle Valuation data</description>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Vehicle_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Valuer_category__c.field-meta.xml
<CustomField>
    <fullName>Valuer_category__c</fullName>
    <label>Valuer category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Empanelled</fullName>
            </value>
            <value>
                <fullName>MFC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/classes/IND_ValuationIDVCntrlTest.cls
@isTest
 public class IND_ValuationIDVCntrlTest {
    @isTest
     public static void loadVehicleDetailsDataTest(){
         try{
                Opportunity opks1 = TestDataUtility.createTestOpportunity(false);
                opks1.StageName = 'Qualification';
                opks1.CloseDate = Date.newInstance(2021, 1, 11);
                opks1.Name = 'testone';
                insert opks1;
                
                Applicant__c apks1 = TestDataUtility.createTestApplicant(false);
                apks1.Opportunity__c = opks1.Id;
                apks1.Contact_number__c = '9743514830';
                apks1.Applicant_Type__c = 'Borrower';
                insert apks1;
                
                 Documents__c dfks1 = new Documents__c();
                 dfks1.Applicant__c = apks1.Id;
                 dfks1.Opportunity_Relation__c = opks1.Id;
                 dfks1.KYC_name__c = 'Aadhar';
                 dfks1.Document_Side__c ='Back';
                 dfks1.Aadhar_Source__c = 'ScanAadhar';
                 dfks1.Name = 'Aadhar';
                 dfks1.Document_Type__c = System.label.AadhaarCard;
                 insert dfks1;
             
                 Final_Term__c fgd3 = new Final_Term__c();
                 fgd3.CRM_IRR__c = 120;
                 fgd3.Loan_Application__c = opks1.Id;
                 fgd3.Holiday_period__c='30';
                 fgd3.EMI_Amount__c= 10000;
                 insert fgd3;
             
                 Vehicle_Detail__c vc2 = new Vehicle_Detail__c();
                 vc2.Loan_Application__c = opks1.Id;
                 vc2.Base_Price__c = 100000.00;
                 vc2.Ben_Code__c = 'testveh';
                 insert vc2; 
             
                 Test.startTest();
                      IND_ValuationIDVCntrl.loadVehicleDetailsData(opks1.Id);
                 Test.stopTest();
         }catch(Exception e){
                System.assertEquals('Script-thrown exception', e.getMessage());
         }
         
     }
     
     @isTest
     public static void checkValidationBeforeSubmitTest(){
         try{
             Opportunity opks1 = TestDataUtility.createTestOpportunity(false);
                opks1.StageName = 'Qualification';
                opks1.CloseDate = Date.newInstance(2021, 1, 11);
                opks1.Name = 'testone';
                insert opks1;
                
                Applicant__c apks1 = TestDataUtility.createTestApplicant(false);
                apks1.Opportunity__c = opks1.Id;
                apks1.Contact_number__c = '9743514830';
                apks1.Applicant_Type__c = 'Borrower';
                insert apks1;
                
                 Documents__c dfks1 = new Documents__c();
                 dfks1.Applicant__c = apks1.Id;
                 dfks1.Opportunity_Relation__c = opks1.Id;
                 dfks1.KYC_name__c = 'Aadhar';
                 dfks1.Document_Side__c ='Back';
                 dfks1.Aadhar_Source__c = 'ScanAadhar';
                 dfks1.Name = 'Aadhar';
                 dfks1.Document_Type__c = System.Label.ValuationReport;
                 insert dfks1;
             
                 Final_Term__c fgd3 = new Final_Term__c();
                 fgd3.CRM_IRR__c = 120;
                 fgd3.Loan_Application__c = opks1.Id;
                 fgd3.Holiday_period__c='30';
                 fgd3.EMI_Amount__c= 10000;
                 insert fgd3;
             
                 Vehicle_Detail__c vc2 = new Vehicle_Detail__c();
                 vc2.Loan_Application__c = opks1.Id;
                 vc2.Base_Price__c = 100000.00;
                 vc2.Ben_Code__c = 'testveh';
                 vc2.Valuer_category__c = System.Label.Empanelled;
                 insert vc2; 
             
                  Test.startTest();
                        IND_ValuationIDVCntrl.checkValidationBeforeSubmit(opks1.Id,vc2.Id);
                  Test.stopTest();
         }catch(Exception e){
              System.assertEquals('Script-thrown exception', e.getMessage());
         }
     }
     
          @isTest
     public static void checkValidationBeforeSubmitTest1(){
         try{
             Opportunity opks1 = TestDataUtility.createTestOpportunity(false);
                opks1.StageName = 'Qualification';
                opks1.CloseDate = Date.newInstance(2021, 1, 11);
                opks1.Name = 'testone';
                insert opks1;
                
                Applicant__c apks1 = TestDataUtility.createTestApplicant(false);
                apks1.Opportunity__c = opks1.Id;
                apks1.Contact_number__c = '9743514830';
                apks1.Applicant_Type__c = 'Borrower';
                insert apks1;
                
                 Documents__c dfks1 = new Documents__c();
                 dfks1.Applicant__c = apks1.Id;
                 dfks1.Opportunity_Relation__c = opks1.Id;
                 dfks1.KYC_name__c = 'Aadhar';
                 dfks1.Document_Side__c ='Back';
                 dfks1.Aadhar_Source__c = 'ScanAadhar';
                 dfks1.Name = 'Aadhar';
                 dfks1.Document_Type__c = System.Label.RC_Document;
                 insert dfks1;
             
                 Final_Term__c fgd3 = new Final_Term__c();
                 fgd3.CRM_IRR__c = 120;
                 fgd3.Loan_Application__c = opks1.Id;
                 fgd3.Holiday_period__c='30';
                 fgd3.EMI_Amount__c= 10000;
                 insert fgd3;
             
                 Vehicle_Detail__c vc2 = new Vehicle_Detail__c();
                 vc2.Loan_Application__c = opks1.Id;
                 vc2.Base_Price__c = 100000.00;
                 vc2.Ben_Code__c = 'testveh';
                 vc2.Valuer_category__c = System.Label.Empanelled;
                 insert vc2; 
             
                  Test.startTest();
                        IND_ValuationIDVCntrl.checkValidationBeforeSubmit(opks1.Id,vc2.Id);
                  Test.stopTest();
         }catch(Exception e){
              System.assertEquals('Script-thrown exception', e.getMessage());
         }
     }
     
      @isTest
     public static void checkValidationBeforeSubmitTest11(){
         try{
             Opportunity opks1 = TestDataUtility.createTestOpportunity(false);
                opks1.StageName = 'Qualification';
                opks1.CloseDate = Date.newInstance(2021, 1, 11);
                opks1.Name = 'testone';
                insert opks1;
                
                Applicant__c apks1 = TestDataUtility.createTestApplicant(false);
                apks1.Opportunity__c = opks1.Id;
                apks1.Contact_number__c = '9743514830';
                apks1.Applicant_Type__c = 'Borrower';
                insert apks1;
                
                 Documents__c dfks1 = new Documents__c();
                 dfks1.Applicant__c = apks1.Id;
                 dfks1.Opportunity_Relation__c = opks1.Id;
                 dfks1.KYC_name__c = 'Aadhar';
                 dfks1.Document_Side__c ='Back';
                 dfks1.Aadhar_Source__c = 'ScanAadhar';
                 dfks1.Name = 'Aadhar';
                 dfks1.Document_Type__c = System.Label.InsurancePolicy;
                 insert dfks1;
             
                 Final_Term__c fgd3 = new Final_Term__c();
                 fgd3.CRM_IRR__c = 120;
                 fgd3.Loan_Application__c = opks1.Id;
                 fgd3.Holiday_period__c='30';
                 fgd3.EMI_Amount__c= 10000;
                 insert fgd3;
             
                 Vehicle_Detail__c vc2 = new Vehicle_Detail__c();
                 vc2.Loan_Application__c = opks1.Id;
                 vc2.Base_Price__c = 100000.00;
                 vc2.Ben_Code__c = 'testveh';
                 vc2.Valuer_category__c = System.Label.Empanelled;
                 insert vc2; 
             
                  Test.startTest();
                        IND_ValuationIDVCntrl.checkValidationBeforeSubmit(opks1.Id,vc2.Id);
                  Test.stopTest();
         }catch(Exception e){
              System.assertEquals('Script-thrown exception', e.getMessage());
         }
     }
     
               @isTest
     public static void checkValidationBeforeSubmitTest2(){
         try{
                Opportunity opks2 = TestDataUtility.createTestOpportunity(false);
                opks2.StageName = 'Qualification';
                opks2.CloseDate = Date.newInstance(2021, 1, 11);
                opks2.Name = 'testone';
                insert opks2;
              
                IND_ValuationIDVCntrl.VehicleDetailsWrapper vdw1 = new IND_ValuationIDVCntrl.VehicleDetailsWrapper();
                vdw1.status = 'testmsg';
                vdw1.message = 'no msg';
             
                 Vehicle_Detail__c vc2 = new Vehicle_Detail__c();
                 vc2.Loan_Application__c = opks2.Id;
                 vc2.Base_Price__c = 100000.00;
                 vc2.Ben_Code__c = 'testveh';
                 vc2.Insurance_expiring_within_60_days__c = true;
                 insert vc2; 
             
                  Test.startTest();
                        IND_ValuationIDVCntrl.checkValidationBeforeSubmit(opks2.Id,vc2.Id);
                  Test.stopTest();
         }catch(Exception e){
              System.assertEquals('Script-thrown exception', e.getMessage());
         }
     }
     
     @isTest
     public static void checkValidationBeforeSubmitTest3(){
         try{
             Opportunity opks1 = TestDataUtility.createTestOpportunity(false);
                opks1.StageName = 'Qualification';
                opks1.CloseDate = Date.newInstance(2021, 1, 11);
                opks1.Name = 'testone';
                insert opks1;
                
                Applicant__c apks1 = TestDataUtility.createTestApplicant(false);
                apks1.Opportunity__c = opks1.Id;
                apks1.Contact_number__c = '9743514830';
                apks1.Applicant_Type__c = 'Borrower';
                insert apks1;
                
                 Documents__c dfks1 = new Documents__c();
                 dfks1.Applicant__c = apks1.Id;
                 dfks1.Opportunity_Relation__c = opks1.Id;
                 dfks1.KYC_name__c = 'Aadhar';
                 dfks1.Document_Side__c ='Back';
                 dfks1.Aadhar_Source__c = 'ScanAadhar';
                 dfks1.Name = 'Aadhar';
                 dfks1.Document_Type__c = System.Label.RC_Document;
                 insert dfks1;
             
                 Final_Term__c fgd3 = new Final_Term__c();
                 fgd3.CRM_IRR__c = 120;
                 fgd3.Loan_Application__c = opks1.Id;
                 fgd3.Holiday_period__c='30';
                 fgd3.EMI_Amount__c= 10000;
                 insert fgd3;
             
                 Vehicle_Detail__c vc2 = new Vehicle_Detail__c();
                 vc2.Loan_Application__c = opks1.Id;
                 vc2.Base_Price__c = 100000.00;
                 vc2.Ben_Code__c = 'testveh';
             //    vc2.Valuer_category__c = System.Label.Empanelled;
                 vc2.Insurance_expiring_within_60_days__c = true;
                 insert vc2; 
             
                  Test.startTest();
                        IND_ValuationIDVCntrl.checkValidationBeforeSubmit(opks1.Id,vc2.Id);
                  Test.stopTest();
         }catch(Exception e){
              System.assertEquals('Script-thrown exception', e.getMessage());
         }
     }
     
     @isTest
     public static void checkValidationBeforeSubmitTest4(){
         try{
             Opportunity opks1 = TestDataUtility.createTestOpportunity(false);
                opks1.StageName = 'Qualification';
                opks1.CloseDate = Date.newInstance(2021, 1, 11);
                opks1.Name = 'testone';
                insert opks1;
                
                Applicant__c apks1 = TestDataUtility.createTestApplicant(false);
                apks1.Opportunity__c = opks1.Id;
                apks1.Contact_number__c = '9743514830';
                apks1.Applicant_Type__c = 'Borrower';
                insert apks1;
                
                 Documents__c dfks1 = new Documents__c();
                 dfks1.Applicant__c = apks1.Id;
                 dfks1.Opportunity_Relation__c = opks1.Id;
                 dfks1.KYC_name__c = 'Aadhar';
                 dfks1.Document_Side__c ='Back';
                 dfks1.Aadhar_Source__c = 'ScanAadhar';
                 dfks1.Name = 'Aadhar';
                 dfks1.Document_Type__c = System.Label.InsurancePolicy;
                 insert dfks1;
             
                 Final_Term__c fgd3 = new Final_Term__c();
                 fgd3.CRM_IRR__c = 120;
                 fgd3.Loan_Application__c = opks1.Id;
                 fgd3.Holiday_period__c='30';
                 fgd3.EMI_Amount__c= 10000;
                 insert fgd3;
             
                 Vehicle_Detail__c vc2 = new Vehicle_Detail__c();
                 vc2.Loan_Application__c = opks1.Id;
                 vc2.Base_Price__c = 100000.00;
                 vc2.Ben_Code__c = 'testveh';
             //    vc2.Valuer_category__c = System.Label.Empanelled;
                 vc2.Insurance_expiring_within_60_days__c = false;
                 insert vc2; 
             
                  Test.startTest();
                        IND_ValuationIDVCntrl.checkValidationBeforeSubmit(opks1.Id,vc2.Id);
                  Test.stopTest();
         }catch(Exception e){
              System.assertEquals('Script-thrown exception', e.getMessage());
         }
     }
     
     @isTest
     public static void loadVehicleDetailsDataForTractorTest(){
         
         try{
         Opportunity opks3 = TestDataUtility.createTestOpportunity(false);
                opks3.StageName = 'Qualification';
                opks3.CloseDate = Date.newInstance(2021, 1, 12);
                opks3.Name = 'testone';
                insert opks3;
         
            Applicant__c apks1 = TestDataUtility.createTestApplicant(false);
                apks1.Opportunity__c = opks3.Id;
                apks1.Contact_number__c = '8743514830';
                apks1.Applicant_Type__c = 'Borrower';
                insert apks1;
                
                 Documents__c dfks1 = new Documents__c();
                 dfks1.Applicant__c = apks1.Id;
                 dfks1.Opportunity_Relation__c = opks3.Id;
                 dfks1.KYC_name__c = 'Aadhar';
                 dfks1.Document_Side__c ='Back';
                 dfks1.Aadhar_Source__c = 'ScanAadhar';
                 dfks1.Name = 'Aadhar';
                 dfks1.Document_Type__c = System.Label.InsurancePolicy;
                 insert dfks1;
         
                 Final_Term__c fgd3 = new Final_Term__c();
                 fgd3.CRM_IRR__c = 120;
                 fgd3.Loan_Application__c = opks3.Id;
                 fgd3.Holiday_period__c='30';
                 fgd3.EMI_Amount__c= 10000;
                 insert fgd3;
         
         
                 Vehicle_Detail__c vc1 = new Vehicle_Detail__c();
                 vc1.Loan_Application__c = opks3.Id;
                 vc1.Base_Price__c = 100000.00;
                 vc1.Ben_Code__c = 'testveh';
                 vc1.Insurance_expiring_within_60_days__c = false;
                 insert vc1;
         
                  Test.startTest();
                        IND_ValuationIDVCntrl.loadVehicleDetailsDataForTractor(opks3.Id);
             Test.stopTest();
         }
         catch(Exception e){
              System.assertEquals('Script-thrown exception', e.getMessage());
         }
     }
     
}