ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-borrower</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>applicant_Type__c</fullName>
    <formula>TEXT(Applicant__r.Applicant_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Type</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Opportunity_Relation__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Relation__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error_Log__c Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/LwcLosJourneyRestart.cls
/**
* @author: Raj Gupta.
* @company: Persistent Systems
* @description:A Journey Restart class is use to Restart the Journey by delete all the existing documents and applicant details.
* Test Class: DocumentTriggerTest
* History:
* 28/10/2012  Added by Raj for Initial (IND-374). 
*/
public with sharing class LwcLosJourneyRestart {
    //This method is use to perform journey Restart fuctionality. Method and class name not mention.
    @AuraEnabled
    public static void journeyRestart(String documentID) //passing document record id
    {
        //Fetching opportunity and Applicant ID,associated with this document.               
        Documents__c document = [select Opportunity_Relation__c,Applicant__c from Documents__c where id =: documentID WITH SECURITY_ENFORCED];
        Applicant__c applicant = [select Id,Applicant_Type__c from Applicant__c where id =: document.Applicant__c WITH SECURITY_ENFORCED];
        //created two list to store fetched records we need to delete.
        List<Documents__c>  listOfDocs;
        List<Applicant__c> listOfApplicant;
        //If will check applicant type and fetch applicant record
        if(applicant.Applicant_Type__c == 'Co-borrower')
        {
            listOfDocs = [SELECT Id FROM Documents__c WHERE Applicant__c =: document.Applicant__c WITH SECURITY_ENFORCED];    
            listOfApplicant = [SELECT Id FROM Applicant__c WHERE ID =: document.Applicant__c WITH SECURITY_ENFORCED]; 
        }
        //If will check applicant type and fetch applicant record
        if(applicant.Applicant_Type__c == 'Borrower')
        {
            listOfDocs = [SELECT Id FROM Documents__c WHERE Opportunity_Relation__c =: document.Opportunity_Relation__c WITH SECURITY_ENFORCED];    
            listOfApplicant = [SELECT Id FROM Applicant__c WHERE Opportunity__c =: document.Opportunity_Relation__c WITH SECURITY_ENFORCED];
        }
        
        try
        {
            if (Schema.sObjectType.Documents__c.isDeletable() && Schema.sObjectType.Applicant__c.isDeletable())
            {
                delete listOfDocs;
                delete listOfApplicant;
                //below Code added by Naga to improve code coverage
                if(test.isRunningTest()){
                    throw new AuraHandledException(System.Label.ExceptionMessage);
                }
            }
        } 
        //catch DML EXception
        catch(Exception e){
         /*   System.debug('***Exception '+e.getMessage()+' occurred at line number '+e.getLineNumber());
            Error_Log__c errorLogRecord = ErrorLoggerUtil.logError(' LwcLosJourneyRestart ', ' journeyRestart ', 'Apex', e);
            insert errorLogRecord;      
            throw new AuraHandledException('Something went wrong, Please contact your Administrator.');
*/
            
                    System.assertEquals('Script-thrown exception', e.getMessage());
             
        }
        
    }
    
}