ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Asset_Verification__c/Asset_Verification__c.object-meta.xml
<CustomObject>
    <description>Asset Verification object will store all the Asset Details verification status where Delivered = Yes</description>
    <label>Asset Verification</label>
    <nameField>
        <label>Asset Verification Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Verifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Asset_Verification__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Asset Verifications</relationshipLabel>
    <relationshipName>Asset_Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Asset_Verification__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Asset Verifications</relationshipLabel>
    <relationshipName>Asset_Verifications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Asset_Verification__c/fields/Is_Post_Sanction_Verified_Asset__c.field-meta.xml
<CustomField>
    <fullName>Is_Post_Sanction_Verified_Asset__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Post Sanction Verified Asset</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Asset_Verification__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inprogress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Case/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Id</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Case/fields/Asset_Verification__c.field-meta.xml
<CustomField>
    <fullName>Asset_Verification__c</fullName>
    <formula>IF( RecordType.Name == &apos;Asset Verification&apos;,IF(ISPICKVAL($User.UserType, &apos;PowerPartner&apos;), HYPERLINK($Label.IBL_Community_Partners_URL+&quot;/s/av-page?c__recordId=&quot;+Id, &quot;Navigate to AV&quot;, &quot;_blank&quot;), HYPERLINK(&quot;/lightning/cmp/c__LOSAV?c__recordId=&quot;+Id, &quot;Navigate to AV&quot;, &quot;_blank&quot;)),&apos;&apos;)</formula>
    <label>Asset Verification</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Sanction_Date__c.field-meta.xml
<CustomField>
    <fullName>Sanction_Date__c</fullName>
    <label>Sanction Date</label>
    <type>Date</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/assetVerificationTriggerHandlerTest.cls
@isTest
public class assetVerificationTriggerHandlerTest {
    @isTest
    public static void updateCaseStatusTest(){
        
        Opportunity opp=TestDataUtility.createTestOpportunity1(false);
        opp.Sanction_Date__c=System.Today();
        Insert opp;
        
         Applicant__c applicant1 = TestDataUtility.createTestApplicatnt1(false);
            applicant1.Opportunity__c = opp.Id;
            
       Case cse=TestDataUtility.createTestCase(false,opp,applicant1);
        Insert cse;
        
        Opportunity opp1=TestDataUtility.createTestOpportunity1(false);
        opp1.Sanction_Date__c=System.Today();
        Insert opp1;
        
         Applicant__c applicant2 = TestDataUtility.createTestApplicatnt1(false);
            applicant2.Opportunity__c = opp1.Id;
            
       Case cse1=TestDataUtility.createTestCase(false,opp1,applicant2);
        Insert cse1;
        
        Asset_Verification__c  avRec = new Asset_Verification__c ();
        avRec.Name = 'testName';
        avRec.Status__c = 'Inprogress';
        avRec.Case__c = cse.Id;
        insert avRec;
        
        List<Id> avRecList=New List<Id>();
        List<Id> caseIdList=New List<Id>();
        caseIdList.add(cse1.Id);
        avRecList.add(avRec.Case__c);
        //if
        Test.startTest();
        assetVerificationTriggerHandler.updateCaseStatus(avRecList);
        assetVerificationTriggerHandler.updateCaseStatus(caseIdList);
        
        avRec.Status__c = 'Completed';
        update avRec;
        
        delete avRec;
        Test.stopTest();
        
      
    }
    @isTest
    public static void updateIsPSVerifiedAssetTest(){
        List<Asset_Verification__c> avList=new List<Asset_Verification__c>();
        Opportunity opp=TestDataUtility.createTestOpportunity1(false);
        opp.Sanction_Date__c=System.Today();
        Insert opp;
        
         Applicant__c applicant1 = TestDataUtility.createTestApplicatnt1(false);
            applicant1.Opportunity__c = opp.Id;
            
       Case cse1=TestDataUtility.createTestCase(false,opp,applicant1);
        Insert cse1;
         Set<Id> caseIds=New Set<Id>();
          
        
        Asset_Verification__c  avRec = new Asset_Verification__c ();
        avRec.Name = 'testName';
        avRec.Is_Post_Sanction_Verified_Asset__c=True;
        avRec.Status__c = 'Completed';
        avRec.Case__c = cse1.Id;
        insert avRec;   
       
        caseIds.add(avRec.Case__c);
        avList.add(avRec);
        Test.startTest();
        assetVerificationTriggerHandler.updateIsPSVerifiedAsset(avList,caseIds);
        Test.stopTest();
    }
}