ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Customer_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_First_Name__c</fullName>
    <label>Customer First Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Customer_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Last_Name__c</fullName>
    <label>Customer Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Id__c</fullName>
    <label>Email-Id</label>
    <type>Email</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Lead_Number__c.field-meta.xml
<CustomField>
    <fullName>Lead_Number__c</fullName>
    <formula>Opportunity__r.Lead_number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Id</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Agent_BL_code__c.field-meta.xml
<CustomField>
    <fullName>Agent_BL_code__c</fullName>
    <label>Agent BL code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Application_number__c.field-meta.xml
<CustomField>
    <fullName>Application_number__c</fullName>
    <label>Application number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Customer_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Last_Name__c</fullName>
    <label>Customer Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Employee_Name__c.field-meta.xml
<CustomField>
    <fullName>Employee_Name__c</fullName>
    <label>Employee Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Employee_No__c.field-meta.xml
<CustomField>
    <fullName>Employee_No__c</fullName>
    <label>Employee No.</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Lead_number__c.field-meta.xml
<CustomField>
    <fullName>Lead_number__c</fullName>
    <label>Lead Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <label>Variant</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Registration_Number__c</fullName>
    <label>Vehicle Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Sub_Category__c</fullName>
    <label>Vehicle Sub-Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Product2/fields/make__c.field-meta.xml
<CustomField>
    <fullName>make__c</fullName>
    <formula>Parent_Product__r.Parent_Product__r.Make_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>make</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Product2/fields/model__c.field-meta.xml
<CustomField>
    <fullName>model__c</fullName>
    <formula>Parent_Product__r.Model_Code__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>model</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Product2/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <label>Model Code</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <formula>IF(ISPICKVAL(Type__c, &apos;Model&apos;),Parent_Product__r.Parent_Product__r.Name, IF(ISPICKVAL(Type__c, &apos;Variant&apos;),Parent_Product__r.Parent_Product__r.Parent_Product__r.Name, IF(ISPICKVAL(Type__c, &apos;Make&apos;),Parent_Product__r.Name, &apos;&apos;)
))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Make</fullName>
            </value>
            <value>
                <fullName>Model</fullName>
            </value>
            <value>
                <fullName>Variant</fullName>
            </value>
            <value>
                <fullName>Class Of Vehicle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Product2/fields/Variant_Code__c.field-meta.xml
<CustomField>
    <fullName>Variant_Code__c</fullName>
    <label>Variant Code</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Product2/recordTypes/Model.recordType-meta.xml
<RecordType>
    <fullName>Model</fullName>
    <active>true</active>
    <label>Model</label>
</RecordType>

ProdIND/ProdPrograms/force-app/main/default/objects/Product2/recordTypes/Variant.recordType-meta.xml
<RecordType>
    <fullName>Variant</fullName>
    <active>true</active>
    <label>Variant</label>
</RecordType>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/Vehicle_Detail__c.object-meta.xml
<CustomObject>
    <label>Vehicle Detail</label>
    <nameField>
        <displayFormat>VD-{00000}</displayFormat>
        <label>Vehicle Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Chassis_number__c.field-meta.xml
<CustomField>
    <fullName>Chassis_number__c</fullName>
    <label>Chassis number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Engine_number__c.field-meta.xml
<CustomField>
    <fullName>Engine_number__c</fullName>
    <label>Engine number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <description>Vehicle Insurance and Vehicle Valuation data</description>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Vehicle_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Location_Of_Vehicle__c.field-meta.xml
<CustomField>
    <fullName>Location_Of_Vehicle__c</fullName>
    <label>Location Of Vehicle</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Buyer place</fullName>
            </value>
            <value>
                <fullName>Customer place</fullName>
            </value>
            <value>
                <fullName>Seller place</fullName>
            </value>
            <value>
                <fullName>Yard</fullName>
            </value>
            <value>
                <fullName>IBL office</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Model_Code__c.field-meta.xml
<CustomField>
    <fullName>Model_Code__c</fullName>
    <label>Model Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Purpose_of_purchase__c.field-meta.xml
<CustomField>
    <fullName>Purpose_of_purchase__c</fullName>
    <label>Purpose of purchase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
                <default>true</default>
                <label>Personal</label>
            </value>
            <value>
                <fullName>Working Capital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Valuer__c.field-meta.xml
<CustomField>
    <fullName>Valuer__c</fullName>
    <label>Valuer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Valuer-1</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Valuer-2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Valuer_category__c.field-meta.xml
<CustomField>
    <fullName>Valuer_category__c</fullName>
    <label>Valuer category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Empanelled</fullName>
            </value>
            <value>
                <fullName>MFC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Valuer_code__c.field-meta.xml
<CustomField>
    <fullName>Valuer_code__c</fullName>
    <label>Valuer code</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <label>Variant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Variant_Code__c.field-meta.xml
<CustomField>
    <fullName>Variant_Code__c</fullName>
    <label>Variant Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Vehicle_Place_Of_Valuation__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Place_Of_Valuation__c</fullName>
    <label>Vehicle&apos;s Place Of Valuation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Vehicle_Registration_number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Registration_number__c</fullName>
    <label>Vehicle Registration number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Vehicle_SubCategory__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_SubCategory__c</fullName>
    <description>Vehicle SubCategory is used to store Vehicle Details value from dedupe screen</description>
    <label>Vehicle SubCategory</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Vehicle_SubType__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_SubType__c</fullName>
    <label>Vehicle SubType</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Vehicle_type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_type__c</fullName>
    <label>Vehicle type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC - Copy/force-app/main/default/classes/IND_MFCValuationRequest.cls
/*------------------------------------------------------------
Author:        Divya Jawale
Company:       Persistent Systems
Description:   This class is wrapper class for the MFC Valuation request 
Test Class:    IND_MFCValuationService_Test
History
Date            Author              Comments
-------------------------------------------------------------
20-12-2021      Divya Jawale       Created
------------------------------------------------------------*/

public with sharing class IND_MFCValuationRequest extends ParentAPIRequest{
    //request paramaters for MFC Valuationrequest
    public final String Lead_Id{get;set;}
    public final String Branch{get;set;}
    public final String Productcode{get;set;}
    public final String ValuerCategory{get;set;}
    public final String ValuerCode{get;set;}
    public final String Valuer{get;set;}
    public final String Purpose{get;set;}
    public final String PlaceOfInspection{get;set;}
    public final String Location_of_Vehicle{get;set;}
    public final String Application_Ref_Type{get;set;}
    public final String Appl_Ref_Deal_No{get;set;}
    public final String CustomerName{get;set;}
    public final String ContactPerson{get;set;}
    public final String MobileNo{get;set;}
    public final String Emailid{get;set;}
    public final String City{get;set;}
    public final String VehicleCatg{get;set;}
    public final String VehicleSubCatg{get;set;}
    public final String Makecode{get;set;}
    public final String Model{get;set;}
    public final String Variantcode{get;set;}
    public final String VehRegNo{get;set;}
    public final String Vehtype{get;set;}
    public final String EngineNo{get;set;}
    public final String ChasisNo{get;set;}
    public final String NameTransferred{get;set;}
    public final String CurrentVehicleOwner{get;set;}
    public final String LienMaerkedIBL{get;set;}
    public final String MarkedOn{get;set;}
    public final String NowLienNameOf{get;set;}
    public final String RequesterName{get;set;}
    public final String RequesterMobilno{get;set;}
    public final String RcCopy{get;set;}
    public final String statename{get;set;}
    public final String MakerID{get;set;}
    public final String VehicleId{get;set;}
    public final String VehRegType{get;set;}
     /*
@Method:      IND_MFCValuationRequest
@Created by:  Divya Jawale
@Description: Contructor to initialize the details
@Param:       Id - opportunityId
@Return:      '' 
*/     
    public IND_MFCValuationRequest(RequestWrapper requestWrapper){
        Boolean isImplement = false;
        if(requestWrapper != null){
            Vehicle_Detail__c vehicleDetail = [select Id, Loan_Application__c,Loan_Application__r.Application_number__c,Loan_Application__r.Lead_Number__c,Loan_Application__r.Agent_BL_code__c,Loan_Application__r.Vehicle_Sub_Category__c,Vehicle_SubType__c,Vehicle_SubCategory__c,
           Loan_Application__r.Employee_Name__c,Loan_Application__r.Employee_No__c,Loan_Application__r.Product_Type__c, Loan_Application__r.Owner.Name,Loan_Application__r.Owner.MobilePhone,
                                               Loan_Application__r.Vehicle_Type__c,Purpose_of_purchase__c,Valuer_category__c,Valuer_code__c,Valuer__c,Vehicle_Place_Of_Valuation__c,
                                               Location_Of_Vehicle__c,City__c,Make__c,Model__c,Variant__c,Vehicle_Registration_number__c,Vehicle_type__c,Engine_number__c,Chassis_number__c,
                                               State__c, Product__c,Model_Code__c FROM Vehicle_Detail__c WHERE Loan_Application__c =:requestWrapper.loanApplicationId and id=:requestWrapper.vehicleId WITH SECURITY_ENFORCED LIMIT 1];
            
            List<Product2> product2 =  [Select variant_code__c from Product2 where name =:vehicleDetail.Variant__c and type__c = 'variant' WITH SECURITY_ENFORCED Limit 1]; 
            isImplement = vehicleDetail.Vehicle_SubType__c == 'Implement' ?  true : false;           
             if(!product2.isEmpty()){                       
                      requestWrapper.variantcode=product2[0].variant_code__c;
                    system.debug('variantcode'+requestWrapper.variantcode);                        
                    }
                    else{
                        throw new IND_Exception('Variant not found in product');                  
              }

              String likeClause = '%' + (vehicleDetail.Product__c)?.substring(0,3).toUpperCase()+'%';
              List<Product2> vehTypeQuery =  [Select ProductCode from Product2 
                            where name LIKE :likeClause and type__c = 'Class Of Vehicle' 
                            WITH SECURITY_ENFORCED Limit 1]; 

              if(vehTypeQuery.isEmpty()){ 
                throw new IND_Exception('Product not found in Product Master'); 
              }
            
            Applicant__c app = [SELECT Id,Contact_number__c,Customer_First_Name__c,Customer_Last_Name__c,Email_Id__c 
                                FROM Applicant__c WHERE Opportunity__c =: requestWrapper.loanApplicationId WITH SECURITY_ENFORCED Limit 1]; 
            
            if(vehicleDetail != null && app != null){
                this.Lead_Id = vehicleDetail.Loan_Application__r.Lead_Number__c == null ? '' :vehicleDetail.Loan_Application__r.Lead_Number__c;
                this.Branch = vehicleDetail.Loan_Application__r.Agent_BL_code__c == null ? '' : vehicleDetail.Loan_Application__r.Agent_BL_code__c;
                this.Productcode = vehicleDetail.Loan_Application__r.Product_Type__c == System.Label.TwoWheeler ?'H' : vehicleDetail.Loan_Application__r.Product_Type__c == System.Label.PassengerVehicles ?'C' : vehicleDetail.Loan_Application__r.Product_Type__c == System.Label.Tractor ? 'T' :'' ;
                this.ValuerCategory = requestWrapper.valuerCategory == null? '' :requestWrapper.valuerCategory=='MFC'?'FC':requestWrapper.valuerCategory; 
                this.ValuerCode = vehicleDetail.Valuer_code__c == null ? '' : vehicleDetail.Valuer_code__c;
                this.Valuer = vehicleDetail.Valuer__c == null ?'': vehicleDetail.Valuer__c;
                this.Purpose = 'F'; 
                this.PlaceOfInspection = requestWrapper.placeOfInspection == null ?'': requestWrapper.placeOfInspection;
                this.Location_of_Vehicle = requestWrapper.locationOfVehicle == null ?'': requestWrapper.locationOfVehicle;
                this.Application_Ref_Type = 'AP'; 
                this.Appl_Ref_Deal_No = vehicleDetail.Loan_Application__r.Application_number__c == null ? '' : vehicleDetail.Loan_Application__r.Application_number__c;
                this.CustomerName = app.Customer_First_Name__c == null ? '' : app.Customer_First_Name__c;
                this.ContactPerson = app.Customer_First_Name__c+' '+app.Customer_Last_Name__c;
                this.MobileNo = app.Contact_number__c == null ?'' : app.Contact_number__c;
                this.Emailid = app.Email_Id__c == null ? '' : app.Email_Id__c ;
                this.City= requestWrapper.city == null ?'': requestWrapper.city; 
                this.VehicleCatg= vehicleDetail.Loan_Application__r.Vehicle_Type__c; 
                if(vehicleDetail.Loan_Application__r.Product_Type__c == System.Label.Tractor){
                    this.VehicleSubCatg= vehicleDetail.Vehicle_SubCategory__c == null ? '' : vehicleDetail.Vehicle_SubCategory__c; 
                }else{
                    this.VehicleSubCatg= vehicleDetail.Loan_Application__r.Vehicle_Sub_Category__c == null ? '' : vehicleDetail.Loan_Application__r.Vehicle_Sub_Category__c; 
                }
                this.Makecode= vehicleDetail.Make__c == null ? '' : vehicleDetail.Make__c;
                if(vehicleDetail.Loan_Application__r.Product_Type__c == System.Label.Tractor){
                    this.Model= vehicleDetail.Model_Code__c == null ? '' :vehicleDetail.Model_Code__c; 
                }else{
                    this.Model= vehicleDetail.Model__c == null ? '' :vehicleDetail.Model__c; 
                }
                this.Variantcode= requestWrapper.variantcode;
                this.VehRegNo= vehicleDetail.Vehicle_Registration_number__c; 
                this.Vehtype= vehTypeQuery[0].ProductCode == 'H'  ?'1' : vehTypeQuery[0].ProductCode == 'S' ?'1': vehTypeQuery[0].ProductCode == 'C' ?'3' :vehTypeQuery[0].ProductCode == 'T' ? '5':'' ;
                this.EngineNo= vehicleDetail.Engine_number__c;
                this.ChasisNo= vehicleDetail.Chassis_number__c; 
                this.NameTransferred= '';
                this.CurrentVehicleOwner='';
                this.LienMaerkedIBL= '';
                this.MarkedOn= '';
                this.NowLienNameOf= '';
                this.RequesterName= vehicleDetail.Loan_Application__r.Owner.Name;
                this.RequesterMobilno= vehicleDetail.Loan_Application__r.Owner.MobilePhone;
                this.RcCopy= '';
                this.statename= requestWrapper.state == null ?'': requestWrapper.state;
                this.MakerID= IntegrationUtilities.getMakerId(); 
                this.VehicleId= requestWrapper.variantcode +'_V1';
                this.VehRegType= vehicleDetail.Loan_Application__r.Vehicle_Type__c;
            }
            else{
            throw new IND_Exception(System.Label.OpportunityIdMissing);
        }
        }
        else{
            throw new IND_Exception(System.Label.OpportunityIdMissing);
        }
        validate(System.Label.MFCValuationAPI,isImplement);
        
    }  
     /*Method to get the HTTP request header data
@Method:      getHttpRequestHeaders
@Created by:  Divya Jawale
@Description: Method to get the HTTP request header data
@Param:       ''
@Return:      Header required to callout the service.
*/
     public override Map<String,String> getHttpRequestHeaders(){    
        Map<String,String> requestHeaderMap = Utilities.getHeaders();
        return requestHeaderMap;
    }
    
    /*Method to validate the request data
@Method:      validate
@Created by:  Divya Jawale
@Description: Method to validate the required input details
@Param:       Service name
@Return:      True - If all the validations are passed.
*/
    public override boolean validate(String serviceName,Boolean isImplement){
        List<String> errorMessageList = new List<String>();
        if(String.isBlank(this.Lead_Id)){
            throw new IND_Exception(System.Label.LeadId);
        }
        if(String.isBlank(this.Branch)){
            throw new IND_Exception(System.Label.Branch);
        }
        if(String.isBlank(this.Purpose)){
            throw new IND_Exception(System.Label.Purpose);
        }
        if(String.isBlank(this.PlaceOfInspection)){
            throw new IND_Exception(System.Label.PlaceOfInspection);
        }
        if(String.isBlank(this.Location_of_Vehicle)){
            throw new IND_Exception(System.Label.Location_of_Vehicle);
        }
        if(String.isBlank(this.Application_Ref_Type)){
            throw new IND_Exception(System.Label.Application_Ref_Type);
        }
        if(String.isBlank(this.Appl_Ref_Deal_No)){
            throw new IND_Exception(System.Label.Appl_Ref_Deal_No);
        }
        if(String.isBlank(this.CustomerName)){
            throw new IND_Exception(System.Label.CustomerName);
        }
        if(String.isBlank(this.ContactPerson)){
            throw new IND_Exception(System.Label.ContactPerson);
        }
        if(String.isBlank(this.MobileNo)){
            throw new IND_Exception(System.Label.EnterMobileNumber);
        }
        if(String.isBlank(this.City)){
            throw new IND_Exception(System.Label.City);
        }
        if(String.isBlank(this.VehicleCatg)){
            throw new IND_Exception(System.Label.VehicleCategory);
        }
        if(String.isBlank(this.VehicleSubCatg)){
            throw new IND_Exception(System.Label.VehicleSubCategory);
        }
        if(String.isBlank(this.Makecode)){
            throw new IND_Exception(System.Label.Makecode);
        }
        if(String.isBlank(this.Model)){
            throw new IND_Exception(System.Label.Model);
        }
        if(String.isBlank(this.Variantcode)){
            throw new IND_Exception(System.Label.VarientCode);
        }
        if(String.isBlank(this.EngineNo) && isImplement == false){
            throw new IND_Exception(System.Label.EngineNo);
        }
        if(String.isBlank(this.ChasisNo) && isImplement == false){
            throw new IND_Exception(System.Label.ChasisNo);
        }
        if(String.isBlank(this.RequesterName)){
            throw new IND_Exception(System.Label.RequesterName);
        }
        if(String.isBlank(this.RequesterMobilno)){
            throw new IND_Exception(System.Label.RequesterMobilno);
        }
        if(String.isBlank(this.MakerID)){
            throw new IND_Exception(System.Label.MakerID);
        }
        if(String.isBlank(this.VehicleId)){
            throw new IND_Exception(System.Label.VehicleId);
        }
        if(String.isBlank(this.VehRegType)){
            throw new IND_Exception(System.Label.VehRegType);
        }
        if(String.isBlank(this.statename)){
            throw new IND_Exception(System.Label.State);
        }
        if(String.isBlank(this.VehRegNo) && isImplement == false){
            throw new IND_Exception(System.Label.VehicleRegistrationNumber);
        }
        return true;
    }    
    
}