ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/applicant_number__c.field-meta.xml
<CustomField>
    <fullName>applicant_number__c</fullName>
    <formula>IF( ISPICKVAL(Applicant_Type__c , &quot;Borrower&quot;), &quot;B&quot;+Id , &quot;C&quot;+Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>applicant number</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-borrower</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Lead_Number__c.field-meta.xml
<CustomField>
    <fullName>Lead_Number__c</fullName>
    <formula>Opportunity__r.Lead_number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Id</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>applicant_Type__c</fullName>
    <formula>TEXT(Applicant__r.Applicant_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Type</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Seller&apos;s Passbook</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Bank Statement</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Cancel Cheque</fullName>
            </value>
            <value>
                <fullName>Driving Licence</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Voter Id</fullName>
            </value>
            <value>
                <fullName>Form 60</fullName>
            </value>
            <value>
                <fullName>Customer Image</fullName>
            </value>
            <value>
                <fullName>Aadhaar</fullName>
            </value>
            <value>
                <fullName>Vehicle Images</fullName>
            </value>
            <value>
                <fullName>RC Document</fullName>
            </value>
            <value>
                <fullName>SPR</fullName>
            </value>
            <value>
                <fullName>APR</fullName>
            </value>
            <value>
                <fullName>Electronic Bill</fullName>
                <label>Electricity Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Water Bill</fullName>
                <label>Water Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Vehicle Insurance Policy</fullName>
            </value>
            <value>
                <fullName>Vehicle Image</fullName>
            </value>
            <value>
                <fullName>Bank Statement</fullName>
            </value>
            <value>
                <fullName>Insurance Policy Doc</fullName>
            </value>
            <value>
                <fullName>Valuation Report</fullName>
            </value>
            <value>
                <fullName>Office FI</fullName>
            </value>
            <value>
                <fullName>Land Photo</fullName>
            </value>
            <value>
                <fullName>Patta Document</fullName>
            </value>
            <value>
                <fullName>Rent Agreement/Reciept</fullName>
            </value>
            <value>
                <fullName>Pension Document</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Engine Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Chassis Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Selfie with Vehicle-uploaded during verification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/KYC_City__c.field-meta.xml
<CustomField>
    <fullName>KYC_City__c</fullName>
    <label>KYC City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/KYC_DOB__c.field-meta.xml
<CustomField>
    <fullName>KYC_DOB__c</fullName>
    <label>KYC DOB</label>
    <type>Date</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Opportunity_Relation__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Relation__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Proof_of_Address_POA__c.field-meta.xml
<CustomField>
    <fullName>Proof_of_Address_POA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proof of Address (POA)</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Proof_of_Identity_POI__c.field-meta.xml
<CustomField>
    <fullName>Proof_of_Identity_POI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proof of Identity (POI)</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Non-Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Date_of_Incorporation__c.field-meta.xml
<CustomField>
    <fullName>Date_of_Incorporation__c</fullName>
    <label>Date of Incorporation</label>
    <type>Date</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Lead_number__c.field-meta.xml
<CustomField>
    <fullName>Lead_number__c</fullName>
    <label>Lead Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/classes/IND_AMLCheckRequest.cls
/*------------------------------------------------------------
Author: Vaishnavi Gadewar
Company: Persistent Systems
Description: This class is wrapper class for the AML Check Request
Test Class: IND_AMLCheckService_Test
History
Date            Author              Comments
------------------------------------------------------------- 
28-12-2021    Vaishnavi Gadewar         Created
13-1-2022     Satyam More				Modified
------------------------------------------------------------*/

public class IND_AMLCheckRequest extends ParentAPIRequest {
    public string Application_No {get;set;}
    public string ruleName {get;set;}
    public List<Fields> fields {get;set;}
    public class Fields {
        public string name {get;set;}
        public string value {get;set;}
        
    }
    public IND_AMLCheckRequest(Applicant__c app){  
        try{
            if(app!=null){
            
                this.Application_No = app.Opportunity__r.Lead_number__c+'_'+app.Applicant_Number__c; //'AC12313244_13423';
                this.ruleName = System.Label.BRANCH_CUSTOMER_WL;
                
                List<fields> fieldList = new List<fields>();
                fields fi = new fields();
                fi.name = 'name';
                fi.value = app.Name;
                
                fields fi1 = new fields();
                fi1.name = 'nationality';
                fi1.value = 'India';
                
                fields fi2 = new fields();
                fi2.name = 'dob';
                fields fi3 = new fields();
                fi3.name = 'resAddrCity';
                
                if(!app.Documents__r.isEmpty()){
                    for(Documents__c doc : app.Documents__r) {
                        if(app.Opportunity__r.Product_Type__c == System.Label.Tractor && app.Opportunity__r.Customer_Type__c == 'Non-Individual' && app.Applicant_Type__c == System.Label.Borrower && doc.Document_Type__c == System.Label.PanCards && doc.KYC_DOB__c != null){
                            //fi2.value = DateTime.newInstance(doc.KYC_DOB__c.year(),doc.KYC_DOB__c.month(),doc.KYC_DOB__c.day()).format('yyyy-MM-dd');
                            fi2.value = DateTime.newInstance(app.Opportunity__r.Date_of_Incorporation__c.year(),app.Opportunity__r.Date_of_Incorporation__c.month(),app.Opportunity__r.Date_of_Incorporation__c.day()).format('yyyy-MM-dd');
                        }else if(doc.Proof_of_Identity_POI__c == true) {
                            fi2.value = DateTime.newInstance(doc.KYC_DOB__c.year(),doc.KYC_DOB__c.month(),doc.KYC_DOB__c.day()).format('yyyy-MM-dd');  
                        }
                        if(doc.Proof_of_Address_POA__c == true || (app.Opportunity__r.Product_Type__c == System.Label.Tractor && app.Opportunity__r.Customer_Type__c == 'Non-Individual' && app.Applicant_Type__c == System.Label.Borrower && String.isNotBlank(doc.KYC_City__c) && doc.Document_Type__c == System.Label.GST)) {
                            fi3.value = doc.KYC_City__c;
                        }
                    }  
                }else{
                    throw new IND_Exception(System.Label.NoKYCFound);
                }   
    
                fieldList.add(fi);
                fieldList.add(fi1);
                fieldList.add(fi2);
                fieldList.add(fi3);
                fields=fieldList;
                fields=fields;
            }
            validate(System.Label.AMLCheck);
        } catch(Exception e){
            ErrorLoggerUtil.logErrorEvent('IND_AMlCheckrequest', 'IND_AMLCheckRequest', System.Label.Apex, e);
            throw new AuraHandledException(e.getMessage());
        }
    }    
    
    
    public override Map<String,String> getHttpRequestHeaders(){    
        Map<String,String> requestHeaderMap = Utilities.getHeaders();
        return requestHeaderMap;
    }
    
    
    public override boolean validate(String serviceName){
        
        if(String.isBlank(this.Application_No)){
            throw new IND_Exception(System.Label.ApplicationNo);
        }
        if(String.isBlank(this.ruleName)){
            throw new IND_Exception(System.Label.ruleName);
        }
        
        return true;
    }
}