ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/applicant_number__c.field-meta.xml
<CustomField>
    <fullName>applicant_number__c</fullName>
    <formula>IF( ISPICKVAL(Applicant_Type__c , &quot;Borrower&quot;), &quot;B&quot;+Id , &quot;C&quot;+Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>applicant number</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/CIC_No__c.field-meta.xml
<CustomField>
    <fullName>CIC_No__c</fullName>
    <description>Used to save value for CRIFF</description>
    <label>CIC No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Lead_Number__c.field-meta.xml
<CustomField>
    <fullName>Lead_Number__c</fullName>
    <formula>Opportunity__r.Lead_number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Id</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/CIBIL_Details__c/CIBIL_Details__c.object-meta.xml
<CustomObject>
    <label>CIBIL Details</label>
    <nameField>
        <displayFormat>CIBIL - {000}</displayFormat>
        <label>CIBIL Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CIBIL Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/CIBIL_Details__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <description>This field represents the M-D relation with Applicant object.</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>CIBIL_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/CIBIL_Details__c/fields/CIC_No__c.field-meta.xml
<CustomField>
    <fullName>CIC_No__c</fullName>
    <description>This field will be used to store the CIC No coming from cibil api.</description>
    <label>CIC No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Lead_number__c.field-meta.xml
<CustomField>
    <fullName>Lead_number__c</fullName>
    <label>Lead Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/classes/IND_CAMPortfolioRequest.cls
/*------------------------------------------------------------
Author:        Thilak Bondiga
Company:       Persistent Systems
Description:   This class is wrapper class for the CAM Portfolio API request 
Test Class:     
History
Date            Author              Comments
-------------------------------------------------------------
12-21-2021      Thilak Bondiga       Created
------------------------------------------------------------*/
public class IND_CAMPortfolioRequest extends ParentAPIRequest {
	
    public string maker_Id {get;set;}
    public string Product_Id {get;set;}  
    public string lead_Id {get;set;}
    public string Cic_No {get;set;}
    
    
    
    // @Method:      IND_CAMPortfolioRequest
    // @Created by:  Thilak Bondiga
    // @Description: Contructor to initialize the details
    // @Param:       Object applicant Record
    // @Return:      ''
    public IND_CAMPortfolioRequest(Applicant__c app,String loanAppId){
        List<CIBIL_Details__c> cibilDetailList = [SELECT Id, CIC_No__c from CIBIL_Details__c WHERE Applicant__c  =: app.Id];

        this.Maker_Id = IntegrationUtilities.getMakerId();
        this.Product_Id = app.Opportunity__r.Product_Type__c!=null && app.Opportunity__r.Product_Type__c == 'Two Wheeler' ? 'H' : app.Opportunity__r.Product_Type__c == 'Passenger Vehicles' ? 'C' :'' ; //H or C
        this.Lead_Id = app.Opportunity__r.Lead_number__c + '_'+ app.applicant_number__c;  
        this.Cic_No = cibilDetailList.size() > 0 && cibilDetailList[0].CIC_No__c != null ? String.valueOf(cibilDetailList[0].CIC_No__c) : '';
        
        validate(System.Label.CAMPortfolio);
    }    
    
    // @Method:      getHttpRequestHeaders
    // @Created by:  Thilak Bondiga
    // @Description: Method to get the HTTP request header data
    // @Param:       ''
    // @Return:      Header required to callout the service.
    public override Map<String,String> getHttpRequestHeaders(){    
        Map<String,String> requestHeaderMap = Utilities.getHeaders();
        return requestHeaderMap;
    }
    
    // @Method:      validate
    // @Created by:  Thilak Bondiga
    // @Description: Method to validate the required input details
    // @Param:       Service name
    // @Return:      True - If all the validations are passed.
   
    public override boolean validate(String serviceName){
        
        if(this.Product_Id == null && String.isBlank(this.Product_Id)){
            throw new IND_Exception(System.Label.ProductId);
        }
        if(this.Lead_Id == null && String.isBlank(this.Lead_Id)){
            throw new IND_Exception(System.Label.Lead_IDError);
        }        
        if(this.Maker_Id == null && String.isBlank(this.Maker_Id)){
            throw new IND_Exception(System.Label.Maker_IdError);
        }
        if(this.Cic_No == null && String.isBlank(this.Cic_No)){
            throw new IND_Exception(System.Label.CIC_IdError);
        }
        
        return true;
    }
}