ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/DocAuth_Application_Id__c.field-meta.xml
<CustomField>
    <fullName>DocAuth_Application_Id__c</fullName>
    <label>DocAuth Application Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Lead_Number__c.field-meta.xml
<CustomField>
    <fullName>Lead_Number__c</fullName>
    <formula>Opportunity__r.Lead_number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Id</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/DocAuth_Application_Id__c.field-meta.xml
<CustomField>
    <fullName>DocAuth_Application_Id__c</fullName>
    <label>DocAuth Application Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Lead_number__c.field-meta.xml
<CustomField>
    <fullName>Lead_number__c</fullName>
    <label>Lead Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC - Copy/force-app/main/default/classes/IND_RunEmiEngineService_Test.cls
/*------------------------------------------------------------
Author:        Satyam More
Company:       Persistent Systems
Description:   Test class created to validate the IND_RunEmiEngineRequest IND_RunEmiEngineService IND_RunEmiEngineRequest class
History
Date            Author              Comments
-------------------------------------------------------------
23-12-2021      Satyam More       Created
------------------------------------------------------------*/
@isTest(SeeAllData=false)
public class IND_RunEmiEngineService_Test {
    
    
@isTest
    public static void testRunEmiEngineService(){
        
        try{   
            
            Profile p = [SELECT Id FROM Profile WHERE Name='CMU'];
            system.debug('p'+ p);
    		User u = new User(Alias = 'standt', Email='standarduser@testorg.com',MobilePhone = '9999999999',
					EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
					LocaleSidKey='en_US', ProfileId = p.Id,
					TimeZoneSidKey='America/Los_Angeles',
					UserName='standarduser4@testorg.com.psdev1');
            insert u;
            
            Opportunity opp = TestDataUtility.createTestOpportunityforRunEmiEngineApi(false);
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            Applicant__c applicant = TestDataUtility.createTestApplicant(false);
            applicant.Opportunity__c=opp.Id;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
            
            String runEmiEngine = '{"leadId":"'+opp.Lead_number__c+'" ,"applicationId":"'+applicant.DocAuth_Application_Id__c+'", "cicNo":"18122021376201"}';
            
            Continuation con = (Continuation)IntegrationEngine.doRunEmiEngineCallout(runEmiEngine);
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('{"JData":"tQSovByAVZugG789TkA1n/ymHPZ0rtg6Hw64sXtlrU/BydfGS8Tcy8QLc2KYwHodCGODkMUnPp+YAp0eoDdvnlEIdmnZb/WTRMRQ9Dwinwiyv5h0VBVUwsFEQRD1iilCsiym6v7zvy6Rn4++T9iPxyO8jil8pBBye3OT+/s86Ig="}');
            response.setStatusCode(200);
            
            String continuationLabel = IntegrationEngine.continuationLabel;
            List<String> labels = new List<String>{continuationLabel};
            Object continuationState= IntegrationEngine.continuationState;
            
            String runEmiEngineCallOutResponse;
             system.runAs(u){
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            runEmiEngineCallOutResponse= (String)IntegrationEngine.processRunEmiEngineCalloutResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
             }
            String responseExpected ='{"body":null,"Upper_Emi_Cap":"15000","Outstanding_Amt":"40000","Lower_Emi_Cap":"20000","Loan_Type":"Personal Loan"}';
            System.assertEquals(responseExpected, runEmiEngineCallOutResponse, 'SUCCESS');
            
        } catch(Exception ex){

        }
    }
   
    @isTest
    public static void testRunEmiEngineService2(){
        
        try{   
            
            Opportunity opp = TestDataUtility.createTestOpportunityforRunEmiEngineApi(false);
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            Applicant__c applicant = TestDataUtility.createTestApplicant(false);
            applicant.Opportunity__c=opp.Id;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
            
            String runEmiEngine = '{"leadId":"" ,"applicationId":"'+applicant.DocAuth_Application_Id__c+'", "cicNo":"18122021376201"}';
            
            Continuation con = (Continuation)IntegrationEngine.doRunEmiEngineCallout(runEmiEngine);
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('{"JData":"tQSovByAVZugG789TkA1n/ymHPZ0rtg6Hw64sXtlrU/BydfGS8Tcy8QLc2KYwHodCGODkMUnPp+YAp0eoDdvnlEIdmnZb/WTRMRQ9Dwinwiyv5h0VBVUwsFEQRD1iilCsiym6v7zvy6Rn4++T9iPxyO8jil8pBBye3OT+/s86Ig="}');
            response.setStatusCode(200);
            
            String continuationLabel = IntegrationEngine.continuationLabel;
            List<String> labels = new List<String>{continuationLabel};
            Object continuationState= IntegrationEngine.continuationState;
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            String runEmiEngineCallOutResponse= (String)IntegrationEngine.processRunEmiEngineCalloutResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
            String responseExpected ='{"body":null,"Upper_Emi_Cap":"15000","Outstanding_Amt":"40000","Lower_Emi_Cap":"20000","Loan_Type":"Personal Loan"}';
            System.assertEquals(responseExpected, runEmiEngineCallOutResponse, 'SUCCESS');
            
        } catch(Exception ex){
            System.assertEquals(ex.getMessage(),'Applicant data not found.', 'Exception');
        }
    }
    
    
    @isTest
    public static void testRunEmiEngineService3(){
        
        try{   
            
            Opportunity opp = TestDataUtility.createTestOpportunityforRunEmiEngineApi(false);
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            Applicant__c applicant = TestDataUtility.createTestApplicant(false);
            applicant.Opportunity__c=opp.Id;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
            
            String runEmiEngine = '{"leadId":"'+opp.Lead_number__c+'" ,"applicationId":"", "cicNo":"18122021376201"}';
            
            Continuation con = (Continuation)IntegrationEngine.doRunEmiEngineCallout(runEmiEngine);
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('{"JData":"tQSovByAVZugG789TkA1n/ymHPZ0rtg6Hw64sXtlrU/BydfGS8Tcy8QLc2KYwHodCGODkMUnPp+YAp0eoDdvnlEIdmnZb/WTRMRQ9Dwinwiyv5h0VBVUwsFEQRD1iilCsiym6v7zvy6Rn4++T9iPxyO8jil8pBBye3OT+/s86Ig="}');
            response.setStatusCode(200);
            
            String continuationLabel = IntegrationEngine.continuationLabel;
            List<String> labels = new List<String>{continuationLabel};
            Object continuationState= IntegrationEngine.continuationState;
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            String runEmiEngineCallOutResponse= (String)IntegrationEngine.processRunEmiEngineCalloutResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
            String responseExpected ='{"body":null,"Upper_Emi_Cap":"15000","Outstanding_Amt":"40000","Lower_Emi_Cap":"20000","Loan_Type":"Personal Loan"}';
            System.assertEquals(responseExpected, runEmiEngineCallOutResponse, 'SUCCESS');
            
        } catch(Exception ex){
            System.assertEquals(ex.getMessage(),'Applicant data not found.', 'Exception');
        }
    }
    
    
    @isTest
    public static void testRunEmiEngineService4(){
        
        try{   
            
            Opportunity opp = TestDataUtility.createTestOpportunityforRunEmiEngineApi(false);
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            Applicant__c applicant = TestDataUtility.createTestApplicant(false);
            applicant.Opportunity__c=opp.Id;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
            
            String runEmiEngine = '{"leadId":"'+opp.Lead_number__c+'" ,"applicationId":"'+applicant.DocAuth_Application_Id__c+'", "cicNo":""}';
            
            Continuation con = (Continuation)IntegrationEngine.doRunEmiEngineCallout(runEmiEngine);
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('{"JData":"tQSovByAVZugG789TkA1n/ymHPZ0rtg6Hw64sXtlrU/BydfGS8Tcy8QLc2KYwHodCGODkMUnPp+YAp0eoDdvnlEIdmnZb/WTRMRQ9Dwinwiyv5h0VBVUwsFEQRD1iilCsiym6v7zvy6Rn4++T9iPxyO8jil8pBBye3OT+/s86Ig="}');
            response.setStatusCode(200);
            
            String continuationLabel = IntegrationEngine.continuationLabel;
            List<String> labels = new List<String>{continuationLabel};
            Object continuationState= IntegrationEngine.continuationState;
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            String runEmiEngineCallOutResponse= (String)IntegrationEngine.processRunEmiEngineCalloutResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
            String responseExpected ='{"body":null,"Upper_Emi_Cap":"15000","Outstanding_Amt":"40000","Lower_Emi_Cap":"20000","Loan_Type":"Personal Loan"}';
            System.assertEquals(responseExpected, runEmiEngineCallOutResponse, 'SUCCESS');
            
        } catch(Exception ex){
            System.assertEquals(ex.getMessage(),'Applicant data not found.', 'Exception');
        }
    }
    
    @isTest
    public static void testRunEmiEngineService5(){
        
        try{   
            
            Opportunity opp = TestDataUtility.createTestOpportunityforRunEmiEngineApi(false);
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            Applicant__c applicant = TestDataUtility.createTestApplicant(false);
            applicant.Opportunity__c=opp.Id;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
            
            String runEmiEngine = '{"leadId":"'+opp.Lead_number__c+'" ,"applicationId":"'+applicant.DocAuth_Application_Id__c+'", "cicNo":"18122021376201"}';
            
            Continuation con = (Continuation)IntegrationEngine.doRunEmiEngineCallout(runEmiEngine);
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('{"JData":"tQSovByAVZugG789TkA1n/ymHPZ0rtg6Hw64sXtlrU/BydfGS8Tcy8QLc2KYwHodCGODkMUnPp+YAp0eoDdvnlEIdmnZb/WTRMRQ9Dwinwiyv5h0VBVUwsFEQRD1iilCsiym6v7zvy6Rn4++T9iPxyO8jil8pBBye3OT+/s86Ig="}');
            response.setStatusCode(500);
            
            String continuationLabel = IntegrationEngine.continuationLabel;
            List<String> labels = new List<String>{continuationLabel};
            Object continuationState= IntegrationEngine.continuationState;
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            String runEmiEngineCallOutResponse= (String)IntegrationEngine.processRunEmiEngineCalloutResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
            String responseExpected ='{"body":null,"Upper_Emi_Cap":"15000","Outstanding_Amt":"40000","Lower_Emi_Cap":"20000","Loan_Type":"Personal Loan"}';
            System.assertEquals(responseExpected, runEmiEngineCallOutResponse, 'Fail');
            
        } catch(Exception ex){
            System.assertEquals(ex.getMessage(),'Applicant data not found.', 'Exception');
        }
    } 
    
    
             @isTest
    public static void validateException(){
        try{
            IND_RunEmiEngineService.getRunEmiEngineCallOutRequest(null, null);
        }catch(Exception pEx){
            System.assert(pEx.getMessage() != null);
        }
        
    }
    
    
}