ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/Deal_Number__c.object-meta.xml
<CustomObject>
    <description>The custom object created for Deal Number generation</description>
    <label>Deal Number</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <formula>DNField1__c  +  DNField2__c  +  ProductCode__c  +  DNField3__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal Number</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/fields/DNField1__c.field-meta.xml
<CustomField>
    <fullName>DNField1__c</fullName>
    <description>DNField1</description>
    <label>DNField1</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/fields/DNField2__c.field-meta.xml
<CustomField>
    <fullName>DNField2__c</fullName>
    <description>DNField2</description>
    <label>DNField2</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Numbers</relationshipLabel>
    <relationshipName>Deal_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Request</fullName>
            </value>
            <value>
                <fullName>RC Upload</fullName>
            </value>
            <value>
                <fullName>Business Payment Details</fullName>
            </value>
            <value>
                <fullName>Insurance Details</fullName>
            </value>
            <value>
                <fullName>New/Used Vehicle Details</fullName>
            </value>
            <value>
                <fullName>Beneficiary Details</fullName>
            </value>
            <value>
                <fullName>Key Fact Statement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number_Setting__c/Deal_Number_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Deal Number Setting</label>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number_Setting__c/fields/MDNField1__c.field-meta.xml
<CustomField>
    <fullName>MDNField1__c</fullName>
    <label>MDNField1</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number_Setting__c/fields/MDNField2__c.field-meta.xml
<CustomField>
    <fullName>MDNField2__c</fullName>
    <label>MDNField2</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/Final_Term__c.object-meta.xml
<CustomObject>
    <description>To store Final term module data.</description>
    <label>Final Term</label>
    <nameField>
        <displayFormat>FT-{000000}</displayFormat>
        <label>Final Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan_Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Final_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>Vehicle_Detail__c</referenceTo>
    <relationshipLabel>Final Terms</relationshipLabel>
    <relationshipName>Final_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/InsuranceDetails__c/InsuranceDetails__c.object-meta.xml
<CustomObject>
    <label>Insurance Details</label>
    <nameField>
        <label>Insurance Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/InsuranceDetails__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Insurance_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/InsuranceDetails__c/fields/Funded_Non_funded__c.field-meta.xml
<CustomField>
    <fullName>Funded_Non_funded__c</fullName>
    <label>Funded/Non funded</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Non-Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/InsuranceDetails__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Insurance_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/InsuranceDetails__c/fields/Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>Vehicle_Detail__c</referenceTo>
    <relationshipLabel>Insurance Details</relationshipLabel>
    <relationshipName>Insurance_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Application_number__c.field-meta.xml
<CustomField>
    <fullName>Application_number__c</fullName>
    <label>Application number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Ben_Code__c.field-meta.xml
<CustomField>
    <fullName>Ben_Code__c</fullName>
    <label>Ben Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <description>IndusInd deal number</description>
    <label>Deal Number</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Total_Funded_Premium__c.field-meta.xml
<CustomField>
    <fullName>Total_Funded_Premium__c</fullName>
    <description>Sum of Insurance details &apos;Funded Premiums&apos;</description>
    <label>Total Funded Premium</label>
    <summarizedField>InsuranceDetails__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>InsuranceDetails__c.Funded_Non_funded__c</field>
        <operation>equals</operation>
        <value>Funded</value>
    </summaryFilterItems>
    <summaryForeignKey>InsuranceDetails__c.Loan_Application__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <label>Variant</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Product2/fields/Asset_Category__c.field-meta.xml
<CustomField>
    <fullName>Asset_Category__c</fullName>
    <label>Asset Category</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Product2/fields/External_Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>External_Reference_Id__c</fullName>
    <externalId>true</externalId>
    <label>External Reference Id</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Product2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Make</fullName>
            </value>
            <value>
                <fullName>Model</fullName>
            </value>
            <value>
                <fullName>Variant</fullName>
            </value>
            <value>
                <fullName>Class Of Vehicle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Product2/recordTypes/Model.recordType-meta.xml
<RecordType>
    <fullName>Model</fullName>
    <active>true</active>
    <label>Model</label>
</RecordType>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/Maker_Id__c.field-meta.xml
<CustomField>
    <fullName>Maker_Id__c</fullName>
    <label>Maker Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/Vehicle_Detail__c.object-meta.xml
<CustomObject>
    <label>Vehicle Detail</label>
    <nameField>
        <displayFormat>VD-{00000}</displayFormat>
        <label>Vehicle Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Ben_Code__c.field-meta.xml
<CustomField>
    <fullName>Ben_Code__c</fullName>
    <label>Ben Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Number</label>
    <referenceTo>Deal_Number__c</referenceTo>
    <relationshipLabel>Vehicle Details</relationshipLabel>
    <relationshipName>Vehicle_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <description>Vehicle Insurance and Vehicle Valuation data</description>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Vehicle_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <label>Variant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/IND_RCLimitCheckService_Test.cls
/*------------------------------------------------------------
Author:        Satyam More
Company:       Persistent Systems
Description:   Test class created to validate the IND_ADAuthenticationRequest IND_ADAuthenticationService IND_ADAuthenticationResponse class
History
Date            Author              Comments
-------------------------------------------------------------
10-12-2021      Satyam More       Created
------------------------------------------------------------*/

@isTest(SeeAllData=false)
public class IND_RCLimitCheckService_Test {    
    @isTest
    public static void testRCLimitCheckService(){
        
        try{   
            
            Profile p = [SELECT Id FROM Profile WHERE Name='IBL Business Executive'];
            system.debug('p'+ p);
    		User u = new User(Alias = 'A ANBU', Email='standarduser@testorg.com',
					EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
					LocaleSidKey='en_US', ProfileId = p.Id,Maker_Id__c = '234',
                              MobilePhone = '9701498575',
					TimeZoneSidKey='America/Los_Angeles',
					UserName='standarduserABC40@testorg.com.psdev1');
            insert u;
            
            System.runAs(u){
                
            Opportunity opp = TestDataUtility.createTestOpportunity211(false);
            opp.Application_number__c = 'A11102302288';
                //opp.Total_Funded_Premium__c = '10000';
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
                
            InsuranceDetails__c insuranceDetails = TestDataUtility.createInsuranceDetails(false,opp);
            insuranceDetails.Funded_Non_funded__c = 'Funded';
            insuranceDetails.Amount__c = 15000;
			if (Schema.sObjectType.Opportunity.isCreateable()){
                insert insuranceDetails;
            }                
                
            Applicant__c applicant = TestDataUtility.createTestApplicant(false);
            applicant.Opportunity__c=opp.Id;
            String loanAppId = applicant.Opportunity__c;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
            
             Vehicle_Detail__c vc2 = new Vehicle_Detail__c();
        vc2.Loan_Application__c = applicant.Opportunity__c;
        vc2.Ben_Code__c = 'testveh';
        vc2.Product__c='TW New';
        vc2.Variant__c = 'twowheeler';
        vc2.Product__c = 'Two Wheeler';
        insert vc2;
        
        Product2 pd1 = new Product2();
        pd1.Asset_Category__c = 'te';
        pd1.Name = vc2.Variant__c;
        pd1.Type__c = 'Model';
        pd1.External_Reference_Id__c = '58568568';
        insert pd1;
                
                Final_Term__c finalTerm = TestDataUtility.createfinalTerm(false,opp);
                if (Schema.sObjectType.Final_Term__c.isCreateable()){
                	insert finalTerm;
            	}
            /*Deal_Number_Setting__c dlNumberSetting= new Deal_Number_Setting__c();
            dlNumberSetting.Name = System.Label.Tractor;
            dlNumberSetting.MDNField1__c ='AB';
            dlNumberSetting.MDNField2__c =2;
            insert dlNumberSetting;
            system.debug('Deal Setting'+ dlNumberSetting);
            
            Deal_Number__c dl = new Deal_Number__c();
            dl.Loan_Application__c = opp.Id;    
            dl.DNField1__c = dlNumberSetting.MDNField1__c;
            dl.DNField2__c = String.valueOf(dlNumberSetting.MDNField2__c);
            dl.Sub_Stage__c = 'test';
            insert dl;   */         
            
            System.debug('insert pd1');
           // String verifyRequest = '{ "Application_No": "AC4969614_85523017724", "Vehicle_Id": "MRBALENO3_V1", "Ben_Code": "BEN000951", "Product": "Two Wheeler" }';
            
            Continuation con = (Continuation)IntegrationEngine.doRCLimitCheckCallout(applicant.Id,loanAppId, 'dealer');
            System.debug('Continuation con' +con);
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('{"JData":"O9V0ilOke9HI78UDCvUn5aYezfrQu2V0oM7Kuba4YvV3E06ktIqmhghRj71mXtUY4hdfZ2AJM1UK6dz92k72h0E9y1YG3ymXqIHKu/G5oTaTatM4zeyrt+v8j9/+kBI1gMVta7qPHWrq0chSx/J7NyheQKa8nQMjvWfXPkRpGtjkj/eeILTGWdkpT12l9RVH"}');
            response.setStatusCode(200);
            System.debug('response' +response);
            String continuationLabel = IntegrationEngine.continuationLabel;
            List<String> labels = new List<String>{continuationLabel};
            Object continuationState= IntegrationEngine.continuationState;
            System.debug('continuationState' +continuationState);
            String callOutResponse;
           
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            callOutResponse= (String)IntegrationEngine.processRCLimitCheckAPIResponse(labels, IntegrationEngine.continuationState);
               System.debug('callOutResponse' +callOutResponse);  
            Test.stopTest();
            
            //String responseExpected ='{"response":{"status":"SUCCESS","respDesc":"Check RC Limit","content":[{"No_Of_Proposals_Available":"1","Available_Disbursal_Amount":"10000.00","Pending_Flag":"Y","Payment_To_DSA_Flag":"N"}]}}';
            String responseExpected ='{"body":null,"response":null}';
            //System.assertEquals(responseExpected, callOutResponse);
             
            }
        } catch(Exception ex){
            System.assertEquals(ex.getMessage(),'Please enter Applicant Id');
        }
    }
     
    @isTest
    public static void testRCLimitCheckService1(){
        
        try{   
            
           Profile p = [SELECT Id FROM Profile WHERE Name='IBL Business Executive'];
            system.debug('p'+ p);
    		User u = new User(Alias = 'A ANBU', Email='standarduser@testorg.com',
					EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
					LocaleSidKey='en_US', ProfileId = p.Id,Maker_Id__c = '234',
                              MobilePhone = '9701498575',
					TimeZoneSidKey='America/Los_Angeles',
					UserName='standarduserABC40@testorg.com.psdev1');
            insert u;
            system.runAs(u){
            Opportunity opp = TestDataUtility.createTestOpportunity211(false);
            opp.Application_number__c = 'A11102302288';
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            Applicant__c applicant = TestDataUtility.createTestApplicant(false);
            applicant.Opportunity__c=opp.Id;
            String loanAppId = applicant.Opportunity__c;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
                
                Final_Term__c finalTerm = TestDataUtility.createfinalTerm(false,opp);
                if (Schema.sObjectType.Final_Term__c.isCreateable()){
                	insert finalTerm;
            	}
            
             Vehicle_Detail__c vc2 = new Vehicle_Detail__c();
        vc2.Loan_Application__c = opp.Id;
        vc2.Ben_Code__c = 'BEN000951';
        vc2.Product__c='TW New';
        vc2.Variant__c = 'twowheeler';
        vc2.Product__c = 'Two Wheeler';
        insert vc2;
        
        Product2 pd1 = new Product2();
        pd1.Asset_Category__c = 'te';
        pd1.Name = vc2.Variant__c;
        pd1.Type__c = 'Model';
        pd1.External_Reference_Id__c = '58568568';
        insert pd1;
    
            
           // String verifyRequest = '{ "Application_No": "AC4969614_85523017724", "Vehicle_Id": "MRBALENO3_V1", "Ben_Code": "BEN000951", "Product": "Two Wheeler" }';
            
            Continuation con = (Continuation)IntegrationEngine.doRCLimitCheckCalloutForDSAOrDealer(applicant.Id,loanAppId,'Dealer','dealer');
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('{"JData":"O9V0ilOke9HI78UDCvUn5aYezfrQu2V0oM7Kuba4YvV3E06ktIqmhghRj71mXtUY4hdfZ2AJM1UK6dz92k72h0E9y1YG3ymXqIHKu/G5oTaTatM4zeyrt+v8j9/+kBI1gMVta7qPHWrq0chSx/J7NyheQKa8nQMjvWfXPkRpGtjkj/eeILTGWdkpT12l9RVH"}');
            response.setStatusCode(200);
            
            String continuationLabel = IntegrationEngine.continuationLabel;
            List<String> labels = new List<String>{continuationLabel};
            Object continuationState= IntegrationEngine.continuationState;
            
            String callOutResponse;
             
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            callOutResponse= (String)IntegrationEngine.processRCLimitCheckAPIResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
             
            //String responseExpected ='{"response":{"status":"SUCCESS","respDesc":"Check RC Limit","content":[{"No_Of_Proposals_Available":"1","Available_Disbursal_Amount":"10000.00","Pending_Flag":"Y","Payment_To_DSA_Flag":"N"}]}}';
            String responseExpected ='{"body":null,"response":null}';
            System.assertEquals(responseExpected, callOutResponse);
            }
        } catch(Exception ex){
          //  System.assertEquals(ex.getMessage(),'Please enter Applicant Id');
        }
    }
    @isTest
    public static void testRCLimitCheckService2(){
        try{
             Profile p = [SELECT Id FROM Profile WHERE Name='IBL Business Executive'];
            system.debug('p'+ p);
    		User u = new User(Alias = 'A ANBU', Email='standarduser@testorg.com',
					EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
					LocaleSidKey='en_US', ProfileId = p.Id,Maker_Id__c = '234',
                              MobilePhone = '9701498575',
					TimeZoneSidKey='America/Los_Angeles',
					UserName='standarduserABC40@testorg.com.psdev1');
            insert u;
            system.runAs(u){
            Opportunity opp = TestDataUtility.createTestOpportunity211(false);
            opp.Application_number__c = 'A11102302288';
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            Applicant__c applicant = TestDataUtility.createTestApplicant(false);
            applicant.Opportunity__c=opp.Id;
            String loanAppId = applicant.Opportunity__c;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
                
               /* Final_Term__c finalTerm = TestDataUtility.createfinalTerm(false,opp);
                if (Schema.sObjectType.Final_Term__c.isCreateable()){
                	insert finalTerm;
            	}*/
            
        Vehicle_Detail__c vc2 = new Vehicle_Detail__c();
        vc2.Loan_Application__c = opp.Id;
        vc2.Ben_Code__c = 'BEN000951';
        vc2.Product__c='TW New';
        vc2.Variant__c = 'twowheeler';
        vc2.Product__c = 'Two Wheeler';
        insert vc2;
        
        Product2 pd1 = new Product2();
        pd1.Asset_Category__c = 'te';
        pd1.Name = vc2.Variant__c;
        pd1.Type__c = 'Model';
        pd1.External_Reference_Id__c = '58568568';
        insert pd1;
         
           // String verifyRequest = '{ "Application_No": "AC4969614_85523017724", "Vehicle_Id": "MRBALENO3_V1", "Ben_Code": "BEN000951", "Product": "Two Wheeler" }';
                
            Continuation con = (Continuation)IntegrationEngine.doRCLimitCheckCallout(applicant.Id,loanAppId, 'dealer'); 
           
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('{"JData":"O9V0ilOke9HI78UDCvUn5aYezfrQu2V0oM7Kuba4YvV3E06ktIqmhghRj71mXtUY4hdfZ2AJM1UK6dz92k72h0E9y1YG3ymXqIHKu/G5oTaTatM4zeyrt+v8j9/+kBI1gMVta7qPHWrq0chSx/J7NyheQKa8nQMjvWfXPkRpGtjkj/eeILTGWdkpT12l9RVH"}');
            response.setStatusCode(200);
            
            String continuationLabel = IntegrationEngine.continuationLabel;
            List<String> labels = new List<String>{continuationLabel};
            Object continuationState= IntegrationEngine.continuationState;
            
            String callOutResponse;
             
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            callOutResponse= (String)IntegrationEngine.processRCLimitCheckAPIResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
             
            //String responseExpected ='{"response":{"status":"SUCCESS","respDesc":"Check RC Limit","content":[{"No_Of_Proposals_Available":"1","Available_Disbursal_Amount":"10000.00","Pending_Flag":"Y","Payment_To_DSA_Flag":"N"}]}}';
            String responseExpected ='{"body":null,"response":null}';
            System.assertEquals(responseExpected, callOutResponse);
            }
        }catch(Exception ex){
           System.assertEquals(ex.getMessage(),'Please enter finance amount');
        }
            
        }
     @isTest
    public static void testRCLimitCheckService3(){
        try{
             Profile p = [SELECT Id FROM Profile WHERE Name='IBL Business Executive'];
            system.debug('p'+ p);
    		User u = new User(Alias = 'A ANBU', Email='standarduser@testorg.com',
					EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
					LocaleSidKey='en_US', ProfileId = p.Id,Maker_Id__c = '234',
                              MobilePhone = '9701498575',
					TimeZoneSidKey='America/Los_Angeles',
					UserName='standarduserABC40@testorg.com.psdev1');
            insert u;
            system.runAs(u){
            Opportunity opp = TestDataUtility.createTestOpportunity211(false);
            opp.Application_number__c = 'A11102302288';
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            Applicant__c applicant = TestDataUtility.createTestApplicant(false);
            applicant.Opportunity__c=opp.Id;
            String loanAppId = applicant.Opportunity__c;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
                
               /* Final_Term__c finalTerm = TestDataUtility.createfinalTerm(false,opp);
                if (Schema.sObjectType.Final_Term__c.isCreateable()){
                	insert finalTerm;
            	}*/
            
        Vehicle_Detail__c vc2 = new Vehicle_Detail__c();
        vc2.Loan_Application__c = opp.Id;
        vc2.Ben_Code__c = 'BEN000951';
        vc2.Product__c='TW New';
        vc2.Variant__c = 'twowheeler';
        vc2.Product__c = 'Two Wheeler';
        insert vc2;
        
        Product2 pd1 = new Product2();
        pd1.Asset_Category__c = 'te';
        pd1.Name = vc2.Variant__c;
        pd1.Type__c = 'Model';
        pd1.External_Reference_Id__c = '58568568';
        insert pd1;
         
           // String verifyRequest = '{ "Application_No": "AC4969614_85523017724", "Vehicle_Id": "MRBALENO3_V1", "Ben_Code": "BEN000951", "Product": "Two Wheeler" }';
             Continuation con = (Continuation)IntegrationEngine.doRCLimitCheckCalloutForDSAOrDealer(applicant.Id,loanAppId,'dealer','dealer'); 
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('{"JData":"O9V0ilOke9HI78UDCvUn5aYezfrQu2V0oM7Kuba4YvV3E06ktIqmhghRj71mXtUY4hdfZ2AJM1UK6dz92k72h0E9y1YG3ymXqIHKu/G5oTaTatM4zeyrt+v8j9/+kBI1gMVta7qPHWrq0chSx/J7NyheQKa8nQMjvWfXPkRpGtjkj/eeILTGWdkpT12l9RVH"}');
            response.setStatusCode(200);
            
            String continuationLabel = IntegrationEngine.continuationLabel;
            List<String> labels = new List<String>{continuationLabel};
            Object continuationState= IntegrationEngine.continuationState;
            
            String callOutResponse;
             
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            callOutResponse= (String)IntegrationEngine.processRCLimitCheckAPIResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
             
            //String responseExpected ='{"response":{"status":"SUCCESS","respDesc":"Check RC Limit","content":[{"No_Of_Proposals_Available":"1","Available_Disbursal_Amount":"10000.00","Pending_Flag":"Y","Payment_To_DSA_Flag":"N"}]}}';
            String responseExpected ='{"body":null,"response":null}';
            System.assertEquals(responseExpected, callOutResponse);
            }
        }catch(Exception ex){
           System.assertEquals(ex.getMessage(),'Please enter finance amount');
        }
            
    }     
}