ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Lead_Number__c.field-meta.xml
<CustomField>
    <fullName>Lead_Number__c</fullName>
    <formula>Opportunity__r.Lead_number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Id</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/Deal_Number__c.object-meta.xml
<CustomObject>
    <description>The custom object created for Deal Number generation</description>
    <label>Deal Number</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <formula>DNField1__c  +  DNField2__c  +  ProductCode__c  +  DNField3__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal Number</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Numbers</relationshipLabel>
    <relationshipName>Deal_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Request</fullName>
            </value>
            <value>
                <fullName>RC Upload</fullName>
            </value>
            <value>
                <fullName>Business Payment Details</fullName>
            </value>
            <value>
                <fullName>Insurance Details</fullName>
            </value>
            <value>
                <fullName>New/Used Vehicle Details</fullName>
            </value>
            <value>
                <fullName>Beneficiary Details</fullName>
            </value>
            <value>
                <fullName>Key Fact Statement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number_Setting__c/Deal_Number_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Deal Number Setting</label>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number_Setting__c/fields/MDNField1__c.field-meta.xml
<CustomField>
    <fullName>MDNField1__c</fullName>
    <label>MDNField1</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number_Setting__c/fields/MDNField2__c.field-meta.xml
<CustomField>
    <fullName>MDNField2__c</fullName>
    <label>MDNField2</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <description>IndusInd deal number</description>
    <label>Deal Number</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Lead_number__c.field-meta.xml
<CustomField>
    <fullName>Lead_number__c</fullName>
    <label>Lead Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Parent_Deal_number__c.field-meta.xml
<CustomField>
    <fullName>Parent_Deal_number__c</fullName>
    <label>Parent Deal number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Details</fullName>
            </value>
            <value>
                <fullName>Capture current residential address</fullName>
            </value>
            <value>
                <fullName>Capture permanent residential address</fullName>
            </value>
            <value>
                <fullName>Capture PAN or Other KYC</fullName>
            </value>
            <value>
                <fullName>Capture Dedupe</fullName>
            </value>
            <value>
                <fullName>Vehicle Dedupe</fullName>
            </value>
            <value>
                <fullName>Declared Income/Required Loan Amount</fullName>
            </value>
            <value>
                <fullName>Bank Account Check</fullName>
            </value>
            <value>
                <fullName>View Application Details</fullName>
            </value>
            <value>
                <fullName>CIBIL</fullName>
            </value>
            <value>
                <fullName>Field Investigation</fullName>
            </value>
            <value>
                <fullName>Credit Assessment</fullName>
            </value>
            <value>
                <fullName>Income Details</fullName>
            </value>
            <value>
                <fullName>Valuation IDV</fullName>
            </value>
            <value>
                <fullName>Final Terms</fullName>
            </value>
            <value>
                <fullName>Insurance Details</fullName>
            </value>
            <value>
                <fullName>Exposure Analysis</fullName>
            </value>
            <value>
                <fullName>Income</fullName>
            </value>
            <value>
                <fullName>CAM and Approval Log</fullName>
            </value>
            <value>
                <fullName>Risk Summary</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Tele-verification &lt;Post Sanction&gt;</fullName>
            </value>
            <value>
                <fullName>Vehicle Inspection and RC Check</fullName>
            </value>
            <value>
                <fullName>Structured EMI</fullName>
            </value>
            <value>
                <fullName>Security Mandate</fullName>
            </value>
            <value>
                <fullName>Additional Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>IHM</fullName>
            </value>
            <value>
                <fullName>Loan Agreement</fullName>
            </value>
            <value>
                <fullName>Signing the e-Agreement</fullName>
            </value>
            <value>
                <fullName>RC Upload</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/classes/CalloutProcessorTest.cls
@isTest
public class CalloutProcessorTest {
    
    private class MockHttpResponse implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            HttpResponse res = new HttpResponse();
            res.setStatusCode(200);
            String response = '{"result": "success"}';
            String jdataRequest = '"JData":';
            String encryptedResponse = IBMEncryption.getEncryptedRequest(response, System.Label.privateKey, System.Label.ivkey);  
            res.setBody('{'+jdataRequest + '"'+encryptedResponse+'"'+'}');
            return res;
        }
    }
    
    @testSetup
    static void testData(){
        Opportunity opp = TestDataUtility.createTestOpportunity(false);
        opp.Product_Type__c = System.Label.Tractor;
        insert opp;
        Applicant__c applicant = TestDataUtility.createTestApplicantForCIBIL(true, opp);
        Deal_Number_Setting__c dlNumberSetting= new Deal_Number_Setting__c();
        dlNumberSetting.Name = System.Label.Tractor;
        dlNumberSetting.MDNField1__c ='AB';
        dlNumberSetting.MDNField2__c = 2.0;
        insert dlNumberSetting;
        
        Deal_Number__c dealNumber=new Deal_Number__c();
        dealNumber.Loan_Application__c = opp.Id;
        dealNumber.Sub_Stage__c = 'RC Upload';
        insert dealNumber;
    }
    @isTest
    static void testCreateHttpRequestForReverseStatus() {
        Opportunity opp = [SELECT Id,Lead_number__c,Product_Type__c,Parent_Deal_number__c FROM Opportunity LIMIT 1];
        Deal_Number__c dealNumber = [SELECT Id FROM Deal_Number__c LIMIT 1];
        
        IND_DealEligibleRefinanceRequest dealEligibleRequest = IND_DealEligibleRefinanceService.getDealEligibleRefinance(opp,dealNumber.Id);
        Test.setMock(HttpCalloutMock.class, new MockHttpResponse());       
        Test.startTest();
        CalloutProcessor obj= new CalloutProcessor(System.Label.DealEligibleRefinanceAPI,dealEligibleRequest);
        obj.serviceName = 'UIDAI OTP';
        HttpRequest req = obj.createHttpRequestForReverseStatus();
        HttpRequest req1 = obj.createHttpRequest();
        System.assertNotEquals(null,req);
        Test.stopTest();
    }
    
    @isTest
    static void testCreateHttpRequest() {
        Opportunity opp = [SELECT Id,Lead_number__c,Product_Type__c,Parent_Deal_number__c FROM Opportunity LIMIT 1];
        Deal_Number__c dealNumber = [SELECT Id FROM Deal_Number__c LIMIT 1];
        
        IND_DealEligibleRefinanceRequest dealEligibleRequest = IND_DealEligibleRefinanceService.getDealEligibleRefinance(opp,dealNumber.Id);
        Test.setMock(HttpCalloutMock.class, new MockHttpResponse());       
        Test.startTest();
        CalloutProcessor obj= new CalloutProcessor(System.Label.DealEligibleRefinanceAPI,dealEligibleRequest);
        obj.serviceName = system.label.Membership;
        HttpRequest req = obj.createHttpRequest();
        System.assertNotEquals(null,req);
        Test.stopTest();
    }
    
    @isTest
    static void testCreateHttpRequest1() {
        Opportunity opp = [SELECT Id,Lead_number__c,Product_Type__c,Parent_Deal_number__c FROM Opportunity LIMIT 1];
        Deal_Number__c dealNumber = [SELECT Id FROM Deal_Number__c LIMIT 1];
        
        IND_DealEligibleRefinanceRequest dealEligibleRequest = IND_DealEligibleRefinanceService.getDealEligibleRefinance(opp,dealNumber.Id);
        Test.setMock(HttpCalloutMock.class, new MockHttpResponse());       
        Test.startTest();
        CalloutProcessor obj= new CalloutProcessor(System.Label.DealEligibleRefinanceAPI,dealEligibleRequest);
        obj.serviceName = System.Label.D2CVehicleValuation;
        HttpRequest req = obj.createHttpRequest();
        System.assertNotEquals(null,req);
        Test.stopTest();
    }
    
    @isTest
    static void testCreateHttpRequest2() {
        Opportunity opp = [SELECT Id,Lead_number__c,Product_Type__c,Parent_Deal_number__c FROM Opportunity LIMIT 1];
        Deal_Number__c dealNumber = [SELECT Id FROM Deal_Number__c LIMIT 1];
        
        IND_DealEligibleRefinanceRequest dealEligibleRequest = IND_DealEligibleRefinanceService.getDealEligibleRefinance(opp,dealNumber.Id);
        Test.setMock(HttpCalloutMock.class, new MockHttpResponse());       
        Test.startTest();
        CalloutProcessor obj= new CalloutProcessor(System.Label.DealEligibleRefinanceAPI,dealEligibleRequest);
        obj.serviceName = System.Label.Payment_Request_For_Tractor;
        HttpRequest req = obj.createHttpRequest(); 
        HttpRequest req1 = obj.createHttpRequestForAadhaarVaultApi();
        System.assertNotEquals(null,req);
        Test.stopTest();
    }    
    
    @isTest
    static void testGetHttpResponseForAll(){ 
        try{
            Opportunity loanApp = [SELECT Id,Lead_number__c FROM Opportunity];
            Applicant__c applicant = [SELECT Id,Opportunity__r.Parent_Deal_number__c,Opportunity__r.Deal_number__c FROM Applicant__c ];
            Continuation con = (Continuation)IntegrationEngine.doNeSLAgreementStatusCallout(applicant.Id,loanApp.Id);
            Map<String, HttpRequest> requests = con.getRequests();
            
            HttpResponse response = new HttpResponse();
            response.setBody('JData":"4jSxLhM7jTK4VPvES1SWnJ+cKI3O+yFsaEutijpuT+g=');            
            response.setStatusCode(200);
            
            String continuationLabel = IntegrationEngine.continuationLabel;
            String membershipResponse = '';
            List<String> labels = new List<String>{continuationLabel};
                Object continuationState= IntegrationEngine.continuationState;   
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            IntegrationEngine.processUidaiBiometricResponse(labels, continuationState);
            Test.stopTest(); 
        }
        catch(Exception ex){
            
        }
    }
}