ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Lead_Number__c.field-meta.xml
<CustomField>
    <fullName>Lead_Number__c</fullName>
    <formula>Opportunity__r.Lead_number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Id</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Insurance_declared_value__c.field-meta.xml
<CustomField>
    <fullName>Insurance_declared_value__c</fullName>
    <label>Insurance declared value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>Vehicle_Detail__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/InsuranceDetails__c/InsuranceDetails__c.object-meta.xml
<CustomObject>
    <label>Insurance Details</label>
    <nameField>
        <label>Insurance Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/InsuranceDetails__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Insurance_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/InsuranceDetails__c/fields/Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>Vehicle_Detail__c</referenceTo>
    <relationshipLabel>Insurance Details</relationshipLabel>
    <relationshipName>Insurance_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Agent_BL_code__c.field-meta.xml
<CustomField>
    <fullName>Agent_BL_code__c</fullName>
    <label>Agent BL code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Ben_Code__c.field-meta.xml
<CustomField>
    <fullName>Ben_Code__c</fullName>
    <label>Ben Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Grid_value__c.field-meta.xml
<CustomField>
    <fullName>Grid_value__c</fullName>
    <label>Grid value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Insurance_declared_value__c.field-meta.xml
<CustomField>
    <fullName>Insurance_declared_value__c</fullName>
    <label>Insurance declared value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Insurance_type__c.field-meta.xml
<CustomField>
    <fullName>Insurance_type__c</fullName>
    <label>Insurance type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Comprehensive</fullName>
            </value>
            <value>
                <fullName>Third Party</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/mapped_BE__c.field-meta.xml
<CustomField>
    <fullName>mapped_BE__c</fullName>
    <description>this stores the mapped BE found in D2C BE mapping API. This BE will be assigned later when initial offer will generate</description>
    <label>mapped BE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>Selling_Price__c</fullName>
    <label>Selling Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Valuation_price__c.field-meta.xml
<CustomField>
    <fullName>Valuation_price__c</fullName>
    <label>Valuation price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <label>Variant</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Registration_Number__c</fullName>
    <label>Vehicle Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Sub_Category__c</fullName>
    <label>Vehicle Sub-Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/Vehicle_Detail__c.object-meta.xml
<CustomObject>
    <label>Vehicle Detail</label>
    <nameField>
        <displayFormat>VD-{00000}</displayFormat>
        <label>Vehicle Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Ben_Code__c.field-meta.xml
<CustomField>
    <fullName>Ben_Code__c</fullName>
    <label>Ben Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Dealer_Sub_dealer_name__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Sub_dealer_name__c</fullName>
    <label>Dealer/Sub-dealer name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Eligible_Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Loan_Amount__c</fullName>
    <label>Eligible Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Executive_Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Executive_Contact_Number__c</fullName>
    <label>Executive Contact Number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Executive_name__c.field-meta.xml
<CustomField>
    <fullName>Executive_name__c</fullName>
    <label>Executive name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Grid_value__c.field-meta.xml
<CustomField>
    <fullName>Grid_value__c</fullName>
    <label>Grid value</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Ins_Expiry_date__c.field-meta.xml
<CustomField>
    <fullName>Ins_Expiry_date__c</fullName>
    <label>Ins. Expiry date</label>
    <type>Date</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Insurance_declared_value__c.field-meta.xml
<CustomField>
    <fullName>Insurance_declared_value__c</fullName>
    <label>Insurance declared value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Insurance_expiring_within_60_days__c.field-meta.xml
<CustomField>
    <fullName>Insurance_expiring_within_60_days__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Insurance expiring within 60 days</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Insurance_type__c.field-meta.xml
<CustomField>
    <fullName>Insurance_type__c</fullName>
    <label>Insurance type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Comprehensive</fullName>
            </value>
            <value>
                <fullName>Third Party</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Lien_in_favor_of__c.field-meta.xml
<CustomField>
    <fullName>Lien_in_favor_of__c</fullName>
    <label>Lien in favor of</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>IBL</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>None</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <description>Vehicle Insurance and Vehicle Valuation data</description>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Vehicle_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Manufacturer_Year_Month__c.field-meta.xml
<CustomField>
    <fullName>Manufacturer_Year_Month__c</fullName>
    <label>Manufacturer Year, Month</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Number_of_ownerships__c.field-meta.xml
<CustomField>
    <fullName>Number_of_ownerships__c</fullName>
    <label>Number of ownerships</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
            </value>
            <value>
                <fullName>2</fullName>
            </value>
            <value>
                <fullName>3</fullName>
            </value>
            <value>
                <fullName>&gt;3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/OEM_Dealer__c.field-meta.xml
<CustomField>
    <fullName>OEM_Dealer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>OEM Dealer</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Purpose_of_purchase__c.field-meta.xml
<CustomField>
    <fullName>Purpose_of_purchase__c</fullName>
    <label>Purpose of purchase</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Personal</fullName>
                <default>true</default>
                <label>Personal</label>
            </value>
            <value>
                <fullName>Working Capital</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>Selling_Price__c</fullName>
    <label>Selling Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Valuation_price__c.field-meta.xml
<CustomField>
    <fullName>Valuation_price__c</fullName>
    <label>Valuation price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Valuer__c.field-meta.xml
<CustomField>
    <fullName>Valuer__c</fullName>
    <label>Valuer</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Valuer-1</label>
            </value>
            <value>
                <fullName>B</fullName>
                <label>Valuer-2</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Variant__c.field-meta.xml
<CustomField>
    <fullName>Variant__c</fullName>
    <label>Variant</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Variant_Code__c.field-meta.xml
<CustomField>
    <fullName>Variant_Code__c</fullName>
    <label>Variant Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Vehicle_Category__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Category__c</fullName>
    <label>Vehicle Category</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Vehicle_registered_in_the_name_of__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_registered_in_the_name_of__c</fullName>
    <label>Vehicle registered in the name of</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
                <default>true</default>
                <label>Borrower</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Vehicle_Registration_number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Registration_number__c</fullName>
    <label>Vehicle Registration number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC - Copy/force-app/main/default/classes/IND_D2CVehicleValuationRequst.cls
/*------------------------------------------------------------
Author:        Rohan Saxena
Company:       Salesforce
Description:   This class is Request Wrapper Class of IBM Reverse Vehicle Valuation API
Test Class:    
History
Date            Author              Comments
-------------------------------------------------------------
07-12-2022      Rohan Saxena         Created
------------------------------------------------------------*/
public with sharing class IND_D2CVehicleValuationRequst extends ParentAPIRequest{
    public final String leadNumber { get; set; }
    public final String beContactNumber { get; set; }
    public final String beSFDCId { get; set; }
    public final String beName { get; set; }
    public final String beId { get; set; }
    public final String beBranchCode { get; set; }
    public final String valuationPrice { get; set; }
    public final String gridValue { get; set; }
    public final String sellingPrice { get; set; }
    public final String insuranceType { get; set; }
    public final String insuranceExpiringWithin60Days { get; set; }
    public final String numberOfOwnerships { get; set; }
    public final String checkOEMDealer { get; set; }
    public String originalRCCopy { get; set; }
    public String insurancePolicyDocument { get; set; }
    public final String motorInsurancePolicyName { get; set; }
    public final String vehicleCategoryCode { get; set; }
    public final String leadSourcedBy { get; set; }
    public final String motorInsuranceAmount { get; set; }
    public final String funded { get; set; }
    public final String nonFunded { get; set; }
    public final String fundedPremium { get; set; }
    public final String IDV { get; set; }
    public final String manufacturerYear { get; set; }
    public final String manufacturerMonth { get; set; }
    public final String valuer { get; set; }
    public final String valuerCategory { get; set; }
    public final String eligibleAmount { get; set; }

    public IND_D2CVehicleValuationRequst(String loanId) {

        //get Vehicle_Detail__c
        List<Vehicle_Detail__c> vehDetailList = new List<Vehicle_Detail__c>([Select Id, Executive_name__c, Executive_Contact_Number__c,Ins_Expiry_date__c, Ben_Code__c,Dealer_Sub_dealer_name__c,Product__c, Loan_Application__c, Variant_Code__c, 
        Selling_Price__c, Manufacturer_Year_Month__c,Vehicle_Registration_number__c,Lien_in_favor_of__c,Insurance_type__c, Variant__c, Insurance_expiring_within_60_days__c, Valuer__c, Eligible_Loan_Amount__c,
        Insurance_declared_value__c, Purpose_of_purchase__c, Number_of_ownerships__c, OEM_Dealer__c, Vehicle_registered_in_the_name_of__c,Vehicle_Category__c,Valuation_price__c, Grid_value__c,
        Loan_Application__r.Agent_BL_code__c, Loan_Application__r.mapped_BE__c,Loan_Application__r.Vehicle_Sub_Category__c, Loan_Application__r.Lead_number__c, Loan_Application__r.OEM_Dealer_Checkbox__c, Insurer_name__c, Base_Prices__c, Valuer_category__c
        From Vehicle_Detail__c Where Loan_Application__c =:loanId ]);

        List<InsuranceDetails__c> insurDetailObj =  [SELECT id, Name, Amount__c, Funded_Non_funded__c, Funded_Premium__c, Insurance_Plan__c
                                                    FROM InsuranceDetails__c
                                                    WHERE Loan_Application__c =: loanId
                                                    WITH SECURITY_ENFORCED
                                                    ];

        List<Applicant__c> app = [Select Id, applicant_number__c FROM Applicant__c WHERE Opportunity__c =: loanId];
        List<Documents__c> docObject = [SELECT Document_Type__c, Name from Documents__c where Opportunity_Relation__c =: loanId and (Name='Vehicle RC Copy' or Name='Vehicle Insurance Policy')];
        if(vehDetailList != null && !vehDetailList.isEmpty()){
            this.leadNumber =vehDetailList[0].Loan_Application__r.Lead_number__c+'_'+app[0].applicant_number__c;
            this.beContactNumber =vehDetailList[0].Executive_Contact_Number__c;
            this.beSFDCId =String.isNotBlank(vehDetailList[0].Loan_Application__r.mapped_BE__c)?vehDetailList[0].Loan_Application__r.mapped_BE__c:'';
            this.beName =vehDetailList[0].Executive_name__c;
            this.beId =String.isNotBlank(vehDetailList[0].Loan_Application__r.mapped_BE__c)?vehDetailList[0].Loan_Application__r.mapped_BE__c:'';
            this.beBranchCode =vehDetailList[0].Loan_Application__r.Agent_BL_code__c;
            this.valuationPrice =vehDetailList[0].Valuation_price__c!=null?String.valueOf(Integer.valueOf(vehDetailList[0].Valuation_price__c)):'0';
            this.gridValue =String.valueOf(Integer.valueOf(vehDetailList[0].Grid_value__c));
            this.sellingPrice =String.valueOf(Integer.valueOf(vehDetailList[0].Selling_Price__c));
            this.insuranceType =String.isNotBlank(vehDetailList[0].Insurance_type__c)?vehDetailList[0].Insurance_type__c:'';
            this.insuranceExpiringWithin60Days =vehDetailList[0].Insurance_expiring_within_60_days__c?'Y':'N';
            this.numberOfOwnerships =vehDetailList[0].Number_of_ownerships__c;
            this.checkOEMDealer =vehDetailList[0].Loan_Application__r.OEM_Dealer_Checkbox__c?'Y':'N';
            
            this.vehicleCategoryCode =String.isNotBlank(vehDetailList[0].Loan_Application__r.Vehicle_Sub_Category__c)?vehDetailList[0].Loan_Application__r.Vehicle_Sub_Category__c:'';
            this.leadSourcedBy ='D2C';
            if(!docObject.isEmpty()){
                for(Documents__c doc:docObject){
                    if(doc.Document_Type__c=='Vehicle Insurance Policy'){
                        this.insurancePolicyDocument = 'Y';
                    } else if(doc.Document_Type__c=='Vehicle RC Copy'){
                        this.originalRCCopy = 'Y';
                    }
                }
            }
            this.originalRCCopy = String.isNotBlank(this.originalRCCopy)?this.originalRCCopy:'N';
            this.insurancePolicyDocument =String.isNotBlank(this.insurancePolicyDocument)?this.insurancePolicyDocument:'N';

            if(insurDetailObj != null && !insurDetailObj.isEmpty()){
                this.motorInsuranceAmount =insurDetailObj[0].Amount__c!=null?String.valueOf(Integer.valueOf(insurDetailObj[0].Amount__c)):'0';
                this.funded = insurDetailObj[0].Funded_Non_funded__c == 'Funded'?'Y':'N';
                this.motorInsurancePolicyName = String.isNotBlank(insurDetailObj[0].Insurance_Plan__c)?insurDetailObj[0].Insurance_Plan__c:'';
                this.nonFunded = insurDetailObj[0].Funded_Non_funded__c != 'Funded'?'Y':'N';
                if(insurDetailObj[0].Funded_Non_funded__c == 'Funded'){
                    this.fundedPremium = insurDetailObj[0].Amount__c!=null?String.valueOf(Integer.valueOf(insurDetailObj[0].Amount__c)):'0';
                }else{
                    this.fundedPremium='0';
                }
                
            }else{
                this.motorInsuranceAmount ='0';
                this.funded ='N';
                this.motorInsurancePolicyName = '';
                this.nonFunded ='N';
                this.fundedPremium='0';
            }
            
            this.IDV =String.valueOf(Integer.valueOf(vehDetailList[0].Insurance_declared_value__c));
            this.manufacturerYear =vehDetailList[0].Manufacturer_Year_Month__c.split('-')[0];
            this.manufacturerMonth =vehDetailList[0].Manufacturer_Year_Month__c.split('-')[1];
            this.valuer =String.isNotBlank(vehDetailList[0].Valuer__c)?vehDetailList[0].Valuer__c:'';
            this.valuerCategory =String.isNotBlank(vehDetailList[0].Valuer_category__c)?vehDetailList[0].Valuer_category__c:'';
            this.eligibleAmount =String.isNotBlank(String.valueOf(Integer.valueOf(vehDetailList[0].Eligible_Loan_Amount__c)))?String.valueOf(Integer.valueOf(vehDetailList[0].Eligible_Loan_Amount__c)):'0';
        }
        

    }
    public override Map<String, String> getHttpRequestHeaders() {
        //Map to store HTTP request header data
        Blob b = Crypto.GenerateAESKey(128);
        String h = EncodingUtil.ConvertTohex(b);
        String guid = h.SubString(0,8)+ '-' + h.SubString(8,12) + '-' + h.SubString(12,16) + '-' + h.SubString(16,20) + '-' + h.substring(20);
        Map<String, String> requestHeaderMap = new Map<String, String>();
        requestHeaderMap.put(IntegrationConstants.CONTENT_TYPE , IntegrationConstants.CONTENT_TYPE_JSON);
        requestHeaderMap.put('X-IBM-Client-Id', System.Label.IBMClientId);
        requestHeaderMap.put('X-IBM-Client-Secret', System.Label.IBMClientSecret);
        requestHeaderMap.put('Origin', URL.getSalesforceBaseUrl().toExternalForm());
        requestHeaderMap.put('UUID', guid);
        return requestHeaderMap;
    }
}