ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-borrower</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Code__c</fullName>
    <label>Customer Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/In_Active_Applicant__c.field-meta.xml
<CustomField>
    <fullName>In_Active_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In-Active Applicant</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/isAllRowSelected__c.field-meta.xml
<CustomField>
    <fullName>isAllRowSelected__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isAllRowSelected</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/isCodeValidateBySalesUser__c.field-meta.xml
<CustomField>
    <fullName>isCodeValidateBySalesUser__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isCodeValidateBySalesUser</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Case/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Id</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Case/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Case/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <formula>TEXT(Loan_Application__r.Product_Type__c)</formula>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Customer_Code__c/Customer_Code__c.object-meta.xml
<CustomObject>
    <label>Customer Code</label>
    <nameField>
        <label>Customer  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Customer_Code__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant_Delete</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Customer_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Customer_Code__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Customer_Codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Customer_Dedupe_Response__c/Customer_Dedupe_Response__c.object-meta.xml
<CustomObject>
    <label>Customer Dedupe Response</label>
    <nameField>
        <displayFormat>CDR-{000000}</displayFormat>
        <label>Customer Dedupe Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Dedupe Response</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Customer_Dedupe_Response__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Customer_Dedupe_Response</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Customer_Dedupe_Response__c/fields/Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Code__c</fullName>
    <label>Customer Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Customer_Dedupe_Response__c/fields/Dedupe_Journey_Status_Reason__c.field-meta.xml
<CustomField>
    <fullName>Dedupe_Journey_Status_Reason__c</fullName>
    <label>Dedupe Journey Status Reason</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Customer_Dedupe_Response__c/fields/IND_isNewCustomer__c.field-meta.xml
<CustomField>
    <fullName>IND_isNewCustomer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isNewCustomer</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Customer_Dedupe_Response__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Code__c</fullName>
    <label>Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Is_Customer_Dedupe_Submit__c.field-meta.xml
<CustomField>
    <fullName>Is_Customer_Dedupe_Submit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Customer Dedupe Submit</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Journey_Stop_Reason__c.field-meta.xml
<CustomField>
    <fullName>Journey_Stop_Reason__c</fullName>
    <label>Journey Stop Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdLWC - Copy/force-app/main/default/classes/LWC_LOS_CMUCustomerDedupe_cntrl.cls
/*------------------------------------------------------------
Author:        Manish Baldota
Company:       Persistent Systems
Description:   This class is use to provide the details to CMU customer dedupe lightning web component.
Test Class:    LWC_LOS_CMUCustomerDedupe_cntrltest
History
Date            Author              Comments
-------------------------------------------------------------
02-16-2021      Manish Baldota       Created
------------------------------------------------------------*/
public with sharing class LWC_LOS_CMUCustomerDedupe_cntrl {

    // @Method:      handleChangeOwnerProcess
    // @Created by:  Manish Baldota
    // @Description: Method to handle the business logic of CMU owner change.
    // @Param:       String : caseId  
    // @Return:  
    @AuraEnabled
    public static ApplicantWrapper getRecordDetails(String caseId) {
        try{
            if(caseId != null){
                ApplicantWrapper applicantWrapper = new ApplicantWrapper();
                Case returnCase = [SELECT Id,Loan_Application__c,Loan_Application__r.Product_Type__c FROM Case WHERE Id=: caseId 
                                    WITH SECURITY_ENFORCED Limit 1];
                applicantWrapper.caseRecord=returnCase;
                List<Applicant__c> finalApplicants = new List<Applicant__c>();
                List<Applicant__c> validatedApplicantList = new List<Applicant__c>();
                Map<String,String> applicantDedupeMap = new Map<String,String>();
                List<Applicant__c> applicantDetails = [SELECT Id,Applicant_Type__c,Name,Opportunity__c,(select Id,IND_isNewCustomer__c from Customer_Dedupe_Response__r) FROM Applicant__c WHERE Opportunity__c =: returnCase.Loan_Application__c AND In_Active_Applicant__c = false AND Opportunity__r.StageName != 'Journey Stop' AND isCodeValidateBySalesUser__c=false WITH SECURITY_ENFORCED];//CISP-3447 (For cmu user can check the dedupe response)// CISP-10782 (Added isCodeValidateBySalesUser__c)
                if(applicantDetails.size()>0){
                    for(Applicant__c app : applicantDetails){
                        if(app.Customer_Dedupe_Response__r.size() > 0 && app.Customer_Dedupe_Response__r[0].IND_isNewCustomer__c){
                           continue; 
                        }
                        finalApplicants.add(app);
                    }
                }
                applicantWrapper.applicantDetails=finalApplicants;
                List<Applicant__c> validatedApplicantDetails = [SELECT Id,Applicant_Type__c,Name,Opportunity__c,Customer_Code__c,isCodeValidateBySalesUser__c,(select Id,IND_isNewCustomer__c,Dedupe_Journey_Status_Reason__c FROM Customer_Dedupe_Response__r) FROM Applicant__c WHERE Opportunity__c =: returnCase.Loan_Application__c AND In_Active_Applicant__c = false AND Opportunity__r.StageName != 'Journey Stop' WITH SECURITY_ENFORCED];
                if(validatedApplicantDetails.size()>0){
                    for(Applicant__c app : validatedApplicantDetails){
                        if(app.Customer_Dedupe_Response__r.size() > 0 &&(app.Customer_Dedupe_Response__r[0].IND_isNewCustomer__c || app.isCodeValidateBySalesUser__c)){
                            validatedApplicantList.add(app);
                        }
                    }
                }
                
                if(validatedApplicantList.size()>0){
                    for(Applicant__c app : validatedApplicantList){
                        applicantDedupeMap.put(app.Applicant_Type__c,app.Customer_Dedupe_Response__r[0].Dedupe_Journey_Status_Reason__c);
                    }
                }
                applicantWrapper.applicantDedupeMap = applicantDedupeMap;
                applicantWrapper.validatedApplicantList=validatedApplicantList;
                return applicantWrapper;
            }else{
                throw new IND_Exception('Case is not available.');
            }
        }Catch(Exception e){
            ErrorLoggerUtil.logErrorEvent('LWC_LOS_CMUCustomerDedupe_cntrl', 'handleChangeOwnerProcess', System.Label.Apex, e, '');
            throw new IND_Exception(e.getMessage());
        }
    }

    public class ApplicantWrapper{
        @AuraEnabled
        public Case caseRecord{get;set;}
        @AuraEnabled
        public List<Applicant__c> applicantDetails{get;set;}
        @AuraEnabled
        public List<Applicant__c> validatedApplicantList{get;set;}
        @AuraEnabled
        public Map<String,String> applicantDedupeMap{get;set;}
    }
    // @Method:      handleJourneyStop
    // @Created by:  Manish Baldota
    // @Description: Method to handle the business logic of CMU owner change.
    // @Param:       String : handleJourneyStop //Loan Application Id  
    // @Return:  
/*    @AuraEnabled    public static void handleJourneyStop(String applicationId,String caseId) {

        try{
            if(applicationId != null){
                Opportunity opp = new Opportunity(Id = applicationId);
                opp.StageName = 'Journey Stop';
                opp.Journey_Stop_Reason__c = System.label.CMUJourneyStopReason;
                if (Schema.sObjectType.Opportunity.isUpdateable()) {
                    UPDATE opp;
				}
            }
            if(caseId != null){
                Case caseToClose = new Case(Id = caseId);
                caseToClose.Status = 'Closed';
                if (Schema.sObjectType.Case.isUpdateable()) {
                    UPDATE caseToClose;
				}
            }
        }Catch(Exception e){
            ErrorLoggerUtil.logErrorEvent('LWC_LOS_CMUCustomerDedupe_cntrl', 'handleChangeOwnerProcess', System.Label.Apex, e, applicationId);
            throw new IND_Exception(e.getMessage());
        }
    } */

    //CISP-4376 start
    @AuraEnabled
    public static List<Applicant__c> checkCustomerResponseAvailable(String oppId) {
        try{           
            List<Applicant__c> applicantDetails = [SELECT Id,isAllRowSelected__c,isCodeValidateBySalesUser__c,Applicant_Type__c,Opportunity__c,(select Id, response__c,Dedupe_Journey_Status_Reason__c from Customer_Dedupe_Response__r)  FROM Applicant__c WHERE Opportunity__c =: oppId AND In_Active_Applicant__c = false AND Opportunity__r.StageName != 'Journey Stop' WITH SECURITY_ENFORCED];//CISP-3447 (For cmu user can check the dedupe response)
            if(!applicantDetails.isEmpty()){
                return applicantDetails;
            }
            return null;
        }Catch(Exception e){
            ErrorLoggerUtil.logErrorEvent('LWC_LOS_CMUCustomerDedupe_cntrl', 'handleChangeOwnerProcess', System.Label.Apex, e, '');
            throw new IND_Exception(e.getMessage());
        }
    }//CISP-4376

    @AuraEnabled
    public static Boolean checkCaseClosed(String caseId) {
        try{           
            Case returnCase = [SELECT Id,Loan_Application__c,status,Loan_Application__r.Is_Customer_Dedupe_Submit__c FROM Case WHERE Id=: caseId 
                                    WITH SECURITY_ENFORCED Limit 1];
            if(returnCase.Status == 'Closed' || returnCase.Loan_Application__r.Is_Customer_Dedupe_Submit__c == true){ //Disable submit button 
                return true;
            }  
            return false;
        }Catch(Exception e){
            ErrorLoggerUtil.logErrorEvent('LWC_LOS_CMUCustomerDedupe_cntrl', 'handleChangeOwnerProcess', System.Label.Apex, e, '');
            throw new IND_Exception(e.getMessage());
        }
    }
}