ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Aadhar_No__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_No__c</fullName>
    <label>Aadhar No.</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Aadhar_OTP_or_Biometric__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_OTP_or_Biometric__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aadhar OTP or Biometric</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Code__c</fullName>
    <label>Customer Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Customer_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_First_Name__c</fullName>
    <label>Customer First Name</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Customer_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Last_Name__c</fullName>
    <label>Customer Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Customer_Code__c/Customer_Code__c.object-meta.xml
<CustomObject>
    <label>Customer Code</label>
    <nameField>
        <label>Customer  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Customer_Code__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant_Delete</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Customer_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Aadhar_Vault_Code__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Vault_Code__c</fullName>
    <description>In case of ETB customer API will return vault code and not the aadhar number</description>
    <label>Aadhar Vault Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/KYC_name__c.field-meta.xml
<CustomField>
    <fullName>KYC_name__c</fullName>
    <label>KYC name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/KYC_No__c.field-meta.xml
<CustomField>
    <fullName>KYC_No__c</fullName>
    <label>KYC No.</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Opportunity_Relation__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Relation__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Pre_Initial_Address__c.field-meta.xml
<CustomField>
    <fullName>Pre_Initial_Address__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field is to identify whether this document is created to capture the address which is filled on D2C app in pre initial offer journey.</description>
    <label>Pre Initial Address</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Code__c</fullName>
    <label>Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Customer_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Last_Name__c</fullName>
    <label>Customer Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/IO_Loan_amount__c.field-meta.xml
<CustomField>
    <fullName>IO_Loan_amount__c</fullName>
    <label>IO Loan Amount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Is_ETB__c.field-meta.xml
<CustomField>
    <fullName>Is_ETB__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is ETB</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/RE_KYC_Stage__c.field-meta.xml
<CustomField>
    <fullName>RE_KYC_Stage__c</fullName>
    <label>RE KYC Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PreInitialOffer</fullName>
            </value>
            <value>
                <fullName>PostInitialOffer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/CaptureAadharInformationTest.cls
@isTest
private class CaptureAadharInformationTest {

    @isTest
    static void testGetAadharDocument() {
        // Create test data
        Opportunity opp = new Opportunity(
            Name = 'Test Opp',
            StageName = 'Prospecting',
            CloseDate = Date.today(),
            Is_ETB__c = true,
            IO_Loan_Amount__c = '700000',
            LeadSource = 'D2C'
        );
        insert opp;
        Applicant__c applicant = new Applicant__c(
            Customer_Code__c = 'Test Code',
            Opportunity__c = opp.Id,
            Customer_First_Name__c = 'Test',
            Customer_Last_Name__c = 'Applicant'
        );
        insert applicant;
        Documents__c document = new Documents__c(
            Opportunity_Relation__c = opp.Id,
            Applicant__c = applicant.Id,
            Name = 'Test Document'
        );
        insert document;

        // Mock the incoming request
        CaptureAadharInformation.AadharRequest request = new CaptureAadharInformation.AadharRequest();
            request.loanApplicationId = opp.Id;
            request.applicantId = applicant.Id;
            request.aadharDocumentId = document.Id;
            request.aadharNumber = '123456789012';
            request.aadharVaultCode = 'TEST';
            request.aadharOTPorBiometric = true;
            request.FirstName = 'Test';
            request.LastName = 'Applicant';
	        request.customerImageBase64Data = 'testCustomerImage';
        	request.aadharBase64EncodedData = 'testAadhaar';

        String requestJSON = JSON.serialize(request);
        RestContext.request = new RestRequest();
        String encryptedResponse = IntegrationUtilities.getEncryptedRequest(requestJSON,System.Label.privateKey,System.Label.ivkey); 
        String jdataRequest = '"JData":';
        RestContext.request.requestBody = Blob.valueOf('{'+jdataRequest + '"'+encryptedResponse+'"'+'}');
		RestResponse res = new RestResponse();
        RestContext.response= res;
        // Call the method
        Test.startTest();
        CaptureAadharInformation.getAadharDocument();
        Test.stopTest();

        // Verify the updates
        opp = [SELECT RE_KYC_Stage__c FROM Opportunity WHERE Id = :opp.Id];
        System.assertEquals('PostInitialOffer', opp.RE_KYC_Stage__c);

        applicant = [SELECT Name, Aadhar_No__c, Aadhar_OTP_or_Biometric__c, Customer_First_Name__c, Customer_Last_Name__c FROM Applicant__c WHERE Id = :applicant.Id];
        System.assertEquals('Test Applicant', applicant.Name);
        System.assertEquals('123456789012', applicant.Aadhar_No__c);
        System.assertEquals(true, applicant.Aadhar_OTP_or_Biometric__c);
        System.assertEquals('Test', applicant.Customer_First_Name__c);
        System.assertEquals('Applicant', applicant.Customer_Last_Name__c);

        document = [SELECT Pre_Initial_Address__c, KYC_No__c, Aadhar_Vault_Code__c, KYC_name__c, First_Name__c, Last_Name__c FROM Documents__c WHERE Id = :document.Id];
        System.assertEquals(false, document.Pre_Initial_Address__c);
        System.assertEquals('123456789012', document.KYC_No__c);
        System.assertEquals('TEST', document.Aadhar_Vault_Code__c);
        System.assertEquals('Test Applicant', document.KYC_name__c);
        System.assertEquals('Test', document.First_Name__c);
        System.assertEquals('Applicant', document.Last_Name__c);
    }

}