ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-borrower</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/CIC_No__c.field-meta.xml
<CustomField>
    <fullName>CIC_No__c</fullName>
    <description>Used to save value for CRIFF</description>
    <label>CIC No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/CRIFF_Report_URL__c.field-meta.xml
<CustomField>
    <fullName>CRIFF_Report_URL__c</fullName>
    <label>CRIFF Report URL</label>
    <type>Url</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/Deal_Number__c.object-meta.xml
<CustomObject>
    <description>The custom object created for Deal Number generation</description>
    <label>Deal Number</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <formula>DNField1__c  +  DNField2__c  +  ProductCode__c  +  DNField3__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal Number</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Numbers</relationshipLabel>
    <relationshipName>Deal_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <label>Integration Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Integration Log</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Integration_Log__c/fields/Retry_count__c.field-meta.xml
<CustomField>
    <fullName>Retry_count__c</fullName>
    <label>Retry count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/Loan_Application_Transaction_History__c.object-meta.xml
<CustomObject>
    <description>created for tackling lead assignments would be used.</description>
    <label>Loan Application Transaction History</label>
    <nameField>
        <label>Loan Application Transaction History</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application Transactions History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Number</label>
    <referenceTo>Deal_Number__c</referenceTo>
    <relationshipLabel>Loan Application Transactions History</relationshipLabel>
    <relationshipName>Loan_Application_Transactions_History</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/fields/Loan_Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Loan Application Transactions History</relationshipLabel>
    <relationshipName>Loan_Application_Transactions_History</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <description>Stage Name</description>
    <label>Module</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/fields/Screen__c.field-meta.xml
<CustomField>
    <fullName>Screen__c</fullName>
    <label>Screen</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/fields/Submitted_Flag__c.field-meta.xml
<CustomField>
    <fullName>Submitted_Flag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submitted</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Low_Payload_Response__e/Low_Payload_Response__e.object-meta.xml
<CustomObject>
    <description>This is created for Low Payload ASync Response. The name has been changed from the previous Name for Recognition. Need to change in any code if already used.</description>
    <label>Low Payload Response</label>
    <pluralLabel>Low Payload Responses</pluralLabel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Low_Payload_Response__e/fields/Reference_Id__c.field-meta.xml
<CustomField>
    <fullName>Reference_Id__c</fullName>
    <description>Integration Log Object record id or any record id if needed for further processing</description>
    <label>Reference Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Low_Payload_Response__e/fields/SVC_Name__c.field-meta.xml
<CustomField>
    <fullName>SVC_Name__c</fullName>
    <description>Integration Name for which PE is published</description>
    <label>SVC Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <description>IndusInd deal number</description>
    <label>Deal Number</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Loan_Application_Number__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application_Number__c</fullName>
    <label>Loan Application Number</label>
    <type>AutoNumber</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Repayments__c/Repayments__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <label>Repayments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Repayments__c/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Number</label>
    <referenceTo>Deal_Number__c</referenceTo>
    <relationshipLabel>Repayments</relationshipLabel>
    <relationshipName>Repayments</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Repayments__c/fields/E_NACH_API_Status__c.field-meta.xml
<CustomField>
    <fullName>E_NACH_API_Status__c</fullName>
    <label>E-NACH API Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Repayments__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Repayments</relationshipLabel>
    <relationshipName>Repayments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Repayments__c/fields/Repayment_Method__c.field-meta.xml
<CustomField>
    <fullName>Repayment_Method__c</fullName>
    <label>Repayment Method</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N</fullName>
                <label>e-NACH</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>ACH</label>
            </value>
            <value>
                <fullName>I</fullName>
                <label>SI</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>IES</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Repayments__c/fields/SI_Status__c.field-meta.xml
<CustomField>
    <fullName>SI_Status__c</fullName>
    <label>SI Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Retry_Count__c/Retry_Count__c.object-meta.xml
<CustomObject>
    <label>Retry Count</label>
    <nameField>
        <displayFormat>Ret-{000000}</displayFormat>
        <label>Retry Count Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retry Counts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Retry_Count__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Retry_Counts</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Retry_Count__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-borrower</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Retry_Count__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <label>Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Retry_Count__c/fields/Loan_Application_Id__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application_Id__c</fullName>
    <label>Loan Application Id</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Retry_Count</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Retry_Count__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Id</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Retry_Counts1</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Retry_Count__c/fields/Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>Vehicle_Detail__c</referenceTo>
    <relationshipLabel>Retry Counts</relationshipLabel>
    <relationshipName>Retry_Counts</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/System_Constant_custom_metadata__mdt/System_Constant_custom_metadata__mdt.object-meta.xml
<CustomObject>
    <label>System Constant</label>
    <pluralLabel>System Constants</pluralLabel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/System_Constant_custom_metadata__mdt/fields/Number_Of_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Number_Of_Attempts__c</fullName>
    <label>Number Of Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <externalId>true</externalId>
    <label>User Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/Vehicle_Detail__c.object-meta.xml
<CustomObject>
    <label>Vehicle Detail</label>
    <nameField>
        <displayFormat>VD-{00000}</displayFormat>
        <label>Vehicle Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Number</label>
    <referenceTo>Deal_Number__c</referenceTo>
    <relationshipLabel>Vehicle Details</relationshipLabel>
    <relationshipName>Vehicle_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/ENACHController.cls
/* 
 @File Name : ENACHController.cls 
 @Description :  Controller class for ENACH
 @Author : Yogesh Rao 
 @Last Modified By : Yogesh Rao 
 @Last Modified On : 28 April 2022 
 @Modification Log : 
 ============================================================================== 
 Ver        Date          Author       Modification 
 ============================================================================== 
 1.0     28 April 2022    Yogesh Rao   Initial Version 
*/
public with sharing class ENACHController {
    /* 
     @description :   Method to check if retry count is exhausted
     @param :  String loanApplicationId
     @param :  String serviceName
     @return : Boolean
    */
    @AuraEnabled
    public static Boolean checkRetryExhausted(String loanApplicationId, String serviceName, String dealId) {
      try {
        if (loanApplicationId != null) {
          //CISP-4181 Added filter of User_Id__c field for fetching Retry_Count__c record
          List<Retry_Count__c> retryCountList = [SELECT Id, Count__c FROM Retry_Count__c WHERE Loan_Application_Id__c = :loanApplicationId AND Service_Name__c = :serviceName AND User_Id__c =: UserInfo.getUserId() AND Vehicle_Detail__r.Deal_Number__c =: dealId WITH SECURITY_ENFORCED];
          if (!retryCountList.isEmpty()) {
            System_Constant_custom_metadata__mdt metadata = System_Constant_custom_metadata__mdt.getInstance(serviceName);
            if (retryCountList[0].Count__c >= metadata.Number_Of_Attempts__c) {
              return true;
            }
          }
        }
        return false;
      } catch (Exception e) {
        ErrorLoggerUtil.logErrorEvent('ENACHController', System.Label.CheckRetryExhausted, System.Label.Apex, e,loanApplicationId);
        throw new AuraHandledException(System.Label.ExceptionMessage);
      }
    }
    /* 
    @description :   Method to increase retry count
    @param :  String loanApplicationId
    @param :  String serviceName
    @return : Boolean 
   */
    @AuraEnabled
    public static Boolean retryCountIncrease(String loanApplicationId, String serviceName, String dealId) {
      try {
        if (loanApplicationId != null) {
          //CISP-4181 Added filter of User_Id__c field for fetching Retry_Count__c record
          List<Retry_Count__c> retryCountList = [SELECT Id, Count__c FROM Retry_Count__c WHERE Loan_Application_Id__c = :loanApplicationId AND Service_Name__c = :serviceName AND User_Id__c =: UserInfo.getUserId() AND Vehicle_Detail__r.Deal_Number__c =: dealId WITH SECURITY_ENFORCED];
          if (!retryCountList.isEmpty()) {
            System_Constant_custom_metadata__mdt metadata = System_Constant_custom_metadata__mdt.getInstance(serviceName);
            Decimal count =  retryCountList[0].Count__c == null ? 0 : retryCountList[0].Count__c;
            if (count < metadata.Number_Of_Attempts__c) {
              retryCountList[0].Count__c += 1;
              if (Schema.sObjectType.Retry_Count__c.isUpdateable()) {
                update retryCountList;
              } else {
                throw new AuraHandledException(System.Label.Retrycountnotupdate);
              }
              if (retryCountList[0].Count__c >= metadata.Number_Of_Attempts__c) {
                return true;
              }
            }
          } else {
            List<Vehicle_Detail__c> vehicleList = new List<Vehicle_Detail__c>([Select Id from Vehicle_Detail__c Where Deal_Number__c =: dealId LIMIT 1]);
            Retry_Count__c retryCount = new Retry_Count__c();
            retryCount.Loan_Application_Id__c = loanApplicationId;
            retryCount.Service_Name__c = serviceName;
            retryCount.Vehicle_Detail__c = vehicleList.size() > 0 ?  vehicleList[0].Id : null;
            retryCount.User_Id__c = UserInfo.getUserId(); //CISP-4181 Populate User Id field while inserting retry count object
            retryCount.Count__c = 1;
            if (Schema.sObjectType.Retry_Count__c.isCreateable()) {
              insert retryCount;
            } else {
              throw new AuraHandledException(System.Label.Retrycountnotinserted);
            }
          }
        }
        return false;
      } catch (Exception e) {
        ErrorLoggerUtil.logErrorEvent('ENACHController', 'retryCountIncrease', System.Label.Apex, e,loanApplicationId);
        throw new AuraHandledException(System.Label.ExceptionMessage);
      }
    }
  
    /* 
     @description :   Method to handle ENACH and SI Platform Event
     @param :  List<Low_Payload_Response__e> newLowPayloadResponseList
     @return : Void
    */
    public static void eNachEventHandler(List<Low_Payload_Response__e> newLowPayloadResponseList) {
      Map<Id, Repayments__c> repaymentsToUpdate = new Map<Id, Repayments__c>();
      Map<String, Repayments__c> loanAppVsRepayment = getRepaymentId(newLowPayloadResponseList);
System.debug('Enach_debug_1'+ loanAppVsRepayment);
      Set<String> loanAppIds = new Set<String>();
      Set<Id> dealIds = new Set<Id>();
      Map<Id, Loan_Application_Transaction_History__c> transactionHistoryToUpdate = new Map<Id, Loan_Application_Transaction_History__c>();
      try {
        Boolean isStatusSuccess = true;
        for (Low_Payload_Response__e event : newLowPayloadResponseList) {
          String leadId = event.Reference_Id__c != null ? event.Reference_Id__c.split('-')[0] : '';
          if (event.SVC_Name__c == 'ENACH Registration Status' && loanAppVsRepayment.get(leadId)!=null && loanAppVsRepayment.get(leadId).Repayment_Method__c =='N') {
            Map<String, Object> resp = (Map<String, Object>) JSON.deserializeUntyped(event.Response__c);
            String encryptedResp = (String) resp.get('JData');
            String decryptedResp = IntegrationUtilities.getDecryptedResponse(encryptedResp, System.Label.privateKey, System.Label.ivkey);
            Map<String, Object> response = (Map<String, Object>) JSON.deserializeUntyped(decryptedResp);
            System.debug('Enach_debug_2'+ response);
            String npciStatusObj = response.containsKey('npcistatus') ? (String)response.get('npcistatus') : null;
            String errorCodeCheck = response.containsKey('error_code') ? (String)response.get('error_code') : null;
             //CISP-15151 Only update the repayment record if the E_NACH_API_Status__c is not success
            if(loanAppVsRepayment.get(leadId).E_NACH_API_Status__c != 'ENACH Registration Success') {
             System.debug('Enach_debug_3'+ npciStatusObj);
            if (npciStatusObj == 'failed') {
             System.debug('Enach_debug_4'+ npciStatusObj);
              isStatusSuccess = false;
              repaymentsToUpdate.put(loanAppVsRepayment.get(leadId).Id, new Repayments__c(Id = loanAppVsRepayment.get(leadId).Id, E_NACH_API_Status__c = 'ENACH Registration Failed', Message__c = (String) response.get('message')));
            } else if(errorCodeCheck == 'E0005'){
              isStatusSuccess = false;
              repaymentsToUpdate.put(loanAppVsRepayment.get(leadId).Id, new Repayments__c(Id = loanAppVsRepayment.get(leadId).Id, E_NACH_API_Status__c = 'Customer Action On ENACH Pending', Message__c = (String) response.get('message')));    
            } else if(String.isBlank(npciStatusObj) && String.isBlank(errorCodeCheck) ) {
            System.debug('Enach_debug_5'+ npciStatusObj);
              isStatusSuccess = false;
              repaymentsToUpdate.put(loanAppVsRepayment.get(leadId).Id, new Repayments__c(Id = loanAppVsRepayment.get(leadId).Id, E_NACH_API_Status__c = 'Response From NPCI Pending', Message__c = (String) response.get('message')));
            } 
            else {
             System.debug('Enach_debug_6'+ npciStatusObj);
              loanAppIds.add(leadId);//To update Loan Transaction History
              repaymentsToUpdate.put(loanAppVsRepayment.get(leadId).Id, new Repayments__c(Id = loanAppVsRepayment.get(leadId).Id, E_NACH_API_Status__c = 'ENACH Registration Success', Message__c = (String) response.get('message')));
              dealIds.add(loanAppVsRepayment.get(leadId).Deal_Number__c);
            }
            }
            //CISP-15151 END
          } else if (event.SVC_Name__c == 'SIStatus' && loanAppVsRepayment.get(leadId)!=null && loanAppVsRepayment.get(leadId).Repayment_Method__c =='I') {
            Map<String, Object> resp = (Map<String, Object>) JSON.deserializeUntyped(event.Response__c);
            String encryptedResp = (String) resp.get('JData');
            String decryptedResp = IntegrationUtilities.getDecryptedResponse(encryptedResp, System.Label.privateKey, System.Label.ivkey);
            Map<String, Object> response = (Map<String, Object>) JSON.deserializeUntyped(decryptedResp);
            Map<String, Object> respObj = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(response.get('response')));
            if ((String) respObj.get('status') == 'SUCCESS') {
              loanAppIds.add(leadId);//To update Loan Transaction History
              ENACHController.SIResponseWrapper siWrapper = (ENACHController.SIResponseWrapper) JSON.deserialize(decryptedResp, ENACHController.SIResponseWrapper.class);
              if(siWrapper?.response?.content[0].Status == 'Customer not initiated for the Standing Instruction' || siWrapper?.response?.content[0].Status == 'Customer registration for the Standing Instruction is pending'){
                isStatusSuccess = false;
                repaymentsToUpdate.put(loanAppVsRepayment.get(leadId).Id, new Repayments__c(Id = loanAppVsRepayment.get(leadId).Id, SI_Status__c = 'In Progress', Message__c = 'Customer registration for the Standing Instruction is pending'));
              }else if(siWrapper?.response?.content[0].Status == 'Customer registration for the Standing Instruction got failed'){
                isStatusSuccess = false;
                repaymentsToUpdate.put(loanAppVsRepayment.get(leadId).Id, new Repayments__c(Id = loanAppVsRepayment.get(leadId).Id, SI_Status__c = 'FAILED', Message__c = siWrapper?.response?.content[0].Status));
              }else if(siWrapper?.response?.content[0].Status == 'Customer registered for the Standing Instruction'){
                repaymentsToUpdate.put(loanAppVsRepayment.get(leadId).Id, new Repayments__c(Id = loanAppVsRepayment.get(leadId).Id, SI_Status__c = 'SUCCESS', Message__c = siWrapper?.response?.content[0].Status));
                dealIds.add(loanAppVsRepayment.get(leadId).Deal_Number__c);
              }
            } else {
              isStatusSuccess = false;
              repaymentsToUpdate.put(loanAppVsRepayment.get(leadId).Id, new Repayments__c(Id = loanAppVsRepayment.get(leadId).Id, SI_Status__c = 'Response is awaited', Message__c = (String) respObj.get('respDesc')));
            }
          }
        }
        if (!repaymentsToUpdate.isEmpty()) {
          System.debug('Enach_debug_7'+ repaymentsToUpdate);
          update repaymentsToUpdate.values();
        }
        if(!loanAppIds.isEmpty() && isStatusSuccess){
          Set<Id> loanIds = new Set<Id>();
          for (Opportunity loan : [SELECT Id FROM Opportunity WHERE Id IN:loanAppIds WITH SECURITY_ENFORCED]) {
            loanIds.add(loan.Id);
          }
          if(dealIds.size() > 0){
            for (Loan_Application_Transaction_History__c each : [SELECT Id, Name, Submitted_Flag__c FROM Loan_Application_Transaction_History__c WHERE Loan_Application_ID__c IN:loanIds AND Deal_Number__c IN : dealIds AND (Name =: System.Label.Repayment_Mandate OR Screen__c =: System.Label.Repayment_Mandate) AND Module__c =: System.Label.Post_Sanction_Checks_and_Documentation WITH SECURITY_ENFORCED]) {
              if (!each.Submitted_Flag__c) {
                transactionHistoryToUpdate.put(each.Id, new Loan_Application_Transaction_History__c(Id = each.Id, Submitted_Flag__c = true));
              }
            }
          }else{
          for (Loan_Application_Transaction_History__c each : [SELECT Id, Name, Submitted_Flag__c FROM Loan_Application_Transaction_History__c WHERE Loan_Application_ID__c IN:loanIds AND (Name =: System.Label.Repayment_Mandate OR Screen__c =: System.Label.Repayment_Mandate) AND Module__c =: System.Label.Post_Sanction_Checks_and_Documentation WITH SECURITY_ENFORCED]) {
            if (!each.Submitted_Flag__c) {
              transactionHistoryToUpdate.put(each.Id, new Loan_Application_Transaction_History__c(Id = each.Id, Submitted_Flag__c = true));
            }
          }
          }
          if (!transactionHistoryToUpdate.isEmpty()) {
            update transactionHistoryToUpdate.values();
          }
        }
      } catch (Exception e) {
        ErrorLoggerUtil.logErrorEvent('ENACHController', 'eNachEventHandler', System.Label.Apex, e);
        throw new ENACHControllerException(System.Label.ExceptionMessage);
      }
    }
    /* @Method : submitENACH
       @description :   Method to update Loan_Application_Transaction_History__c after ENACH is completed
       @param :  String loanApplicationId
       @return : Void 
      */
    @AuraEnabled
    public static void submitENACH(String loanApplicationId) {
      try {
        Map<Id, Loan_Application_Transaction_History__c> listToUpdate = new Map<Id, Loan_Application_Transaction_History__c>();
        for (Loan_Application_Transaction_History__c each : [SELECT Id, Name, Submitted_Flag__c FROM Loan_Application_Transaction_History__c WHERE Loan_Application_ID__c = :loanApplicationId AND Name =: System.Label.Repayment_Mandate WITH SECURITY_ENFORCED]) {
          if (!each.Submitted_Flag__c) {
            listToUpdate.put(each.Id, new Loan_Application_Transaction_History__c(Id = each.Id, Submitted_Flag__c = true));
          }
        }
        if (!listToUpdate.isEmpty() && Schema.sObjectType.Loan_Application_Transaction_History__c.isUpdateable()) {
          update listToUpdate.values();
        }
      } catch (Exception e) {
        ErrorLoggerUtil.logErrorEvent('ENACHController', 'submitENACH', System.Label.Apex, e,loanApplicationId);
        throw new ENACHControllerException(System.Label.ExceptionMessage); 
      }
    }
  
    /* 
     @description :   Method to get repaymentIds
     @param :  List<Low_Payload_Response__e>
     @return : Map<Id,Id> mapOfLoanApplicationIdVsRepaymentId
    */
    public static Map<String, Repayments__c> getRepaymentId(List<Low_Payload_Response__e> newLowPayloadResponseList) {
      Set<String> loanAppNum = new Set<String>();
      Map<String, Repayments__c> loanAppVsRepayment = new Map<String, Repayments__c>();
      for (Low_Payload_Response__e each : newLowPayloadResponseList) {
        if(each.Reference_Id__c !=null){
          String leadId = each.Reference_Id__c != null ? each.Reference_Id__c.split('-')[0] : '';
          loanAppNum.add(leadId);
        }
      }
      if(!loanAppNum.isEmpty()){
        for(Opportunity each:[SELECT Id,Loan_Application_Number__c,(SELECT Id,Repayment_Method__c, E_NACH_API_Status__c,Deal_Number__c FROM Repayments__r LIMIT 1) FROM Opportunity WHERE Id IN:loanAppNum WITH SECURITY_ENFORCED]){//CISP-15151 Added E_NACH_API_Status__c field
          if(each.Repayments__r!=null){
            loanAppVsRepayment.put(each.Id,each.Repayments__r[0]);
          }
        }
      }
      return loanAppVsRepayment;
    }
    /* //SFTRAC-401- Aakash
     @description :   Method to get getApplicantId
     @param :  List<Low_Payload_Response__e>
     @return : Map<Id,Id> applicantMap 
    */
  
    public static void criffEventHandler(List<Low_Payload_Response__e> newLowPayloadResponseList) {
  
      Map<Id, Applicant__c> applicantToUpdate = new Map<Id, Applicant__c>();
      Set<String> applicantSet = new Set<String>();
      Map<String, String> applicantMap = new Map<String, String>();
      Map<String, String> loanApplicationMap = new Map<String, String>();
      Set<String> loanAppIds = new Set<String>();
      Set<String> referenceIdSet = new Set<String>();
      for (Low_Payload_Response__e each : newLowPayloadResponseList) {
        if(each.Reference_Id__c !=null){
          String applicantId = each.Reference_Id__c != null ? each.Reference_Id__c.split('-')[0] : '';
          applicantSet.add(applicantId);
          String referenceId = each.Reference_Id__c != null ? each.Reference_Id__c : '';
          referenceIdSet.add(referenceId);
        }
      }
  
      String cicNoValue;
  
      if(!applicantSet.isEmpty()){
        for(Applicant__c each:[SELECT Id, Opportunity__c,CIC_No__c,Applicant_Type__c FROM Applicant__c WHERE Id IN:applicantSet WITH SECURITY_ENFORCED]){
          applicantMap.put(each.Id,each.Id);
          loanApplicationMap.put(each.Id,each.Opportunity__c);
          if(each.Applicant_Type__c == 'Borrower' && each.CIC_No__c != ''){
            cicNoValue = each.CIC_No__c;
          }
        }
      }
  
      for (Low_Payload_Response__e eventRec : newLowPayloadResponseList) {
        String appliId = eventRec.Reference_Id__c != null ? eventRec.Reference_Id__c.split('-')[0] : '';
        if (eventRec.SVC_Name__c == System.Label.GetCRIFReport && applicantMap.get(appliId)!=null) {
          Map<String, Object> resp = (Map<String, Object>) JSON.deserializeUntyped(eventRec.Response__c);
          String encryptedResp = (String) resp.get('JData');
          String decryptedResp = IntegrationUtilities.getDecryptedResponse(encryptedResp, System.Label.privateKey, System.Label.ivkey);
          Map<String, Object> response = (Map<String, Object>) JSON.deserializeUntyped(decryptedResp);
          Map<String, Object> respObj = (Map<String, Object>) JSON.deserializeUntyped(JSON.serialize(response.get('response')));
          if ((String) respObj.get('status') == 'SUCCESS') {
            loanAppIds.add(loanApplicationMap.get(appliId));//To update Loan Transaction History
            //Create a Response Wrappper for 
            ENACHController.CRIFFResponseWrapper criffWrapper = (ENACHController.CRIFFResponseWrapper) JSON.deserialize(decryptedResp, ENACHController.CRIFFResponseWrapper.class);
            String criffURL = criffWrapper != null && criffWrapper.response != null && criffWrapper.response.content != null && criffWrapper.response.content[0].Reporturl != '' ? criffWrapper?.response?.content[0].Reporturl+'/?CIC_No='+cicNoValue : '';
            applicantToUpdate.put(applicantMap.get(appliId), new Applicant__c(Id = applicantMap.get(appliId), CRIFF_Report_URL__c = criffURL));
          }
        }
      }
  
      if(!applicantToUpdate.isEmpty()) {
        update applicantToUpdate.values();
      }
    }
    @AuraEnabled
    public static List<Integration_Log__c> enachJournyStatusHistory(String loanApplicationId){//CISP-21804
      try{
        List<Integration_Log__c> enachJournyStatusHistory = new List<Integration_Log__c>();
       List<Integration_Log__c> enachStatusData=[SELECT Id,Service_Name__c,Loan_Application__c,Original_response__c,Original_request__c FROM Integration_Log__c where Service_Name__c ='ENACH Registration Status' and Loan_Application__c=:loanApplicationId ORDER BY CreatedDate DESC];
        for(Integration_Log__c intList : enachStatusData){
           if(intList.Original_response__c != null && intList.Original_response__c != ''){
            enachJournyStatusHistory.add(intList);
           }
        }
        if(enachJournyStatusHistory != null && enachJournyStatusHistory.size()>0){
     return enachJournyStatusHistory;
    }else{
        return null;
    }
  }Catch(Exception e){
    ErrorLoggerUtil.logErrorEvent('ENACHController', 'enachJournyStatusHistory', 'Class', e);
    throw new AuraHandledException(System.Label.ExceptionMessage);
  } 
    }//CISP-21804 
    public class SIResponseWrapper {
      Response response;
    }
  
    public class Response {
      String status;
      String respDesc;
      List<Content> content;
    }
  
    public class Content {
      String Deal_No;
      String Status;
    }
    //SFTRAC-410 Starts
    public class CRIFFResponseWrapper {
      CriffResponse response;
    }
  
    public class CriffResponse {
      String status;
      String respDesc;
      List<CriffContent> content;
    }
  
    public class CriffContent {
      String Isreportgenerated;
      String Reporturl;
    }
    //SFTRAC-410 Ends
  
    public class ENACHControllerException extends Exception {}
  }