ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Bureau_Pull_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Bureau_Pull_Attempts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Bureau Pull Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Income_Ca__c.field-meta.xml
<CustomField>
    <fullName>Income_Ca__c</fullName>
    <label>Income Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>SEP</fullName>
            </value>
            <value>
                <fullName>SENP</fullName>
            </value>
            <value>
                <fullName>SAL</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/PAN_No__c.field-meta.xml
<CustomField>
    <fullName>PAN_No__c</fullName>
    <label>PAN No.</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADVOCATE</fullName>
            </value>
            <value>
                <fullName>AGRICULTURE PRODUCE</fullName>
            </value>
            <value>
                <fullName>AGRICULTURIST</fullName>
            </value>
            <value>
                <fullName>ASSOCIATION</fullName>
            </value>
            <value>
                <fullName>AUTO CONSULTANT</fullName>
            </value>
            <value>
                <fullName>AUTOMOBILE ANCILLARY</fullName>
            </value>
            <value>
                <fullName>AUTOMOBILE DEALERS</fullName>
            </value>
            <value>
                <fullName>AUTOMOBILE MANUFACTURER</fullName>
            </value>
            <value>
                <fullName>BAKERY</fullName>
            </value>
            <value>
                <fullName>BANK EMPLOYEE</fullName>
            </value>
            <value>
                <fullName>BAR OWNER</fullName>
            </value>
            <value>
                <fullName>BEAUTY PARLOR</fullName>
            </value>
            <value>
                <fullName>BLDG. CONTRACTOR</fullName>
            </value>
            <value>
                <fullName>BLUE METAL</fullName>
            </value>
            <value>
                <fullName>BROKER</fullName>
            </value>
            <value>
                <fullName>BUILDER</fullName>
            </value>
            <value>
                <fullName>CABLE</fullName>
            </value>
            <value>
                <fullName>CEMENT</fullName>
            </value>
            <value>
                <fullName>CERAMICS</fullName>
            </value>
            <value>
                <fullName>CHARTERED ACCOUNTANT</fullName>
            </value>
            <value>
                <fullName>CHEMICALS AND DYES</fullName>
            </value>
            <value>
                <fullName>CHIT COMPANY</fullName>
            </value>
            <value>
                <fullName>CLINIC</fullName>
            </value>
            <value>
                <fullName>COAL MINING</fullName>
            </value>
            <value>
                <fullName>COFFEE AND TEA</fullName>
            </value>
            <value>
                <fullName>COLLECTION AGENCY</fullName>
            </value>
            <value>
                <fullName>COMMISSION AGENCY</fullName>
            </value>
            <value>
                <fullName>COMPUTER PERIPHERAL DEALER</fullName>
            </value>
            <value>
                <fullName>CONSTRUCTION COMPANY</fullName>
            </value>
            <value>
                <fullName>CONSULTANTS OPERATING FROM RESIDENCE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Selfie_Retry_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Selfie_Retry_Attempts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Selfie Retry Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Whatsapp_number__c.field-meta.xml
<CustomField>
    <fullName>Whatsapp_number__c</fullName>
    <label>Whatsapp number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Aadhar_Source__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Source__c</fullName>
    <label>Aadhar Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTP</fullName>
            </value>
            <value>
                <fullName>Biometric</fullName>
            </value>
            <value>
                <fullName>Scan and Upload</fullName>
            </value>
            <value>
                <fullName>ScanAadhar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/CMU_Accept_Reject__c.field-meta.xml
<CustomField>
    <fullName>CMU_Accept_Reject__c</fullName>
    <label>CMU Accept/Reject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Name_Mismatch_Pass__c.field-meta.xml
<CustomField>
    <fullName>Name_Mismatch_Pass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Name Mismatch Pass</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Name_Mismatch_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Name_Mismatch_Percentage__c</fullName>
    <label>Name Match Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Opportunity_Relation__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Relation__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/PAN_No__c.field-meta.xml
<CustomField>
    <fullName>PAN_No__c</fullName>
    <label>PAN No.</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Proof_of_Identity_POI__c.field-meta.xml
<CustomField>
    <fullName>Proof_of_Identity_POI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proof of Identity (POI)</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Rejection_Fields__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Fields__c</fullName>
    <label>Rejection Fields</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>CMU_Accept_Reject__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Kyc_Fields</valueSetName>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACCOUNTANT</fullName>
            </value>
            <value>
                <fullName>ADVOCATE</fullName>
            </value>
            <value>
                <fullName>AGRICULTURE PRODUCE</fullName>
            </value>
            <value>
                <fullName>AGRICULTURIST</fullName>
            </value>
            <value>
                <fullName>AQUACULTURE</fullName>
            </value>
            <value>
                <fullName>ASSOCIATION</fullName>
            </value>
            <value>
                <fullName>AUTO CONSULTANT</fullName>
            </value>
            <value>
                <fullName>AUTO OWNER</fullName>
            </value>
            <value>
                <fullName>AUTOMOBILE ANCILLARY</fullName>
            </value>
            <value>
                <fullName>AUTOMOBILE DEALERS</fullName>
            </value>
            <value>
                <fullName>AUTOMOBILE MANUFACTURER</fullName>
            </value>
            <value>
                <fullName>BAKERY</fullName>
            </value>
            <value>
                <fullName>BAKERY &amp; SMALL FOOD RETAILS</fullName>
            </value>
            <value>
                <fullName>BANK EMPLOYEE</fullName>
            </value>
            <value>
                <fullName>BAR OWNER</fullName>
            </value>
            <value>
                <fullName>BEAUTY PARLOR</fullName>
            </value>
            <value>
                <fullName>BED WORKER</fullName>
            </value>
            <value>
                <fullName>BIDI WORK</fullName>
            </value>
            <value>
                <fullName>BLDG. CONTRACTOR</fullName>
            </value>
            <value>
                <fullName>BLUE METAL</fullName>
            </value>
            <value>
                <fullName>BOOK SHOP - RETAIL</fullName>
            </value>
            <value>
                <fullName>BRICKS - MFGR</fullName>
            </value>
            <value>
                <fullName>BROKER</fullName>
            </value>
            <value>
                <fullName>BUILDER</fullName>
            </value>
            <value>
                <fullName>BUSINESS - MASALA POWER</fullName>
            </value>
            <value>
                <fullName>BUSINESS- STONE - SUPPLIER</fullName>
            </value>
            <value>
                <fullName>CABLE</fullName>
            </value>
            <value>
                <fullName>CANDLE -MFGRS</fullName>
            </value>
            <value>
                <fullName>CANTEEN &amp; MESS</fullName>
            </value>
            <value>
                <fullName>CARPENTER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Selfie_Retry_Attempts__c.field-meta.xml
<CustomField>
    <fullName>Selfie_Retry_Attempts__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Selfie Retry Attempts</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Whatsapp_number__c.field-meta.xml
<CustomField>
    <fullName>Whatsapp_number__c</fullName>
    <label>Whatsapp number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/classes/DocumentTriggerTest.cls
/*
* @author: Raj Gupta.
* @company: Persistent Systems
* @description: Test class for IND_DocumentTrigger class.
* History:
* Inputs: None
* 11/10/2012  Added by Raj for Initial (IND-309). 
*/
@isTest
public class DocumentTriggerTest
{
    //Setup method is use to create demo data.
    @testSetup 
    static void setup()
    {
       /* TriggerSwitch__c trgSwitch = new TriggerSwitch__c();
        trgSwitch.Name = 'IND_DocumentTrigger';
        trgSwitch.Active__c = true;
        insert trgSwitch;*/
        
        TriggerSwitch__c trgSwitch = TestDataUtility.getTrigerSwitchData(true);
        
        Opportunity optg1 = new Opportunity();
        optg1.StageName = 'Qualification';
        optg1.CloseDate = Date.newInstance(2021, 1, 11);
        optg1.Name = 'testone';
        insert optg1;
        
        
        //Applicant__c applicant = new Applicant__c(Name='Applicant1',Contact_Number__c ='1234567891',Whatsapp_number__c='1231231231',Income_Ca__c='SAL',Profile__c = 'Software Engineer', Bureau_Pull_Attempts__c=1,Selfie_Retry_Attempts__c=2);
        Applicant__c applicant = TestDataUtility.createTestApplicant(false);
        applicant.Opportunity__c = optg1.Id;
        
        if (Schema.sObjectType.Applicant__c.isCreateable())
        {   
            insert applicant;     
        }
        
        Documents__c document = new Documents__c();
        
        //Documents__c document=new Documents__c();
        document.Opportunity_Relation__c = optg1.Id;
        document.Applicant__c = applicant.Id;       
        document.Proof_of_Identity_POI__c = false;
        document.Name_Mismatch_Percentage__c = 10;
        document.Name_Mismatch_Pass__c = true;        
        if (Schema.sObjectType.Applicant__c.isCreateable())
        {   
            insert document;    
        }
        
    }
    
    //DocumentUpdate method is test method use to test IND_documentTrigger
    @isTest
    public static void documentUpdate()
    {
           
        try
        {
            Test.startTest();
            Documents__c doc = [SELECT PAN_No__c,Proof_of_Identity_POI__c,Rejection_Fields__c FROM Documents__c LIMIT 1];
            doc.Proof_of_Identity_POI__c = true;
            doc.PAN_No__c = 'xxxxxxxxxxxx';
            update doc;
            doc.PAN_No__c = 'yyyyyyyyyy';
            doc.Name_Mismatch_Pass__c = true;
            doc.Name_Mismatch_Percentage__c = 80;
            update doc;
            Test.stopTest();
        }
        //DML exception handle here.
       Catch(Exception e){
          /*  System.debug('***Exception '+e.getMessage()+' occurred at line number '+e.getLineNumber());
            Error_Log__c errorLogRecord = ErrorLoggerUtil.logError(System.Label.documentTriggerTest, ' afterUpdate ', System.Label.Apex, e);
            insert errorLogRecord;
            throw new TriggerHandler.TriggerHandlerException(System.Label.ExceptionMessage);*/
            Boolean expectedExceptionThrown = e.getMessage().contains('XYZ') ? true : false;
            System.AssertEquals(expectedExceptionThrown, false);
	    }
    }
    
    @isTest
    public static void documentUpdates()
    {    
        try
        {
            Test.startTest();
            Documents__c doc = [SELECT Aadhar_Source__c FROM Documents__c LIMIT 1];
            doc.Aadhar_Source__c = 'OTP';
            update doc;
            Test.stopTest();
        }
        //DML exception handle here.
       Catch(Exception e){
            Boolean expectedExceptionThrown = e.getMessage().contains('XYZ') ? true : false;
            System.AssertEquals(expectedExceptionThrown, false);
	    }
    }

    @isTest
    public static void documentUpdate3()
    {
        try
        {
            Test.startTest();
            Documents__c doc = [SELECT Proof_of_Identity_POI__c, Rejection_Fields__c FROM Documents__c LIMIT 1];
            doc.Proof_of_Identity_POI__c = true;
            doc.CMU_Accept_Reject__c = 'Reject';
            doc.CMU_Rejection_Reason__c = 'Incorrect fields';
            doc.Rejection_Fields__c = 'Gender;Salutation';
            update doc;
            Test.stopTest();
        }
        //DML exception handle here.
       Catch(Exception e){
            Boolean expectedExceptionThrown = e.getMessage().contains('XYZ') ? true : false;
            System.AssertEquals(expectedExceptionThrown, false);
	    }
    }
}