ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-borrower</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/In_Active_Applicant__c.field-meta.xml
<CustomField>
    <fullName>In_Active_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In-Active Applicant</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/Loan_Application_Transaction_History__c.object-meta.xml
<CustomObject>
    <description>created for tackling lead assignments would be used.</description>
    <label>Loan Application Transaction History</label>
    <nameField>
        <label>Loan Application Transaction History</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application Transactions History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/fields/Assignment_status__c.field-meta.xml
<CustomField>
    <fullName>Assignment_status__c</fullName>
    <label>Assignment status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/fields/Current_Owner__c.field-meta.xml
<CustomField>
    <fullName>Current_Owner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Current Owner</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Transactions_History_Current_Owner</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/fields/Loan_Application_ID__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application_ID__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Loan Application Transactions History</relationshipLabel>
    <relationshipName>Loan_Application_Transactions_History</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/fields/Module_Name__c.field-meta.xml
<CustomField>
    <fullName>Module_Name__c</fullName>
    <label>Module Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Additional Details</fullName>
            </value>
            <value>
                <fullName>Asset Details</fullName>
            </value>
            <value>
                <fullName>Vehicle Insurance</fullName>
            </value>
            <value>
                <fullName>Vehicle Valuation</fullName>
            </value>
            <value>
                <fullName>Loan Details</fullName>
            </value>
            <value>
                <fullName>Income Details</fullName>
            </value>
            <value>
                <fullName>Final Terms</fullName>
            </value>
            <value>
                <fullName>Insurance Details</fullName>
            </value>
            <value>
                <fullName>FI</fullName>
            </value>
            <value>
                <fullName>Post Sanction Checks and Documentation</fullName>
            </value>
            <value>
                <fullName>Disbursement Request Preparation</fullName>
            </value>
            <value>
                <fullName>Qualification</fullName>
            </value>
            <value>
                <fullName>Needs Analysis</fullName>
            </value>
            <value>
                <fullName>Proposal</fullName>
            </value>
            <value>
                <fullName>Closed Won</fullName>
            </value>
            <value>
                <fullName>Loan Initiation</fullName>
            </value>
            <value>
                <fullName>Prospecting</fullName>
            </value>
            <value>
                <fullName>Offer Screen</fullName>
            </value>
            <value>
                <fullName>Existing EMI</fullName>
            </value>
            <value>
                <fullName>Credit Processing</fullName>
            </value>
            <value>
                <fullName>Additional Customer Details</fullName>
                <isActive>false</isActive>
                <label>Additional Customer Details</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Journey_Restart_Reason__c.field-meta.xml
<CustomField>
    <fullName>Journey_Restart_Reason__c</fullName>
    <label>Journey Restart Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/PreviousAccountId__c.field-meta.xml
<CustomField>
    <fullName>PreviousAccountId__c</fullName>
    <label>PreviousAccountId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/HandleJourney_UtilityTest.cls
@isTest
public class HandleJourney_UtilityTest {
    @isTest
    public static void handleCMUJourneyRestartTest(){
        try{
        Opportunity opp = TestDataUtility.createTestOpportunity(false);
        opp.Journey_Restart_Reason__c = 'testreason';
        opp.CloseDate = Date.newInstance(2022, 1, 11);
        //opp.StageName = 'Journey Restart';
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            
            Applicant__c applicant = TestDataUtility.createTestApplicantForSMS(false);
            applicant.Opportunity__c = opp.Id;
            applicant.Applicant_Type__c = System.label.Borrower;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
        
            Test.startTest();
                HandleJourney_Utility.handleCMUJourneyRestart(applicant.Id,opp.Journey_Restart_Reason__c);
            Test.stopTest();
        }catch(Exception e){
            System.assertEquals('Script-thrown exception', e.getMessage());
        }
    }
    
    @isTest
    public static void handleLoanApplictionNumberTest(){
         Opportunity opp = TestDataUtility.createTestOpportunity(false);
         if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
        
           Test.startTest();
                  HandleJourney_Utility.handleLoanApplictionNumber(opp.Id,'CMU Journey Restart');
                //  HandleJourney_Utility.handleLoanApplictionNumber('_JR','CMU Journey Restart');
           Test.stopTest();
    }
     @isTest
    public static void handleCMUJourneyRestartTest1(){
        try{
        Opportunity opp = TestDataUtility.createTestOpportunity(false);
        opp.Journey_Restart_Reason__c = 'testreason';
        opp.CloseDate = Date.newInstance(2022, 1, 11);
        //opp.StageName = 'Journey Restart';
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            
            Applicant__c applicant = TestDataUtility.createTestApplicantForSMS(false);
            applicant.Opportunity__c = opp.Id;
            applicant.Applicant_Type__c = System.label.Borrower;
            applicant.In_Active_Applicant__c = false;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
        
            Test.startTest();
                HandleJourney_Utility.handleCMUJourneyRestart(applicant.Id,opp.Journey_Restart_Reason__c);
                HandleJourney_Utility.handleCMUJourneyRestart('test','test');
            Test.stopTest();
        }catch(Exception e){
            System.assertEquals('Script-thrown exception', e.getMessage());
        }
    }
    
     @isTest
    public static void handleCMUJourneyRestartTest2(){
        try{
        Opportunity opp = TestDataUtility.createTestOpportunity(false);
        opp.Journey_Restart_Reason__c = 'testreason';
        opp.CloseDate = Date.newInstance(2022, 1, 11);
       // opp.LeadSource = 'DSA';
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            
            Applicant__c applicant = TestDataUtility.createTestApplicantForSMS(false);
            applicant.Opportunity__c = opp.Id;
            applicant.Applicant_Type__c = 'Co-Borrower';
            applicant.In_Active_Applicant__c = false;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
        
            Test.startTest();
                HandleJourney_Utility.handleCMUJourneyRestart(applicant.Id,opp.Journey_Restart_Reason__c);
                HandleJourney_Utility.handleCMUJourneyRestart('test','test');
            Test.stopTest();
        }catch(Exception e){
            System.assertEquals('Script-thrown exception', e.getMessage());
        }
    }
    
    
    public static void handleCMUJourneyRestartTest3(){
        try{
        Opportunity opp = TestDataUtility.createTestOpportunity(false);
        opp.Journey_Restart_Reason__c = 'testreason';
        opp.CloseDate = Date.newInstance(2022, 1, 11);
        opp.StageName = 'Journey Restart';
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            
            Applicant__c applicant = TestDataUtility.createTestApplicantForSMS(false);
            applicant.Opportunity__c = opp.Id;
            applicant.Applicant_Type__c = 'Co-Borrower';
            applicant.In_Active_Applicant__c = false;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
        
            Test.startTest();
                HandleJourney_Utility.handleCMUJourneyRestart(applicant.Id,opp.Journey_Restart_Reason__c);
                HandleJourney_Utility.handleCMUJourneyRestart('test','test');
            Test.stopTest();
        }catch(Exception e){
            System.assertEquals('Script-thrown exception', e.getMessage());
        }
    }
    
    @isTest
    public static void getLastSalesUserIdTest(){
        try{
            Opportunity opks1 = new Opportunity();
                opks1.StageName = 'Qualification';
                opks1.CloseDate = Date.newInstance(2021, 1, 11);
                opks1.Name = 'testone';
                opks1.OwnerId = UserInfo.getUserId();
                insert opks1;
            
                Loan_Application_Transaction_History__c lth1 = new Loan_Application_Transaction_History__c();
                lth1.Loan_Application_ID__c = opks1.Id;
                lth1.Module_Name__c = 'Credit Processing';
                lth1.Assignment_status__c = 'Accepted';
                lth1.RecordTypeId = Schema.SObjectType.Loan_Application_Transaction_History__c.getRecordTypeInfosByName().get('Stage Change').getRecordTypeId();
                insert lth1;
            
                Test.startTest();
                      HandleJourney_Utility.getLastSalesUserId(opks1.Id);
                Test.stopTest();
        }catch(Exception e){
            System.assertEquals('Script-thrown exception', e.getMessage());
        }
    }
    
    @isTest
    public static void getLastSalesUserIdTest1(){
        try{
            Opportunity opks1 = new Opportunity();
                opks1.StageName = 'Qualification';
                opks1.CloseDate = Date.newInstance(2021, 1, 11);
                opks1.Name = 'testone';
                opks1.OwnerId = UserInfo.getUserId();
                insert opks1;
            
                Loan_Application_Transaction_History__c lth1 = new Loan_Application_Transaction_History__c();
                lth1.Loan_Application_ID__c = opks1.Id;
                lth1.Module_Name__c = 'Credit Processing';
                lth1.Assignment_status__c = 'Accepted';
                lth1.Current_Owner__c = UserInfo.getUserId();
                lth1.RecordTypeId = Schema.SObjectType.Loan_Application_Transaction_History__c.getRecordTypeInfosByName().get('Stage Change').getRecordTypeId();
                insert lth1;
            
                Test.startTest();
                      HandleJourney_Utility.getLastSalesUserId(opks1.Id);
                      HandleJourney_Utility.getLastSalesUserId('test');
                      HandleJourney_Utility.handleLoanApplictionNumber(null,null);
                Test.stopTest();
        }catch(Exception e){
            System.assertEquals('Script-thrown exception', e.getMessage());
        }
    }
    @isTest
    public static void getBussDoneByIDTest1(){
        try{
            Account acc = new Account();
            acc.Name = 'AccName';
            insert acc;
            
            Account acc1 = new Account();
            acc1.Name = 'AccName';
            insert acc1;
            
            Opportunity opks1 = new Opportunity();
            opks1.StageName = 'Qualification';
            opks1.CloseDate = Date.newInstance(2021, 1, 11);
            opks1.Name = 'testone';
            opks1.OwnerId = UserInfo.getUserId();
            opks1.AccountId = acc.Id;
            opks1.PreviousAccountId__c = acc1.Id;
            insert opks1;
            
            AccountTeamMember atm2 = new AccountTeamMember();
            atm2.AccountId = opks1.AccountId;
            atm2.TeamMemberRole = 'BE';
            atm2.UserId = UserInfo.getUserId();
            insert atm2;
            
                Test.startTest();
                      HandleJourney_Utility.getBussDoneByID(opks1.Id);
            		
                Test.stopTest();
        }catch(Exception e){
            
        }
    }
    
     @isTest
    public static void getBussSourceByTestTest1(){
        try{
            Account acc = new Account();
            acc.Name = 'AccName';
            insert acc;
            
            Account acc1 = new Account();
            acc1.Name = 'AccName';
            insert acc1;
            
            Opportunity opks1 = new Opportunity();
            opks1.StageName = 'Qualification';
            opks1.CloseDate = Date.newInstance(2021, 1, 11);
            opks1.Name = 'testone';
            opks1.OwnerId = UserInfo.getUserId();
            opks1.AccountId = acc.Id;
            opks1.PreviousAccountId__c = acc1.Id;
            insert opks1;
            
            AccountTeamMember atm2 = new AccountTeamMember();
            atm2.AccountId = opks1.AccountId;
            atm2.TeamMemberRole = 'BE';
            atm2.UserId = UserInfo.getUserId();
            insert atm2;
            
                Test.startTest();
                      HandleJourney_Utility.getBussSourceBy(opks1.Id);
            		
                Test.stopTest();
        }catch(Exception e){
            
        }
    }
    
    @isTest
    public static void getBussSourceByTest(){
        try{
            Account acc = new Account();
            acc.Name = 'AccName';
            insert acc;
            
            Opportunity opks1 = new Opportunity();
            opks1.StageName = 'Qualification';
            opks1.CloseDate = Date.newInstance(2021, 1, 11);
            opks1.Name = 'testone';
            opks1.OwnerId = UserInfo.getUserId();
            opks1.AccountId = acc.Id;
            insert opks1;
            
            AccountTeamMember atm2 = new AccountTeamMember();
            atm2.AccountId = opks1.AccountId;
            atm2.TeamMemberRole = 'BE';
            atm2.UserId = UserInfo.getUserId();
            insert atm2;
            
                Test.startTest();
                      HandleJourney_Utility.getBussSourceBy(opks1.Id);
                        		
                Test.stopTest();
        }catch(Exception e){
            
        }
    }
    @isTest
    public static void getBussDoneByIDTest(){
        try{
            Account acc = new Account();
            acc.Name = 'AccName';
            insert acc;
            
            Opportunity opks1 = new Opportunity();
            opks1.StageName = 'Qualification';
            opks1.CloseDate = Date.newInstance(2021, 1, 11);
            opks1.Name = 'testone';
            opks1.OwnerId = UserInfo.getUserId();
            opks1.AccountId = acc.Id;
            insert opks1;
            
            AccountTeamMember atm2 = new AccountTeamMember();
            atm2.AccountId = opks1.AccountId;
            atm2.TeamMemberRole = 'BE';
            atm2.UserId = UserInfo.getUserId();
            insert atm2;
            
                Test.startTest();
                      HandleJourney_Utility.getBussDoneByID(opks1.Id);
            		
                Test.stopTest();
        }catch(Exception e){
            
        }
    }
}