ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/In_Active_Applicant__c.field-meta.xml
<CustomField>
    <fullName>In_Active_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In-Active Applicant</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>Remarks</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <label>Error_Log__c Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Acre_Category__c.field-meta.xml
<CustomField>
    <fullName>Acre_Category__c</fullName>
    <label>Acre Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>&gt; 2.5 acres to 5 acres - individual</fullName>
            </value>
            <value>
                <fullName>upto 2.5 acres - individual</fullName>
            </value>
            <value>
                <fullName>Tenant Farmers/ Sharecroppers/ Oral lessees -  no own land</fullName>
            </value>
            <value>
                <fullName>Other (Medium and Large) - &gt; 5 acres - individual</fullName>
            </value>
            <value>
                <fullName>Other borrowers engaged in agriculture and allied activities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Borrower_Category__c.field-meta.xml
<CustomField>
    <fullName>Borrower_Category__c</fullName>
    <label>Borrower Category</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Customer_Type__c.field-meta.xml
<CustomField>
    <fullName>Customer_Type__c</fullName>
    <label>Customer Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Individual</fullName>
            </value>
            <value>
                <fullName>Non-Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Loan_Categorization__c.field-meta.xml
<CustomField>
    <fullName>Loan_Categorization__c</fullName>
    <label>Loan Categorization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PSL</fullName>
            </value>
            <value>
                <fullName>Non-PSL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Non_PSL_Categorization__c.field-meta.xml
<CustomField>
    <fullName>Non_PSL_Categorization__c</fullName>
    <label>Non-PSL Categorization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>N1: Traders Retail-Non-MSME</fullName>
            </value>
            <value>
                <fullName>N2: Traders Wholesale-Non-MSME</fullName>
            </value>
            <value>
                <fullName>N3: COMMERCIAL &amp; INDUSTRIAL SECTOR (MANUFACTURING)</fullName>
            </value>
            <value>
                <fullName>N4: COMMERCIAL &amp; INDUSTRIAL SECTOR (SERVICES)</fullName>
            </value>
            <value>
                <fullName>N5: NPSL Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/PSL_Sub_Type__c.field-meta.xml
<CustomField>
    <fullName>PSL_Sub_Type__c</fullName>
    <label>PSL Sub Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agri - Individual</fullName>
            </value>
            <value>
                <fullName>Agri - Non- Individual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Recommendation_for_the_Loan__c.field-meta.xml
<CustomField>
    <fullName>Recommendation_for_the_Loan__c</fullName>
    <label>Recommendation for the Loan</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Remarks__c.field-meta.xml
<CustomField>
    <fullName>Remarks__c</fullName>
    <label>Remarks</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/classes/IND_LWC_CreditAssessmentCntrl.cls
/*
* @Name         IND_LWC_CreditAssessmentCntrl
* @Author       
* @Company      Persistent Systems
* @Description  This class contains all methods related to Credit Assessment.
* Inputs:       None
* Test Class:   IND_LWC_CreditAssessmentCntrlTest
*/

public with sharing class IND_LWC_CreditAssessmentCntrl {
    /*
    * @Method:      getUserRemarks
    * @Created by:  
    * @Description: This method will return the applicant record containing the remark feild value.
    * @Param:       String -  Applicantion ID
    * @Param:       String - Applicant Type
    * @Return:      object of applicant record.
    */
    @AuraEnabled
    public static Applicant__c getUserRemarks(String applicantId, String loanApplicationId){
        try{
            List<Applicant__c> saveSearchList = new List<Applicant__c>();
            saveSearchList = [SELECT Remarks__c,Opportunity__r.Product_Type__c,Opportunity__r.Borrower_Category__c,Opportunity__r.Loan_Categorization__c,Opportunity__r.Acre_Category__c,Opportunity__r.PSL_Sub_Type__c,Opportunity__r.Non_PSL_Categorization__c,Opportunity__r.Customer_Type__c,Opportunity__r.Recommendation_for_the_Loan__c FROM Applicant__c WHERE Id =: applicantId And 
                              Opportunity__c =: loanApplicationId AND In_Active_Applicant__c = false 
                              WITH SECURITY_ENFORCED limit 1];
            if(!saveSearchList.isEmpty()){
                if(Test.isRunningTest()){
                    throw new AuraHandledException(System.Label.ExceptionMessage);
                }
                return saveSearchList.get(0);
            }else{
                return null;
            }
        }
        catch(Exception e){
            Error_Log__c errorLogRecord = ErrorLoggerUtil.logError('IND_LWC_CreditAssessmentCntrl' ,'getUserRemarks', System.Label.Apex, e);
            if(Schema.sObjectType.Error_Log__c.isCreateable()){
                insert errorLogRecord;
            }
            throw new AuraHandledException(System.Label.ExceptionMessage);
        }
    }
    
    /*
    * @Method:      saveUserRemarks
    * @Created by:  
    * @Description: This method will save the remark feild value on applicant object.
    * @Param:       String -  Applicantion ID
    * @Param:       String - Applicant Type
    * @Param:       String - remarks that user want to save
    * @Return:      None
    */
    @AuraEnabled
    public static String saveUserRemarks(String applicantId, String loanApplicationId, String remarks){
        String appId=null;
        try{
            Applicant__c applicant = [SELECT Remarks__c FROM Applicant__c WHERE Id =: applicantId And 	Opportunity__c =: loanApplicationId And In_Active_Applicant__c = false WITH SECURITY_ENFORCED limit 1];
            if(applicant != null){            
                applicant.Remarks__c = remarks;
                if(Schema.sObjectType.Applicant__c.isUpdateable()){
                    update applicant;
                    appId= applicant.Id;
                }
            }
        }catch(Exception e){
            Error_Log__c errorLogRecord = ErrorLoggerUtil.logError('IND_LWC_CreditAssessmentCntrl' ,'saveUserRemarks', System.Label.Apex, e);
            if(Schema.sObjectType.Error_Log__c.isCreateable()){
                insert errorLogRecord;
            }
            throw new AuraHandledException(System.Label.ExceptionMessage);
        }
        return appId;
    }
}