ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-borrower</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Check_Eligibility_Message__c.field-meta.xml
<CustomField>
    <fullName>Check_Eligibility_Message__c</fullName>
    <description>In this field we will store the value of message returned by gattingCheckEligibility of Apex Class.</description>
    <label>Check Eligibility Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/In_Active_Applicant__c.field-meta.xml
<CustomField>
    <fullName>In_Active_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In-Active Applicant</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Scorecard_Decision__c.field-meta.xml
<CustomField>
    <fullName>Scorecard_Decision__c</fullName>
    <label>Scorecard Decision</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/Final_Term__c.object-meta.xml
<CustomObject>
    <description>To store Final term module data.</description>
    <label>Final Term</label>
    <nameField>
        <displayFormat>FT-{000000}</displayFormat>
        <label>Final Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/CRM_IRR__c.field-meta.xml
<CustomField>
    <fullName>CRM_IRR__c</fullName>
    <label>Offer engine CRM IRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/FIwaiver_presentAddress__c.field-meta.xml
<CustomField>
    <fullName>FIwaiver_presentAddress__c</fullName>
    <defaultValue>&apos;Not Waived&apos;</defaultValue>
    <description>API response store here</description>
    <label>FIwaiver_PermanentAddress</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Net_IRR__c.field-meta.xml
<CustomField>
    <fullName>Net_IRR__c</fullName>
    <label>Net IRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/PricingEngine_thresholdNetrr__c.field-meta.xml
<CustomField>
    <fullName>PricingEngine_thresholdNetrr__c</fullName>
    <label>Threshold Net IRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Tenure__c.field-meta.xml
<CustomField>
    <fullName>Tenure__c</fullName>
    <label>Offer engine Tenure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Basic_Price__c.field-meta.xml
<CustomField>
    <fullName>Basic_Price__c</fullName>
    <label>Basic Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/CRM_IRR__c.field-meta.xml
<CustomField>
    <fullName>CRM_IRR__c</fullName>
    <label>CRM IRR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Ex_showroom_price__c.field-meta.xml
<CustomField>
    <fullName>Ex_showroom_price__c</fullName>
    <label>Ex-showroom price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Funding_on_Ex_Showroom__c.field-meta.xml
<CustomField>
    <fullName>Funding_on_Ex_Showroom__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funding on Ex-Showroom</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Funding_on_ORP__c.field-meta.xml
<CustomField>
    <fullName>Funding_on_ORP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funding on ORP</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Grid_value__c.field-meta.xml
<CustomField>
    <fullName>Grid_value__c</fullName>
    <label>Grid value</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Imputed_IRR__c.field-meta.xml
<CustomField>
    <fullName>Imputed_IRR__c</fullName>
    <label>Imputed IRR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Is_Revoked__c.field-meta.xml
<CustomField>
    <fullName>Is_Revoked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Revoked</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Net_IRR__c.field-meta.xml
<CustomField>
    <fullName>Net_IRR__c</fullName>
    <label>Net IRR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/On_Road_price__c.field-meta.xml
<CustomField>
    <fullName>On_Road_price__c</fullName>
    <label>On Road price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/On_Road_price_carwale__c.field-meta.xml
<CustomField>
    <fullName>On_Road_price_carwale__c</fullName>
    <label>On Road price carwale</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Received_AML_API_response__c.field-meta.xml
<CustomField>
    <fullName>Received_AML_API_response__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Received AML API response</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>Selling_Price__c</fullName>
    <label>Selling Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Details</fullName>
            </value>
            <value>
                <fullName>Capture current residential address</fullName>
            </value>
            <value>
                <fullName>Capture permanent residential address</fullName>
            </value>
            <value>
                <fullName>Capture PAN or Other KYC</fullName>
            </value>
            <value>
                <fullName>Capture Dedupe</fullName>
            </value>
            <value>
                <fullName>Vehicle Dedupe</fullName>
            </value>
            <value>
                <fullName>Declared Income/Required Loan Amount</fullName>
            </value>
            <value>
                <fullName>Bank Account Check</fullName>
            </value>
            <value>
                <fullName>View Application Details</fullName>
            </value>
            <value>
                <fullName>CIBIL</fullName>
            </value>
            <value>
                <fullName>Field Investigation</fullName>
            </value>
            <value>
                <fullName>Credit Assessment</fullName>
            </value>
            <value>
                <fullName>Income Details</fullName>
            </value>
            <value>
                <fullName>Valuation IDV</fullName>
            </value>
            <value>
                <fullName>Final Terms</fullName>
            </value>
            <value>
                <fullName>Insurance Details</fullName>
            </value>
            <value>
                <fullName>Exposure Analysis</fullName>
            </value>
            <value>
                <fullName>Income</fullName>
            </value>
            <value>
                <fullName>CAM and Approval Log</fullName>
            </value>
            <value>
                <fullName>Risk Summary</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Tele-verification &lt;Post Sanction&gt;</fullName>
            </value>
            <value>
                <fullName>Vehicle Inspection and RC Check</fullName>
            </value>
            <value>
                <fullName>Structured EMI</fullName>
            </value>
            <value>
                <fullName>Security Mandate</fullName>
            </value>
            <value>
                <fullName>Additional Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>IHM</fullName>
            </value>
            <value>
                <fullName>Loan Agreement</fullName>
            </value>
            <value>
                <fullName>Signing the e-Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Total_Funded_Premium__c.field-meta.xml
<CustomField>
    <fullName>Total_Funded_Premium__c</fullName>
    <description>Sum of Insurance details &apos;Funded Premiums&apos;</description>
    <label>Total Funded Premium</label>
    <summarizedField>InsuranceDetails__c.Amount__c</summarizedField>
    <summaryFilterItems>
        <field>InsuranceDetails__c.Funded_Non_funded__c</field>
        <operation>equals</operation>
        <value>Funded</value>
    </summaryFilterItems>
    <summaryForeignKey>InsuranceDetails__c.Loan_Application__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Retry_Count__c/Retry_Count__c.object-meta.xml
<CustomObject>
    <label>Retry Count</label>
    <nameField>
        <displayFormat>Ret-{000000}</displayFormat>
        <label>Retry Count Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retry Counts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Retry_Count__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-borrower</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/Vehicle_Detail__c.object-meta.xml
<CustomObject>
    <label>Vehicle Detail</label>
    <nameField>
        <displayFormat>VD-{00000}</displayFormat>
        <label>Vehicle Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Grid_value__c.field-meta.xml
<CustomField>
    <fullName>Grid_value__c</fullName>
    <label>Grid value</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Selling_Price__c.field-meta.xml
<CustomField>
    <fullName>Selling_Price__c</fullName>
    <label>Selling Price</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Vehicle_type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_type__c</fullName>
    <label>Vehicle type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/IND_RiskSummaryController.cls
/**
* @Name         IND_RiskSummaryController
* @Author       Sivakumar Gudipati
* @Company      Persistent Systems
* @Description  This class contains all methods related to Risk Summary
* Test Class:   IND_RiskSummaryController_Test
* History:     
*/

public with sharing class IND_RiskSummaryController {
    
    /*
    * @Method:      getApplicants
    * @Created by:  Sivakumar Gudipati
    * @Description: This method will return the applicant record containing the remark feild value.
    * @Param:       String -  Applicantion ID
    * @Param:       String - Applicant Type
    * @Return:      object of applicant record.
    */
    @AuraEnabled(cacheable=true)
    public static List<Opportunity> getApplicants(String loanAppId){
        
        List<Opportunity> loanApplications = new List<Opportunity>();
        String productType = [SELECT Id, Product_Type__c FROM Opportunity WHERE Id =:loanAppId LIMIT 1].Product_Type__c;

        if(productType == System.Label.Tractor){
            loanApplications = [
                SELECT Id, On_Road_price_carwale__c,Basic_Price__c,Selling_Price__c,Grid_value__c,Imputed_IRR__c,Net_IRR__c,Funding_on_ORP__c,Total_Funded_Premium__c,
                Funding_on_Ex_Showroom__c,On_Road_price__c,Ex_showroom_price__c,Received_AML_API_response__c,Sub_Stage__c,Vehicle_Type__c,Product_Type__c,Is_Revoked__c,
                    (SELECT Id, Scorecard_Decision__c, Check_Eligibility_Message__c, Applicant_Type__c FROM Applicants__r where In_Active_Applicant__c = false),
                    (SELECT Id ,FIwaiver_presentAddress__c , Tenure__c ,PricingEngine_thresholdNetrr__c ,CRM_IRR__c ,Inputted_IRR__c,Net_IRR__c,
                        LtvEngine_Ltv__c ,OfferengineMaxTenure__c ,OfferengineMinTenure__c ,Loan_Amount__c ,Fi_Score_Band__c,
                        OfferengineMaxLoanAmount__c ,OfferengineMinLoanAmount__c ,FIwaiver_currentAddress__c,
                        FIwaiver_offAddress__c ,Current_Residence_FI__c,FIwaiver_co_currentAddress__c,FIwaiver_co_offAddress__c,
                        FIwaiver_co_presentAddress__c,Required_CRM_IRR__c,Vehicle_Detail__r.Variant__c
                    FROM Final_Terms__r WHERE Vehicle_Detail__c != null ORDER BY Vehicle_Detail__r.CreatedDate ASC), (SELECT Id, Valuation_price__c, Selling_Price__c, Grid_value__c,Base_Prices__c FROM Vehicle_Details__r)
                FROM Opportunity 
                WHERE Id = :loanAppId
            ];
        }
        else{
            loanApplications = [
                SELECT Id, On_Road_price_carwale__c,Basic_Price__c,Selling_Price__c,Grid_value__c,Imputed_IRR__c,Net_IRR__c,Funding_on_ORP__c,Total_Funded_Premium__c,
                Funding_on_Ex_Showroom__c,On_Road_price__c,Ex_showroom_price__c,Received_AML_API_response__c,Sub_Stage__c,Vehicle_Type__c,Product_Type__c,Is_Revoked__c,
                    (SELECT Id, Scorecard_Decision__c, Check_Eligibility_Message__c, Applicant_Type__c FROM Applicants__r where In_Active_Applicant__c = false),
                    (SELECT Id ,FIwaiver_presentAddress__c , Tenure__c ,PricingEngine_thresholdNetrr__c ,CRM_IRR__c ,Inputted_IRR__c,Net_IRR__c,
                        LtvEngine_Ltv__c ,OfferengineMaxTenure__c ,OfferengineMinTenure__c ,Loan_Amount__c ,
                        OfferengineMaxLoanAmount__c ,OfferengineMinLoanAmount__c ,FIwaiver_currentAddress__c,
                        FIwaiver_offAddress__c ,Current_Residence_FI__c,FIwaiver_co_currentAddress__c,FIwaiver_co_offAddress__c,
                        FIwaiver_co_presentAddress__c,Required_CRM_IRR__c
                    FROM Final_Terms__r), (SELECT Id, Valuation_price__c, Selling_Price__c, Grid_value__c,Base_Prices__c FROM Vehicle_Details__r)
                FROM Opportunity 
                WHERE Id = :loanAppId
            ];//CISP-2735 - Is_Revoked__c // CISP-2877 - Total_Funded_Premium__c
        }
         
        return loanApplications;
    }
    
    // Update Risk Summary data
    @AuraEnabled
    public static String updateRiskSummaryData(String finalTerm, String loanApps){
        try {
            Final_Term__c ft = (Final_Term__c) JSON.deserialize(finalTerm, Final_Term__c.class);
            update ft;
            Opportunity opp = (Opportunity) JSON.deserialize(loanApps, Opportunity.class);
            update opp;
            return 'Success';
        } catch(Exception ex){
            return ex.getMessage();
        }
        
    }
    
    @AuraEnabled
    public static boolean retryAttemptsExasted(String loanApplicationId){
        boolean retryExasted =false;
        
        try{
            System_Constant_custom_metadata__mdt metadata = System_Constant_custom_metadata__mdt.getInstance('AML'); 
            Retry_Count__c retryCount = new Retry_Count__c();
            List<Retry_Count__c> retryCountList = new List<Retry_Count__c>();
            retryCountList = [select Loan_Application_Id__c from Retry_Count__c where Loan_Application_Id__c =: loanApplicationId and Service_Name__c = 'AML' WITH SECURITY_ENFORCED limit 1];
            System.debug('retryCountList '+retryCountList);
            if(retryCountList.isEmpty()) {
                retryCount.Loan_Application_Id__c = loanApplicationId;
                retryCount.Service_Name__c = 'AML';
                retryCount.Count__c = 1;
                if(Schema.sObjectType.Retry_Count__c.isCreateable())
                {
                  //  insert retryCount;
                }
                retryExasted =false;
            }
            else{               
                //If number of attempts are greater than predefined number of attempts.
                Retry_Count__c  count = [select Count__c from Retry_Count__c where Loan_Application_Id__c =: loanApplicationId and Service_Name__c ='AML' WITH SECURITY_ENFORCED];
                if(count.Count__c >= metadata.Number_Of_Attempts__c)
                {                     
                    retryExasted =true;                    
                }else{
                    retryCount.Loan_Application_Id__c = loanApplicationId;
                    retryCount.Service_Name__c = 'AML';
                    retryCount.Count__c = retryCountList[0].Count__c+1;
                    // if(Schema.sObjectType.Retry_Count__c.isUpdatable())
                    // {
                   // update retryCount;
                    //  }
                }
            }
            
        }catch(exception ex){
            system.debug('Exception '+ex.getMessage() +'  '+ ex.getLineNumber() +'  '+ ex.getCause()) ;
        }
        
        return retryExasted;
    }
    
    }