ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-borrower</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Withdrawal_Reason__c.field-meta.xml
<CustomField>
    <fullName>Withdrawal_Reason__c</fullName>
    <label>Withdrawal Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Financial terms not agreed to</fullName>
            </value>
            <value>
                <fullName>Customer deferred purchase plan</fullName>
            </value>
            <value>
                <fullName>Customer shifted to cash purchase</fullName>
            </value>
            <value>
                <fullName>Customer withdrew the loan application</fullName>
            </value>
            <value>
                <fullName>Elapse of time</fullName>
            </value>
            <value>
                <fullName>Finance availed from some other bank/FI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/Application_withdrwalControllerTest.cls
@isTest
public class Application_withdrwalControllerTest {
    @isTest
    public static void getApplicationTest(){
        try{
            Opportunity opp = TestDataUtility.createTestOpportunity(false);
            opp.StageName = 'Withdrawn';
            opp.Withdrawal_Reason__c = 'Financial terms not agreed to';
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
            
            Applicant__c app1 = TestDataUtility.createTestApplicantForSMS(false);
            app1.Opportunity__c = opp.Id;
            app1.Applicant_Type__c = 'Co-borrower';
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert app1;
            }
            
            Test.startTest();
                  Application_withdrwalController.getApplication(opp.Id,opp.Withdrawal_Reason__c);
            Test.stopTest();
            
            
        }catch(Exception e){
            System.assertEquals('Script-thrown exception', e.getMessage());
        }
    }
    
    @isTest
    public static void gattingCheckEligibilityAPITest(){
        Test.startTest();
             IntegrationUtilities.gattingCheckEligibilityAPI();
        Test.stopTest();
    }
    
    @isTest
    public static void getAPIKeysTest(){
        Test.startTest();
             IntegrationUtilities.getAPIKeys('pkey');
             IntegrationUtilities.getAPIKeys('iv');
             IntegrationUtilities.getAPIKeys('');
        Test.stopTest();
    }
    
    @isTest
    public static void getCoborrowerNameTest(){
        Test.startTest();
             IntegrationUtilities.getCoborrowerName('Co Borrower');
        Test.stopTest();
    }
    
    @isTest
    public static void getCicNoTest(){
        Test.startTest();
             IntegrationUtilities.getCicNo();
        Test.stopTest();
    }
    
    @isTest
    public static void getMakerIdTest(){
        Test.startTest();
              IntegrationUtilities.getMakerId();
        Test.stopTest();
    }
    
    @isTest
    public static void getAPIConfigurationTest(){
        Test.startTest();
            //  IntegrationUtilities.getAPIConfiguration('ADAuthentication');
        Test.stopTest();
    }
    
    @isTest
    public static void getStubResponseTest(){
        Test.startTest();
             IntegrationUtilities.getStubResponse('APD Pending');
        Test.stopTest();
    }
    
    @isTest
    public static void getStubResponseTest1(){
        Test.startTest();
             IntegrationUtilities.getStubResponse('test');
        Test.stopTest();
    }
    
 }