ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MALE</fullName>
            </value>
            <value>
                <fullName>FEMALE</fullName>
            </value>
            <value>
                <fullName>OTHERS MALE</fullName>
            </value>
            <value>
                <fullName>OTHERS FEMALE</fullName>
            </value>
            <value>
                <fullName>OTHERS PREFER NOT TO DISCLOSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Seller&apos;s Passbook</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Bank Statement</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Cancel Cheque</fullName>
            </value>
            <value>
                <fullName>Driving Licence</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Voter Id</fullName>
            </value>
            <value>
                <fullName>Form 60</fullName>
            </value>
            <value>
                <fullName>Customer Image</fullName>
            </value>
            <value>
                <fullName>Aadhaar</fullName>
            </value>
            <value>
                <fullName>Vehicle Images</fullName>
            </value>
            <value>
                <fullName>RC Document</fullName>
            </value>
            <value>
                <fullName>SPR</fullName>
            </value>
            <value>
                <fullName>APR</fullName>
            </value>
            <value>
                <fullName>Electronic Bill</fullName>
                <label>Electricity Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Water Bill</fullName>
                <label>Water Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Vehicle Insurance Policy</fullName>
            </value>
            <value>
                <fullName>Vehicle Image</fullName>
            </value>
            <value>
                <fullName>Bank Statement</fullName>
            </value>
            <value>
                <fullName>Insurance Policy Doc</fullName>
            </value>
            <value>
                <fullName>Valuation Report</fullName>
            </value>
            <value>
                <fullName>Office FI</fullName>
            </value>
            <value>
                <fullName>Land Photo</fullName>
            </value>
            <value>
                <fullName>Patta Document</fullName>
            </value>
            <value>
                <fullName>Rent Agreement/Reciept</fullName>
            </value>
            <value>
                <fullName>Pension Document</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Engine Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Chassis Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Selfie with Vehicle-uploaded during verification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MALE</fullName>
            </value>
            <value>
                <fullName>FEMALE</fullName>
            </value>
            <value>
                <fullName>TRANSGENDER</fullName>
            </value>
            <value>
                <fullName>OTHERS MALE</fullName>
            </value>
            <value>
                <fullName>OTHERS FEMALE</fullName>
            </value>
            <value>
                <fullName>OTHERS PREFER NOT TO DISCLOSE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/KYC_DOB__c.field-meta.xml
<CustomField>
    <fullName>KYC_DOB__c</fullName>
    <label>KYC DOB</label>
    <type>Date</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Opportunity_Relation__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Relation__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Proof_of_Identity_POI__c.field-meta.xml
<CustomField>
    <fullName>Proof_of_Identity_POI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proof of Identity (POI)</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>Vehicle_Detail__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/Final_Term__c.object-meta.xml
<CustomObject>
    <description>To store Final term module data.</description>
    <label>Final Term</label>
    <nameField>
        <displayFormat>FT-{000000}</displayFormat>
        <label>Final Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Installment_Frequency__c.field-meta.xml
<CustomField>
    <fullName>Installment_Frequency__c</fullName>
    <label>Installment Frequency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monthly</fullName>
            </value>
            <value>
                <fullName>bi-monthly</fullName>
            </value>
            <value>
                <fullName>Quarterly</fullName>
            </value>
            <value>
                <fullName>Half yearly</fullName>
            </value>
            <value>
                <fullName>Structured</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Offer engine Loan Amount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan_Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Final_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Tenure__c.field-meta.xml
<CustomField>
    <fullName>Tenure__c</fullName>
    <label>Offer engine Tenure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>Vehicle_Detail__c</referenceTo>
    <relationshipLabel>Final Terms</relationshipLabel>
    <relationshipName>Final_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Application_number__c.field-meta.xml
<CustomField>
    <fullName>Application_number__c</fullName>
    <label>Application number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Loan_amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_amount__c</fullName>
    <label>Loan amount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/Vehicle_Detail__c.object-meta.xml
<CustomObject>
    <label>Vehicle Detail</label>
    <nameField>
        <displayFormat>VD-{00000}</displayFormat>
        <label>Vehicle Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Loan Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <description>Vehicle Insurance and Vehicle Valuation data</description>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Vehicle_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Vehicle_type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_type__c</fullName>
    <label>Vehicle type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC - Copy/force-app/main/default/classes/IND_InsurancePremiumRequest.cls
/*------------------------------------------------------------
Author: Santhosh Mothe
Company: Persistent Systems
Description: This class is wrapper class for the DocAuth Document Report Request
Test Class: 
History
Date            Author              Comments
------------------------------------------------------------- 
12-01-2022    Santhosh Mothe            Created
------------------------------------------------------------*/
public with sharing class IND_InsurancePremiumRequest extends ParentAPIRequest{
    //request paramaters for insurance premium request
    public String Application_No{get;set;}
    public String Vehicle_ID{get;set;}
    public String Product{get;set;}
    public String Age {get;set;}
    public String Gender {get;set;} //SFTRAC-629
    public String Periodicity {get;set;} //SFTRAC-629
    // public String Ins_Product {get;set;}
    // public String Plan_Code{get;set;}
    public String Fin_Amount{get;set;}
    public String Tenure{get;set;}
    public List<Product_Details> Product_Details{get;set;}

    public class Product_Details {
    public String Ins_Product{get;set;}
    public String Opt_YN{get;set;}
    public String Plan_Code{get;set;}
    public String Premium{get;set;}
    public String Fund_YN{get;set;}
    }
    /*
* @Method Name: Constructor
* @Created by: 	Santhosh Mothe.
* @Description: create the InsurancePremium
* @Param:       Object Request Wrapper 
* @Return:      void
*/
    public IND_InsurancePremiumRequest(Applicant__c app,String Ins_Product, String Plan_Code,String loanAppId){
        this(app,Ins_Product,Plan_Code,loanAppId,'');
    }
    public IND_InsurancePremiumRequest(Applicant__c app,String Ins_Product, String Plan_Code,String loanAppId, String assetId){
        try{
         if( app != null){
             List<Documents__c> docList = [SELECT Proof_of_Identity_POI__c, Applicant__c,Gender__c,KYC_DOB__c,Opportunity_Relation__c, Document_Type__c, Opportunity_Relation__r.LeadSource //D2C Change
                                           FROM Documents__c 
                                           WHERE Opportunity_Relation__c =:loanAppId AND Applicant__c =: app.Id
                                           WITH SECURITY_ENFORCED];
                                           
             for(Documents__c doc : docList)  {
                if(doc.Proof_of_Identity_POI__c == true){
                    if(doc.KYC_DOB__c != null){
                        Date kycDOB = doc.KYC_DOB__c;
                        this.Age = calculateAge(kycDOB);
                        if(app.Opportunity__r.Product_Type__c=='Tractor'){//SFTRAC-629
                            this.Gender = doc.Gender__c != null && doc.Gender__c =='Male' ? 'M' : doc.Gender__c =='Female' ? 'F':'' ; 
                        }/*else{
                            this.Gender =doc.Gender__c;//CISP-21364
                        }*/
                    }
                } else if(doc.Proof_of_Identity_POI__c == false){
                    if(doc.KYC_DOB__c != null && this.Age == null){
                        if(app.Opportunity__r.Product_Type__c != Label.Tractor){
                        Date kycDOB = doc.KYC_DOB__c;
                        this.Age = calculateAge(kycDOB);
                        }
                        if(app.Opportunity__r.Product_Type__c=='Tractor'){//SFTRAC-629
                            this.Gender = doc.Gender__c != null && doc.Gender__c =='Male' ? 'M' : doc.Gender__c =='Female' ? 'F':'' ; 
                        }/*else{
                            this.Gender =doc.Gender__c;//CISP-21364
                        }*/
                    }
                }
             }                         
             this.Application_No =  String.valueOf(app.Opportunity__r.Application_number__c);
             this.Vehicle_ID = app.Opportunity__r.Vehicle_type__c=='New'? '1' : '4';
            List<Vehicle_Detail__c> vehLst = new List<Vehicle_Detail__c>();
            if(String.isBlank(assetId)){
                vehLst = [SELECT ID,Product__c,Loan_Application__c  FROM Vehicle_Detail__c WHERE Loan_Application__c =:app.Opportunity__c];
             }else{
                vehLst = [SELECT Id,Product__c,Loan_Application__c  FROM Vehicle_Detail__c WHERE Loan_Application__c =:app.Opportunity__c AND Id =: assetId WITH SECURITY_ENFORCED];
             }

            for(Vehicle_Detail__c vedObj:vehLst)
            {
                this.Product = vedObj.Product__c != null && vedObj.Product__c == 'Two Wheeler' && app.Opportunity__r.Vehicle_type__c=='Refinance' ? 'S' : vedObj.Product__c == 'Two Wheeler' ? 'H' : vedObj.Product__c == 'Passenger Vehicles' ? 'C' : vedObj.Product__c == System.Label.Tractor ? 'T' : '' ;
            }
            List<Final_Term__c> objFinalTerms = new List<Final_Term__c>();
            if(String.isBlank(assetId)){
                objFinalTerms = [SELECT id, Loan_amount__c, Tenure__c,Installment_Frequency__c FROM Final_Term__c WHERE Loan_Application__c = :loanAppId LIMIT 1];
            }else{
                objFinalTerms = [SELECT Id, Loan_amount__c, Tenure__c,Installment_Frequency__c FROM Final_Term__c WHERE Loan_Application__c = :loanAppId AND Vehicle_Detail__c =: assetId LIMIT 1];
            }
            if (objFinalTerms.size() != 0) {
                this.Fin_Amount = objFinalTerms[0].Loan_amount__c;
                this.Tenure = objFinalTerms[0].Tenure__c;
                if(app.Opportunity__r.Product_Type__c=='Tractor'){//SFTRAC-629
                    this.Periodicity = objFinalTerms[0].Installment_Frequency__c == 'Monthly' ? 'M' : objFinalTerms[0].Installment_Frequency__c == 'Quarterly' ? 'Q' : objFinalTerms[0].Installment_Frequency__c == 'Half yearly' ? 'H' : '';  //SFTRAC-629
                }/*else{
                    this.Periodicity ='';
                }*/
            }else if(app.Opportunity__r.Product_Type__c=='Tractor'){//SFTRAC-629
                this.Periodicity ='';
            }

            Product_Details = new List<Product_Details>();
            
            List<Product_Details> prodetailList = (List<Product_Details>) JSON.deserialize(Ins_Product, List<Product_Details>.class);
            for (Product_Details pro : prodetailList) {
                if (String.isNotBlank(pro.Ins_Product)) {
                    Product_Details productDetali = new Product_Details();
                    if(app.Opportunity__r.Product_Type__c == Label.PassengerVehicles && pro.Ins_Product == 'LI_EMI'){
                        productDetali.Ins_Product = 'COMBO';
                        productDetali.Plan_Code = 'LI_EMI';
                    }else{
                        productDetali.Ins_Product = pro.Ins_Product;
                        productDetali.Plan_Code = pro.Plan_Code != null ? pro.Plan_Code : '';
                    }
                    productDetali.Opt_YN = pro.Opt_YN == 'Y' ? 'Y' : 'N';
                    productDetali.Premium = pro.Premium !=null ? String.valueOf(pro.Premium) : '';
                    productDetali.Fund_YN = pro.Fund_YN == 'Y' ? 'Y' : 'N';
                    this.Product_Details.add(productDetali);
                }
            }
        }
        validate(System.Label.Insurance_Premium, app.Opportunity__r.Product_Type__c); //SFTRAC-629 added one more parameter app.Opportunity__r.Product_Type__c
        }catch(Exception e){
            throw new IND_Exception(e.getMessage()+' => '+e.getStackTraceString()); 
        }

    }
    public static String calculateAge (Date dt){
        date todayDate =date.today();
        Integer age = todayDate.year() - dt.year();
        if(todayDate.month() < dt.month() || (todayDate.month() == dt.month() && todayDate.day() < dt.day())) {
            age--;
        }
        return String.valueOf(age);
    }
    
    
    /*
* @Method Name: getHttpRequestHeaders
* @Created by: 	Santhosh Mothe.
* @Description: Method to get the HTTP request header data
* @Return:      Map
*/
    public override Map<String,String> getHttpRequestHeaders(){    
        //Map to store HTTP request header data
        Map<String,String> requestHeaderMap = Utilities.getHeaders();
        return requestHeaderMap;
    }
    
    //
    /*
* @Method Name: Constructor
* @Created by: 	Santhosh Mothe.
* @Description: Method to validate the request data
* @Param:       String serviceName 
* @Return:      boolean
*/
    public override boolean validate(String serviceName, String oppProductType){
      
        if(String.isBlank(this.Application_No)){
            throw new IND_Exception(System.Label.ApplicationNo);
        }
        if(String.isBlank(this.Vehicle_ID)){
            throw new IND_Exception(System.Label.VehicleId);
        }
        if(String.isBlank(this.Product)){
            throw new IND_Exception(System.Label.Product);
        }
        if(String.isBlank(this.Age)){
            throw new IND_Exception(System.Label.Age);
        }
        if(String.isBlank(this.Gender) && oppProductType == 'Tractor'){ //SFTRAC-629
            throw new IND_Exception(System.Label.Gender);
        }
        // if(String.isBlank(this.Ins_Product)){
        //     throw new IND_Exception(System.Label.Ins_Product);
        // }
        // if(String.isBlank(this.Plan_Code)){
        //    throw new IND_Exception(System.Label.Plan_Code);
        // }
        if(String.isBlank(this.Fin_Amount)){
			throw new IND_Exception(System.Label.FinAmount);
        }
        if(String.isBlank(this.Tenure)){
			throw new IND_Exception(System.Label.Tenure);
        }
        
        return true;
    }
}