ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Lead_Number__c.field-meta.xml
<CustomField>
    <fullName>Lead_Number__c</fullName>
    <formula>Opportunity__r.Lead_number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Id</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Aggregator_Source__c.field-meta.xml
<CustomField>
    <fullName>Aggregator_Source__c</fullName>
    <label>Aggregator Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Customer_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Name__c</fullName>
    <description>Field used in DSA portal&apos;s list view</description>
    <formula>Applicant_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer Name</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/D2C_journey_drop_screen__c.field-meta.xml
<CustomField>
    <fullName>D2C_journey_drop_screen__c</fullName>
    <label>D2C journey drop screen</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/D2C_Journey_Status__c.field-meta.xml
<CustomField>
    <fullName>D2C_Journey_Status__c</fullName>
    <description>This field will be populated by D2C portal in case of journey drop of journey is moved to assisted.</description>
    <label>D2C Journey Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Initial offer drop</fullName>
            </value>
            <value>
                <fullName>Final offer drop</fullName>
            </value>
            <value>
                <fullName>Move to assisted</fullName>
            </value>
            <value>
                <fullName>Journey stop</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Is_Pre_Approved__c.field-meta.xml
<CustomField>
    <fullName>Is_Pre_Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Pre Approved?</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Last_Drop_Screen__c.field-meta.xml
<CustomField>
    <fullName>Last_Drop_Screen__c</fullName>
    <description>Used in D2C</description>
    <label>Last Journey Drop Screen</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Lead_number__c.field-meta.xml
<CustomField>
    <fullName>Lead_number__c</fullName>
    <label>Lead Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Details</fullName>
            </value>
            <value>
                <fullName>Capture current residential address</fullName>
            </value>
            <value>
                <fullName>Capture permanent residential address</fullName>
            </value>
            <value>
                <fullName>Capture PAN or Other KYC</fullName>
            </value>
            <value>
                <fullName>Capture Dedupe</fullName>
            </value>
            <value>
                <fullName>Vehicle Dedupe</fullName>
            </value>
            <value>
                <fullName>Declared Income/Required Loan Amount</fullName>
            </value>
            <value>
                <fullName>Bank Account Check</fullName>
            </value>
            <value>
                <fullName>View Application Details</fullName>
            </value>
            <value>
                <fullName>CIBIL</fullName>
            </value>
            <value>
                <fullName>Field Investigation</fullName>
            </value>
            <value>
                <fullName>Credit Assessment</fullName>
            </value>
            <value>
                <fullName>Income Details</fullName>
            </value>
            <value>
                <fullName>Valuation IDV</fullName>
            </value>
            <value>
                <fullName>Final Terms</fullName>
            </value>
            <value>
                <fullName>Insurance Details</fullName>
            </value>
            <value>
                <fullName>Exposure Analysis</fullName>
            </value>
            <value>
                <fullName>Income</fullName>
            </value>
            <value>
                <fullName>CAM and Approval Log</fullName>
            </value>
            <value>
                <fullName>Risk Summary</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Tele-verification &lt;Post Sanction&gt;</fullName>
            </value>
            <value>
                <fullName>Vehicle Inspection and RC Check</fullName>
            </value>
            <value>
                <fullName>Structured EMI</fullName>
            </value>
            <value>
                <fullName>Security Mandate</fullName>
            </value>
            <value>
                <fullName>Additional Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>IHM</fullName>
            </value>
            <value>
                <fullName>Loan Agreement</fullName>
            </value>
            <value>
                <fullName>Signing the e-Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/classes/D2C_OpportunityHandler.cls
public class D2C_OpportunityHandler {

    static map<Id, Boolean> initialOfferDropMap = new map<Id, Boolean>();

    public static void sendMoveToAssistedEmail(Set<Id> oppIdSet) {
        List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();
        List<Opportunity> oppList = [SELECT Id, Owner.Email, Lead_number__c, Customer_Name__c, Contact_number__c,StageName FROM Opportunity WHERE Id IN: oppIdSet AND Owner.Email != null];
        EmailTemplate et = [
            SELECT Id, Body, Subject
            FROM EmailTemplate
            WHERE DeveloperName = 'D2CLeadTransferredBE'
        ];

        for(Opportunity opp : oppList){
            String subject = et.Subject;
            subject = subject.replace('{!Opportunity.Lead_number__c}', opp.Lead_number__c != null ? opp.Lead_number__c : '');

            String emailBody = et.Body;
            emailBody = emailBody.replace('{!Opportunity.Lead_number__c}', opp.Lead_number__c != null ? opp.Lead_number__c : '');
            emailBody = emailBody.replace('{!Opportunity.Customer_Name__c}', opp.Customer_Name__c != null ? opp.Customer_Name__c : '');
            emailBody = emailBody.replace('{!Opportunity.Contact_number__c}', opp.Contact_number__c != null ? opp.Contact_number__c : '');

            List<String> toAddress = new List<String>();
            toAddress.add(opp.Owner.Email);
            allmsg.add(generateMail(subject, emailBody, toAddress));
            opp.StageName = 'Withdrawn';
        }
        try {
            if(oppList.size() > 0){
                database.update(oppList, false);
            }
            Messaging.sendEmail(allmsg, false);
            return;
        } catch (Exception e) {
            System.debug(e.getMessage());
        }
    }


    public static void sendVehicleDedupeEmail(Set<Id> oppIdSet){
        List<Messaging.SingleEmailMessage> allmsg = new List<Messaging.SingleEmailMessage>();
        List<Opportunity> oppList = [SELECT Id, Lead_number__c, Owner.Email, Product_Type__c, Vehicle_Type__c, Is_Pre_Approved__c FROM Opportunity WHERE Id IN: oppIdSet AND Owner.Email != null];
        EmailTemplate et = [
            SELECT Id, Body, Subject
            FROM EmailTemplate
            WHERE DeveloperName = 'D2CStageChangedVehicleDedupe'
        ];
        for(Opportunity opp: oppList){
            String vehicleType = opp.Is_Pre_Approved__c ? 'Pre Approved' : opp.Product_Type__c + ' ' + opp.Vehicle_Type__c;

            String subject = et.Subject;
            subject = subject.replace('{!Opportunity.Lead_number__c}', opp.Lead_number__c != null ? opp.Lead_number__c : '');

            String emailBody = et.Body;
            emailBody = emailBody.replace('{!Opportunity.Lead_number__c}', opp.Lead_number__c != null ? opp.Lead_number__c : '');
            emailBody = emailBody.replace('{vehicletype}', vehicleType);

            List<String> toAddress = new List<String>();
            toAddress.add(opp.Owner.Email);
            allmsg.add(generateMail(subject, emailBody, toAddress));
        }
        if(!allmsg.isEmpty()){
            Messaging.sendEmail(allmsg, false);
        }
    }

    public static Messaging.SingleEmailMessage generateMail(String subject, String emailBody, List<String> toAddress){
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        mail.setSenderDisplayName('IBL D2C');
        mail.setToAddresses(toAddress);
        mail.setSubject(subject);
        mail.setSaveAsActivity(false);
        mail.setUseSignature(false);
        mail.setPlainTextBody(emailBody);
        return mail;
    }

    public static void updateLastDropScreen(Map<Id,Opportunity> mapNewOpp,Map<Id,Opportunity> lstOldOpp) {
        
        for (Opportunity newOpp: mapNewOpp.values()) {
            Opportunity oldOpp = lstOldOpp.get(newOpp.Id);
            
            if((newOpp.LeadSource == 'D2C' && String.isNotBlank(newOpp.Sub_Stage__c))){
                
                if((newOpp.Sub_Stage__c != oldOpp.Sub_Stage__c) && newOpp.Sub_Stage__c.equalsIgnoreCase('Vehicle Dedupe') 
                    && newOpp.Vehicle_Type__c.equalsIgnoreCase('new')) {
                        newOpp.Sub_Stage__c = oldOpp.Sub_Stage__c;
                }
                
                if((newOpp.D2C_Journey_Status__c == IntegrationConstants.STATUS_INITIAL_OFFER_DROP) 
                    
                    && String.isNotBlank(newOpp.D2C_journey_drop_screen__c) 
                    && (newOpp.D2C_journey_drop_screen__c != oldOpp.D2C_journey_drop_screen__c)
                    && String.isBlank(newOpp.Aggregator_Source__c) && !newOpp.Is_Pre_Approved__c ) {
                        newOpp.Last_Drop_Screen__c = newOpp.D2C_journey_drop_screen__c;
                        newOpp.D2C_journey_drop_screen__c  = '';

                        initialOfferDropMap.put(newOpp.Id, true);
                        System.debug('in if 2 '+ initialOfferDropMap);
                    }
            }

        }
    }

    public static void callConvox(Map<Id,Opportunity> newOppMap,Map<Id,Opportunity> oldOppMap) {
        Set<Id> oppIdSet = new Set<Id>();
        for (Opportunity newOpp: newOppMap.values()) {
            Opportunity oldOpp = oldOppMap.get(newOpp.Id);
            System.debug('in if 3' + initialOfferDropMap);
            if(!initialOfferDropMap.isEmpty() && initialOfferDropMap.containsKey(newOpp.Id) 
            && initialOfferDropMap.get(newOpp.Id)) {
                oppIdSet.add(newOpp.Id);
            }
        }
        if(!oppIdSet.isEmpty()){
            Applicant__c app = [Select Id, Contact_number__c from Applicant__c WHERE Opportunity__c IN: oppIdSet limit 1];
        	conVoxAPIHandler.callApi(IntegrationConstants.CONVOX_DATAUPLOAD, app.Contact_number__c, app.Id);
        }
    }

}