ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Code__c</fullName>
    <label>Customer Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Bank_Masters__c/Bank_Masters__c.object-meta.xml
<CustomObject>
    <label>Bank Master</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Masters</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Bank_Masters__c/fields/Bank_Code__c.field-meta.xml
<CustomField>
    <fullName>Bank_Code__c</fullName>
    <externalId>true</externalId>
    <label>Bank Code</label>
    <precision>7</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Customer_Code__c/Customer_Code__c.object-meta.xml
<CustomObject>
    <label>Customer Code</label>
    <nameField>
        <label>Customer  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Codes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Customer_Code__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant_Delete</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Customer_Codes</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Customer_Code__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Customer_Codes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/Deal_Number__c.object-meta.xml
<CustomObject>
    <description>The custom object created for Deal Number generation</description>
    <label>Deal Number</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <formula>DNField1__c  +  DNField2__c  +  ProductCode__c  +  DNField3__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal Number</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/fields/DNField1__c.field-meta.xml
<CustomField>
    <fullName>DNField1__c</fullName>
    <description>DNField1</description>
    <label>DNField1</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/fields/DNField2__c.field-meta.xml
<CustomField>
    <fullName>DNField2__c</fullName>
    <description>DNField2</description>
    <label>DNField2</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Deal Numbers</relationshipLabel>
    <relationshipName>Deal_Numbers</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Payment Request</fullName>
            </value>
            <value>
                <fullName>RC Upload</fullName>
            </value>
            <value>
                <fullName>Business Payment Details</fullName>
            </value>
            <value>
                <fullName>Insurance Details</fullName>
            </value>
            <value>
                <fullName>New/Used Vehicle Details</fullName>
            </value>
            <value>
                <fullName>Beneficiary Details</fullName>
            </value>
            <value>
                <fullName>Key Fact Statement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number_Setting__c/Deal_Number_Setting__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Deal Number Setting</label>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number_Setting__c/fields/MDNField1__c.field-meta.xml
<CustomField>
    <fullName>MDNField1__c</fullName>
    <label>MDNField1</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number_Setting__c/fields/MDNField2__c.field-meta.xml
<CustomField>
    <fullName>MDNField2__c</fullName>
    <label>MDNField2</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Exposure__c/Exposure__c.object-meta.xml
<CustomObject>
    <label>Exposure</label>
    <nameField>
        <label>Exposure Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Exposures</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Exposure__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Exposures</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Exposure__c/fields/CIF_ID__c.field-meta.xml
<CustomField>
    <fullName>CIF_ID__c</fullName>
    <label>CIF ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Exposure__c/fields/Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Code__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer Code</label>
    <referenceTo>Customer_Code__c</referenceTo>
    <relationshipName>Exposures</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Exposure__c/fields/Deal_No__c.field-meta.xml
<CustomField>
    <fullName>Deal_No__c</fullName>
    <label>Deal No</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Exposure__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Exposures</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Customer_Code__c.field-meta.xml
<CustomField>
    <fullName>Customer_Code__c</fullName>
    <label>Customer Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <description>IndusInd deal number</description>
    <label>Deal Number</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Details</fullName>
            </value>
            <value>
                <fullName>Capture current residential address</fullName>
            </value>
            <value>
                <fullName>Capture permanent residential address</fullName>
            </value>
            <value>
                <fullName>Capture PAN or Other KYC</fullName>
            </value>
            <value>
                <fullName>Capture Dedupe</fullName>
            </value>
            <value>
                <fullName>Vehicle Dedupe</fullName>
            </value>
            <value>
                <fullName>Declared Income/Required Loan Amount</fullName>
            </value>
            <value>
                <fullName>Bank Account Check</fullName>
            </value>
            <value>
                <fullName>View Application Details</fullName>
            </value>
            <value>
                <fullName>CIBIL</fullName>
            </value>
            <value>
                <fullName>Field Investigation</fullName>
            </value>
            <value>
                <fullName>Credit Assessment</fullName>
            </value>
            <value>
                <fullName>Income Details</fullName>
            </value>
            <value>
                <fullName>Valuation IDV</fullName>
            </value>
            <value>
                <fullName>Final Terms</fullName>
            </value>
            <value>
                <fullName>Insurance Details</fullName>
            </value>
            <value>
                <fullName>Exposure Analysis</fullName>
            </value>
            <value>
                <fullName>Income</fullName>
            </value>
            <value>
                <fullName>CAM and Approval Log</fullName>
            </value>
            <value>
                <fullName>Risk Summary</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Tele-verification &lt;Post Sanction&gt;</fullName>
            </value>
            <value>
                <fullName>Vehicle Inspection and RC Check</fullName>
            </value>
            <value>
                <fullName>Structured EMI</fullName>
            </value>
            <value>
                <fullName>Security Mandate</fullName>
            </value>
            <value>
                <fullName>Additional Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>IHM</fullName>
            </value>
            <value>
                <fullName>Loan Agreement</fullName>
            </value>
            <value>
                <fullName>Signing the e-Agreement</fullName>
            </value>
            <value>
                <fullName>RC Upload</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Repayments__c/Repayments__c.object-meta.xml
<CustomObject>
    <label>Repayment</label>
    <nameField>
        <label>Repayments Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Repayments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Repayments__c/fields/Bank_Master__c.field-meta.xml
<CustomField>
    <fullName>Bank_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Bank Master</label>
    <referenceTo>Bank_Masters__c</referenceTo>
    <relationshipLabel>Repayments</relationshipLabel>
    <relationshipName>Repayments</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Repayments__c/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deal Number</label>
    <referenceTo>Deal_Number__c</referenceTo>
    <relationshipLabel>Repayments</relationshipLabel>
    <relationshipName>Repayments</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Repayments__c/fields/Is_Netbanking_available_with_customer__c.field-meta.xml
<CustomField>
    <fullName>Is_Netbanking_available_with_customer__c</fullName>
    <label>Is Netbanking available with customer</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Repayments__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Repayments</relationshipLabel>
    <relationshipName>Repayments</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/Maker_Id__c.field-meta.xml
<CustomField>
    <fullName>Maker_Id__c</fullName>
    <label>Maker Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/IND_ENACHRegistrationJourneyRequestTest.cls
@isTest
public class IND_ENACHRegistrationJourneyRequestTest {
    @TestSetup
    public static void createTestData(){
        Profile p = [SELECT Id FROM Profile WHERE Name='IBL Business Executive'];
        
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,
                          TimeZoneSidKey='America/Los_Angeles',
                          MobilePhone = '9701498575', IsActive = true,
                          UserName='standarduser4@testorg.com.psdev1',Maker_Id__c='10002');
        insert u;
        System.runAs(u) 
        {
            Opportunity opp = TestDataUtility.createTestOpportunity(false);
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            } 
            
            Deal_Number_Setting__c dlNumberSetting= new Deal_Number_Setting__c();
            dlNumberSetting.Name = System.Label.TwoWheeler;
            dlNumberSetting.MDNField1__c ='AB';
            dlNumberSetting.MDNField2__c = 2.0;
            insert dlNumberSetting;
            
            
            Deal_Number__c dl=new Deal_Number__c();
            dl.Loan_Application__c = opp.Id;
            dl.DNField1__c = dlNumberSetting.MDNField1__c;
            dl.DNField2__c = String.valueOf(dlNumberSetting.MDNField2__c.round());
            dl.Sub_Stage__c = 'RC Upload'; 
            insert dl;
            Applicant__c applicant = TestDataUtility.createTestApplicantForSMS(false);
            applicant.Opportunity__c=opp.Id;
            applicant.Customer_Code__c = '12345';
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
            Bank_Masters__c bankMaster = new Bank_Masters__c();
            bankMaster.Name='BANK OF BARODA';
            bankMaster.Bank_Code__c=12;            
            insert bankMaster;
            
            Repayments__c repayment = TestDataUtility.createTestRepayments(false,opp);
            repayment.Bank_Master__c = bankMaster.Id;     
			repayment.Deal_Number__c = dl.Id;            
            repayment.Is_Netbanking_available_with_customer__c = 'yes';
            if (Schema.sObjectType.Repayments__c.isCreateable()){
                insert repayment;
            }
                       
            List<Exposure__c> lstExp = new List<Exposure__c>();
            for(Integer i=0;i<1;i++) {
                lstExp.add(new Exposure__c(Name = 'expName'+i,
                                           Loan_Application__c = opp.id,
                                           Applicant__c = applicant.id,
                                           CIF_ID__c ='3534534',
                                           Deal_No__c = 'something1'
                                          ));
            }
            insert lstExp;
        }
    }
    
    @isTest
    public static void verifyIND_ENACHRegistrationJourneyRequest(){
        User u = [SELECT Id,usertype FROM User WHERE UserName='standarduser4@testorg.com.psdev1' AND IsActive = true LIMIT 1]; 
        System.runAs(u) 
        {
            try
            {
                Test.startTest();
                Applicant__c applicant = [SELECT Id, Opportunity__c, Customer_Code__c, Contact_number__c, Email_Id__c FROM Applicant__c LIMIT 1];                   
                List<Repayments__c> repayment=[SELECT Id,Repayment_to_be_done_by__c,Bank_Master__c, Bank_Master__r.Name,IFSC_Code__c,Account_Number__c,Created_Date__c,End_Date__c,Frequency__c,EMI_Amount__c 
                                       FROM Repayments__c 
                                       WHERE Loan_Application__c=:applicant.Opportunity__c WITH SECURITY_ENFORCED];
       			System.debug('repayment '+repayment[0].Bank_Master__c);
                Deal_Number__c dl = [select id from Deal_Number__c limit 1];
                IND_ENACHRegistrationJourneyRequest result = new IND_ENACHRegistrationJourneyRequest(applicant, applicant.Opportunity__c,dl.Id);
                Boolean isValid = result.validate(System.Label.StampingDetails);
                System.assert(isValid);
                
                Map<String,String> resultHeadersMap = result.getHttpRequestHeaders();
                System.assert(!resultHeadersMap.isEmpty());
                Test.stopTest();
            }
            catch(Exception e)
            {
                
            }
        }
    }
	
	@isTest
    public static void verifyIND_ENACHRegistrationJourneyRequest1(){
        User u = [SELECT Id,usertype FROM User WHERE UserName='standarduser4@testorg.com.psdev1' AND IsActive = true LIMIT 1]; 
        System.runAs(u) 
        {
            try
            {
                Test.startTest();
                
                Opportunity op = [select id, product_type__c,AccountId from Opportunity limit 1];
                
                Opportunity opp = TestDataUtility.createTestOpportunityForOcr(false);
                opp.StageName = 'Journey Restart';
                opp.Is_Mobile_Journey_Completed__c = true;
                opp.Vehicle_Type__c = System.Label.used;
                opp.CloseDate = Date.newInstance(2022, 1, 11);
                opp.Product_Type__c = System.Label.TwoWheeler;
                opp.Sanction_Status__c = System.Label.nonStp;
                opp.Vehicle_Sub_Category__c = 'UPB';
                opp.Funded__c = true;
                opp.Is_customer_interested_in_a_motor_insura__c = true;
                opp.Motor_Insurance_Premium__c = 10000;
                opp.Agent_BL_code__c = '1234';
                opp.AccountId = op.AccountId;
                insert opp;  
                
                Applicant__c applicant = [SELECT Id, Opportunity__c, Customer_Code__c, Contact_number__c, Email_Id__c FROM Applicant__c LIMIT 1];                   
                List<Repayments__c> repayment=[SELECT Id,Repayment_to_be_done_by__c,Bank_Master__c, Bank_Master__r.Name,IFSC_Code__c,Account_Number__c,Created_Date__c,End_Date__c,Frequency__c,EMI_Amount__c 
                                       FROM Repayments__c 
                                       WHERE Loan_Application__c=:applicant.Opportunity__c WITH SECURITY_ENFORCED];
                Deal_Number__c dl = [select id from Deal_Number__c limit 1];
                
                op.Product_Type__c = 'Passenger Vehicles';
                op.StageName = 'Final Offer';
                op.Parent_Loan_Application__c = opp.Id;
                update op;
                IND_ENACHRegistrationJourneyRequest result = new IND_ENACHRegistrationJourneyRequest(applicant, op.Id,dl.Id);
                Boolean isValid = result.validate(System.Label.StampingDetails);
                System.assert(isValid);
                
                Map<String,String> resultHeadersMap = result.getHttpRequestHeaders();
                System.assert(!resultHeadersMap.isEmpty());
                Test.stopTest();
            }
            catch(Exception e)
            {
                
            }
        }
    }
    
}