ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-borrower</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Customer_Qualification__c.field-meta.xml
<CustomField>
    <fullName>Customer_Qualification__c</fullName>
    <label>Customer Qualification</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>P3</fullName>
                <label>A.C.S</label>
            </value>
            <value>
                <fullName>B2</fullName>
                <label>B.A</label>
            </value>
            <value>
                <fullName>B3</fullName>
                <label>B.COM</label>
            </value>
            <value>
                <fullName>B1</fullName>
                <label>B.Sc</label>
            </value>
            <value>
                <fullName>P1</fullName>
                <label>C.A</label>
            </value>
            <value>
                <fullName>P2</fullName>
                <label>I.C.W.A</label>
            </value>
            <value>
                <fullName>B5</fullName>
                <label>M.A</label>
            </value>
            <value>
                <fullName>B6</fullName>
                <label>M.COM</label>
            </value>
            <value>
                <fullName>B4</fullName>
                <label>M.SC</label>
            </value>
            <value>
                <fullName>P4</fullName>
                <label>M.B.A</label>
            </value>
            <value>
                <fullName>P5</fullName>
                <label>M.C.A</label>
            </value>
            <value>
                <fullName>P6</fullName>
                <label>B.E</label>
            </value>
            <value>
                <fullName>P7</fullName>
                <label>M.E</label>
            </value>
            <value>
                <fullName>P8</fullName>
                <label>P.G.D.C.A</label>
            </value>
            <value>
                <fullName>P9</fullName>
                <label>H.R.D</label>
            </value>
            <value>
                <fullName>P10</fullName>
                <label>D.C.A</label>
            </value>
            <value>
                <fullName>P11</fullName>
                <label>D.B.M</label>
            </value>
            <value>
                <fullName>P12</fullName>
                <label>L.L.B</label>
            </value>
            <value>
                <fullName>B7</fullName>
                <label>S S L C</label>
            </value>
            <value>
                <fullName>P14</fullName>
                <label>D.M.M</label>
            </value>
            <value>
                <fullName>P15</fullName>
                <label>P.G.D.M.M</label>
            </value>
            <value>
                <fullName>P16</fullName>
                <label>D P E C</label>
            </value>
            <value>
                <fullName>P17</fullName>
                <label>D.M.E</label>
            </value>
            <value>
                <fullName>P18</fullName>
                <label>OTHERS</label>
            </value>
            <value>
                <fullName>P19</fullName>
                <label>ICWA INTER</label>
            </value>
            <value>
                <fullName>P20</fullName>
                <label>M.M.S</label>
            </value>
            <value>
                <fullName>P21</fullName>
                <label>D.I.R.&amp;P.M</label>
            </value>
            <value>
                <fullName>P22</fullName>
                <label>D.B.A</label>
            </value>
            <value>
                <fullName>ILLI</fullName>
                <label>ILLITERATE</label>
            </value>
            <value>
                <fullName>ELEM</fullName>
                <label>ELEMENTARY</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Marital_status__c.field-meta.xml
<CustomField>
    <fullName>Marital_status__c</fullName>
    <label>Marital status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DIVOR</fullName>
                <label>DIVORCE</label>
            </value>
            <value>
                <fullName>DVRCE</fullName>
                <label>DIVORCEE</label>
            </value>
            <value>
                <fullName>MARR</fullName>
                <label>MARRIED</label>
            </value>
            <value>
                <fullName>SINGP</fullName>
                <label>SINGLE PARENT</label>
            </value>
            <value>
                <fullName>UNMAR</fullName>
                <label>UN MARRIED</label>
            </value>
            <value>
                <fullName>WIDOW</fullName>
            </value>
            <value>
                <fullName>WIDWR</fullName>
                <label>WIDOWER</label>
            </value>
            <value>
                <fullName>Divorced</fullName>
                <isActive>false</isActive>
                <label>Divorced</label>
            </value>
            <value>
                <fullName>Married</fullName>
                <isActive>false</isActive>
                <label>Married</label>
            </value>
            <value>
                <fullName>SINGLE</fullName>
                <isActive>false</isActive>
                <label>SINGLE</label>
            </value>
            <value>
                <fullName>Single Parent</fullName>
                <isActive>false</isActive>
                <label>Single Parent</label>
            </value>
            <value>
                <fullName>Widower</fullName>
                <isActive>false</isActive>
                <label>Widower</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Willing_to_open_Bank_Account_with_IIB__c.field-meta.xml
<CustomField>
    <fullName>Willing_to_open_Bank_Account_with_IIB__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Willing to open Bank Account with IIB ?</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>applicant_Type__c</fullName>
    <formula>TEXT(Applicant__r.Applicant_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Type</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Marital_status__c.field-meta.xml
<CustomField>
    <fullName>Marital_status__c</fullName>
    <description>This field was created for CMU User</description>
    <formula>Text(Applicant__r.Marital_status__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Marital status</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/recordTypes/KYC.recordType-meta.xml
<RecordType>
    <fullName>KYC</fullName>
    <active>true</active>
    <label>KYC Document</label>
</RecordType>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/CVO_Accepts_SPDC_Documents__c.field-meta.xml
<CustomField>
    <fullName>CVO_Accepts_SPDC_Documents__c</fullName>
    <label>CVO Accepts SPDC Documents</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Is_Mobile_Journey_Completed__c.field-meta.xml
<CustomField>
    <fullName>Is_Mobile_Journey_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Mobile Journey Completed</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Sanction_Status__c.field-meta.xml
<CustomField>
    <fullName>Sanction_Status__c</fullName>
    <label>Sanction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>STP</fullName>
            </value>
            <value>
                <fullName>Non-STP</fullName>
                <default>true</default>
                <label>Non-STP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Details</fullName>
            </value>
            <value>
                <fullName>Capture current residential address</fullName>
            </value>
            <value>
                <fullName>Capture permanent residential address</fullName>
            </value>
            <value>
                <fullName>Capture PAN or Other KYC</fullName>
            </value>
            <value>
                <fullName>Capture Dedupe</fullName>
            </value>
            <value>
                <fullName>Vehicle Dedupe</fullName>
            </value>
            <value>
                <fullName>Declared Income/Required Loan Amount</fullName>
            </value>
            <value>
                <fullName>Bank Account Check</fullName>
            </value>
            <value>
                <fullName>View Application Details</fullName>
            </value>
            <value>
                <fullName>CIBIL</fullName>
            </value>
            <value>
                <fullName>Field Investigation</fullName>
            </value>
            <value>
                <fullName>Credit Assessment</fullName>
            </value>
            <value>
                <fullName>Income Details</fullName>
            </value>
            <value>
                <fullName>Valuation IDV</fullName>
            </value>
            <value>
                <fullName>Final Terms</fullName>
            </value>
            <value>
                <fullName>Insurance Details</fullName>
            </value>
            <value>
                <fullName>Exposure Analysis</fullName>
            </value>
            <value>
                <fullName>Income</fullName>
            </value>
            <value>
                <fullName>CAM and Approval Log</fullName>
            </value>
            <value>
                <fullName>Risk Summary</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Tele-verification &lt;Post Sanction&gt;</fullName>
            </value>
            <value>
                <fullName>Vehicle Inspection and RC Check</fullName>
            </value>
            <value>
                <fullName>Structured EMI</fullName>
            </value>
            <value>
                <fullName>Security Mandate</fullName>
            </value>
            <value>
                <fullName>Additional Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>IHM</fullName>
            </value>
            <value>
                <fullName>Loan Agreement</fullName>
            </value>
            <value>
                <fullName>Signing the e-Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/Maker_Id__c.field-meta.xml
<CustomField>
    <fullName>Maker_Id__c</fullName>
    <label>Maker Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/classes/GetFilesControllerTest.cls
@isTest
public class GetFilesControllerTest {
    
    @testSetup 
    static void testDataSetup() {
        //create user
        Profile p = [SELECT Id FROM Profile WHERE Name='IBL Business Executive'];
        UserRole ur = new UserRole(Name = 'CEO');
        insert ur;
        User u = new User(Alias = 'standt2', Email='standarduser2@testorg.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id, UserRoleId = ur.Id, Maker_Id__c='12',IsActive = true,
                          TimeZoneSidKey='America/Los_Angeles',UserName='test1_userprod123@indusbank.com',MobilePhone = '9089078967');
        insert u;
        
        Profile p1 = [SELECT Id FROM Profile WHERE Name='Platform Event Profile'];
        User u1 = new User(Alias = 'standt2', Email='standarduser2@testorg.com',
                           EmailEncodingKey='UTF-8', LastName='platformUser', LanguageLocaleKey='en_US',
                           LocaleSidKey='en_US', ProfileId = p1.Id,Maker_Id__c='12',IsActive = true,
                           TimeZoneSidKey='America/Los_Angeles',UserName='platformUser@indusbank.com',MobilePhone = '9089078967');
        insert u1;
        System.runAs(u) 
        {
            // Create Opportunity
            Opportunity oppUsed = TestDataUtility.createTestOpportunityForOcr(false);
            oppUsed.Sub_Stage__c = System.Label.Field_Investigation;
            oppUsed.Is_Mobile_Journey_Completed__c = true;
            oppUsed.Vehicle_Type__c = System.Label.used;
            oppUsed.Product_Type__c = System.Label.TwoWheeler;
            oppUsed.Sanction_Status__c = System.Label.nonStp;
            insert oppUsed; 
            
            Opportunity opp = TestDataUtility.createTestOpportunityForOcr(false);
            opp.Name = 'VDR Test';
            opp.StageName='Post Sanction Checks and Documentation';
            opp.Product_Type__c='Tractor';
            opp.CVO_Accepts_SPDC_Documents__c = 'No';
            insert opp;    
            
            // Create Applicant__c
            Applicant__c applicant = TestDataUtility.createTestApplicantForMFCValuation(false, opp);
            applicant.Willing_to_open_Bank_Account_with_IIB__c = true;
            applicant.Applicant_Type__c = 'Borrower';
            applicant.Customer_Qualification__c = 'B1';
            applicant.Marital_status__c = 'MARR';
            insert applicant;
            
            Applicant__c applicant1 = TestDataUtility.createTestApplicantForMFCValuation(false, opp);
            applicant1.Willing_to_open_Bank_Account_with_IIB__c = true;
            applicant1.Applicant_Type__c = System.Label.CoBorrower;
            applicant1.Customer_Qualification__c = 'B1';
            applicant1.Marital_status__c = 'MARR';
            insert applicant1;
            
            Documents__c docRec = TestDataUtility.createTestKYCDocForBre(true, applicant, opp);
            ContentVersion contentVersion = TestDataUtility.createContentVersionforOcrFront('test',true,docRec);
        }
        
        System.runAs(u1) 
        {
            Opportunity oppUsed = TestDataUtility.createTestOpportunityForOcr(false);
            oppUsed.Sub_Stage__c = System.Label.Field_Investigation;
            oppUsed.Is_Mobile_Journey_Completed__c = true;
            oppUsed.Vehicle_Type__c = System.Label.used;
            oppUsed.Product_Type__c = System.Label.TwoWheeler;
            oppUsed.Sanction_Status__c = System.Label.nonStp;
            insert oppUsed;               
        }
    }
    
    @isTest
    public static void getUserRoleTest(){
        try{
            
            Test.startTest();
            User u = [SELECT Id,usertype FROM User WHERE UserName='test1_userprod123@indusbank.com' AND IsActive = true LIMIT 1];
            System.runAs(u) 
            {
                String result = GetFilesController.getUserRole(u.Id);
                System.assertEquals('CEO', result);
                
                String result1 = GetFilesController.getUserRole(null);
                System.assertEquals(null, result1);
            }
            Test.stopTest();
        }catch(Exception e){
            System.assertEquals('Script-thrown exception', e.getMessage());
        }
    }
    
    @isTest
    public static void getFilesListTest(){
        try{
            
            Test.startTest();
            User u = [SELECT Id,usertype FROM User WHERE UserName='test1_userprod123@indusbank.com' AND IsActive = true LIMIT 1];
            Opportunity oppRec1 = [SELECT Id, Vehicle_Type__c, Product_Type__c FROM Opportunity WHERE Name='VDR Test' LIMIT 1];
            Applicant__c appRec = [SELECT Id, Opportunity__c FROM Applicant__c WHERE Applicant_Type__c = 'Borrower' LIMIT 1];
            Documents__c docRec = [SELECT Id, Opportunity_Relation__c,Applicant__c,Document_Type__c FROM Documents__c  LIMIT 1];
            
            System.runAs(u) 
            {
                GetFilesController.FilesWrapper[] filesList = GetFilesController.getFilesList(docRec.Id);
                System.assertEquals('KYC Document', filesList[0].recordTypeName);
                
                GetFilesController.FilesWrapper[] filesList1 = GetFilesController.getFilesList(null);
                System.assertEquals(null, filesList1);
                
                GetFilesController.FileVersionWrapper fileVersion = new GetFilesController.FileVersionWrapper('test','test','test',Date.today(),'test');
            }
            Test.stopTest();
        }catch(Exception e){
            System.assertEquals('Script-thrown exception', e.getMessage());
        }
    }
    
    @isTest
    public static void isKYCDocumentTest(){
        try{
            
            Test.startTest();
            User u = [SELECT Id,usertype FROM User WHERE UserName='test1_userprod123@indusbank.com' AND IsActive = true LIMIT 1];
            Opportunity oppRec1 = [SELECT Id, Vehicle_Type__c, Product_Type__c FROM Opportunity WHERE Name='VDR Test' LIMIT 1];
            Applicant__c appRec = [SELECT Id, Opportunity__c FROM Applicant__c WHERE Applicant_Type__c = 'Borrower' LIMIT 1];
            Documents__c docRec = [SELECT Id, Opportunity_Relation__c,Applicant__c,Document_Type__c FROM Documents__c  LIMIT 1];
            ContentVersion contentVersion = TestDataUtility.createContentVersionforOcrFront('test',true,docRec);
            ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion limit 1];
            
            ContentDocumentLink contentlink=new ContentDocumentLink();
            contentlink.LinkedEntityId=oppRec1.id;
            contentlink.ContentDocumentId=testcontent.ContentDocumentId;
            contentlink.Visibility = 'AllUsers'; 
            insert contentlink;
            
            System.runAs(u) 
            {
                GetFilesController.isKYCDocument(docRec.Id);
                GetFilesController.deleteFile(testcontent.ContentDocumentId,contentlink.Id);
                GetFilesController.deleteFile(docRec.Id,docRec.Id);
            }
            Test.stopTest();
        }catch(Exception e){
            System.assertEquals('Script-thrown exception', e.getMessage());
        }
    }
    
    @isTest
    public static void isResiDocumentTest(){
        User u = [SELECT Id,usertype FROM User WHERE UserName='test1_userprod123@indusbank.com' AND IsActive = true LIMIT 1];
    
        system.runAs(u)
        {
            String resiRecordTypeId = Schema.sObjectType.Documents__c.getRecordTypeInfosByName().get('Resi Profile Documents').getRecordTypeId();
            Opportunity oppRec1 = [SELECT Id, Vehicle_Type__c, Product_Type__c FROM Opportunity WHERE Name='VDR Test' LIMIT 1];
            Documents__c docRec = [SELECT Id, Opportunity_Relation__c,Applicant__c,Document_Type__c FROM Documents__c  LIMIT 1];
            docRec.RecordTypeId = resiRecordTypeId;
            docRec.Document_Type__c = 'Resi Profile Document';
            update docRec;
            
            Test.startTest();
            GetFilesController.isResiDocument(docRec.Id);
            Test.StopTest();
        
        }
          
    }
    
}