ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/applicant_number__c.field-meta.xml
<CustomField>
    <fullName>applicant_number__c</fullName>
    <formula>IF( ISPICKVAL(Applicant_Type__c , &quot;Borrower&quot;), &quot;B&quot;+Id , &quot;C&quot;+Id)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>applicant number</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/DocAuth_Application_Id__c.field-meta.xml
<CustomField>
    <fullName>DocAuth_Application_Id__c</fullName>
    <label>DocAuth Application Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Lead_Number__c.field-meta.xml
<CustomField>
    <fullName>Lead_Number__c</fullName>
    <formula>Opportunity__r.Lead_number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Id</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/PAN_No__c.field-meta.xml
<CustomField>
    <fullName>PAN_No__c</fullName>
    <label>PAN No.</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/Deal_Number__c.object-meta.xml
<CustomObject>
    <description>The custom object created for Deal Number generation</description>
    <label>Deal Number</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <formula>DNField1__c  +  DNField2__c  +  ProductCode__c  +  DNField3__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal Number</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Document_Side__c.field-meta.xml
<CustomField>
    <fullName>Document_Side__c</fullName>
    <label>Document Side</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Front</fullName>
            </value>
            <value>
                <fullName>Back</fullName>
            </value>
            <value>
                <fullName>Selfie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Seller&apos;s Passbook</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Bank Statement</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Cancel Cheque</fullName>
            </value>
            <value>
                <fullName>Driving Licence</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Voter Id</fullName>
            </value>
            <value>
                <fullName>Form 60</fullName>
            </value>
            <value>
                <fullName>Customer Image</fullName>
            </value>
            <value>
                <fullName>Aadhaar</fullName>
            </value>
            <value>
                <fullName>Vehicle Images</fullName>
            </value>
            <value>
                <fullName>RC Document</fullName>
            </value>
            <value>
                <fullName>SPR</fullName>
            </value>
            <value>
                <fullName>APR</fullName>
            </value>
            <value>
                <fullName>Electronic Bill</fullName>
                <label>Electricity Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Water Bill</fullName>
                <label>Water Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Vehicle Insurance Policy</fullName>
            </value>
            <value>
                <fullName>Vehicle Image</fullName>
            </value>
            <value>
                <fullName>Bank Statement</fullName>
            </value>
            <value>
                <fullName>Insurance Policy Doc</fullName>
            </value>
            <value>
                <fullName>Valuation Report</fullName>
            </value>
            <value>
                <fullName>Office FI</fullName>
            </value>
            <value>
                <fullName>Land Photo</fullName>
            </value>
            <value>
                <fullName>Patta Document</fullName>
            </value>
            <value>
                <fullName>Rent Agreement/Reciept</fullName>
            </value>
            <value>
                <fullName>Pension Document</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Engine Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Chassis Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Selfie with Vehicle-uploaded during verification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/KYC_City__c.field-meta.xml
<CustomField>
    <fullName>KYC_City__c</fullName>
    <label>KYC City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/KYC_DOB__c.field-meta.xml
<CustomField>
    <fullName>KYC_DOB__c</fullName>
    <label>KYC DOB</label>
    <type>Date</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/KYC_Issuance_Date__c.field-meta.xml
<CustomField>
    <fullName>KYC_Issuance_Date__c</fullName>
    <label>KYC Issuance Date</label>
    <type>Date</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/KYC_name__c.field-meta.xml
<CustomField>
    <fullName>KYC_name__c</fullName>
    <label>KYC name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/KYC_No__c.field-meta.xml
<CustomField>
    <fullName>KYC_No__c</fullName>
    <label>KYC No.</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Opportunity_Relation__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Relation__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/PAN_No__c.field-meta.xml
<CustomField>
    <fullName>PAN_No__c</fullName>
    <label>PAN No.</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Proof_of_Address_POA__c.field-meta.xml
<CustomField>
    <fullName>Proof_of_Address_POA__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proof of Address (POA)</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Proof_of_Identity_POI__c.field-meta.xml
<CustomField>
    <fullName>Proof_of_Identity_POI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proof of Identity (POI)</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/recordTypes/KYC.recordType-meta.xml
<RecordType>
    <fullName>KYC</fullName>
    <active>true</active>
    <label>KYC Document</label>
</RecordType>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Agent_BL_code__c.field-meta.xml
<CustomField>
    <fullName>Agent_BL_code__c</fullName>
    <label>Agent BL code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Ben_Code__c.field-meta.xml
<CustomField>
    <fullName>Ben_Code__c</fullName>
    <label>Ben Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <description>IndusInd deal number</description>
    <label>Deal Number</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/DocAuth_Application_Id__c.field-meta.xml
<CustomField>
    <fullName>DocAuth_Application_Id__c</fullName>
    <label>DocAuth Application Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Finance_Amount__c.field-meta.xml
<CustomField>
    <fullName>Finance_Amount__c</fullName>
    <formula>Required_Loan_amount__c +  Total_Funded_Premium__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Finance Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Funded__c.field-meta.xml
<CustomField>
    <fullName>Funded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funded</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Is_customer_interested_in_a_motor_insura__c.field-meta.xml
<CustomField>
    <fullName>Is_customer_interested_in_a_motor_insura__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is customer interested in a motor insura</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Lead_number__c.field-meta.xml
<CustomField>
    <fullName>Lead_number__c</fullName>
    <label>Lead Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Parent_Deal_number__c.field-meta.xml
<CustomField>
    <fullName>Parent_Deal_number__c</fullName>
    <label>Parent Deal number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Required_Loan_amount__c.field-meta.xml
<CustomField>
    <fullName>Required_Loan_amount__c</fullName>
    <label>Required Loan amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Sub_Category__c</fullName>
    <label>Vehicle Sub-Category</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/Maker_Id__c.field-meta.xml
<CustomField>
    <fullName>Maker_Id__c</fullName>
    <label>Maker Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/classes/DSA_IntegrationEngineTest.cls
@isTest
public class DSA_IntegrationEngineTest {
    @testSetup
    static void testDataSetup()
    {
        Profile p = [SELECT Id FROM Profile WHERE Name='IBL CVO'];
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',MobilePhone = '9999999999',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id, Maker_Id__c='12',
                          TimeZoneSidKey='America/Los_Angeles',
                          UserName='standarduser4@testorg.com.psdev1');
        insert u;
        System.runAs(u){
            Opportunity opp = TestDataUtility.createTestOpportunity(false);
            opp.Deal_Number__c = 'TUT06226H';
            opp.Parent_Deal_number__c = 'DL109939';
            opp.Lead_Number__c='L-10122021-1685';
            opp.Product_Type__c = 'Passenger Vehicles';
            opp.Required_Loan_amount__c = 50000;
            opp.LeadSource = 'DSA';
            if (Schema.sObjectType.Opportunity.isCreateable()){

                insert opp;
            }
            Applicant__c applicant = TestDataUtility.createTestApplicantForSMS(false);
            applicant.Opportunity__c=opp.Id;
            applicant.DocAuth_Application_Id__c = 'AC1241_24524353_g1';
            String dealNumber = opp.Deal_Number__c;
            String loanAppId = opp.id;
            if (Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicant;
            }
            Documents__c doc = new Documents__c();
            doc.Name = 'Test document';
            doc.Document_Type__c = 'PAN';
            doc.Document_Side__c = 'Front';
            doc.Age__c = 30;
            doc.KYC_DOB__c = Date.newInstance(1993, 05, 05);
            doc.KYC_City__c = 'Mumbai';
            doc.PAN_No__c = 'testpan';
            doc.KYC_name__c = 'Test KYC Name';
            doc.KYC_No__c = Integrationutilities.getencryptedrequest('TN2020090003150',System.Label.privateKey,System.Label.ivkey);
            doc.KYC_Issuance_Date__c = Date.newInstance(2022, 05, 20);
            doc.Proof_of_Address_POA__c = true;
            doc.Proof_of_Identity_POI__c = true;
            doc.Opportunity_Relation__c = opp.Id;
            doc.Applicant__c =applicant.id;
            insert doc;


        }

    }

    @isTest
    public static void doAMLCheckCalloutTest(){
        try{
            User u = [SELECT Id,usertype FROM User WHERE UserName='standarduser4@testorg.com.psdev1' AND IsActive = true LIMIT 1];

            Opportunity loanApp = [SELECT Id,Lead_number__c FROM Opportunity];
            Applicant__c applicant = [SELECT Id,DocAuth_Application_Id__c,Applicant_Number__c,Name,Opportunity__r.Lead_number__c,(SELECT Id,Proof_of_Address_POA__c,Proof_of_Identity_POI__c, KYC_DOB__c, KYC_City__c FROM Documents__r WHERE KYC_DOB__c != NULL AND KYC_City__c != NULL AND (Proof_of_Address_POA__c = true OR Proof_of_Identity_POI__c = true)) FROM Applicant__c ];
            System.debug('applicant ---> ' + applicant);
            Continuation con = (Continuation)IntegrationEngine.doAMLCheckCallout(applicant.Id,loanApp.Id);

            Map<String, HttpRequest> requests = con.getRequests();
            //system.assert(requests.size() == 1);
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('JData":"bmvHXB5/b59ltoDPA8dwPKjM9zW1GwK5fvqA5/8G5ng/DZCG559eHYwynGh3m3kpuywLZET1DqqOzmR2Ko2z06E/CLbdl3PjIPBUdzm3WvWeOWPbqKvSBm48N5LS4vy4VfpvD4M0jl1J1OlJK+Zx+X326SRlbJxcTImhh1gwXa05SExDifebbRABcCtMAHqmdNeq6DS0TTcQNiKDhkiV4pKg9vemcOKL9PvgP2P/YeAIQOoqetiRtV45RLTdYScv/11BWP6/0AM6LQTtDzp3+oUAZkV8hJluV3uCxuERC2tp8L2Jscx4jkWwalbiBjSmRS7h0VHkpmMy7728h+PkHLRSSjebpTw8CQRnpf3l8eI=');
            response.setStatusCode(200);

            String continuationLabel = IntegrationEngine.continuationLabel;
            System.debug('continuationLabel ---> ' + continuationLabel);
            String membershipResponse = '';
            List<String> labels = new List<String>{continuationLabel};
                Object continuationState= IntegrationEngine.continuationState;
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            membershipResponse = (String)IntegrationEngine.processAMLCheckAPIResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
            String responseExpected ='{"response":{"status":"SUCCESS","respDesc":"Deal Master","content":[{"DealNumber":"","DealNoExists":"No","StatusFlag":" ","Engine_Number":"","Chassis_Number":"","Make":"","Model":"","Variant":"","Manufacture_Year_Month":"","Owner_Name":"","No_of_Ownership":"0"}]}}';
            System.assertEquals(responseExpected, membershipResponse,'SUCCESS');


        } catch(Exception ex){
            System.debug('error ---> ' + ex.getMessage());
            System.debug('error ---> ' + ex.getLineNumber());
            //System.assertEquals('Script-thrown exception', ex.getMessage());
        }
    }

    @isTest
    public static void doDealMasterCalloutForCustomerNameTest(){
        try{
            User u = [SELECT Id,usertype FROM User WHERE UserName='standarduser4@testorg.com.psdev1' AND IsActive = true LIMIT 1];

            Opportunity loanApp = [SELECT Id,Lead_number__c,Deal_Number__c FROM Opportunity];
            Applicant__c applicant = [select Id, Opportunity__c FROM Applicant__c ];

            Continuation con = (Continuation)IntegrationEngine.doDealMasterCalloutForCustomerName(loanApp.Deal_Number__c,loanApp.Id);
            System.debug('con ---> ' + con);
            Map<String, HttpRequest> requests = con.getRequests();
            //system.assert(requests.size() == 1);
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('JData":"bmvHXB5/b59ltoDPA8dwPKjM9zW1GwK5fvqA5/8G5ng/DZCG559eHYwynGh3m3kpuywLZET1DqqOzmR2Ko2z06E/CLbdl3PjIPBUdzm3WvWeOWPbqKvSBm48N5LS4vy4VfpvD4M0jl1J1OlJK+Zx+X326SRlbJxcTImhh1gwXa05SExDifebbRABcCtMAHqmdNeq6DS0TTcQNiKDhkiV4pKg9vemcOKL9PvgP2P/YeAIQOoqetiRtV45RLTdYScv/11BWP6/0AM6LQTtDzp3+oUAZkV8hJluV3uCxuERC2tp8L2Jscx4jkWwalbiBjSmRS7h0VHkpmMy7728h+PkHLRSSjebpTw8CQRnpf3l8eI=');
            response.setStatusCode(200);

            String continuationLabel = IntegrationEngine.continuationLabel;
            String membershipResponse = '';
            List<String> labels = new List<String>{continuationLabel};
                Object continuationState= IntegrationEngine.continuationState;
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            membershipResponse = (String)IntegrationEngine.processDealMasterAPIResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
            String responseExpected ='{"response":{"status":"SUCCESS","respDesc":"Deal Master","content":[{"DealNumber":"","DealNoExists":"No","StatusFlag":" ","Engine_Number":"","Chassis_Number":"","Make":"","Model":"","Variant":"","Manufacture_Year_Month":"","Owner_Name":"","No_of_Ownership":"0"}]}}';
            System.assertEquals(responseExpected, membershipResponse,'SUCCESS');
        } catch(Exception ex){
            System.debug('error ---> ' + ex.getMessage());
            System.debug('error ---> ' + ex.getLineNumber());
            //System.assert(ex.getMessage().contains('List has no rows for assignment to SObject'));
        }
    }


    @isTest
    public static void doNeSLAgreementStatusCalloutTest(){
        try{
            User u = [SELECT Id,usertype FROM User WHERE UserName='standarduser4@testorg.com.psdev1' AND IsActive = true LIMIT 1];

            Opportunity loanApp = [SELECT Id,Lead_number__c FROM Opportunity];
            Applicant__c applicant = [SELECT Id,Opportunity__r.Parent_Deal_number__c,Opportunity__r.Deal_number__c FROM Applicant__c ];
            System.debug('applicant ---> ' + applicant);
            Continuation con = (Continuation)IntegrationEngine.doNeSLAgreementStatusCallout(applicant.Id,loanApp.Id);

            Map<String, HttpRequest> requests = con.getRequests();
            system.assert(requests.size() != 1);
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('JData":"bmvHXB5/b59ltoDPA8dwPKjM9zW1GwK5fvqA5/8G5ng/DZCG559eHYwynGh3m3kpuywLZET1DqqOzmR2Ko2z06E/CLbdl3PjIPBUdzm3WvWeOWPbqKvSBm48N5LS4vy4VfpvD4M0jl1J1OlJK+Zx+X326SRlbJxcTImhh1gwXa05SExDifebbRABcCtMAHqmdNeq6DS0TTcQNiKDhkiV4pKg9vemcOKL9PvgP2P/YeAIQOoqetiRtV45RLTdYScv/11BWP6/0AM6LQTtDzp3+oUAZkV8hJluV3uCxuERC2tp8L2Jscx4jkWwalbiBjSmRS7h0VHkpmMy7728h+PkHLRSSjebpTw8CQRnpf3l8eI=');
            response.setStatusCode(200);

            String continuationLabel = IntegrationEngine.continuationLabel;
            System.debug('continuationLabel ---> ' + continuationLabel);
            String membershipResponse = '';
            List<String> labels = new List<String>{continuationLabel};
                Object continuationState= IntegrationEngine.continuationState;
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            membershipResponse = (String)IntegrationEngine.processNeSLAgreementStatusAPIResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
            String responseExpected ='{"response":{"status":"SUCCESS","respDesc":"Deal Master","content":[{"DealNumber":"","DealNoExists":"No","StatusFlag":" ","Engine_Number":"","Chassis_Number":"","Make":"","Model":"","Variant":"","Manufacture_Year_Month":"","Owner_Name":"","No_of_Ownership":"0"}]}}';
            System.assertEquals(responseExpected, membershipResponse,'SUCCESS');


        } catch(Exception ex){
            System.debug('error ---> ' + ex.getMessage());
            System.debug('error ---> ' + ex.getLineNumber());
            //System.assertEquals('Script-thrown exception', ex.getMessage());
        }
    }
    @isTest
    public static void doNeSLAgreementStatusCalloutTest1(){
        try{
            User u = [SELECT Id,usertype FROM User WHERE UserName='standarduser4@testorg.com.psdev1' AND IsActive = true LIMIT 1];

            Opportunity loanApp = [SELECT Id,Lead_number__c FROM Opportunity];
            Applicant__c applicant = [SELECT Id,Opportunity__r.Parent_Deal_number__c,Opportunity__r.Deal_number__c FROM Applicant__c ];
            System.debug('applicant ---> ' + applicant);
            Continuation con = (Continuation)IntegrationEngine.doNeSLAgreementStatusCallout(applicant.Id,loanApp.Id);

            Map<String, HttpRequest> requests = con.getRequests();
            //system.assert(requests.size() == 1);
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('JData":"bmvHXB5/b59ltoDPA8dwPKjM9zW1GwK5fvqA5/8G5ng/DZCG559eHYwynGh3m3kpuywLZET1DqqOzmR2Ko2z06E/CLbdl3PjIPBUdzm3WvWeOWPbqKvSBm48N5LS4vy4VfpvD4M0jl1J1OlJK+Zx+X326SRlbJxcTImhh1gwXa05SExDifebbRABcCtMAHqmdNeq6DS0TTcQNiKDhkiV4pKg9vemcOKL9PvgP2P/YeAIQOoqetiRtV45RLTdYScv/11BWP6/0AM6LQTtDzp3+oUAZkV8hJluV3uCxuERC2tp8L2Jscx4jkWwalbiBjSmRS7h0VHkpmMy7728h+PkHLRSSjebpTw8CQRnpf3l8eI=');
            response.setStatusCode(200);

            String continuationLabel = IntegrationEngine.continuationLabel;
            System.debug('continuationLabel ---> ' + continuationLabel);
            String membershipResponse = '';
            List<String> labels = new List<String>{continuationLabel};
                Object continuationState= IntegrationEngine.continuationState;
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            membershipResponse = (String)IntegrationEngine.processNeSLAgreementStatusAPIResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
            String responseExpected ='{"response":{"status":"SUCCESS","respDesc":"Deal Master","content":[{"DealNumber":"","DealNoExists":"No","StatusFlag":" ","Engine_Number":"","Chassis_Number":"","Make":"","Model":"","Variant":"","Manufacture_Year_Month":"","Owner_Name":"","No_of_Ownership":"0"}]}}';
            System.assertEquals(responseExpected, membershipResponse,'SUCCESS');


        } catch(Exception ex){
            System.debug('error ---> ' + ex.getMessage());
            System.debug('error ---> ' + ex.getLineNumber());
            //System.assertEquals('Script-thrown exception', ex.getMessage());
        }
    }

    @isTest
    public static void doStampingDetailsCalloutTest(){
        try{
            User u = [SELECT Id,usertype FROM User WHERE UserName='standarduser4@testorg.com.psdev1' AND IsActive = true LIMIT 1];

            Opportunity loanApp = [SELECT Id,Deal_number__c,Product_Type__c,Lead_number__c,Finance_Amount__c FROM Opportunity];
            Applicant__c applicant = [SELECT Id,Opportunity__r.Parent_Deal_number__c,Opportunity__r.Deal_number__c FROM Applicant__c ];
            System.debug('applicant ---> ' + applicant);
            Continuation con = (Continuation)IntegrationEngine.doStampingDetailsCallout(applicant.Id,loanApp.Id,'33','test');

            Map<String, HttpRequest> requests = con.getRequests();
            //system.assert(requests.size() == 1);
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('JData":"bmvHXB5/b59ltoDPA8dwPKjM9zW1GwK5fvqA5/8G5ng/DZCG559eHYwynGh3m3kpuywLZET1DqqOzmR2Ko2z06E/CLbdl3PjIPBUdzm3WvWeOWPbqKvSBm48N5LS4vy4VfpvD4M0jl1J1OlJK+Zx+X326SRlbJxcTImhh1gwXa05SExDifebbRABcCtMAHqmdNeq6DS0TTcQNiKDhkiV4pKg9vemcOKL9PvgP2P/YeAIQOoqetiRtV45RLTdYScv/11BWP6/0AM6LQTtDzp3+oUAZkV8hJluV3uCxuERC2tp8L2Jscx4jkWwalbiBjSmRS7h0VHkpmMy7728h+PkHLRSSjebpTw8CQRnpf3l8eI=');
            response.setStatusCode(200);

            String continuationLabel = IntegrationEngine.continuationLabel;
            System.debug('continuationLabel ---> ' + continuationLabel);
            String membershipResponse = '';
            List<String> labels = new List<String>{continuationLabel};
                Object continuationState= IntegrationEngine.continuationState;
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            membershipResponse = (String)IntegrationEngine.processStampingDetailsAPIResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
            String responseExpected ='{"response":{"status":"SUCCESS","respDesc":"Deal Master","content":[{"DealNumber":"","DealNoExists":"No","StatusFlag":" ","Engine_Number":"","Chassis_Number":"","Make":"","Model":"","Variant":"","Manufacture_Year_Month":"","Owner_Name":"","No_of_Ownership":"0"}]}}';
            System.assertEquals(responseExpected, membershipResponse,'SUCCESS');


        } catch(Exception ex){
            System.debug('error ---> ' + ex.getMessage());
            System.debug('error ---> ' + ex.getLineNumber());
            //System.assertEquals('Script-thrown exception', ex.getMessage());
        }
    }

    @isTest
    public static void doStampingDetailsCalloutTest1(){
        try{
            User u = [SELECT Id,usertype FROM User WHERE UserName='standarduser4@testorg.com.psdev1' AND IsActive = true LIMIT 1];

            Opportunity loanApp = [SELECT Id,Deal_number__c,Product_Type__c,Lead_number__c,Finance_Amount__c FROM Opportunity];
            Applicant__c applicant = [SELECT Id,Opportunity__r.Parent_Deal_number__c,Opportunity__r.Deal_number__c FROM Applicant__c ];
            System.debug('applicant ---> ' + applicant);
            Continuation con = (Continuation)IntegrationEngine.doStampingDetailsCallout(applicant.Id,loanApp.Id,'33','test');

            Map<String, HttpRequest> requests = con.getRequests();
            system.assert(requests.size() != 1);
            // Create a mock response
            HttpResponse response = new HttpResponse();
            response.setBody('JData":"bmvHXB5/b59ltoDPA8dwPKjM9zW1GwK5fvqA5/8G5ng/DZCG559eHYwynGh3m3kpuywLZET1DqqOzmR2Ko2z06E/CLbdl3PjIPBUdzm3WvWeOWPbqKvSBm48N5LS4vy4VfpvD4M0jl1J1OlJK+Zx+X326SRlbJxcTImhh1gwXa05SExDifebbRABcCtMAHqmdNeq6DS0TTcQNiKDhkiV4pKg9vemcOKL9PvgP2P/YeAIQOoqetiRtV45RLTdYScv/11BWP6/0AM6LQTtDzp3+oUAZkV8hJluV3uCxuERC2tp8L2Jscx4jkWwalbiBjSmRS7h0VHkpmMy7728h+PkHLRSSjebpTw8CQRnpf3l8eI=');
            response.setStatusCode(250);

            String continuationLabel = IntegrationEngine.continuationLabel;
            System.debug('continuationLabel ---> ' + continuationLabel);
            String membershipResponse = '';
            List<String> labels = new List<String>{continuationLabel};
                Object continuationState= IntegrationEngine.continuationState;
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            membershipResponse = (String)IntegrationEngine.processStampingDetailsAPIResponse(labels, IntegrationEngine.continuationState);
            Test.stopTest();
            String responseExpected ='{"response":{"status":"SUCCESS","respDesc":"Deal Master","content":[{"DealNumber":"","DealNoExists":"No","StatusFlag":" ","Engine_Number":"","Chassis_Number":"","Make":"","Model":"","Variant":"","Manufacture_Year_Month":"","Owner_Name":"","No_of_Ownership":"0"}]}}';
            System.assertEquals(responseExpected, membershipResponse,'SUCCESS');


        } catch(Exception ex){
            System.debug('error ---> ' + ex.getMessage());
            System.debug('error ---> ' + ex.getLineNumber());
            //System.assertEquals('Script-thrown exception', ex.getMessage());
        }
    }


    @isTest
    public static void doIHMReceiptCalloutTest(){
        try{
            User u = [SELECT Id,usertype FROM User WHERE UserName='standarduser4@testorg.com.psdev1' AND IsActive = true LIMIT 1];

            Opportunity loanApp = [SELECT Id,Lead_number__c FROM Opportunity];
            Applicant__c applicant = [SELECT Id,Opportunity__r.Deal_number__c FROM Applicant__c ];
            System.debug('applicant ---> ' + applicant);
            Continuation con = (Continuation)IntegrationEngine.doIHMReceiptCallout(applicant.Id,loanApp.Id,'test');

            Map<String, HttpRequest> requests = con.getRequests();
            //system.assert(requests.size() == 1);
            // Create a mock response
            // HttpResponse response = new HttpResponse();
            // response.setBody('JData":"bmvHXB5/b59ltoDPA8dwPKjM9zW1GwK5fvqA5/8G5ng/DZCG559eHYwynGh3m3kpuywLZET1DqqOzmR2Ko2z06E/CLbdl3PjIPBUdzm3WvWeOWPbqKvSBm48N5LS4vy4VfpvD4M0jl1J1OlJK+Zx+X326SRlbJxcTImhh1gwXa05SExDifebbRABcCtMAHqmdNeq6DS0TTcQNiKDhkiV4pKg9vemcOKL9PvgP2P/YeAIQOoqetiRtV45RLTdYScv/11BWP6/0AM6LQTtDzp3+oUAZkV8hJluV3uCxuERC2tp8L2Jscx4jkWwalbiBjSmRS7h0VHkpmMy7728h+PkHLRSSjebpTw8CQRnpf3l8eI=');
            // response.setStatusCode(200);

            //String continuationLabel = IntegrationEngine.continuationLabel;
            //System.debug('continuationLabel ---> ' + continuationLabel);
            String membershipResponse = '';
            //List<String> labels = new List<String>{continuationLabel};
            //  Object continuationState= IntegrationEngine.continuationState;
            Test.startTest();
            //Test.setContinuationResponse(continuationLabel, response);
            // membershipResponse = (String)IntegrationEngine.processDealMasterAPIResponse(labels, IntegrationEngine.continuationState);

            HttpResponse response = new HttpResponse();
            String body = '{"JData":"bmvHXB5/b59ltoDPA8dwPKjM9zW1GwK5fvqA5/8G5njZcJY00rL9wJSIMpbrzEBGczzs/qwlKFOA2/srolJ6l1djQPyCsWPhGnh7CqucCWPqwsLVYtyAskLBb8ekrCuVrKDeBNiojndyKtLQoX7upFsTrRkJmZJNIgdkS7hNrJigY5/m9JrXCt+K6YQwxMDFlsL3BshrRI8XlQdZTrUgYg=="}';
            response.setBody(body);
            response.setStatusCode(200);

            String continuationLabel = IntegrationEngine.continuationLabel;
            //Object continuationState= IntegrationEngine.continuationState;
            List<String> labels = new List<String>{continuationLabel};

                Object continuationState= IntegrationEngine.continuationState;
            membershipResponse = (String)IntegrationEngine.processIHMReceiptResponse(labels, IntegrationEngine.continuationState);

            System.debug('labels===>'+labels);
            System.debug('continuationState===>'+continuationState);


            Test.setContinuationResponse(continuationLabel, response);
            //Object result3 = aml.processSMSGatewayResponse(labels, aml.continuationState);

            Test.stopTest();
            String responseExpected ='{"response":{"status":"SUCCESS","respDesc":"Deal Master","content":[{"DealNumber":"","DealNoExists":"No","StatusFlag":" ","Engine_Number":"","Chassis_Number":"","Make":"","Model":"","Variant":"","Manufacture_Year_Month":"","Owner_Name":"","No_of_Ownership":"0"}]}}';
            //System.assertEquals(responseExpected, membershipResponse,'SUCCESS');


        } catch(Exception ex){
            System.debug('error ---> ' + ex.getMessage());
            System.debug('error ---> ' + ex.getLineNumber());
            //System.assertEquals('Script-thrown exception', ex.getMessage());
        }
    }
    @isTest
    public static void doRCLimitCheckCalloutTest(){
        try{
            User u = [SELECT Id,usertype FROM User WHERE UserName='standarduser4@testorg.com.psdev1' AND IsActive = true LIMIT 1];
            Opportunity optg1 = new Opportunity();
            optg1.StageName = 'Loan Details';
            optg1.CloseDate = Date.newInstance(2022, 1, 11);
            optg1.Name = 'testone';
            optg1.Vehicle_Type__c = 'New';
            optg1.Product_Type__c = 'Passenger Vehicles';
            optg1.Ben_Code__c = 'optg2';
            optg1.Vehicle_Sub_Category__c = 'UOM';
            optg1.Agent_BL_code__c = 'BLC';
            optg1.Funded__c = false;
            optg1.Is_customer_interested_in_a_motor_insura__c = true;
            optg1.Motor_Insurance_Premium__c = 20000;
            optg1.Sub_Stage__c = 'Business Payment Details';

            insert optg1;

            Applicant__c objApplicant = new Applicant__c();
            objApplicant.Opportunity__c = optg1.Id;
            objApplicant.Applicant_Type__c = 'Borrower';
            objApplicant.Contact_number__c = '1234567890';
            insert objApplicant;

            Test.startTest();
            IntegrationEngine.doRCLimitCheckCallout(objApplicant.Id, optg1.Id,'test');
            Test.stopTest();
        } catch(Exception ex){
            System.debug('error ---> ' + ex.getMessage());
            System.debug('error ---> ' + ex.getLineNumber());
            //System.assertEquals('Script-thrown exception', ex.getMessage());
        }
    }
    @isTest
    public static void doSmsGatewayCalloutTest(){
        try{
            User u = [SELECT Id,usertype FROM User WHERE username='standarduser4@testorg.com.psdev1' AND IsActive = true LIMIT 1];

            String loanApplicationId = '00671000001Dz1tAAC';
            Opportunity loanApp = [SELECT Id,Lead_number__c,Deal_number__c FROM Opportunity];
            System.debug('loanApp::' + loanApp);
            Applicant__c applicant = [SELECT Id,Contact_number__c,Whatsapp_number__c,OTP_for_borrower__c,Opportunity__r.Deal_number__c,Opportunity__r.Lead_number__c FROM Applicant__c LIMIT 1];
            System.debug('applicant::' + applicant);
            RequestWrapper requestWrapper = new RequestWrapper();
            requestWrapper.applicantId = applicant.ID;
            String statusCheckString = '{"enachStatus":"00671000001 "  ,"loanApplicationId":"00671000001Dz1tAAC", "applicantId":"' + applicant.Id + '"}';
            system.debug('requestWraper in test class>>'+requestWrapper);
            Object str1 = DSA_IntegrationEngine.doSmsGatewayCallout(statusCheckString);

            HttpResponse response = new HttpResponse();
            response.setBody('JData":"bmvHXB5/b59ltoDPA8dwPKjM9zW1GwK5fvqA5/8G5ng/DZCG559eHYwynGh3m3kpuywLZET1DqqOzmR2Ko2z06E/CLbdl3PjIPBUdzm3WvWeOWPbqKvSBm48N5LS4vy4VfpvD4M0jl1J1OlJK+Zx+X326SRlbJxcTImhh1gwXa05SExDifebbRABcCtMAHqmdNeq6DS0TTcQNiKDhkiV4pKg9vemcOKL9PvgP2P/YeAIQOoqetiRtV45RLTdYScv/11BWP6/0AM6LQTtDzp3+oUAZkV8hJluV3uCxuERC2tp8L2Jscx4jkWwalbiBjSmRS7h0VHkpmMy7728h+PkHLRSSjebpTw8CQRnpf3l8eI=');
            response.setStatusCode(200);

            String continuationLabel = IntegrationEngine.continuationLabel;
            System.debug('continuationLabel ---> ' + continuationLabel);
            String membershipResponse = '';
            List<String> labels = new List<String>{continuationLabel};
                Object continuationState= IntegrationEngine.continuationState;
            Test.startTest();
            Test.setContinuationResponse(continuationLabel, response);
            RequestWrapper requestWrapper1 = (RequestWrapper)IntegrationUtilities.parseJSONRequest('xyz','RequestWrapper');
            Test.stopTest();
            String responseExpected ='{"response":{"status":"SUCCESS","respDesc":"Deal Master","content":[{"DealNumber":"","DealNoExists":"No","StatusFlag":" ","Engine_Number":"","Chassis_Number":"","Make":"","Model":"","Variant":"","Manufacture_Year_Month":"","Owner_Name":"","No_of_Ownership":"0"}]}}';
            System.assertEquals(responseExpected, membershipResponse,'SUCCESS');


        } catch(Exception ex){
            System.debug('error ---> ' + ex.getMessage());
            System.debug('error ---> ' + ex.getLineNumber());
            //System.assertEquals('Script-thrown exception', ex.getMessage());
        }
    }
}