ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Lead_Number__c.field-meta.xml
<CustomField>
    <fullName>Lead_Number__c</fullName>
    <formula>Opportunity__r.Lead_number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Id</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Seller&apos;s Passbook</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Bank Statement</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Cancel Cheque</fullName>
            </value>
            <value>
                <fullName>Driving Licence</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Voter Id</fullName>
            </value>
            <value>
                <fullName>Form 60</fullName>
            </value>
            <value>
                <fullName>Customer Image</fullName>
            </value>
            <value>
                <fullName>Aadhaar</fullName>
            </value>
            <value>
                <fullName>Vehicle Images</fullName>
            </value>
            <value>
                <fullName>RC Document</fullName>
            </value>
            <value>
                <fullName>SPR</fullName>
            </value>
            <value>
                <fullName>APR</fullName>
            </value>
            <value>
                <fullName>Electronic Bill</fullName>
                <label>Electricity Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Water Bill</fullName>
                <label>Water Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Vehicle Insurance Policy</fullName>
            </value>
            <value>
                <fullName>Vehicle Image</fullName>
            </value>
            <value>
                <fullName>Bank Statement</fullName>
            </value>
            <value>
                <fullName>Insurance Policy Doc</fullName>
            </value>
            <value>
                <fullName>Valuation Report</fullName>
            </value>
            <value>
                <fullName>Office FI</fullName>
            </value>
            <value>
                <fullName>Land Photo</fullName>
            </value>
            <value>
                <fullName>Patta Document</fullName>
            </value>
            <value>
                <fullName>Rent Agreement/Reciept</fullName>
            </value>
            <value>
                <fullName>Pension Document</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Engine Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Chassis Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Selfie with Vehicle-uploaded during verification</fullName>
            </value>
            <value>
                <fullName>IHM Receipt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/IHM__c.field-meta.xml
<CustomField>
    <fullName>IHM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IHM</label>
    <referenceTo>IHM__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Invoice_Details__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Invoice Details</label>
    <referenceTo>Invoice_Details__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Opportunity_Relation__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Relation__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>Vehicle_Detail__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/IHM__c/IHM__c.object-meta.xml
<CustomObject>
    <label>IHM</label>
    <nameField>
        <label>IHM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IHMs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/IHM__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>IHMs</relationshipLabel>
    <relationshipName>IHMs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/IHM__c/fields/Total_IHM_paid_to_dealer_A__c.field-meta.xml
<CustomField>
    <fullName>Total_IHM_paid_to_dealer_A__c</fullName>
    <label>Total IHM paid to dealer (A)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Invoice_Details__c/Invoice_Details__c.object-meta.xml
<CustomObject>
    <label>Invoice Details</label>
    <nameField>
        <displayFormat>INVD-{00000}</displayFormat>
        <label>Invoice Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Invoice_Details__c/fields/Chassis_No__c.field-meta.xml
<CustomField>
    <fullName>Chassis_No__c</fullName>
    <label>Chassis No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Invoice_Details__c/fields/Documents__c.field-meta.xml
<CustomField>
    <fullName>Documents__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Documents</label>
    <referenceTo>Documents__c</referenceTo>
    <relationshipLabel>Invoice Details</relationshipLabel>
    <relationshipName>Invoice_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Invoice_Details__c/fields/Engine_No__c.field-meta.xml
<CustomField>
    <fullName>Engine_No__c</fullName>
    <label>Engine No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Invoice_Details__c/fields/Invoice_Charger__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Charger__c</fullName>
    <label>Invoice Charger</label>
    <length>254</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Invoice_Details__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Invoice Details</relationshipLabel>
    <relationshipName>Invoice_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Invoice_Details__c/fields/Tax_Invoice_Date__c.field-meta.xml
<CustomField>
    <fullName>Tax_Invoice_Date__c</fullName>
    <label>Tax Invoice Date</label>
    <type>Date</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Invoice_Details__c/fields/Tax_Invoice_No__c.field-meta.xml
<CustomField>
    <fullName>Tax_Invoice_No__c</fullName>
    <label>Tax Invoice No</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Invoice_Details__c/fields/Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>Vehicle_Detail__c</referenceTo>
    <relationshipLabel>Invoice Details</relationshipLabel>
    <relationshipName>Invoice_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/LoanDisbursementDetails__c/LoanDisbursementDetails__c.object-meta.xml
<CustomObject>
    <label>LoanDisbursementDetails</label>
    <nameField>
        <label>LoanDisbursementDetails  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LoanDisbursementDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/LoanDisbursementDetails__c/fields/Chassis_no__c.field-meta.xml
<CustomField>
    <fullName>Chassis_no__c</fullName>
    <label>Chassis no.</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/LoanDisbursementDetails__c/fields/Engine_no__c.field-meta.xml
<CustomField>
    <fullName>Engine_no__c</fullName>
    <label>Engine no.</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/LoanDisbursementDetails__c/fields/Parent_Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Parent_Loan_Application__c</fullName>
    <label>Parent Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>LoanDisbursementDetails</relationshipLabel>
    <relationshipName>LoanDisbursementDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Lead_number__c.field-meta.xml
<CustomField>
    <fullName>Lead_number__c</fullName>
    <label>Lead Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Parent_Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Parent_Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Revoked parent application</description>
    <label>Parent Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Registration_Number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Registration_Number__c</fullName>
    <label>Vehicle Registration Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/Vehicle_Detail__c.object-meta.xml
<CustomObject>
    <label>Vehicle Detail</label>
    <nameField>
        <displayFormat>VD-{00000}</displayFormat>
        <label>Vehicle Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Engine_number__c.field-meta.xml
<CustomField>
    <fullName>Engine_number__c</fullName>
    <label>Engine number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <description>Vehicle Insurance and Vehicle Valuation data</description>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Vehicle_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Vehicle_Registration_number__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Registration_number__c</fullName>
    <label>Vehicle Registration number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/OlaInvoiceUpdateAPI.cls
@RestResource(urlMapping='/OlaInvoiceUpdate/')
global with sharing class OlaInvoiceUpdateAPI { 
    @HTTPPut
    global static void updateInvoiceDetails(){
        
        Boolean errorFlag = false;
        String errorMsg = '';
        RestRequest req  = RestContext.request;
        String leadPayload = req.requestBody.toString();
        ResponseWrapper response = new responseWrapper();
        RequestWrapper jsonParsed = new RequestWrapper();
        String decryptedReqBody = IntegrationUtilities.getDecryptedResponse(leadPayload,System.Label.privateKey,System.Label.ivkey);
        String encryptedResponse = '';
        String jdataRequest = '"JData":';    
        String loanId = '';

        try{
            jsonParsed =(RequestWrapper)JSON.deserialize(decryptedReqBody , RequestWrapper.class);

            //request validation start
            if(jsonParsed.applicationNumber==null){
                errorFlag = true;
                errorMsg = 'applicationNumber is missing in the request';
            } else if(jsonParsed.invoiceNumber==null){
                errorFlag = true;
                errorMsg = 'invoiceNumber is missing in the request';
            } else if(jsonParsed.invoiceDate==null){
                errorFlag = true;
                errorMsg = 'invoiceDate is missing in the request';
            } else if(jsonParsed.model==null){
                errorFlag = true;
                errorMsg = 'model is missing in the request';
            } else if(jsonParsed.engineNumber==null){
                errorFlag = true;
                errorMsg = 'engineNumber is missing in the request';
            } else if(jsonParsed.registrationNumber==null){
                errorFlag = true;
                errorMsg = 'registrationNumber is missing in the request';
            } else if(jsonParsed.chassisNumber==null){
                errorFlag = true;
                errorMsg = 'chassisNumber is missing in the request';
            } else if(jsonParsed.invoiceCharger==null){
                errorFlag = true;
                errorMsg = 'invoiceCharger is missing in the request';
            } else if(jsonParsed.ihmReceiptNo==null){
                errorFlag = true;
                errorMsg = 'ihmReceiptNo is missing in the request';
            } else if(jsonParsed.ihmReceiptDate==null){
                errorFlag = true;
                errorMsg = 'ihmReceiptDate is missing in the request';
            } else{
                errorFlag = false;
                errorMsg = '';
            }

            if(!errorFlag){
                String applicationNo = jsonParsed.applicationNumber;
                List<Opportunity> latestOpp = [select Id,name from Opportunity where name=:jsonParsed.applicationNumber order by CreatedDate DESC limit 1];//OLA-275    
                String soqlInvoice = 'SELECT id, Tax_Invoice_No__c, Tax_Invoice_Date__c,Loan_Application__c  FROM Invoice_Details__c WHERE Loan_Application__r.Lead_number__c= \'' + String.escapeSingleQuotes(applicationNo) + '\' and Loan_Application__c=\'' + String.escapeSingleQuotes(latestOpp[0].Id) + '\' LIMIT 1';//OLA-275
                String soqlVehicle = 'SELECT id, Model__c, Engine_number__c, Vehicle_Registration_number__c FROM Vehicle_Detail__c WHERE Loan_Application__r.Lead_number__c= \'' + String.escapeSingleQuotes(applicationNo) + '\' and Loan_Application__c=\'' + String.escapeSingleQuotes(latestOpp[0].Id) + '\' LIMIT 1';//OLA-275
                String soqlIHM = 'SELECT id, Total_IHM_paid_to_dealer_A__c FROM IHM__c WHERE Loan_Application__r.Lead_number__c= \'' + String.escapeSingleQuotes(applicationNo) + '\' and Loan_Application__c=\'' + String.escapeSingleQuotes(latestOpp[0].Id) + '\' LIMIT 1';//OLA-275
                String soqlApplicant = 'SELECT id FROM Applicant__c WHERE Opportunity__r.Lead_number__c= \'' + String.escapeSingleQuotes(applicationNo) + '\' and Opportunity__c=\'' + String.escapeSingleQuotes(latestOpp[0].Id) + '\' LIMIT 1';//OLA-275
                String soqlLoanDisb = 'Select id from LoanDisbursementDetails__c where Parent_Loan_Application__r.Lead_number__c=\''+ String.escapeSingleQuotes(applicationNo) + '\' and Parent_Loan_Application__c=\'' + String.escapeSingleQuotes(latestOpp[0].Id) + '\' LIMIT 1';//OLA-275
                List<Invoice_Details__c> invoiceDetail = Database.query(soqlInvoice);
                List<Vehicle_Detail__c> vehicleDetail = Database.query(soqlVehicle);
                List<IHM__c> ihmDetails = Database.query(soqlIHM);
                List<Applicant__c> applicantDetails = Database.query(soqlApplicant);
                List<LoanDisbursementDetails__c> loanDisbList = Database.query(soqlLoanDisb);

                if(invoiceDetail.size()==0){
                    errorFlag = true;
                    errorMsg = 'Invoice detail not found for the given application number.';
                    RestContext.response.statusCode = 400;
                    response.message = errorMsg;
                    response.statusCode = '400';
                    encryptedResponse = IntegrationUtilities.getEncryptedRequest(JSON.serialize(response),System.Label.privateKey,System.Label.ivkey);   
                    RestContext.response.responseBody = Blob.valueOf('{'+jdataRequest + '"'+encryptedResponse+'"'+'}');
                    RestContext.response.addHeader('Content-Type', 'application/json');
                } else if(vehicleDetail.size()==0){
                    errorFlag = true;
                    errorMsg = 'Vehicle detail not found for the given application number.';
                    RestContext.response.statusCode = 400;
                    response.message = errorMsg;
                    response.statusCode = '400';
                    encryptedResponse = IntegrationUtilities.getEncryptedRequest(JSON.serialize(response),System.Label.privateKey,System.Label.ivkey);   
                    RestContext.response.responseBody = Blob.valueOf('{'+jdataRequest + '"'+encryptedResponse+'"'+'}');
                    RestContext.response.addHeader('Content-Type', 'application/json');
                } else {
                    invoiceDetail.get(0).Tax_Invoice_No__c = jsonParsed.invoiceNumber;
                    invoiceDetail.get(0).Tax_Invoice_Date__c = jsonParsed.invoiceDate;
                    invoiceDetail.get(0).Chassis_No__c = jsonParsed.chassisNumber;
                    invoiceDetail.get(0).Invoice_Charger__c = jsonParsed.invoiceCharger;
                    invoiceDetail.get(0).Engine_No__c = jsonParsed.engineNumber;
                    loanId = invoiceDetail.get(0).Loan_Application__c;
                    update invoiceDetail;

                    //vehicleDetail.get(0).Model__c = jsonParsed.model;
                    vehicleDetail.get(0).Engine_number__c = jsonParsed.engineNumber;
                    vehicleDetail.get(0).Vehicle_Registration_number__c = jsonParsed.registrationNumber;
                    update vehicleDetail;

                    LoanDisbursementDetails__c loanDisDetails = new LoanDisbursementDetails__c();
                    loanDisDetails.Chassis_No__c = jsonParsed.chassisNumber;
                    loanDisDetails.Engine_No__c = jsonParsed.engineNumber;
                    if(loanDisbList.size()>0){
                        loanDisDetails.id = loanDisbList.get(0).id;
                        update loanDisDetails;
                    }

                    List<Documents__c> existingtInvoice = [Select id from Documents__c where Document_Type__c = 'IHM Receipt' and Opportunity_Relation__c=:invoiceDetail.get(0).Loan_Application__c Limit 1];

                    Documents__c docObject= new Documents__c(Name = 'IHM', is_Active__c=false);
                    
                    docObject.Opportunity_Relation__c=invoiceDetail.get(0).Loan_Application__c;
                    docObject.RecordTypeId = Schema.SObjectType.Documents__c.getRecordTypeInfosByName().get(System.Label.Other_Document_Record_Type).getRecordTypeId();
                    docObject.Document_Type__c = 'IHM Receipt';
                    docObject.IHM_receipt_number__c = jsonParsed.ihmReceiptNo;
                    docObject.IHM_receipt_date__c = jsonParsed.ihmReceiptDate;
                    docObject.id = (existingtInvoice.size()>0) ? existingtInvoice.get(0).id : docObject.id;
                    docObject.IHM_amount_as_per_receipt__c = ihmDetails.size()>0 ? ihmDetails.get(0).Total_IHM_paid_to_dealer_A__c : docObject.IHM_amount_as_per_receipt__c;
                    if(existingtInvoice.size()==0){
                        docObject.Applicant__c = applicantDetails.size()>0 ? applicantDetails.get(0).id : '';//adding required fields
                        insert docObject;
                    } else {
                        update docObject;
                    }

                    RestContext.response.statusCode = 200;
                    response.message = 'Invoice updated sucessfully';
                    response.statusCode = '200';
                    encryptedResponse = IntegrationUtilities.getEncryptedRequest(JSON.serialize(response),System.Label.privateKey,System.Label.ivkey);   
                    RestContext.response.responseBody = Blob.valueOf('{'+jdataRequest + '"'+encryptedResponse+'"'+'}');
                    RestContext.response.addHeader('Content-Type', 'application/json');
                    IntegrationUtilities.createIntegrationLogger(leadPayload, jsonParsed.toString(), 'Record created', '', 'OLA Request', '', loanId, System.Label.Success);
                }
            } else{
                RestContext.response.statusCode = 400;
                response.message = errorMsg;
                response.statusCode = '400';
                encryptedResponse = IntegrationUtilities.getEncryptedRequest(JSON.serialize(response),System.Label.privateKey,System.Label.ivkey);   
                RestContext.response.responseBody = Blob.valueOf('{'+jdataRequest + '"'+encryptedResponse+'"'+'}');
                RestContext.response.addHeader('Content-Type', 'application/json');
            }
            


        } catch(Exception e){
            system.debug('exc '+e.getMessage());
            system.debug('exc '+e.getLineNumber());
            RestContext.response.statusCode = 400;
            response.message = 'Something went wrong';
            response.statusCode = '400';
            RestContext.response.addHeader('Content-Type', 'application/json');
            encryptedResponse = IntegrationUtilities.getEncryptedRequest(JSON.serialize(response),System.Label.privateKey,System.Label.ivkey);   
            RestContext.response.responseBody = Blob.valueOf('{'+jdataRequest + '"'+encryptedResponse+'"'+'}');

            String deserror = 'Something went wrong ---> '+e.getMessage()+ ' Exception line number-->'+e.getLineNumber();
            String error = '{ "response": { "status": "FAILED", "respDesc": "'+deserror+'"} }';
            IntegrationUtilities.createIntegrationLogger(leadPayload, jsonParsed.toString(), error, '', 'OLA Request', '', loanId, System.Label.Failure);
            ErrorLoggerUtil.logErrorEvent('OlaInvoiceUpdateAPI', 'updateInvoiceDetails', System.Label.Apex, e,loanId);
            
        }
    }

    public class ResponseWrapper{
        Public String message;
        Public String statusCode;
    }

    Public class RequestWrapper{
        Public String applicationNumber;
        Public String invoiceNumber;
        Public Date invoiceDate;
        Public String model;
        Public String engineNumber;
        Public String registrationNumber;
        Public String chassisNumber;
        Public String invoiceCharger;
        Public String ihmReceiptNo;
        Public Date ihmReceiptDate;
        
    }
}