ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Scorecard_Decision__c.field-meta.xml
<CustomField>
    <fullName>Scorecard_Decision__c</fullName>
    <label>Scorecard Decision</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Who_will_repay_the_loan__c.field-meta.xml
<CustomField>
    <fullName>Who_will_repay_the_loan__c</fullName>
    <label>Who will repay the loan</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-borrower</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Additional_Document__c.field-meta.xml
<CustomField>
    <fullName>Additional_Document__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Additional Documents</description>
    <label>Additional Document</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/DocAuth_Passed__c.field-meta.xml
<CustomField>
    <fullName>DocAuth_Passed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Doc Auth Report Pass</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Seller&apos;s Passbook</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Bank Statement</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Cancel Cheque</fullName>
            </value>
            <value>
                <fullName>Driving Licence</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Voter Id</fullName>
            </value>
            <value>
                <fullName>Form 60</fullName>
            </value>
            <value>
                <fullName>Customer Image</fullName>
            </value>
            <value>
                <fullName>Aadhaar</fullName>
            </value>
            <value>
                <fullName>Vehicle Images</fullName>
            </value>
            <value>
                <fullName>RC Document</fullName>
            </value>
            <value>
                <fullName>SPR</fullName>
            </value>
            <value>
                <fullName>APR</fullName>
            </value>
            <value>
                <fullName>Electronic Bill</fullName>
                <label>Electricity Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Water Bill</fullName>
                <label>Water Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Vehicle Insurance Policy</fullName>
            </value>
            <value>
                <fullName>Vehicle Image</fullName>
            </value>
            <value>
                <fullName>Bank Statement</fullName>
            </value>
            <value>
                <fullName>Insurance Policy Doc</fullName>
            </value>
            <value>
                <fullName>Valuation Report</fullName>
            </value>
            <value>
                <fullName>Office FI</fullName>
            </value>
            <value>
                <fullName>Land Photo</fullName>
            </value>
            <value>
                <fullName>Patta Document</fullName>
            </value>
            <value>
                <fullName>Rent Agreement/Reciept</fullName>
            </value>
            <value>
                <fullName>Pension Document</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Engine Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Chassis Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Selfie with Vehicle-uploaded during verification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Golden_Source_Pass__c.field-meta.xml
<CustomField>
    <fullName>Golden_Source_Pass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Golden Source Pass</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/is_Active__c.field-meta.xml
<CustomField>
    <fullName>is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Is_Document_Eligible__c.field-meta.xml
<CustomField>
    <fullName>Is_Document_Eligible__c</fullName>
    <label>Is Document Eligible</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Is_Photocopy__c.field-meta.xml
<CustomField>
    <fullName>Is_Photocopy__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Photocopy?</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/KYC_DOB__c.field-meta.xml
<CustomField>
    <fullName>KYC_DOB__c</fullName>
    <label>KYC DOB</label>
    <type>Date</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Name_Mismatch_Pass__c.field-meta.xml
<CustomField>
    <fullName>Name_Mismatch_Pass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Name Mismatch Pass</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Name_Mismatch_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Name_Mismatch_Percentage__c</fullName>
    <label>Name Match Percentage</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Opportunity_Relation__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Relation__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Proof_of_Identity_POI__c.field-meta.xml
<CustomField>
    <fullName>Proof_of_Identity_POI__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Proof of Identity (POI)</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Selfie_report_Pass__c.field-meta.xml
<CustomField>
    <fullName>Selfie_report_Pass__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Selfie report Pass</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/CVO_Accepts_SPDC_Documents__c.field-meta.xml
<CustomField>
    <fullName>CVO_Accepts_SPDC_Documents__c</fullName>
    <label>CVO Accepts SPDC Documents</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Retry_Count__c/Retry_Count__c.object-meta.xml
<CustomObject>
    <label>Retry Count</label>
    <nameField>
        <displayFormat>Ret-{000000}</displayFormat>
        <label>Retry Count Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Retry Counts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Retry_Count__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Retry_Counts</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Retry_Count__c/fields/Count__c.field-meta.xml
<CustomField>
    <fullName>Count__c</fullName>
    <label>Count</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Retry_Count__c/fields/Loan_Application_Id__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application_Id__c</fullName>
    <label>Loan Application Id</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Retry_Count</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Retry_Count__c/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User Id</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Retry_Counts1</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/Maker_Id__c.field-meta.xml
<CustomField>
    <fullName>Maker_Id__c</fullName>
    <label>Maker Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/User_Id__c.field-meta.xml
<CustomField>
    <fullName>User_Id__c</fullName>
    <externalId>true</externalId>
    <label>User Id</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/classes/DocumentFileCntrlTest.cls
@IsTest
public class DocumentFileCntrlTest {
    @testSetup
    static void setup(){
        Profile p = [SELECT Id FROM Profile WHERE Name='IBL Business Executive'];
        User u = new User(Alias = 'standt2', Email='standarduser2@testorg.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,Maker_Id__c='12',IsActive = true,
                          TimeZoneSidKey='America/Los_Angeles',UserName='test12_userprod1234@indusbank.com',MobilePhone = '9089078967');
        insert u;
        System.runAs(u) 
        {
            //create Oppty records
            List<Opportunity> opptyList = new List<Opportunity>();
            Opportunity opp = TestDataUtility.createTestOpportunity(false);
            opp.Name = 'VDR Test';
            opp.StageName='Post Sanction Checks and Documentation';
            opp.Product_Type__c='Passenger Vehicles';
            opp.CVO_Accepts_SPDC_Documents__c = 'No';
            opptyList.add(opp);
            if(Schema.sObjectType.Opportunity.isCreateable()){
                insert opptyList;
            }
            List<Applicant__c> applicantList = new List<Applicant__c>();
            Applicant__c applicant1 = TestDataUtility.createTestApplicatnt1(false);
            applicant1.Opportunity__c = opp.Id;
            applicant1.Who_will_repay_the_loan__c = 'Borrower';
            applicant1.Scorecard_Decision__c = 'Light Red';
            applicantList.add(applicant1);
            if(Schema.sObjectType.Applicant__c.isCreateable()){
                insert applicantList;
            }
            // List<Documents__c> docList = new List<Documents__c>();
            Documents__c doc1 = TestDataUtility.createTestDocumentITR(false, applicant1, opp);
            doc1.Opportunity_Relation__c = opp.Id;
            doc1.Is_Document_Eligible__c='No';
            doc1.Is_active__c = true;
            doc1.Document_Type__c = 'Chassis Number uploaded during verification';
            doc1.Additional_Document__c = true;
            // docList.add(doc1);
            if(Schema.sObjectType.Documents__c.isCreateable()){
                insert doc1;
            }
            ContentVersion contentVersion1 = new ContentVersion(
                Title          = 'testfname',
                PathOnClient   = 'Pic.jpg',
                VersionData    = Blob.valueOf('Test Content'),
                IsMajorVersion = true);
            insert contentVersion1; 
            List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
            
            //create ContentDocumentLink  record
            ContentDocumentLink cdl = new ContentDocumentLink();
            cdl.LinkedEntityId = doc1.Id;
            cdl.ContentDocumentId = documents[0].Id;
            cdl.ShareType = 'V';
            cdl.Visibility = 'AllUsers';
            insert cdl;

            Documents__c doc2 = new Documents__c( Applicant__c =applicantList[0].id,
                                                     Name= 'Customer Image',
                                                     Opportunity_Relation__c=opp.Id,
                                                     DocAuth_Passed__c = true,
                                                     KYC_DOB__c= Date.newInstance(1991, 06, 05 ),
                                                     Selfie_report_Pass__c = true,
                                                     Golden_Source_Pass__c = true,
                                                     Proof_of_Identity_POI__c = true,
                                                     Name_Mismatch_Percentage__c = 00,
                                                     Is_Photocopy__c=true,
                                                     Document_Type__c='Customer Image',
                                                     Name_Mismatch_Pass__c = true,
                                                    is_Active__c=true);
            insert doc2;
            
            ContentVersion contentVersion2 = new ContentVersion(
                Title          = 'testname',
                PathOnClient   = 'Pic.jpg',
                VersionData    = Blob.valueOf('Test Content 2'),
                IsMajorVersion = true);
            insert contentVersion2; 
            List<ContentDocument> documentss = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
            
            //create ContentDocumentLink  record
            ContentDocumentLink cdl2 = new ContentDocumentLink();
            cdl2.LinkedEntityId = doc2.Id;
            cdl2.ContentDocumentId = documentss[0].Id;
            cdl2.ShareType = 'V';
            cdl2.Visibility = 'AllUsers';
            insert cdl2;


           //Create Retry_Count__c records
           List<Retry_Count__c> rtCountList = new List<Retry_Count__c>();
           Retry_Count__c retryCount1 = new Retry_Count__c();
           retryCount1.Service_Name__c = System.Label.CMU_Front;
           retryCount1.Count__c = 0;
           retryCount1.Loan_Application_Id__c = opp.Id;
           retryCount1.Applicant__c=applicantList[0].id;
           retryCount1.User_Id__c = u.Id;
           rtCountList.add(retryCount1);

           Retry_Count__c retryCount2 = new Retry_Count__c();
           retryCount2.Service_Name__c = System.Label.CMU_Back;
           retryCount2.Count__c = 0;
           retryCount2.Loan_Application_Id__c = opp.Id;
           retryCount2.User_Id__c = u.Id;
           retryCount2.Applicant__c=applicantList[0].id;
           rtCountList.add(retryCount2);
           if(Schema.sObjectType.Retry_Count__c.isCreateable()){
               insert rtCountList;
           }
           

        }
    }
    @IsTest
    public static void test_getRelatedFile(){
        Test.startTest();
        User u = [SELECT Id,usertype FROM User WHERE UserName='test12_userprod1234@indusbank.com' AND IsActive = true LIMIT 1]; 
        System.runAs(u) 
        {
            try{
                Documents__c docId =[Select Id From Documents__c LIMIT 1];
                Documents__c docId2 =[Select Id From Documents__c WHERE Document_Type__c='Chassis Number uploaded during verification' LIMIT 1];
                String addnlDataStringNeg = DocumentFileCntrl.getRelatedFile(docId.Id);
                String getImageFile = DocumentFileCntrl.getImageFile(docId2.Id);
                DocumentFileCntrl.getPOIdetails(docId2.Id);
                //System.assertEquals('{"docDetails":[]}', addnlDataStringNeg);
            } catch(Exception ex){
                System.assert(ex.getMessage().contains('Implementation restriction'));
            }
        }
        Test.stopTest();
    }
    @IsTest
    public static void test_getRelatedDocumentDetails(){
        Test.startTest();
        User u = [SELECT Id,usertype FROM User WHERE UserName='test12_userprod1234@indusbank.com' AND IsActive = true LIMIT 1]; 
        System.runAs(u) 
        {
            try{
                Documents__c docId =[Select Id From Documents__c LIMIT 1];
                DocumentFileCntrl.DocumentDataWrapper wrapperObj = new DocumentFileCntrl.DocumentDataWrapper();
                wrapperObj = DocumentFileCntrl.getRelatedDocumentDetails(docId.Id);
            } catch(Exception ex){
                System.assert(ex.getMessage().contains('Implementation restriction'));
            }
        }
        Test.stopTest();
    }
    @IsTest
    public static void test_retryCountIncrease(){
        Test.startTest();
        User u = [SELECT Id,usertype FROM User WHERE UserName='test12_userprod1234@indusbank.com' AND IsActive = true LIMIT 1]; 
        System.runAs(u) 
        {
            try{
                Documents__c docRec =[Select Id,Opportunity_Relation__c From Documents__c LIMIT 1];
                Boolean haveRetryAttemt = DocumentFileCntrl.retryCountIncrease(docRec.Opportunity_Relation__c, System.Label.CMU_Front);
            } catch(Exception ex){
                System.assert(ex.getMessage().contains('Implementation restriction'));
            }
        }
        Test.stopTest();
    }
    @IsTest
    public static void test_retryCountIncrease_Negative(){
        Test.startTest();
        User u = [SELECT Id,usertype FROM User WHERE UserName='test12_userprod1234@indusbank.com' AND IsActive = true LIMIT 1]; 
        System.runAs(u) 
        {
            try{
                Documents__c docRec =[Select Id,Opportunity_Relation__c From Documents__c LIMIT 1];
                Boolean haveRetryAttemt = DocumentFileCntrl.retryCountIncrease(docRec.Opportunity_Relation__c, 'Test');
            } catch(Exception ex){
                System.assert(ex.getMessage().contains('Implementation restriction'));
            }
        }
        Test.stopTest();
    }
    @IsTest
    public static void test_getImageFile(){
        Test.startTest();
        User u = [SELECT Id,usertype FROM User WHERE UserName='test12_userprod1234@indusbank.com' AND IsActive = true LIMIT 1]; 
        System.runAs(u) 
        {
            try{
                Documents__c docRec =[Select Id,Opportunity_Relation__c From Documents__c Where Name != 'Customer Image' LIMIT 1];
                DocumentFileCntrl.getImageFile(docRec.Id);
            } catch(Exception ex){
                System.assert(ex.getMessage().contains('Implementation restriction'));
            }
        }
        Test.stopTest();
    }
    @IsTest
    public static void test_getPOIdetails(){
        Test.startTest();
        User u = [SELECT Id,usertype FROM User WHERE UserName='test12_userprod1234@indusbank.com' AND IsActive = true LIMIT 1]; 
        System.runAs(u) 
        {
            try{
                Documents__c docRec =[Select Id,Opportunity_Relation__c From Documents__c Where Applicant__c != null LIMIT 1];
                docRec.Proof_of_Identity_POI__c = true;
                update docRec;
                DocumentFileCntrl.getPOIdetails(docRec.Id);
            } catch(Exception ex){
                System.assert(ex.getMessage().contains('Implementation restriction'));
            }
        }
        Test.stopTest();
    }

    @IsTest
    public static void test_deleteDocumentRecord(){
        Test.startTest();
        User u = [SELECT Id,usertype FROM User WHERE UserName='test12_userprod1234@indusbank.com' AND IsActive = true LIMIT 1]; 
        System.runAs(u) 
        {
            try{
                Documents__c docId =[Select Id From Documents__c LIMIt 1];
                ContentVersion uploadedImage = [SELECT Id,ContentDocumentId FROM ContentVersion LIMIT 1];
                List<String> docList = new List<String>();
                docList.add(uploadedImage.ContentDocumentId);
                DocumentFileCntrl.deleteDocumentRecord(docId.Id, JSON.serialize(docList));
            } catch(Exception ex){
                System.assert(ex.getMessage().contains('Implementation restriction'));
            }
        }
        Test.stopTest();
    }
}