ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-borrower</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Lead_Number__c.field-meta.xml
<CustomField>
    <fullName>Lead_Number__c</fullName>
    <formula>Opportunity__r.Lead_number__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Lead Id</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>applicant_Type__c</fullName>
    <formula>TEXT(Applicant__r.Applicant_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Type</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/CMU_Accept_Reject__c.field-meta.xml
<CustomField>
    <fullName>CMU_Accept_Reject__c</fullName>
    <label>CMU Accept/Reject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/CMU_Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>CMU_Rejection_Reason__c</fullName>
    <label>CMU Rejection Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>CMU_Accept_Reject__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Incorrect fields</fullName>
            </value>
            <value>
                <fullName>Documents reject or Customer Photo reject</fullName>
            </value>
            <value>
                <fullName>Incorrect document</fullName>
            </value>
            <value>
                <fullName>Signature missing</fullName>
            </value>
            <value>
                <fullName>Date of birth not available</fullName>
            </value>
            <value>
                <fullName>Form 60 not filled properly</fullName>
            </value>
            <value>
                <fullName>Form 60 image not clear</fullName>
            </value>
            <value>
                <fullName>Form 60 details not tallying with data points</fullName>
            </value>
            <value>
                <fullName>Blank form 60 attached</fullName>
            </value>
            <value>
                <fullName>PAN acknowledgement number incorrect / incomplete in Form 60</fullName>
            </value>
            <value>
                <fullName>Name of the applicant / customer does not match as per NSDL records</fullName>
            </value>
            <value>
                <fullName>Relationship not tagged properly</fullName>
            </value>
            <value>
                <fullName>Shareholding pattern not tagged properly</fullName>
            </value>
            <value>
                <fullName>Entity type mismatch</fullName>
            </value>
            <value>
                <fullName>Document number mismatch for mandatory documents</fullName>
            </value>
            <value>
                <fullName>DOI incorrect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Seller&apos;s Passbook</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Bank Statement</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Cancel Cheque</fullName>
            </value>
            <value>
                <fullName>Driving Licence</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Voter Id</fullName>
            </value>
            <value>
                <fullName>Form 60</fullName>
            </value>
            <value>
                <fullName>Customer Image</fullName>
            </value>
            <value>
                <fullName>Aadhaar</fullName>
            </value>
            <value>
                <fullName>Vehicle Images</fullName>
            </value>
            <value>
                <fullName>RC Document</fullName>
            </value>
            <value>
                <fullName>SPR</fullName>
            </value>
            <value>
                <fullName>APR</fullName>
            </value>
            <value>
                <fullName>Electronic Bill</fullName>
                <label>Electricity Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Water Bill</fullName>
                <label>Water Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Vehicle Insurance Policy</fullName>
            </value>
            <value>
                <fullName>Vehicle Image</fullName>
            </value>
            <value>
                <fullName>Bank Statement</fullName>
            </value>
            <value>
                <fullName>Insurance Policy Doc</fullName>
            </value>
            <value>
                <fullName>Valuation Report</fullName>
            </value>
            <value>
                <fullName>Office FI</fullName>
            </value>
            <value>
                <fullName>Land Photo</fullName>
            </value>
            <value>
                <fullName>Patta Document</fullName>
            </value>
            <value>
                <fullName>Rent Agreement/Reciept</fullName>
            </value>
            <value>
                <fullName>Pension Document</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Engine Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Chassis Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Selfie with Vehicle-uploaded during verification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/IHM__c.field-meta.xml
<CustomField>
    <fullName>IHM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>IHM</label>
    <referenceTo>IHM__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/is_Active__c.field-meta.xml
<CustomField>
    <fullName>is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Opportunity_Relation__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Relation__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Rejection_Fields__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Fields__c</fullName>
    <label>Rejection Fields</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>CMU_Accept_Reject__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Kyc_Fields</valueSetName>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/Final_Term__c.object-meta.xml
<CustomObject>
    <description>To store Final term module data.</description>
    <label>Final Term</label>
    <nameField>
        <displayFormat>FT-{000000}</displayFormat>
        <label>Final Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/is_Active__c.field-meta.xml
<CustomField>
    <fullName>is_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is Active</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan_Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Final_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/IHM__c/IHM__c.object-meta.xml
<CustomObject>
    <label>IHM</label>
    <nameField>
        <label>IHM Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>IHMs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/IHM__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>IHMs</relationshipLabel>
    <relationshipName>IHMs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/IHM__c/fields/Total_amount_to_be_paid_by_customer_G__c.field-meta.xml
<CustomField>
    <fullName>Total_amount_to_be_paid_by_customer_G__c</fullName>
    <label>Total amount to be paid by customer (G)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Funding_on_ORP__c.field-meta.xml
<CustomField>
    <fullName>Funding_on_ORP__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Funding on ORP</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/IModuleId__c.field-meta.xml
<CustomField>
    <fullName>IModuleId__c</fullName>
    <label>IModuleId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Lead_number__c.field-meta.xml
<CustomField>
    <fullName>Lead_number__c</fullName>
    <label>Lead Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Payment_Request_Generation_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Request_Generation_Date__c</fullName>
    <label>Payment Request Generation Date</label>
    <type>DateTime</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/RTO_Road_Tax__c.field-meta.xml
<CustomField>
    <fullName>RTO_Road_Tax__c</fullName>
    <label>RTO Road Tax</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Sanction_Date__c.field-meta.xml
<CustomField>
    <fullName>Sanction_Date__c</fullName>
    <label>Sanction Date</label>
    <type>Date</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/Maker_Id__c.field-meta.xml
<CustomField>
    <fullName>Maker_Id__c</fullName>
    <label>Maker Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/IND_ReverseStatusCalloutQueueableTest.cls
/*------------------------------------------------------------
Author:        Vishal Gadhave
Company:       Nanostuffs Technologies
Description:   Test class for IND_ReverseStatusCalloutQueueable.
Inputs:        None 
Test Classes:    
History
Date            Author              Comments
-------------------------------------------------------------
4-11-2022      Vishal               Created
------------------------------------------------------------*/
@isTest
public class IND_ReverseStatusCalloutQueueableTest {
	
    @testSetup
    public static void setupData(){
        Profile p = [SELECT Id FROM Profile WHERE Name='IBL Business Executive'];
        User u = new User(Alias = 'standt2', email='standarduser2@testorg.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,Maker_Id__c='12',IsActive = true,
                          timezonesidkey='america/los_angeles',username='vishal@indusbank.com',MobilePhone = '9089078967');
        insert u;
        System.runAs(u)
        {
            Opportunity opp = TestDataUtility.createTestOpportunity(false);
            opp.RTO_Road_Tax__c = 13;
            opp.Vehicle_Type__c ='New';
            opp.Funding_on_ORP__c = true;
            opp.IModuleId__c = 'DA0012573';
            if(Schema.sObjectType.Opportunity.isCreateable())
                insert opp;
                
            IHM__c ihmObj = new IHM__c();
            ihmObj.Loan_Application__c = opp.Id;
            ihmObj.Total_amount_to_be_paid_by_customer_G__c = 2000;
            
            insert ihmObj;
            Applicant__c objApplicant = new Applicant__c();
            objApplicant.Opportunity__c = opp.Id;
            objApplicant.Applicant_Type__c = 'Borrower';
            objApplicant.Contact_number__c = '1234567890';
            if(Schema.sObjectType.Applicant__c.isCreateable())
                insert objApplicant;
            
            Documents__c objDocument = new Documents__c();
            objDocument.Opportunity_Relation__c = opp.Id;
            objDocument.name = 'DocName';
            objDocument.Document_Type__c = 'Insurance Policy Doc';
            objDocument.is_Active__c = true;
            objDocument.Applicant__c = objApplicant.Id;
            if(Schema.sObjectType.Documents__c.isCreateable())
                insert objDocument;
        }
    }
    @isTest
    public static void doReverseStatusCallout_Test(){
        User u = [SELECT Id,usertype FROM User WHERE username='vishal@indusbank.com' AND IsActive = true LIMIT 1]; 
        System.runAs(u) 
        {
            Test.startTest();
            try{
                String loanAppId = [Select Id From Opportunity LIMIT 1].Id;
                String status = 'SANCTIONED';
                String code = '230003';
                String Imod = 'DA0012573';
                Test.setMock(HttpCalloutMock.class, new ReverseStatusCalloutTestMock());
                Id pactLmsJobId = System.enqueueJob(new IND_ReverseStatusCalloutQueueable(loanAppId,status,code));
                List<Opportunity> opps = [Select Id,Lead_number__c from Opportunity where IModuleId__c=:Imod WITH SECURITY_ENFORCED Limit 1];
                Test.stopTest();
                //Opportunity loanAppRec = [Select Id, Payment_Request_Generation_Date__c From Opportunity Where Id =:loanAppId LIMIT 1];
                System.assertNotEquals(null, pactLmsJobId);                
            }catch(Exception e){
                System.debug('Exception ' + e.getMessage());
            }
        }        
    }
    
    @isTest
    public static void doReverseStatusCallout_Negative(){
        User u = [SELECT Id,usertype FROM User WHERE username='vishal@indusbank.com' AND IsActive = true LIMIT 1]; 
        System.runAs(u) 
        {	
            try{
                Test.startTest();
                String loanAppId = [Select Id From Opportunity LIMIT 1].Id;
                String status = 'SANCTIONED';
                String code = '230003';
                Test.setMock(HttpCalloutMock.class, new ReverseStatusCalloutFailureTestMock());
                Id pactLmsJobId = System.enqueueJob(new IND_ReverseStatusCalloutQueueable(loanAppId,status,code));
                Test.stopTest();
                Opportunity loanAppRec = [Select Id, Payment_Request_Generation_Date__c From Opportunity Where Id =:loanAppId LIMIT 1];
                System.assertNotEquals(null, pactLmsJobId);
                System.assertNotEquals(system.now(), loanAppRec.Payment_Request_Generation_Date__c);
            } catch(Exception ex){
                System.assertNotEquals(null, ex.getMessage());
            }
        }
    }
    
    @isTest
    public static void IND_ReverseStatusRequestMethod(){
        String loanAppId = [Select Id From Opportunity LIMIT 1].Id;
        Opportunity oppObj = [SELECT ID from Opportunity LIMIT 1];
        oppObj.Sanction_Date__c = Date.newInstance(2024, 08, 20);
                update oppObj;
                Final_Term__c fObj = new Final_Term__c();
                fObj.Loan_Application__c =oppObj.Id;
                insert fObj;
        String status = 'SANCTIONED';
        String code = '230003';
        
        Applicant__c objApplicant = new Applicant__c();
        objApplicant.Opportunity__c = loanAppId;
        objApplicant.Applicant_Type__c = 'Borrower';
        objApplicant.Contact_number__c = '1234567890';
        
        if(Schema.sObjectType.Applicant__c.isCreateable())
            insert objApplicant;
        
        Documents__c objDocument = new Documents__c();
        objDocument.Opportunity_Relation__c = loanAppId;
        objDocument.name = 'DocName';
        objDocument.CMU_Accept_Reject__c = 'Reject';
        objDocument.CMU_Rejection_Reason__c ='Incorrect fields';
        objDocument.Rejection_Fields__c ='PAN No.';
        objDocument.Document_Type__c = 'Insurance Policy Doc';
        objDocument.is_Active__c = true;
        objDocument.Applicant__c = objApplicant.Id;
        if(Schema.sObjectType.Documents__c.isCreateable())
            insert objDocument;
        
        Test.startTest();
            try{
                IND_ReverseStatusRequest indr = new IND_ReverseStatusRequest(loanAppId,status,code);
            }catch(Exception e){
                System.debug('Exception ' + e.getMessage());
            }
        Test.stopTest();
    }
    
    @isTest
    public static void IND_ReverseStatusServiceTestMethod(){
        String loanAppId = [Select Id From Opportunity LIMIT 1].Id;
        String status = 'SANCTIONED';
        String code = '230003';
        Test.startTest();
        IND_ReverseStatusService.getReverseStatusCallOutRequest(loanAppId,status,code);
        Test.stopTest();
    }
    
    @isTest
    public static void IND_ReverseStatusServiceTestMethod2(){
         Test.startTest();
        try{
            String loanAppId = [Select Id From Account LIMIT 1].Id;
            String status = 'SANCTIONED';
            String code = '230003';
            
            IND_ReverseStatusService.getReverseStatusCallOutRequest(loanAppId,status,code);
        }catch(Exception e){
            System.debug('Exception ' + e.getMessage());
        }
        Test.stopTest();
    }
    
    @isTest
    public static void IND_ReverceStatusResponseTest(){
         Test.startTest();
        try{
            IND_ReverceStatusResponse.response resp = new IND_ReverceStatusResponse.response();
            IND_ReverceStatusResponse.content cont = new IND_ReverceStatusResponse.content();
            IND_ReverceStatusResponse.error_message err = new IND_ReverceStatusResponse.error_message();
            list<IND_ReverceStatusResponse.content> ContentOfAPI = new list<IND_ReverceStatusResponse.content>();
            resp.status = 'SUCCESS';
            resp.respDesc = 'Test';
            resp.content = ContentOfAPI;
            cont.enquiry_id = 'NX-07112022-980609455';
            cont.error_message = null;
            cont.message = 'Application Status of DA0012569 updated successfully';
            cont.status = 'success';
            cont.updated_status = '340002';
            cont.success = 'True';
        }catch(Exception e){
            System.debug('Exception ' + e.getMessage());
        }
        Test.stopTest();
    }
    @isTest
    public static void doReverseStatusCallout_TestNew(){
        User u = [SELECT Id,usertype FROM User WHERE username='vishal@indusbank.com' AND IsActive = true LIMIT 1]; 
        System.runAs(u) 
        {
            Test.startTest();
            try{
                Opportunity loanAppId = [Select Id From Opportunity LIMIT 1];
                loanAppId.LeadSource = System.label.Mahindra_Custom_Lead_API_Value;
        		loanAppId.Sanction_Date__c = Date.newInstance(2024, 08, 20);
                update loanAppId;
                Final_Term__c fObj = new Final_Term__c();
                fObj.Loan_Application__c =loanAppId.Id;
                insert fObj;
                String status = 'SANCTIONED';
                String code = '230003';
                String Imod = 'DA0012573';
                Test.setMock(HttpCalloutMock.class, new ReverseStatusCalloutTestMock());
                Id pactLmsJobId = System.enqueueJob(new IND_ReverseStatusCalloutQueueable(loanAppId.Id,status,code));
                List<Opportunity> opps = [Select Id,Lead_number__c from Opportunity where IModuleId__c=:Imod WITH SECURITY_ENFORCED Limit 1];
                Test.stopTest();
                //Opportunity loanAppRec = [Select Id, Payment_Request_Generation_Date__c From Opportunity Where Id =:loanAppId LIMIT 1];
                System.assertNotEquals(null, pactLmsJobId);                
            }catch(Exception e){
                System.debug('Exception ' + e.getMessage());
            }
        }        
    }
}