ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-borrower</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/Deal_Number__c.object-meta.xml
<CustomObject>
    <description>The custom object created for Deal Number generation</description>
    <label>Deal Number</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Deal Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deal Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Deal_Number__c/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <formula>DNField1__c  +  DNField2__c  +  ProductCode__c  +  DNField3__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Deal Number</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Deal_Number__c.field-meta.xml
<CustomField>
    <fullName>Deal_Number__c</fullName>
    <description>IndusInd deal number</description>
    <label>Deal Number</label>
    <length>16</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/IND_WeightedIRRService_Test.cls
/*------------------------------------------------------------
Author:        Prashant Dixit
Description:   This Test class is used for code coverage of IND_WeightedIRRService, IND_WeightedIRRRequest & IND_WeightedIRRResponse     
History
Date            Author              Comments
-------------------------------------------------------------
28-12-2023      Prashant Dixit      Created
------------------------------------------------------------*/
@isTest
public class IND_WeightedIRRService_Test {
    @isTest
    public static void getWeightedIRRRequestTest(){ 
        Opportunity opp = new Opportunity(StageName = 'Qualification',CloseDate = Date.newInstance(2021, 1, 11),Name = 'testone', Deal_Number__c = 'TUT06226H', Vehicle_Type__c = 'New');
        insert opp;
        
        Applicant__c app = new Applicant__c(Opportunity__c = opp.Id, Applicant_Type__c = 'Co-borrower');
        insert app;
        
        Test.startTest();
        IND_WeightedIRRRequest indWeightRRReq = IND_WeightedIRRService.getWeightedIRRRequest(app.Id, opp.Id);
        Test.stopTest();
    }
    @isTest
    public static void getWeightedIRRRequestTest1(){
        Opportunity opp = new Opportunity(StageName = 'Qualification',CloseDate = Date.newInstance(2021, 1, 11),Name = 'testone', Deal_Number__c = 'TUT06226H', Vehicle_Type__c = 'New');
        insert opp;
        
        Applicant__c app = new Applicant__c(Opportunity__c = opp.Id, Applicant_Type__c = 'Co-borrower');
        insert app;
        
        Test.startTest();
        try{
            IND_WeightedIRRRequest indWeightRRReq1 = IND_WeightedIRRService.getWeightedIRRRequest(null, '');
        }catch(Exception ex){
            System.debug('Exception is -> '+ex.getMessage());
        }
        Test.stopTest();
    }
    
    @isTest
    public static void weightedIRRResponseTest() {
        ParentAPIResponse parentApiResponse = new ParentAPIResponse();
        IND_WeightedIRRResponse weightedIRRResponse = new IND_WeightedIRRResponse();
        weightedIRRResponse.response = new IND_WeightedIRRResponse.Response();
        weightedIRRResponse.response.status = 'Success';
        weightedIRRResponse.response.respDesc = 'Test Description';

        IND_WeightedIRRResponse.Content content = new IND_WeightedIRRResponse.Content();
        String str = content.Weighted_IRR;
        weightedIRRResponse.response.content = new List<IND_WeightedIRRResponse.Content>{content};
    }
   
    @isTest
    public static void getHttpRequestHeadersTest() {
       Test.startTest();
        IND_WeightedIRRRequest weightedIRRReq = new IND_WeightedIRRRequest('test', null);
        Map<String, String> mapOfGetHeaderRec = weightedIRRReq.getHttpRequestHeaders();
       Test.stopTest();
    }
}