ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/CIBIL_Details__c/CIBIL_Details__c.object-meta.xml
<CustomObject>
    <label>CIBIL Details</label>
    <nameField>
        <displayFormat>CIBIL - {000}</displayFormat>
        <label>CIBIL Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CIBIL Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/CIBIL_Details__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <description>This field represents the M-D relation with Applicant object.</description>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>CIBIL_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdLWC - Copy/force-app/main/default/classes/IND_CIBILServiceDSA.cls
public class IND_CIBILServiceDSA {
   
    public static IND_CIBILRequestDSA getcibilCallout(Applicant__c app, List<Documents__c> docs, String loanAppId, List<CIBIL_Details__c> cibilDetails, String customer_Code){
        try
        {
            IND_CIBILRequestDSA request = new IND_CIBILRequestDSA(app,docs,loanAppId,cibilDetails, customer_Code);            
            return request;
        }
        catch(Exception ex){
            ErrorLoggerUtil.logErrorEvent('IND_CIBILService', 'getcibilCallout', System.Label.Apex, ex,loanAppId);
            throw new IND_Exception(ex.getMessage());          
        }  
    }

}