ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>Applicant_Type__c</fullName>
    <label>Applicant Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Borrower</fullName>
            </value>
            <value>
                <fullName>Co-borrower</fullName>
            </value>
            <value>
                <fullName>Guarantor</fullName>
            </value>
            <value>
                <fullName>Beneficiary</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Applicants</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Aadhar_Source__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Source__c</fullName>
    <label>Aadhar Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTP</fullName>
            </value>
            <value>
                <fullName>Biometric</fullName>
            </value>
            <value>
                <fullName>Scan and Upload</fullName>
            </value>
            <value>
                <fullName>ScanAadhar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/applicant_Type__c.field-meta.xml
<CustomField>
    <fullName>applicant_Type__c</fullName>
    <formula>TEXT(Applicant__r.Applicant_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Applicant Type</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Document_Side__c.field-meta.xml
<CustomField>
    <fullName>Document_Side__c</fullName>
    <label>Document Side</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Front</fullName>
            </value>
            <value>
                <fullName>Back</fullName>
            </value>
            <value>
                <fullName>Selfie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Seller&apos;s Passbook</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Bank Statement</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Cancel Cheque</fullName>
            </value>
            <value>
                <fullName>Driving Licence</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Voter Id</fullName>
            </value>
            <value>
                <fullName>Form 60</fullName>
            </value>
            <value>
                <fullName>Customer Image</fullName>
            </value>
            <value>
                <fullName>Aadhaar</fullName>
            </value>
            <value>
                <fullName>Vehicle Images</fullName>
            </value>
            <value>
                <fullName>RC Document</fullName>
            </value>
            <value>
                <fullName>SPR</fullName>
            </value>
            <value>
                <fullName>APR</fullName>
            </value>
            <value>
                <fullName>Electronic Bill</fullName>
                <label>Electricity Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Water Bill</fullName>
                <label>Water Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Vehicle Insurance Policy</fullName>
            </value>
            <value>
                <fullName>Vehicle Image</fullName>
            </value>
            <value>
                <fullName>Bank Statement</fullName>
            </value>
            <value>
                <fullName>Insurance Policy Doc</fullName>
            </value>
            <value>
                <fullName>Valuation Report</fullName>
            </value>
            <value>
                <fullName>Office FI</fullName>
            </value>
            <value>
                <fullName>Land Photo</fullName>
            </value>
            <value>
                <fullName>Patta Document</fullName>
            </value>
            <value>
                <fullName>Rent Agreement/Reciept</fullName>
            </value>
            <value>
                <fullName>Pension Document</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Engine Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Chassis Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Selfie with Vehicle-uploaded during verification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Income_Details__c.field-meta.xml
<CustomField>
    <fullName>Income_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Income Details</label>
    <referenceTo>Income_Details__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Opportunity_Relation__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Relation__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/Final_Term__c.object-meta.xml
<CustomObject>
    <description>To store Final term module data.</description>
    <label>Final Term</label>
    <nameField>
        <displayFormat>FT-{000000}</displayFormat>
        <label>Final Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/CRM_IRR__c.field-meta.xml
<CustomField>
    <fullName>CRM_IRR__c</fullName>
    <label>Offer engine CRM IRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Holiday_period__c.field-meta.xml
<CustomField>
    <fullName>Holiday_period__c</fullName>
    <label>Holiday period</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
            </value>
            <value>
                <fullName>30</fullName>
            </value>
            <value>
                <fullName>60</fullName>
            </value>
            <value>
                <fullName>90</fullName>
            </value>
            <value>
                <fullName>120</fullName>
            </value>
            <value>
                <fullName>150</fullName>
            </value>
            <value>
                <fullName>180</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan_Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Final_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Income_Details__c/Income_Details__c.object-meta.xml
<CustomObject>
    <label>Income Details</label>
    <nameField>
        <label>Income Details Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Income Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Income_Details__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Income_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Income_Details__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ITR-V</fullName>
            </value>
            <value>
                <fullName>ITR-Forms</fullName>
            </value>
            <value>
                <fullName>Form26As</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/InsuranceDetails__c/InsuranceDetails__c.object-meta.xml
<CustomObject>
    <label>Insurance Details</label>
    <nameField>
        <label>Insurance Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Insurance Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/InsuranceDetails__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Insurance_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/InsuranceDetails__c/fields/Funded_Non_funded__c.field-meta.xml
<CustomField>
    <fullName>Funded_Non_funded__c</fullName>
    <label>Funded/Non funded</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Funded</fullName>
            </value>
            <value>
                <fullName>Non-Funded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/InsuranceDetails__c/fields/Funded_Premium__c.field-meta.xml
<CustomField>
    <fullName>Funded_Premium__c</fullName>
    <label>Funded Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/InsuranceDetails__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Insurance_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Contact_number__c.field-meta.xml
<CustomField>
    <fullName>Contact_number__c</fullName>
    <label>Contact number</label>
    <type>Phone</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/CRM_IRR__c.field-meta.xml
<CustomField>
    <fullName>CRM_IRR__c</fullName>
    <label>CRM IRR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/Vehicle_Detail__c.object-meta.xml
<CustomObject>
    <label>Vehicle Detail</label>
    <nameField>
        <displayFormat>VD-{00000}</displayFormat>
        <label>Vehicle Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Funded_Premium__c.field-meta.xml
<CustomField>
    <fullName>Funded_Premium__c</fullName>
    <label>Funded Premium</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <description>Vehicle Insurance and Vehicle Valuation data</description>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Vehicle_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/classes/ind_ApplicationFormSigningControllerTest.cls
@isTest
public class ind_ApplicationFormSigningControllerTest {
    @isTest
    public static void getloanappidTest(){
                Opportunity opks1 = new Opportunity();
                opks1.StageName = 'Qualification';
                opks1.CloseDate = Date.newInstance(2021, 1, 11);
                opks1.Name = 'testone';
                insert opks1;
                
                Applicant__c apks1 = new Applicant__c();
                apks1.Opportunity__c = opks1.Id;
                apks1.Contact_number__c = '9743514830';
                apks1.Applicant_Type__c = 'Borrower';
                insert apks1;
        
                Test.startTest();
                       ind_ApplicationFormSigningController.getloanappid(apks1.Id);
                Test.stopTest();
    }
    
    @isTest
    public static void getInsurenDetailsTest(){
        
                Opportunity opks1 = new Opportunity();
                opks1.StageName = 'Qualification';
                opks1.CloseDate = Date.newInstance(2021, 1, 11);
                opks1.Name = 'testone';
                insert opks1;
                
                Applicant__c apks1 = new Applicant__c();
                apks1.Opportunity__c = opks1.Id;
                apks1.Contact_number__c = '9743514830';
                apks1.Applicant_Type__c = 'Borrower';
                insert apks1;
        
                InsuranceDetails__c insuDetail = new InsuranceDetails__c();
                insuDetail.Applicant__c = apks1.id;
                insuDetail.Funded_Premium__c=400.00;
                insuDetail.Loan_Application__c = opks1.id;
           //     insuDetail.Funded_Non_funded__c = 'Funded';
           //     insuDetail.Name = 'MOTOR';
                insert insuDetail;
        
                Test.startTest();
                      ind_ApplicationFormSigningController.getInsurenDetails(apks1.id);
                Test.stopTest();
    }
    
    @isTest
    public static void getKYCDetailsTest(){
        
                Opportunity opks1 = new Opportunity();
                opks1.StageName = 'Qualification';
                opks1.CloseDate = Date.newInstance(2021, 1, 11);
                opks1.Name = 'testone';
                insert opks1;
                
                Applicant__c apks1 = new Applicant__c();
                apks1.Opportunity__c = opks1.Id;
                apks1.Contact_number__c = '9743514830';
                apks1.Applicant_Type__c = 'Borrower';
                insert apks1;
        
                 Documents__c dfks1 = new Documents__c();
                 dfks1.Applicant__c = apks1.Id;
                 dfks1.Opportunity_Relation__c = opks1.Id;
                 dfks1.Document_Type__c = 'Customer Image';
                 dfks1.Document_Side__c ='Back';
                 dfks1.Aadhar_Source__c = 'ScanAadhar';
                 insert dfks1;
        
                 Test.startTest();
                       ind_ApplicationFormSigningController.getKYCDetails(apks1.Id);
                 Test.stopTest();
    }
    
    @isTest
    public static void getIncomeDetailsTest(){
        
        Opportunity opp1 = TestDataUtility.createTestOpportunity(false);
        insert opp1;
        
        Applicant__c app1 = TestDataUtility.createTestApplicant(false);
        app1.Opportunity__c= opp1.Id;
        app1.Applicant_Type__c = System.Label.Borrower;
        insert app1;
        
        Income_Details__c inc1 = TestDataUtility.createTestIncomeDetails(false);
        inc1.Applicant__c = app1.id;
        insert inc1;
        
        Test.startTest();
             ind_ApplicationFormSigningController.getIncomeDetails(app1.id);
        Test.stopTest();
    }
    
    @isTest
    public static void getFinalTermTest(){
        
        Opportunity opp1 = TestDataUtility.createTestOpportunity(false);
        insert opp1;
        
        Applicant__c app1 = TestDataUtility.createTestApplicant(false);
        app1.Opportunity__c= opp1.Id;
        app1.Applicant_Type__c = System.Label.Borrower;
        insert app1;
        
        Final_Term__c ftv1 = new Final_Term__c();
        ftv1.CRM_IRR__c = 120;
        ftv1.Loan_Application__c = opp1.Id;
        ftv1.Holiday_period__c='30';
        ftv1.EMI_Amount__c= 10000;
        insert ftv1;
        
        Test.startTest();
             ind_ApplicationFormSigningController.getFinalTerm(app1.Id);
        Test.stopTest();
    }
    
    @isTest
    public static void getInsurenceDetailsTest(){
        Opportunity opp1 = TestDataUtility.createTestOpportunity(false);
        insert opp1;
        
        Applicant__c app1 = TestDataUtility.createTestApplicant(false);
        app1.Opportunity__c= opp1.Id;
        app1.Applicant_Type__c = System.Label.Borrower;
        insert app1;
        
        InsuranceDetails__c insuDetail = new InsuranceDetails__c();
        insuDetail.Applicant__c = app1.id;
        insuDetail.Funded_Premium__c=400.00;
        insuDetail.Loan_Application__c = opp1.id;
        insert insuDetail;
        
        Test.startTest();
              ind_ApplicationFormSigningController.getInsurenceDetails(app1.id);
        Test.stopTest();
    }
    
    @isTest
    public static void getvehicleTest(){
        Opportunity opp1 = TestDataUtility.createTestOpportunity(false);
        insert opp1;
        
        Applicant__c app1 = TestDataUtility.createTestApplicant(false);
        app1.Opportunity__c= opp1.Id;
        app1.Applicant_Type__c = System.Label.Borrower;
        insert app1;
        
        Vehicle_Detail__c vech = new Vehicle_Detail__c();
        vech.Loan_Application__c = opp1.Id;
        insert vech;
        
        Test.startTest();
              ind_ApplicationFormSigningController.getvehicle(app1.Id);
        Test.stopTest();
    }
    
    @isTest
    public static void getProductTypeTest(){
        Opportunity opp1 = TestDataUtility.createTestOpportunity(false);
        insert opp1;
        
        Applicant__c app1 = TestDataUtility.createTestApplicant(false);
        app1.Opportunity__c= opp1.Id;
        app1.Applicant_Type__c = System.Label.Borrower;
        insert app1;
        
        Test.startTest();
             ind_ApplicationFormSigningController.getProductType(app1.Id);
        Test.stopTest();
    }
    
    @isTest
    public static void getApplicentDocumentsTest(){
        Opportunity opp1 = TestDataUtility.createTestOpportunity(false);
        insert opp1;
        
        Applicant__c app1 = TestDataUtility.createTestApplicant(false);
        app1.Opportunity__c= opp1.Id;
        app1.Applicant_Type__c = System.Label.Borrower;
        insert app1;
        
        Documents__c dfks1 = new Documents__c();
        dfks1.Applicant__c = app1.Id;
        dfks1.Opportunity_Relation__c = opp1.Id;
        dfks1.Document_Type__c = 'Customer Image';
        dfks1.Document_Side__c ='Back';
        dfks1.Aadhar_Source__c = 'ScanAadhar';
        insert dfks1;
        
        Test.startTest();
              ind_ApplicationFormSigningController.getApplicentDocuments(app1.Id);
        Test.stopTest();
    }
    @isTest 
    public static void DisplayCustomerImageTest(){
        
                Opportunity opks1 = new Opportunity();
                opks1.StageName = 'Qualification';
                opks1.CloseDate = Date.newInstance(2021, 1, 11);
                opks1.Name = 'testone';
                insert opks1;
                
                Applicant__c apks1 = new Applicant__c();
                apks1.Opportunity__c = opks1.Id;
                apks1.Contact_number__c = '9743514830';
                apks1.Applicant_Type__c = 'Borrower';
                insert apks1;
                
                 Documents__c dfks1 = new Documents__c();
                 dfks1.Applicant__c = apks1.Id;
                 dfks1.Opportunity_Relation__c = opks1.Id;
                 dfks1.Document_Type__c = 'Customer Image';
                 dfks1.Document_Side__c ='Back';
                 dfks1.Aadhar_Source__c = 'ScanAadhar';
                 insert dfks1;
        
                 Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');

                 ContentVersion cv = new ContentVersion();
                 cv.title = 'test content trigger';      
                 cv.PathOnClient ='test';           
                 cv.VersionData =beforeblob;          
                 insert cv;   
        
                 ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];

        
                 ContentDocumentLink contentlink = new ContentDocumentLink();
                 contentlink.ShareType = 'V';
                 contentlink.LinkedEntityId = dfks1.Id; 
                 contentlink.ContentDocumentId = testcontent.ContentDocumentId;
                 contentlink.Visibility = 'AllUsers'; 
                 insert contentlink;
        
                 Test.startTest();
                        ind_ApplicationFormSigningController.DisplayCustomerImage(apks1.Id);
                 Test.stopTest();
       
    }
}