ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/IND_ExternalCustomerDedupeAPIService.cls
/*------------------------------------------------------------
Author:        Divya Jawale
Company:       Salesforce
Description:   This class is service class for the External Customer Dedupe API 
Test Class:    IND_ExternalCustomerDedupeService_Test
History
Date            Author              Comments
-------------------------------------------------------------
28-10-2021      Divya Jawale      Created
------------------------------------------------------------*/
public class IND_ExternalCustomerDedupeAPIService {

    /*
    * @Method:      getExternalDedupeCallout
    * @Created by:  Divya
    * @Description: This method will returns valid External Customer Dedupe API
    * @Param:       Id - Applicant Object 
    * @Return:      Object - IND_ExternalCustomerDedupeAPIRequest type request
    */
    public static IND_ExternalCustomerDedupeAPIRequest getExternalDedupeCallout(Applicant__c app, List<Documents__c> docs, String loanAppId){
        try{
            IND_ExternalCustomerDedupeAPIRequest request = new IND_ExternalCustomerDedupeAPIRequest(app, docs,loanAppId);
            return request;
        }
        catch(Exception ex){
            ErrorLoggerUtil.logErrorEvent('IND_ExternalCustomerDedupeAPIService', 'getexternalDedupeCallout', System.Label.Apex, ex,loanAppId);
            throw new IND_Exception(ex.getMessage());   
        }
    }
    
}