ProdIND/ProdPrograms/force-app/main/default/objects/Case/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Case/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <formula>TEXT(Loan_Application__r.Product_Type__c)</formula>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Case/recordTypes/FI.recordType-meta.xml
<RecordType>
    <fullName>FI</fullName>
    <active>true</active>
    <businessProcess>FI Process</businessProcess>
    <label>FI</label>
</RecordType>

ProdIND/ProdPrograms/force-app/main/default/objects/Field_Investigation__c/Field_Investigation__c.object-meta.xml
<CustomObject>
    <label>Field Investigation</label>
    <nameField>
        <displayFormat>FI-{00000}</displayFormat>
        <label>Field Investigation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Field Investigations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Field_Investigation__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipName>IBL_Field_Investigations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdLWC - Copy/force-app/main/default/classes/IND_LWC_FICasePageCntrl.cls
/*------------------------------------------------------------
Author:        Manish Baldota
Company:       Persistent Systems
Description:   This class is used to provide the details to the FI case page lWC component.
Test Class:    
History
Date            Author              Comments
-------------------------------------------------------------
25-04-2022      Manish Baldota       Created
------------------------------------------------------------*/
public with sharing class IND_LWC_FICasePageCntrl {
    // @Method:      handleChangeOwnerProcess
    // @Created by:  Manish Baldota
    // @Description: Method to handle the business logic of CMU owner change.
    // @Param:       String : caseId  
    // @Return:  
    @AuraEnabled(cacheable = true)
    public static Field_Investigation__c getFIRecord(String caseId){
        try{
            if(String.isNotBlank(caseId)){
                List<Field_Investigation__c> fieldInvestiagationList = [SELECT Id, RecordType.Name,Case__r.Loan_Application__r.Product_Type__c,Case__r.Product_Type__c FROM Field_Investigation__c
                                                                        WHERE Case__c =: caseId LIMIT 1];
                if(!fieldInvestiagationList.isEmpty()){
                    return fieldInvestiagationList[0];
                }else{
                    throw new IND_Exception('Field Investigation Details are not available, Please contact your administrator.');
                }
            }else{
                throw new IND_Exception('Something went wrong, Please contact your administator.');
            }
        }Catch(Exception e){
            ErrorLoggerUtil.logErrorEvent('getFIID', 'IND_LWC_FICasePageCntrl', System.Label.Apex, e, '');
            throw new IND_Exception(e.getMessage());
        }
        
    }
}