ProdIND/ProdPrograms/force-app/main/default/objects/High_Payload_Response__e/High_Payload_Response__e.object-meta.xml
<CustomObject>
    <description>This is created for High Payload ASync Response. The name has been changed from the previous Name for Recognition. Need to change in any code if already used.</description>
    <label>High Payload Response</label>
    <pluralLabel>High Payload Responses</pluralLabel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/High_Payload_Response__e/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>To Store request to be published</description>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/High_Payload_Response__e/fields/Response_Ext__c.field-meta.xml
<CustomField>
    <fullName>Response_Ext__c</fullName>
    <label>Response Ext</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/classes/HandleHighPayLoadResponseTest.cls
@isTest
public class HandleHighPayLoadResponseTest {
    
    @isTest
    public static void verifyHandleHighPayLoadResponse(){
        Opportunity opp = TestDataUtility.createTestOpportunity(true);
        High_Payload_Response__e objNewEvent = new High_Payload_Response__e();
        objNewEvent.Reference_Id__c = opp.Id;
        objNewEvent.Response__c = JSON.serialize(opp);
        objNewEvent.Response_Ext__c = JSON.serialize(opp);
        Test.startTest();
        List<Database.SaveResult> results = EventBus.publish(new List<High_Payload_Response__e>{objNewEvent});
        Test.stopTest();
        // Inspect publishing result for each event
        for (Database.SaveResult sr : results) {
            System.assert(sr.isSuccess());
        }
    }  
    
}