ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/CMU_Accept_Reject__c.field-meta.xml
<CustomField>
    <fullName>CMU_Accept_Reject__c</fullName>
    <label>CMU Accept/Reject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/CMU_Rejection_Reason__c.field-meta.xml
<CustomField>
    <fullName>CMU_Rejection_Reason__c</fullName>
    <label>CMU Rejection Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>CMU_Accept_Reject__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Incorrect fields</fullName>
            </value>
            <value>
                <fullName>Documents reject or Customer Photo reject</fullName>
            </value>
            <value>
                <fullName>Incorrect document</fullName>
            </value>
            <value>
                <fullName>Signature missing</fullName>
            </value>
            <value>
                <fullName>Date of birth not available</fullName>
            </value>
            <value>
                <fullName>Form 60 not filled properly</fullName>
            </value>
            <value>
                <fullName>Form 60 image not clear</fullName>
            </value>
            <value>
                <fullName>Form 60 details not tallying with data points</fullName>
            </value>
            <value>
                <fullName>Blank form 60 attached</fullName>
            </value>
            <value>
                <fullName>PAN acknowledgement number incorrect / incomplete in Form 60</fullName>
            </value>
            <value>
                <fullName>Name of the applicant / customer does not match as per NSDL records</fullName>
            </value>
            <value>
                <fullName>Relationship not tagged properly</fullName>
            </value>
            <value>
                <fullName>Shareholding pattern not tagged properly</fullName>
            </value>
            <value>
                <fullName>Entity type mismatch</fullName>
            </value>
            <value>
                <fullName>Document number mismatch for mandatory documents</fullName>
            </value>
            <value>
                <fullName>DOI incorrect</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Seller&apos;s Passbook</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Bank Statement</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Cancel Cheque</fullName>
            </value>
            <value>
                <fullName>Driving Licence</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Voter Id</fullName>
            </value>
            <value>
                <fullName>Form 60</fullName>
            </value>
            <value>
                <fullName>Customer Image</fullName>
            </value>
            <value>
                <fullName>Aadhaar</fullName>
            </value>
            <value>
                <fullName>Vehicle Images</fullName>
            </value>
            <value>
                <fullName>RC Document</fullName>
            </value>
            <value>
                <fullName>SPR</fullName>
            </value>
            <value>
                <fullName>APR</fullName>
            </value>
            <value>
                <fullName>Electronic Bill</fullName>
                <label>Electricity Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Water Bill</fullName>
                <label>Water Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Vehicle Insurance Policy</fullName>
            </value>
            <value>
                <fullName>Vehicle Image</fullName>
            </value>
            <value>
                <fullName>Bank Statement</fullName>
            </value>
            <value>
                <fullName>Insurance Policy Doc</fullName>
            </value>
            <value>
                <fullName>Valuation Report</fullName>
            </value>
            <value>
                <fullName>Office FI</fullName>
            </value>
            <value>
                <fullName>Land Photo</fullName>
            </value>
            <value>
                <fullName>Patta Document</fullName>
            </value>
            <value>
                <fullName>Rent Agreement/Reciept</fullName>
            </value>
            <value>
                <fullName>Pension Document</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Engine Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Chassis Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Selfie with Vehicle-uploaded during verification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Opportunity_Relation__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Relation__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/Final_Term__c.object-meta.xml
<CustomObject>
    <description>To store Final term module data.</description>
    <label>Final Term</label>
    <nameField>
        <displayFormat>FT-{000000}</displayFormat>
        <label>Final Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/CRM_IRR__c.field-meta.xml
<CustomField>
    <fullName>CRM_IRR__c</fullName>
    <label>Offer engine CRM IRR</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Documentation_charges__c.field-meta.xml
<CustomField>
    <fullName>Documentation_charges__c</fullName>
    <label>Documentation charges</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Loan_Amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_Amount__c</fullName>
    <label>Offer engine Loan Amount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan_Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Final_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Service_charges__c.field-meta.xml
<CustomField>
    <fullName>Service_charges__c</fullName>
    <label>Service charges</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Tenure__c.field-meta.xml
<CustomField>
    <fullName>Tenure__c</fullName>
    <label>Offer engine Tenure</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/CRM_IRR__c.field-meta.xml
<CustomField>
    <fullName>CRM_IRR__c</fullName>
    <label>CRM IRR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Documentation_Charges__c.field-meta.xml
<CustomField>
    <fullName>Documentation_Charges__c</fullName>
    <label>Documentation Charges</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/IModuleId__c.field-meta.xml
<CustomField>
    <fullName>IModuleId__c</fullName>
    <label>IModuleId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Loan_amount__c.field-meta.xml
<CustomField>
    <fullName>Loan_amount__c</fullName>
    <label>Loan amount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Sanction_Date__c.field-meta.xml
<CustomField>
    <fullName>Sanction_Date__c</fullName>
    <label>Sanction Date</label>
    <type>Date</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Service_Charges__c.field-meta.xml
<CustomField>
    <fullName>Service_Charges__c</fullName>
    <label>Service Charges</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/classes/IND_ReverseStatusRequest.cls
/*------------------------------------------------------------
Author: Vishal Gadhave & Parimal Shinde
Company: Nanostuffs Technologies
Description: This class is wrapper class for the Reverse Status Request
Test Class: 
*/

public class IND_ReverseStatusRequest extends ParentAPIRequest{
    
    //public Id loanAppId {get;set;}
    //public String Application_No{get;set;}
    public String application_status {get;set;}
   //public String loan_type_id {get;set;}
    public String application_sub_status {get;set;}
    public String last_updated_timestamp {get;set;}
    //public String status_comment {get;set;}    
    public List<document_re_upload_list> document_re_upload_list {get;set;}
    public List<disbursement_details> disbursement_details {get;set;}
    public String unique_id{get;set;}
    public String los_id{get;set;}
    public String reference_id{get;set;}
    public String comment{get;set;}
    public String approved_date{get;set;}
    public String approved_tenure{get;set;}
    public String approved_roi{get;set;}
    public String approved_loan_amount{get;set;}
    public String approved_processing_fee{get;set;}

    
    public class document_re_upload_list {
        public String bank_code {get;set;}
        public String reject_reason {get;set;}
    }
    public class disbursement_details {   
    }
    
    public IND_ReverseStatusRequest(Id loanAppId, String status, String code)
    {
        if(loanAppId != null)
        {
            List<document_re_upload_list> docList = new List<document_re_upload_list>();
            document_re_upload_list docRecord = new document_re_upload_list();
            disbursement_details disRecord = new disbursement_details();
            try{
                Opportunity opp = [select IModuleId__c,LastModifiedDate, (select Document_Type__c, CMU_Accept_Reject__c, CMU_Rejection_Reason__c from Documents__r where CMU_Accept_Reject__c = 'Reject'),Sanction_Date__c,(select id,Tenure__c,CRM_IRR__c,Loan_Amount__c,Service_charges__c,Documentation_charges__c from Final_Terms__r ) from Opportunity where Id=: loanAppId WITH SECURITY_ENFORCED limit 1];
                System.debug('opp doc records: '+opp.Documents__r);
                if(opp!=null)
                {
                    //this.Application_No = opp.IModuleId__c;
                    this.application_status = code;
                    //this.loan_type_id = System.Label.MSIL_Loan_Type_ID;
                    this.application_sub_status ='';
                    DateTime lastModifiedDate = opp.LastModifiedDate;
                    this.last_updated_timestamp = lastModifiedDate.format('yyyy-MM-dd HH:mm:ss');
                    //this.status_comment = System.Label.MSIL_Status_Comment;
                    if(opp.Documents__r != null && opp.Documents__r.size() > 0) {
                        for(Documents__c docs : opp.Documents__r) {
                            docRecord.bank_code = docs.Document_Type__c;
                        	docRecord.reject_reason = docs.CMU_Rejection_Reason__c;
                        	docList.add(docRecord);                        	
                        }
                        this.document_re_upload_list = docList;
                    }
                    this.unique_id = opp.IModuleId__c;
                    this.los_id = opp.IModuleId__c;
                    this.reference_id = '';
                    this.comment = '';
                    String dateString='';
                    if(opp.Sanction_Date__c!=null){
                        Datetime dt = Datetime.newInstance(opp.Sanction_Date__c.year(), opp.Sanction_Date__c.month(),opp.Sanction_Date__c.day());
                        dateString = dt.format('dd-MM-yyyy');
                    }
                    this.approved_date =  (opp.Sanction_Date__c != null) ? dateString : '';
                    if(opp.Final_Terms__r != null && opp.Final_Terms__r.size() > 0) {
                        for(Final_Term__c ft : opp.Final_Terms__r) {
                            this.approved_tenure = (ft.Tenure__c != null) ? ft.Tenure__c : '';
                            this.approved_roi = '';
                            this.approved_loan_amount = (ft.Loan_Amount__c != null) ? ft.Loan_Amount__c : '';
                            // Decimal totalProcessingFee = 0;
                            // if(ft.Service_charges__c != null) {
                            //     totalProcessingFee += Decimal.valueOf(ft.Service_charges__c);
                            // }
                            // if(ft.Documentation_charges__c != null) {
                            //     totalProcessingFee += Decimal.valueOf(ft.Documentation_charges__c);
                            // }
                            // this.approved_processing_fee = totalProcessingFee.format();
                            this.approved_processing_fee = '';
                        }
                    }
                }
            }
            catch(Exception ex)
            {
                System.debug(ex);
                throw new IND_Exception(ex.getMessage());
            }
        } 
    }     
}