ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/CMU_Accept_Reject__c.field-meta.xml
<CustomField>
    <fullName>CMU_Accept_Reject__c</fullName>
    <label>CMU Accept/Reject</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Is_Rejected_By_CMU__c.field-meta.xml
<CustomField>
    <fullName>Is_Rejected_By_CMU__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Rejected By CMU?</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Opportunity_Relation__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Relation__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Rejection_Fields__c.field-meta.xml
<CustomField>
    <fullName>Rejection_Fields__c</fullName>
    <label>Rejection Fields</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <controllingField>CMU_Accept_Reject__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Kyc_Fields</valueSetName>
    </valueSet>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/CMURejectComponentController.cls
public class CMURejectComponentController {

    @AuraEnabled
    public static List<Documents__c> getDocumentsList(String oppId){
        String userId = UserInfo.getUserId();
        List<Documents__c> docsList = [SELECT Id,Name,Is_Rejected_By_CMU__c,Rejection_Fields__c 
                                       FROM Documents__c WHERE CMU_Accept_Reject__c = 'Reject' 
                                       AND Opportunity_Relation__r.OwnerId =: userId];
        if(docsList != null && docsList.size() > 0){
            return docsList;
        }
        return null;
    }
  
    @AuraEnabled
    public static List<Documents__c> getDocumentDetails(String docId){
        List<Schema.FieldSetMember> fieldList = readFieldSet('IND_LWC_CMURejectFields', 'Documents__c');
        String docQuery = 'SELECT ';
        for(Schema.FieldSetMember fieldMember : fieldList){
            docQuery += fieldMember.getFieldPath() + ',';
        }
        docQuery += 'Id FROM Documents__c WHERE Id = \''+ docId +'\' LIMIT 1';
        System.debug('docQuery ### ' + docQuery);
        return Database.query(docQuery);
    }

    private static List<Schema.FieldSetMember> readFieldSet(String fieldSetName, String ObjectName){
        Map<String, Schema.SObjectType> GlobalDescribeMap = Schema.getGlobalDescribe(); 
        Schema.SObjectType SObjectTypeObj = GlobalDescribeMap.get(ObjectName);
        Schema.DescribeSObjectResult DescribeSObjectResultObj = SObjectTypeObj.getDescribe();
        Schema.FieldSet fieldSetObj = DescribeSObjectResultObj.FieldSets.getMap().get(fieldSetName);
        return fieldSetObj.getFields(); 
    }
}