ProdIND/ProdPrograms/force-app/main/default/objects/Integration_Logger_Event__e/Integration_Logger_Event__e.object-meta.xml
<CustomObject>
    <label>Integration Logger Event</label>
    <pluralLabel>Integration Logger Events</pluralLabel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Integration_Logger_Event__e/fields/EncryptedRequest__c.field-meta.xml
<CustomField>
    <fullName>EncryptedRequest__c</fullName>
    <description>A field to capture encrypted request</description>
    <label>Encrypted Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Integration_Logger_Event__e/fields/EncryptedResponse__c.field-meta.xml
<CustomField>
    <fullName>EncryptedResponse__c</fullName>
    <description>Field to capture encrypted response</description>
    <label>Encrypted Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Integration_Logger_Event__e/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <description>A field to capture request</description>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Integration_Logger_Event__e/fields/Request_Ext__c.field-meta.xml
<CustomField>
    <fullName>Request_Ext__c</fullName>
    <description>Request extension</description>
    <label>Request Ext</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Integration_Logger_Event__e/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>A field to capture Encrypted Response</description>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Integration_Logger_Event__e/fields/Response_Ext__c.field-meta.xml
<CustomField>
    <fullName>Response_Ext__c</fullName>
    <description>Response extension</description>
    <label>Response Ext</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Integration_Logger_Event__e/fields/ServiceName__c.field-meta.xml
<CustomField>
    <fullName>ServiceName__c</fullName>
    <description>Field to capture service name</description>
    <label>Service Name</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Integration_Logger_Event__e/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status flag depicts API Success or Failure.</description>
    <label>Status</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/IntegrationLoggerPETest.cls
@isTest
public class IntegrationLoggerPETest {
	 @isTest
    static void testIntegrationLoggerPlatformEventTrigger() {
        // Start test context
        Test.startTest();
        
        // Create a list of platform events
        List<Integration_Logger_Event__e> events = new List<Integration_Logger_Event__e>();

        // Define a sample event with all necessary fields filled out
        Integration_Logger_Event__e sampleEvent1 = new Integration_Logger_Event__e(
            Request__c = 'Sample Request',
            Response__c = 'Sample Response',
            EncryptedRequest__c = 'Encrypted Request',
            EncryptedResponse__c = 'Encrypted Response',
            ServiceName__c = 'Sample Service',
            Request_Ext__c = 'Request Extension',
            Response_Ext__c = 'Response Extension',
            Status__c = 'Success'
        );
        
        events.add(sampleEvent1);

        // Insert platform events
        EventBus.publish(events);
        
        // End test context
        Test.stopTest();
       
    }
}