ProdIND/ProdPrograms/force-app/main/default/objects/Account/fields/Product_type__c.field-meta.xml
<CustomField>
    <fullName>Product_type__c</fullName>
    <label>Product type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/AccountTeamMember/fields/FI_Executive_Counter__c.field-meta.xml
<CustomField>
    <fullName>FI_Executive_Counter__c</fullName>
    <label>FI Executive Counter</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/AccountTeamMember/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>L0.5</fullName>
            </value>
            <value>
                <fullName>L1</fullName>
            </value>
            <value>
                <fullName>L2</fullName>
            </value>
            <value>
                <fullName>L3</fullName>
            </value>
            <value>
                <fullName>L3.5</fullName>
            </value>
            <value>
                <fullName>L4</fullName>
            </value>
            <value>
                <fullName>L5</fullName>
            </value>
            <value>
                <fullName>L6</fullName>
            </value>
            <value>
                <fullName>L7</fullName>
            </value>
            <value>
                <fullName>L8</fullName>
            </value>
            <value>
                <fullName>L9</fullName>
            </value>
            <value>
                <fullName>L10</fullName>
            </value>
            <value>
                <fullName>L11</fullName>
            </value>
            <value>
                <fullName>L5.5</fullName>
            </value>
            <value>
                <fullName>L4.5</fullName>
            </value>
            <value>
                <fullName>L6.5</fullName>
            </value>
            <value>
                <fullName>L2.5</fullName>
            </value>
            <value>
                <fullName>L9.5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <label>Applicant  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/In_Active_Applicant__c.field-meta.xml
<CustomField>
    <fullName>In_Active_Applicant__c</fullName>
    <defaultValue>false</defaultValue>
    <label>In-Active Applicant</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Applicant__c/fields/Would_you_like_to_open_a_bank_account__c.field-meta.xml
<CustomField>
    <fullName>Would_you_like_to_open_a_bank_account__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Would you like to open a bank account ?</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/CAM__c/CAM__c.object-meta.xml
<CustomObject>
    <label>CAM</label>
    <nameField>
        <displayFormat>CAM-{00000000}</displayFormat>
        <label>CAM Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CAMS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/CAM__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Whether the CAM is active default is true</description>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/CAM__c/fields/BE_CVO_Remark__c.field-meta.xml
<CustomField>
    <fullName>BE_CVO_Remark__c</fullName>
    <description>Remark added by BE/CVO at the time of submitting the CAM.</description>
    <label>BE/CVO Remark</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/CAM__c/fields/Conditional_Approval__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Approval__c</fullName>
    <description>Comments to be given at the time of Conditionally approving the proposal.</description>
    <label>Conditional Approval</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/CAM__c/fields/Is_Hold__c.field-meta.xml
<CustomField>
    <fullName>Is_Hold__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Hold</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/CAM__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>CAMS</relationshipLabel>
    <relationshipName>CAMS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/CAM__c/fields/Proposal_Status__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Status__c</fullName>
    <description>Final Approval Status (possible values Accept, Reject and Withdrawn)</description>
    <label>Proposal Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deviation_Master__c/Deviation_Master__c.object-meta.xml
<CustomObject>
    <description>This object will store all the Master Deviation records</description>
    <label>Deviation Master</label>
    <nameField>
        <label>Master Deviation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deviations Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Deviation_Master__c/fields/Deviation_Level__c.field-meta.xml
<CustomField>
    <fullName>Deviation_Level__c</fullName>
    <label>Deviation Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Mitigant_Master__c/Mitigant_Master__c.object-meta.xml
<CustomObject>
    <label>Mitigant Master</label>
    <nameField>
        <label>Master Mitigant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mitigants Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Is_Mobile_Journey_Completed__c.field-meta.xml
<CustomField>
    <fullName>Is_Mobile_Journey_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Mobile Journey Completed</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Sanction_Status__c.field-meta.xml
<CustomField>
    <fullName>Sanction_Status__c</fullName>
    <label>Sanction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>STP</fullName>
            </value>
            <value>
                <fullName>Non-STP</fullName>
                <default>true</default>
                <label>Non-STP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <formula>IF(!ISBLANK( Aggregator_Source__c ) &amp;&amp; ISPICKVAL(LeadSource,&quot;D2C&quot;) ,
&quot;Aggregator&quot;,
IF(ISPICKVAL(LeadSource,&quot;D2C&quot;) &amp;&amp; Is_Pre_Approved__c == true,&quot;Pre Approved&quot;,&quot;Normal&quot;)
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Source</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Details</fullName>
            </value>
            <value>
                <fullName>Capture current residential address</fullName>
            </value>
            <value>
                <fullName>Capture permanent residential address</fullName>
            </value>
            <value>
                <fullName>Capture PAN or Other KYC</fullName>
            </value>
            <value>
                <fullName>Capture Dedupe</fullName>
            </value>
            <value>
                <fullName>Vehicle Dedupe</fullName>
            </value>
            <value>
                <fullName>Declared Income/Required Loan Amount</fullName>
            </value>
            <value>
                <fullName>Bank Account Check</fullName>
            </value>
            <value>
                <fullName>View Application Details</fullName>
            </value>
            <value>
                <fullName>CIBIL</fullName>
            </value>
            <value>
                <fullName>Field Investigation</fullName>
            </value>
            <value>
                <fullName>Credit Assessment</fullName>
            </value>
            <value>
                <fullName>Income Details</fullName>
            </value>
            <value>
                <fullName>Valuation IDV</fullName>
            </value>
            <value>
                <fullName>Final Terms</fullName>
            </value>
            <value>
                <fullName>Insurance Details</fullName>
            </value>
            <value>
                <fullName>Exposure Analysis</fullName>
            </value>
            <value>
                <fullName>Income</fullName>
            </value>
            <value>
                <fullName>CAM and Approval Log</fullName>
            </value>
            <value>
                <fullName>Risk Summary</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Tele-verification &lt;Post Sanction&gt;</fullName>
            </value>
            <value>
                <fullName>Vehicle Inspection and RC Check</fullName>
            </value>
            <value>
                <fullName>Structured EMI</fullName>
            </value>
            <value>
                <fullName>Security Mandate</fullName>
            </value>
            <value>
                <fullName>Additional Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>IHM</fullName>
            </value>
            <value>
                <fullName>Loan Agreement</fullName>
            </value>
            <value>
                <fullName>Signing the e-Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/Maker_Id__c.field-meta.xml
<CustomField>
    <fullName>Maker_Id__c</fullName>
    <label>Maker Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/classes/lWC_ManualDeviationMitigantsCntrlTest.cls
/**
* @description       : This test class is for lWC_ManualDeviationMitigantsCntrl Apex class.
* @author            : Aakash J
* @group             : 
* @created on		 : 08-11-2023
* @Version 		  	 : 1.0
**/
@isTest
public class lWC_ManualDeviationMitigantsCntrlTest {
	@testSetup static void createCAMData() {
		Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(Alias = 'standt2', Email='standarduser2@testorg.com',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,Maker_Id__c='12',IsActive = true,
                          TimeZoneSidKey='America/Los_Angeles',UserName='test_userprod123@indusbank.com.uat',MobilePhone = '9089078967');
        insert u;
        System.runAs(u) 
        {
            Account au1 = new Account();
            au1.Name = 'test';
            au1.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Business Account').getRecordTypeId();
            insert au1;
            
            List<AccountTeamMember> atmList = new List<AccountTeamMember>();
            AccountTeamMember atm1 = new AccountTeamMember();
            atm1.AccountId = au1.Id;
            atm1.TeamMemberRole = 'ACM';
            atm1.UserId = UserInfo.getUserId();
            atm1.FI_Executive_Counter__c = 3;
             atm1.Level__c ='L4;L1;L2';
            insert atm1;
            
            Opportunity opp = TestDataUtility.createTestLoanApplication(true);        
            opp.Sub_Stage__c = System.Label.Field_Investigation;
            opp.Is_Mobile_Journey_Completed__c = true;
            opp.Vehicle_Type__c = System.Label.used;
            opp.Product_Type__c = System.Label.TwoWheeler;
            opp.Sanction_Status__c = System.Label.nonStp;
            opp.AccountId = au1.Id;
            update opp;
            
            Applicant__c applicant = TestDataUtility.createTestApplicantService(true,opp);
            applicant.In_Active_Applicant__c = false;
            applicant.Would_you_like_to_open_a_bank_account__c = true;
            update applicant;
            
            Deviation_Master__c deviMaster = new Deviation_Master__c();
            deviMaster.Name ='Test DeviMaster';
            deviMaster.Active__c =true;
            deviMaster.Deviation_Level__c ='L4';
            deviMaster.Parameter__c ='Test DeviMaster Parameter';
            deviMaster.Source__c ='Manual';
            insert deviMaster;
            
            Mitigant_Master__c mitiMaster = new Mitigant_Master__c();
            mitiMaster.Name ='Test mitiMaster';
            mitiMaster.Active__c =true;
            mitiMaster.Description__c ='Test mitiMaster Parameter';
            insert mitiMaster;
            
            CAM__c parentCam = new CAM__c();
            parentCam.Loan_Application__c = opp.Id;
            parentCam.BE_CVO_Remark__c = 'testbeCVO';
            //parentCam.Is_Hold__c = true;
            parentCam.Conditional_Approval__c = 'testapproved';
            parentCam.Proposal_Status__c = 'Approved';
            insert parentCam;
            
        }
    }
    
    @isTest public static void testClassmethod(){
        User u = [SELECT Id FROM User WHERE UserName='test_userprod123@indusbank.com.uat' AND IsActive = true LIMIT 1]; 
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        List<Deviation_Master__c> devMasterRecords = [SELECT Id, Name, Active__c, Deviation_Level__c, Parameter__c,
                                                          Source__c  FROM Deviation_Master__c where Active__c = true];
        
        List<Mitigant_Master__c> mitiMasterRecords = [SELECT Id, Name, Active__c, Description__c
                                                          FROM Mitigant_Master__c where Active__c = true];
        
        CAM__c parentCam = [Select id,Loan_Application__c From CAM__c Limit 1];
        AccountTeamMember atm1 = new AccountTeamMember();
            atm1.AccountId =[SELECT Id FROM Account WHERE NAme='test' LIMIT 1].Id;
            atm1.TeamMemberRole = 'ACM';
            atm1.UserId = UserInfo.getUserId();
            atm1.FI_Executive_Counter__c = 3;
             atm1.Level__c ='L4;L1;L2';
            insert atm1;
        System.runAs(u) 
        {	
            list<lWC_ManualDeviationMitigantsCntrl.deviationMasterWrapper>  devirecordsLst = new list<lWC_ManualDeviationMitigantsCntrl.deviationMasterWrapper>();
            lWC_ManualDeviationMitigantsCntrl.deviationMasterWrapper deviationMasterWrapperRec = new lWC_ManualDeviationMitigantsCntrl.deviationMasterWrapper();
            if(!devMasterRecords.isEmpty()){
                deviationMasterWrapperRec.Deviation_Id = devMasterRecords[0].Name;
                deviationMasterWrapperRec.Source = devMasterRecords[0].Source__c;
                deviationMasterWrapperRec.Parameter = devMasterRecords[0].Parameter__c;
                deviationMasterWrapperRec.Deviation_Level = devMasterRecords[0].Deviation_Level__c;
                devirecordsLst.add(deviationMasterWrapperRec);     
            }
            
            list<lWC_ManualDeviationMitigantsCntrl.mitigantsMasterWrapper>  mitigantsMasterWrapperLst = new list<lWC_ManualDeviationMitigantsCntrl.mitigantsMasterWrapper>();
            lWC_ManualDeviationMitigantsCntrl.mitigantsMasterWrapper mitigantsMasterWrapperRec = new lWC_ManualDeviationMitigantsCntrl.mitigantsMasterWrapper();
            if(!mitiMasterRecords.isEmpty()){
                mitigantsMasterWrapperRec.Name = mitiMasterRecords[0].Name;
                mitigantsMasterWrapperRec.Description = mitiMasterRecords[0].Description__c;
                mitigantsMasterWrapperLst.add(mitigantsMasterWrapperRec);     
            }
                        
            Test.startTest();
            lWC_ManualDeviationMitigantsCntrl.getOpportunity(opp.Id);
            lWC_ManualDeviationMitigantsCntrl.fetchMitigantRecords(String.valueOf(parentCam.Id));
            lWC_ManualDeviationMitigantsCntrl.fetchManulaDeviationRecords(String.valueOf(parentCam.Id));
         	lWC_ManualDeviationMitigantsCntrl.getdeviMasterRecords();
            lWC_ManualDeviationMitigantsCntrl.getmitigantsMasterRecords();
            lWC_ManualDeviationMitigantsCntrl.saveDeviationRec(devirecordsLst, String.valueOf(parentCam.Id));
            lWC_ManualDeviationMitigantsCntrl.saveMitigantRec(mitigantsMasterWrapperLst,String.valueOf(parentCam.Id));
            lWC_ManualDeviationMitigantsCntrl.sendApprovalCAMReqAPI(String.valueOf(parentCam.Id));
         	Test.stopTest();
            
        }
    }
}