ProdIND/ProdPrograms/force-app/main/default/objects/Account/fields/Product_type__c.field-meta.xml
<CustomField>
    <fullName>Product_type__c</fullName>
    <label>Product type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Case/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant Id</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Case/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <formula>TEXT(Loan_Application__r.Product_Type__c)</formula>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Case/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <formula>Loan_Application__r.Vehicle_Type__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Vehicle Type</label>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <label>Documents</label>
    <nameField>
        <label>Documents Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Aadhar_Source__c.field-meta.xml
<CustomField>
    <fullName>Aadhar_Source__c</fullName>
    <label>Aadhar Source</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>OTP</fullName>
            </value>
            <value>
                <fullName>Biometric</fullName>
            </value>
            <value>
                <fullName>Scan and Upload</fullName>
            </value>
            <value>
                <fullName>ScanAadhar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Addresss_Type__c.field-meta.xml
<CustomField>
    <fullName>Addresss_Type__c</fullName>
    <label>Address Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Current Residential Address</fullName>
            </value>
            <value>
                <fullName>Permanent Residential Address</fullName>
            </value>
            <value>
                <fullName>Office Address</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Document_Type__c.field-meta.xml
<CustomField>
    <fullName>Document_Type__c</fullName>
    <label>Document Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Seller&apos;s Passbook</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Bank Statement</fullName>
            </value>
            <value>
                <fullName>Seller&apos;s Cancel Cheque</fullName>
            </value>
            <value>
                <fullName>Driving Licence</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
            <value>
                <fullName>Passport</fullName>
            </value>
            <value>
                <fullName>Voter Id</fullName>
            </value>
            <value>
                <fullName>Form 60</fullName>
            </value>
            <value>
                <fullName>Customer Image</fullName>
            </value>
            <value>
                <fullName>Aadhaar</fullName>
            </value>
            <value>
                <fullName>Vehicle Images</fullName>
            </value>
            <value>
                <fullName>RC Document</fullName>
            </value>
            <value>
                <fullName>SPR</fullName>
            </value>
            <value>
                <fullName>APR</fullName>
            </value>
            <value>
                <fullName>Electronic Bill</fullName>
                <label>Electricity Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Water Bill</fullName>
                <label>Water Bill (within 2 months)</label>
            </value>
            <value>
                <fullName>Vehicle Insurance Policy</fullName>
            </value>
            <value>
                <fullName>Vehicle Image</fullName>
            </value>
            <value>
                <fullName>Bank Statement</fullName>
            </value>
            <value>
                <fullName>Insurance Policy Doc</fullName>
            </value>
            <value>
                <fullName>Valuation Report</fullName>
            </value>
            <value>
                <fullName>Office FI</fullName>
            </value>
            <value>
                <fullName>Land Photo</fullName>
            </value>
            <value>
                <fullName>Patta Document</fullName>
            </value>
            <value>
                <fullName>Rent Agreement/Reciept</fullName>
            </value>
            <value>
                <fullName>Pension Document</fullName>
            </value>
            <value>
                <fullName>Signature</fullName>
            </value>
            <value>
                <fullName>Engine Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Chassis Number uploaded during verification</fullName>
            </value>
            <value>
                <fullName>Selfie with Vehicle-uploaded during verification</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Opportunity_Relation__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Relation__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Documents__c/fields/Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>Vehicle_Detail__c</referenceTo>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipName>Loan_Applications</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Is_Mobile_Journey_Completed__c.field-meta.xml
<CustomField>
    <fullName>Is_Mobile_Journey_Completed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Mobile Journey Completed</label>
    <type>Checkbox</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Sanction_Status__c.field-meta.xml
<CustomField>
    <fullName>Sanction_Status__c</fullName>
    <label>Sanction Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>STP</fullName>
            </value>
            <value>
                <fullName>Non-STP</fullName>
                <default>true</default>
                <label>Non-STP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Sub_Stage__c.field-meta.xml
<CustomField>
    <fullName>Sub_Stage__c</fullName>
    <label>Sub Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>User Details</fullName>
            </value>
            <value>
                <fullName>Capture current residential address</fullName>
            </value>
            <value>
                <fullName>Capture permanent residential address</fullName>
            </value>
            <value>
                <fullName>Capture PAN or Other KYC</fullName>
            </value>
            <value>
                <fullName>Capture Dedupe</fullName>
            </value>
            <value>
                <fullName>Vehicle Dedupe</fullName>
            </value>
            <value>
                <fullName>Declared Income/Required Loan Amount</fullName>
            </value>
            <value>
                <fullName>Bank Account Check</fullName>
            </value>
            <value>
                <fullName>View Application Details</fullName>
            </value>
            <value>
                <fullName>CIBIL</fullName>
            </value>
            <value>
                <fullName>Field Investigation</fullName>
            </value>
            <value>
                <fullName>Credit Assessment</fullName>
            </value>
            <value>
                <fullName>Income Details</fullName>
            </value>
            <value>
                <fullName>Valuation IDV</fullName>
            </value>
            <value>
                <fullName>Final Terms</fullName>
            </value>
            <value>
                <fullName>Insurance Details</fullName>
            </value>
            <value>
                <fullName>Exposure Analysis</fullName>
            </value>
            <value>
                <fullName>Income</fullName>
            </value>
            <value>
                <fullName>CAM and Approval Log</fullName>
            </value>
            <value>
                <fullName>Risk Summary</fullName>
            </value>
            <value>
                <fullName>Insurance</fullName>
            </value>
            <value>
                <fullName>Tele-verification &lt;Post Sanction&gt;</fullName>
            </value>
            <value>
                <fullName>Vehicle Inspection and RC Check</fullName>
            </value>
            <value>
                <fullName>Structured EMI</fullName>
            </value>
            <value>
                <fullName>Security Mandate</fullName>
            </value>
            <value>
                <fullName>Additional Documents</fullName>
            </value>
            <value>
                <fullName>Invoice</fullName>
            </value>
            <value>
                <fullName>IHM</fullName>
            </value>
            <value>
                <fullName>Loan Agreement</fullName>
            </value>
            <value>
                <fullName>Signing the e-Agreement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/Maker_Id__c.field-meta.xml
<CustomField>
    <fullName>Maker_Id__c</fullName>
    <label>Maker Id</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/User/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/Vehicle_Detail__c.object-meta.xml
<CustomObject>
    <label>Vehicle Detail</label>
    <nameField>
        <displayFormat>VD-{00000}</displayFormat>
        <label>Vehicle Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Vehicle_type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_type__c</fullName>
    <label>Vehicle type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/classes/OffRollEmpApproval_Test.cls
@isTest(seeAllData = false)
public class OffRollEmpApproval_Test {	
    
    @testSetup static void testDataSetup() 
    {
        //Create User     
        Contact con = TestDataUtility.createTestContact(true);
        Profile p = [SELECT Id FROM Profile WHERE Name='IBL Partner Community Counter Staff'];     
        User u = new User(Alias = 'standt', Email='standarduser@testorg.com',MobilePhone = '9999999999',
                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                          LocaleSidKey='en_US', ProfileId = p.Id,Maker_Id__c='12',IsActive = true,
                          TimeZoneSidKey='America/Los_Angeles', ContactId = con.Id,
                          UserName='test_userprod123987654735353@indusbank.com');
        insert u;
        
        Profile p1 = [SELECT Id FROM Profile WHERE Name='IBL Business Executive'];    
        User u1 = new User(Alias = 'standt1', Email='standarduser1@testorg.com',MobilePhone = '9999999999',
                           EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                           LocaleSidKey='en_US', ProfileId = p1.Id,Maker_Id__c='12',IsActive = true,
                           TimeZoneSidKey='America/Los_Angeles',UserName='test_user@abc1.com');
        insert u1;
        
        Profile p2 = [SELECT Id FROM Profile WHERE Name='IBL Marketing Officer'];
        User u2 = new User(Alias = 'standt2', Email='standarduser2@testorg.com',MobilePhone = '9999999999',
                           EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                           LocaleSidKey='en_US', ProfileId = p2.Id,Maker_Id__c='12',IsActive = true,
                           TimeZoneSidKey='America/Los_Angeles',UserName='test_user@abc2.com');
        insert u2;
        
        Profile p3 = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u3 = new User(Alias = 'standt3', Email='standarduser3@testorg.com',MobilePhone = '9999999999',
                           EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                           LocaleSidKey='en_US', ProfileId = p3.Id,Maker_Id__c='12',IsActive = true,
                           TimeZoneSidKey='America/Los_Angeles',UserName='test_user@abc3.com');
        insert u3;
        
        List<AccountTeamMember> acTMList = new List<AccountTeamMember>();
        System.runAs(u) 
        {
            //Create Account
            Account acc = TestDataUtility.createTestAccount(true);           
            
            //Create Account Team Member         
            AccountTeamMember acTM1 = new AccountTeamMember(AccountId = acc.Id, UserId = u1.Id, TeamMemberRole = 'BE');
            AccountTeamMember acTM2 = new AccountTeamMember(AccountId = acc.Id, UserId = u2.Id, TeamMemberRole = 'MO');
            AccountTeamMember acTM3 = new AccountTeamMember(AccountId = acc.Id, UserId = u3.Id, TeamMemberRole = 'PE');
            acTMList.add(acTM1);
            acTMList.add(acTM2);
            acTMList.add(acTM3);         
            
            // Create Opportunity
            Opportunity opp = TestDataUtility.createTestOpportunityForOcr(false);         
            opp.Sub_Stage__c = System.Label.Field_Investigation;
            opp.Is_Mobile_Journey_Completed__c = true;
            opp.Vehicle_Type__c = System.Label.used;
            opp.Product_Type__c = System.Label.TwoWheeler;
            opp.Sanction_Status__c = System.Label.nonStp;         
            opp.AccountId = acc.Id;
            opp.ownerId = u.Id;
            insert opp;
            
            // Create Applicant__c
            Applicant__c applicant = TestDataUtility.createTestApplicantForMFCValuation(true, opp);
            
            // Create Vehicle Detail
            Vehicle_Detail__c vehDet = TestDataUtility.createTestVehicleDetailForMFCValuation(true, opp);
            
            // Create Documents__c
            List<Documents__c> docList = new List<Documents__c>();
            Documents__c doc1 = TestDataUtility.createTestKYCDocsForOcrFront(false, applicant, opp);
            doc1.Document_Type__c = System.Label.AadhaarCard;
            doc1.Addresss_Type__c = System.Label.Document_Office_Address_Type;
            doc1.Aadhar_Source__c = 'OTP';   
            doc1.Opportunity_Relation__c = opp.Id;
            doc1.is_Active__c = true;
            docList.add(doc1);
            
            Documents__c doc2 = TestDataUtility.createTestKYCDocsForOcrFront(false, applicant, opp);
            doc2.Document_Type__c = System.Label.AadhaarCard;
            doc2.Addresss_Type__c = System.Label.Document_Office_Address_Type;
            doc2.Aadhar_Source__c = 'OTP';  
            doc2.Opportunity_Relation__c = opp.Id;
            doc2.is_Active__c = true;
            docList.add(doc2);
            insert docList;
            
            // Create Case
            Case cse = TestDataUtility.createTestCase(false, opp, applicant);
            cse.Type = System.Label.Case_Office_FI_Type;            
            insert cse;
            
            // Create Field Investigation
            Field_Investigation__c fiRecord = TestDataUtility.createTestFieldInvestigation(false, cse);
            fiRecord.FI_Feedback__c = '0';
            insert fiRecord;
        }
        System.runAs(u1) 
        {                            
            // Create Opportunity
            Opportunity opp1 = TestDataUtility.createTestOpportunityForOcr(false);         
            opp1.Sub_Stage__c = System.Label.Field_Investigation;
            opp1.Is_Mobile_Journey_Completed__c = true;
            opp1.Vehicle_Type__c = System.Label.used;
            opp1.Product_Type__c = System.Label.TwoWheeler;
            opp1.Sanction_Status__c = System.Label.nonStp;                     
            insert opp1;
            
            // Create Applicant__c
            Applicant__c applicant1 = TestDataUtility.createTestApplicantForMFCValuation(true, opp1);

            // Create Case
            Case cse = TestDataUtility.createTestCase(false, opp1, applicant1);
            cse.Type = System.Label.Case_Office_FI_Type;            
            insert cse;               
        }
        insert acTMList;
    }     
    
    @isTest 
    public static void UpdateFieldsOnConfirmationTest()
    {
        User u = [SELECT Id,usertype FROM User WHERE UserName='test_user@abc1.com' AND IsActive = true LIMIT 1];         
        System.runAs(u) 
        {
            try
            {                
                Case cse = [SELECT Id, OwnerId FROM Case WHERE OwnerId =: u.Id LIMIT 1];                
                Test.startTest();
                OffRollEmpApproval.UpdateFieldsOnConformation(cse.id);
                Test.stopTest();
                OffRollEmpApproval.UpdateFieldsOnConformation(null); 
                Case cseUpdated = [SELECT Id, Status, OwnerId FROM Case WHERE OwnerId =: u.Id LIMIT 1]; 
                System.assertEquals('Closed', cseUpdated.Status);
            }
            catch(Exception e)
            {
                System.assertEquals('Script-thrown exception', e.getMessage());
            }
        }        
    } 
    
    @isTest 
    public static void checkCaseTest()
    {
        User u = [SELECT Id,usertype FROM User WHERE UserName='test_user@abc1.com' AND IsActive = true LIMIT 1];         
        System.runAs(u) 
        {
            try
            {                
                Opportunity opp = [SELECT Id, OwnerId FROM Opportunity WHERE OwnerId =: u.Id LIMIT 1];                
                Test.startTest();
                Boolean result1 = OffRollEmpApproval.checkCase(opp.id);   
                Boolean result2 = OffRollEmpApproval.checkCase(null); 
                Test.stopTest();                     
                System.assertEquals(true, result1);
                System.assertEquals(false, result2);
            }
            catch(Exception e)
            {
                System.assertEquals('Script-thrown exception', e.getMessage());
            }
        }        
    } 
    
    @isTest 
    public static void createCaseTest1()
    {        
        User u = [SELECT Id,usertype FROM User WHERE UserName='test_userprod123987654735353@indusbank.com' AND IsActive = true LIMIT 1];
        Opportunity oppRec = [SELECT Id, ownerId, Vehicle_Type__c, Product_Type__c FROM Opportunity WHERE Vehicle_Type__c = 'Used' LIMIT 1];
        AccountTeamMember userMember = [SELECT Id, UserId, User.userType, TeamMemberRole FROM AccountTeamMember WHERE TeamMemberRole = 'PE' AND User.UserType != 'PowerPartner' AND User.isActive = true LIMIT 1];
        System.debug(u);
        System.runAs(u) 
        {
            try
            {                
                Test.startTest();
                OffRollEmpApproval.createCase(oppRec.Id,'Two Wheeler',oppRec.ownerId);
                Test.stopTest();
                userMember.TeamMemberRole = 'RPM';
                update userMember;
                OffRollEmpApproval.createCase(oppRec.Id,'Two Wheeler',oppRec.ownerId);
            }
            catch(Exception e)
            {
                System.assertEquals('Script-thrown exception', e.getMessage());
            }
        }        
    }
    
    @isTest 
    public static void createCaseTest2()
    {        
        User u = [SELECT Id,usertype FROM User WHERE UserName='test_userprod123987654735353@indusbank.com' AND IsActive = true LIMIT 1];
        Opportunity oppRec = [SELECT Id, Vehicle_Type__c,ownerId, Product_Type__c FROM Opportunity WHERE Vehicle_Type__c = 'Used' LIMIT 1];
        AccountTeamMember userMember = [SELECT Id, UserId, User.userType, TeamMemberRole FROM AccountTeamMember WHERE TeamMemberRole = 'PE' AND User.UserType != 'PowerPartner' AND User.isActive = true LIMIT 1];
        
        System.runAs(u) 
        {
            try
            {                
                Test.startTest();
                OffRollEmpApproval.createCase(oppRec.Id,'Passenger Vehicles',oppRec.ownerId);
                Test.stopTest();
                userMember.TeamMemberRole = 'SH';
                update userMember;
                OffRollEmpApproval.createCase(oppRec.Id,'Two Wheeler',oppRec.ownerId);
            }
            catch(Exception e)
            {
                System.assertEquals('Script-thrown exception', e.getMessage());
            }
        }        
    }
    
    @isTest 
    public static void createCaseTest3()
    {        
        User u = [SELECT Id,usertype FROM User WHERE UserName='test_userprod123987654735353@indusbank.com' AND IsActive = true LIMIT 1];
        Opportunity oppRec = [SELECT Id, Vehicle_Type__c,ownerId, Product_Type__c FROM Opportunity WHERE Vehicle_Type__c = 'Used' LIMIT 1];
        AccountTeamMember userMember = [SELECT Id, UserId, User.userType, TeamMemberRole FROM AccountTeamMember WHERE TeamMemberRole = 'PE' AND User.UserType != 'PowerPartner' AND User.isActive = true LIMIT 1];
        
        System.runAs(u) 
        {
            try
            {                
                Test.startTest();
                OffRollEmpApproval.createCase(oppRec.Id,'Tractor',oppRec.ownerId);
                Test.stopTest();
                userMember.TeamMemberRole = 'SH';
                update userMember;
                OffRollEmpApproval.createCase(oppRec.Id,'Two Wheeler',oppRec.ownerId);
            }
            catch(Exception e)
            {
                System.assertEquals('Script-thrown exception', e.getMessage());
            }
        }          
    }
         
}