ProdIND/ProdPrograms/force-app/main/default/objects/EMI_Schedule__c/EMI_Schedule__c.object-meta.xml
<CustomObject>
    <label>EMI Schedule</label>
    <nameField>
        <displayFormat>EMI-{000000}</displayFormat>
        <label>EMI Schedule Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>EMI Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/EMI_Schedule__c/fields/From_Month__c.field-meta.xml
<CustomField>
    <fullName>From_Month__c</fullName>
    <label>From Month</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/EMI_Schedule__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>EMI Schedules</relationshipLabel>
    <relationshipName>EMI_Schedules</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/EMI_Schedule__c/fields/Number_of_Installments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Installments__c</fullName>
    <label>Number of Installments</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/EMI_Schedule__c/fields/To_Month__c.field-meta.xml
<CustomField>
    <fullName>To_Month__c</fullName>
    <label>To Month</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/EMI_Schedule__c/fields/Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>Vehicle_Detail__c</referenceTo>
    <relationshipLabel>EMI Schedules</relationshipLabel>
    <relationshipName>EMI_Schedules</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/Final_Term__c.object-meta.xml
<CustomObject>
    <description>To store Final term module data.</description>
    <label>Final Term</label>
    <nameField>
        <displayFormat>FT-{000000}</displayFormat>
        <label>Final Term Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Final Terms</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan_Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Final_Terms</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Final_Term__c/fields/Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>Vehicle_Detail__c</referenceTo>
    <relationshipLabel>Final Terms</relationshipLabel>
    <relationshipName>Final_Terms</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/Loan_Application_Transaction_History__c.object-meta.xml
<CustomObject>
    <description>created for tackling lead assignments would be used.</description>
    <label>Loan Application Transaction History</label>
    <nameField>
        <label>Loan Application Transaction History</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Loan Application Transactions History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Loan_Application_Transaction_History__c/fields/Module__c.field-meta.xml
<CustomField>
    <fullName>Module__c</fullName>
    <description>Stage Name</description>
    <label>Module</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Structered_EMI__c/Structered_EMI__c.object-meta.xml
<CustomObject>
    <label>Structered EMI</label>
    <nameField>
        <displayFormat>Str-{00000}</displayFormat>
        <label>Structered EMI Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Structered EMIs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Structered_EMI__c/fields/From_Month__c.field-meta.xml
<CustomField>
    <fullName>From_Month__c</fullName>
    <label>From Month</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Structered_EMI__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Structered EMIs</relationshipLabel>
    <relationshipName>Structered_EMIs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Structered_EMI__c/fields/Number_of_Installments__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Installments__c</fullName>
    <label>Number of Installments</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Structered_EMI__c/fields/To_Month__c.field-meta.xml
<CustomField>
    <fullName>To_Month__c</fullName>
    <label>To Month</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Structered_EMI__c/fields/Vehicle_Detail__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vehicle Detail</label>
    <referenceTo>Vehicle_Detail__c</referenceTo>
    <relationshipLabel>Structered EMIs</relationshipLabel>
    <relationshipName>Structered_EMIs</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/Vehicle_Detail__c.object-meta.xml
<CustomObject>
    <label>Vehicle Detail</label>
    <nameField>
        <displayFormat>VD-{00000}</displayFormat>
        <label>Vehicle Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <description>Vehicle Insurance and Vehicle Valuation data</description>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipName>Vehicle_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/InstallmentScheduleControllerTest.cls
@isTest
private class InstallmentScheduleControllerTest {

    @isTest
    static void getRecentEMIdetailsTest() {
        Opportunity opp = new Opportunity();
            opp.Name = 'opptestone';
            opp.StageName = 'Loan Details';
            opp.CloseDate = Date.newInstance(2022, 1, 11);
            opp.Product_Type__c = 'Two Wheeler';
            insert opp;
         
            EMI_Schedule__c emisch = new EMI_Schedule__c();
            emisch.Loan_Application__c = opp.id;
            emisch.From_Month__c = 1;
            emisch.To_Month__c = 1;
            
            insert emisch;

            InstallmentScheduleController.getRecentEMIdetails(opp.id);
        
        Final_Term__c finalTerm = new Final_Term__c();
        finalTerm.Loan_Application__c = opp.id;
        insert finalTerm;

        InstallmentScheduleController.getFinalTermsLoandetails(opp.id);
        
        Structered_EMI__c struemi = new Structered_EMI__c();
        struemi.Number_of_Installments__c = 2;
        struemi.Loan_Application__c = opp.id;
        emisch.From_Month__c = 1;
        emisch.To_Month__c = 1;
        insert struemi;

        Loan_Application_Transaction_History__c loanHis = new Loan_Application_Transaction_History__c();
        loanHis.Name = 'Structured EMI';
        loanHis.Module__c = 'Post Sanction Checks and Documentation';
        insert loanHis;

        Vehicle_Detail__c vech = new Vehicle_Detail__c();
        vech.Loan_Application__c = opp.id;
        insert vech;


        InstallmentScheduleController.getFirstStructureEMI(opp.id);
        InstallmentScheduleController.calculateMonthlyPayment(20,10,10);
        InstallmentScheduleController.updateStructuredEMIDate(opp.id);
        InstallmentScheduleController.updateTransactionRecord(opp.id);
        List<Integer> sInt = new List<Integer>();
        sInt.add(2);
        sInt.add(2);
        sInt.add(2);
        sInt.add(2);

        InstallmentScheduleController.structuredEMIRepaymentSchedule(sInt,20.0,'10',date.today(),5,5,'1',date.today(),date.today(),false,opp.id);
        String str = '[{ "emiDueDate": "2024-09-19", "installmentNumber": "1", "installmentAmount": "5979.0", "openingPrincipal": "65000.0", "pricipalComponent": "5979.0", "interestComponent": "0.0", "closingPrincipal": "59021.0" }, { "emiDueDate": "2024-10-21", "installmentNumber": "2", "installmentAmount": "5979.0", "openingPrincipal": "59021.0", "pricipalComponent": "4833.93", "interestComponent": "1145.07", "closingPrincipal": "54187.07" }]';
        InstallmentScheduleController.saveInstallmentScheduleTractor(opp.id,str,'Structured',vech.id);
        InstallmentScheduleController.saveInstallmentSchedule(opp.id,str,'Structured');
        InstallmentScheduleController.emiRepaymentSchedule(20.0,'10',date.today(),5,5,'1',date.today()-1,date.today()-2,false,opp.id,2000);


    }
    @isTest
    static void getRecentEMIdetailsTestNeg() {

        Opportunity opp = new Opportunity();
        opp.Name = 'opptestone';
        opp.StageName = 'Loan Details';
        opp.CloseDate = Date.newInstance(2022, 1, 11);
        opp.Product_Type__c = 'Two Wheeler';
        insert opp;

        InstallmentScheduleController.emiRepaymentSchedule(20.0,'10',date.today(),5,5,'2',date.today()-1,date.today()-2,false,opp.id,2000);

    }
   
}