ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Application_Sequence_Number__c.field-meta.xml
<CustomField>
    <fullName>Application_Sequence_Number__c</fullName>
    <description>For generating application number sequence</description>
    <label>Application Sequence Number</label>
    <type>AutoNumber</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/System_Configuration__c/System_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to store system configurations</description>
    <label>System Configuration</label>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/System_Configuration__c/fields/Eligible_Roles_for_BE_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Roles_for_BE_Assignment__c</fullName>
    <label>Eligible Roles for BE Assignment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/System_Configuration__c/fields/Eligible_Roles_for_CS_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Roles_for_CS_Assignment__c</fullName>
    <label>Eligible Roles for CS Assignment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/System_Configuration__c/fields/Eligible_Roles_for_MA_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Roles_for_MA_Assignment__c</fullName>
    <label>Eligible Roles for MA Assignment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/System_Configuration__c/fields/Eligible_Roles_for_MO_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Roles_for_MO_Assignment__c</fullName>
    <label>Eligible Roles for MO Assignment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC - Copy/force-app/main/default/classes/Schedule_Application_Number_SequenceTest.cls
@isTest
public class Schedule_Application_Number_SequenceTest {
    
 /*   @isTest
    public static void testData(){
        System_Configuration__c sysConfig = new System_Configuration__c();
        sysConfig.Name = 'System Configuration';
        sysConfig.Eligible_Roles_for_BE_Assignment__c = 'BE,CS';
        sysConfig.Eligible_Roles_for_CS_Assignment__c = 'CS,MA';
        sysConfig.Eligible_Roles_for_MA_Assignment__c = 'MA,MO';
        sysConfig.Eligible_Roles_for_MO_Assignment__c = 'BE,CS,MA,MO';
        insert sysConfig;
        
        List<Opportunity> opList = new List<Opportunity>();
        
        Opportunity opl1 = new Opportunity();
        opl1.StageName = 'Qualification';
        opl1.CloseDate = System.today();
        opl1.Name = 'testname';
        //opl1.Application_Sequence_Number__c = '00165';
        insert opl1;
        opList.add(opl1);
        
        
        Schedule_Application_Number_Sequence sn1 = new Schedule_Application_Number_Sequence();
        string sn2 = '0 00 00 * * ?';
        Id jobId = System.schedule('LeadSeq', sn2, sn1);
        System.assert(jobId != null);
    } */
}