ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Lead_Number_Sequence__c.field-meta.xml
<CustomField>
    <fullName>Lead_Number_Sequence__c</fullName>
    <description>This sequence would be used to generate Lead Number suffix.</description>
    <label>Lead Number Sequence</label>
    <type>AutoNumber</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/System_Configuration__c/System_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This is used to store system configurations</description>
    <label>System Configuration</label>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/System_Configuration__c/fields/Application_Date__c.field-meta.xml
<CustomField>
    <fullName>Application_Date__c</fullName>
    <description>Date of application</description>
    <label>Application Date</label>
    <type>Date</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/System_Configuration__c/fields/Application_Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Application_Sequence_No__c</fullName>
    <defaultValue>00000</defaultValue>
    <description>For Apllication no.</description>
    <label>Application Sequence No</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/System_Configuration__c/fields/Eligible_Roles_for_BE_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Roles_for_BE_Assignment__c</fullName>
    <label>Eligible Roles for BE Assignment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/System_Configuration__c/fields/Eligible_Roles_for_CS_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Roles_for_CS_Assignment__c</fullName>
    <label>Eligible Roles for CS Assignment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/System_Configuration__c/fields/Eligible_Roles_for_MA_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Roles_for_MA_Assignment__c</fullName>
    <label>Eligible Roles for MA Assignment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/System_Configuration__c/fields/Eligible_Roles_for_MO_Assignment__c.field-meta.xml
<CustomField>
    <fullName>Eligible_Roles_for_MO_Assignment__c</fullName>
    <label>Eligible Roles for MO Assignment</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/System_Configuration__c/fields/Lead_Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>Lead_Sequence_No__c</fullName>
    <label>Lead Sequence No</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC - Copy/force-app/main/default/classes/UniqueLeadNumberHandler1Test.cls
@isTest
public class UniqueLeadNumberHandler1Test {
      @isTest
    public static void generateLeadnumberTest(){
         Opportunity opp = TestDataUtility.createTestOpportunity(false);
      //   opp.Lead_Number_Sequence__c = '00262';
            if (Schema.sObjectType.Opportunity.isCreateable()){
                insert opp;
            }
         System_Configuration__c seqNumber = New System_Configuration__c(Name='System Configuration',Application_Date__c	=Date.today(),Application_Sequence_No__c=6,Eligible_Roles_for_BE_Assignment__c='BE,CS',
                                                                       Eligible_Roles_for_CS_Assignment__c='CS,MA',Eligible_Roles_for_MA_Assignment__c='MA,MO',Eligible_Roles_for_MO_Assignment__c='BE,CS,MA,MO',
                                                                       Lead_Sequence_No__c='984935');
        Insert seqNumber;
          Map<Id, Opportunity> opMap = new Map<Id, Opportunity>();
          opMap.put(opp.Id,opp);
        
        Test.startTest();
              UniqueLeadNumberHandler1.generateLeadnumber(opMap);
        Test.stopTest();
    }
}