ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Vehicle_Type__c.field-meta.xml
<CustomField>
    <fullName>Vehicle_Type__c</fullName>
    <label>Vehicle Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/IND_ValidateRecentLeadRequestTest.cls
@isTest
public class IND_ValidateRecentLeadRequestTest {
    
    @isTest
    public static void verifyIND_ValidateRecentLeadRequest(){
        Opportunity opgd1 = new Opportunity();
        opgd1.StageName = 'Qualification';
        opgd1.CloseDate = Date.newInstance(2021, 1, 11);
        opgd1.Name = 'testone';
        opgd1.Product_Type__c = 'Two Wheeler';
        opgd1.Vehicle_Type__c = 'New';
        insert opgd1;
        
          IND_ValidateRecentLeadRequest result = new IND_ValidateRecentLeadRequest('sCICNo',  'sLeadNo',  opgd1.Id);
     //   Boolean isValid = result.validate(System.Label.ValidateRecentLead);
      //  System.assert(isValid);
        
          Map<String,String> resultHeadersMap = result.getHttpRequestHeaders();
     //   System.assert(!resultHeadersMap.isEmpty()); 
        
    }    
    
    
    
}