ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ALL</fullName>
            </value>
            <value>
                <fullName>Two Wheeler</fullName>
            </value>
            <value>
                <fullName>Passenger Vehicles</fullName>
            </value>
            <value>
                <fullName>C</fullName>
            </value>
            <value>
                <fullName>H</fullName>
            </value>
            <value>
                <fullName>Tractor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Vehicle_Detail__c/Vehicle_Detail__c.object-meta.xml
<CustomObject>
    <label>Vehicle Detail</label>
    <nameField>
        <displayFormat>VD-{00000}</displayFormat>
        <label>Vehicle Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicle Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/classes/IND_CombinedBERServiceTest.cls
@isTest
private class IND_CombinedBERServiceTest {
    
    @isTest
    static void testGetCombinedBreRequest(){
        Opportunity opp = TestDataUtility.createTestOpportunity(false);
        opp.Name = 'VDR Test';
        opp.Product_Type__c = 'Tractor';
        insert opp;
        Vehicle_Detail__c  vehicleDetail = TestDataUtility.createTestVehicleDetailForIbb(true, opp);
        
        Test.startTest();
        try {
            IND_CombinedBERRequest request = IND_CombinedBERService.getCombinedBreRequest(opp.Id, vehicleDetail.Id);
        } catch (IND_Exception ex) {
            System.assertNotEquals(null,ex.getMessage());
        }
        Test.stopTest();
    }
    
    @isTest
    static void testGetCombinedBreRequest1() {        
        Test.startTest();
        try {
            IND_CombinedBERService.getCombinedBreRequest(null, null);
        } catch (IND_Exception ex) {
            System.assertNotEquals(null,ex.getMessage());
        }
        Test.stopTest();
    }
    
    
}