ProdIND/ProdPrograms/force-app/main/default/objects/CAM__c/CAM__c.object-meta.xml
<CustomObject>
    <label>CAM</label>
    <nameField>
        <displayFormat>CAM-{00000000}</displayFormat>
        <label>CAM Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CAMS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/CAM__c/fields/BE_CVO_Remark__c.field-meta.xml
<CustomField>
    <fullName>BE_CVO_Remark__c</fullName>
    <description>Remark added by BE/CVO at the time of submitting the CAM.</description>
    <label>BE/CVO Remark</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/CAM__c/fields/Conditional_Approval__c.field-meta.xml
<CustomField>
    <fullName>Conditional_Approval__c</fullName>
    <description>Comments to be given at the time of Conditionally approving the proposal.</description>
    <label>Conditional Approval</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/CAM__c/fields/Loan_Application__c.field-meta.xml
<CustomField>
    <fullName>Loan_Application__c</fullName>
    <label>Loan Application</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>CAMS</relationshipLabel>
    <relationshipName>CAMS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/CAM__c/fields/Proposal_Status__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Status__c</fullName>
    <description>Final Approval Status (possible values Accept, Reject and Withdrawn)</description>
    <label>Proposal Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Accept</fullName>
            </value>
            <value>
                <fullName>Reject</fullName>
            </value>
            <value>
                <fullName>Withdrawn</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deviation__c/Deviation__c.object-meta.xml
<CustomObject>
    <label>Deviation</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Deviation No.</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deviations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Deviation__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Conditionally Approve</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deviation__c/fields/Deviation_Description__c.field-meta.xml
<CustomField>
    <fullName>Deviation_Description__c</fullName>
    <description>To be retrieved from FICO engine</description>
    <label>Deviation Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deviation__c/fields/Deviation_Level__c.field-meta.xml
<CustomField>
    <fullName>Deviation_Level__c</fullName>
    <description>To be retrieved from FICO engine</description>
    <label>Deviation Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deviation__c/fields/Parent_CAM__c.field-meta.xml
<CustomField>
    <fullName>Parent_CAM__c</fullName>
    <label>Parent CAM</label>
    <referenceTo>CAM__c</referenceTo>
    <relationshipLabel>Deviations</relationshipLabel>
    <relationshipName>Deviations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deviation__c/fields/Proposal_Status__c.field-meta.xml
<CustomField>
    <fullName>Proposal_Status__c</fullName>
    <label>Proposal Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Hold</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Conditional Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Deviation__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <description>Comma separated values for roles for which Deviation will be triggered</description>
    <label>Role</label>
    <type>TextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Opportunity/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Not Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Proposal_Approval_Log__c/Proposal_Approval_Log__c.object-meta.xml
<CustomObject>
    <label>Proposal Approval Log</label>
    <nameField>
        <label>Proposal Approval Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Proposal Approval Logs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

ProdIND/ProdPrograms/force-app/main/default/objects/Proposal_Approval_Log__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <label>Approval Status</label>
    <type>TextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Proposal_Approval_Log__c/fields/Deviation_Id__c.field-meta.xml
<CustomField>
    <fullName>Deviation_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Deviation Id</label>
    <referenceTo>Deviation__c</referenceTo>
    <relationshipLabel>Proposal Approval Logs</relationshipLabel>
    <relationshipName>Proposal_Approval_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Proposal_Approval_Log__c/fields/Forward_Remark__c.field-meta.xml
<CustomField>
    <fullName>Forward_Remark__c</fullName>
    <label>Forward Remark</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Proposal_Approval_Log__c/fields/Forwarded_By__c.field-meta.xml
<CustomField>
    <fullName>Forwarded_By__c</fullName>
    <label>Forwarded By</label>
    <type>TextArea</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Proposal_Approval_Log__c/fields/Parent_CAM__c.field-meta.xml
<CustomField>
    <fullName>Parent_CAM__c</fullName>
    <label>Parent CAM</label>
    <referenceTo>CAM__c</referenceTo>
    <relationshipLabel>Proposal Approval Logs</relationshipLabel>
    <relationshipName>Proposal_Approval_Logs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

ProdIND/ProdPrograms/force-app/main/default/objects/Proposal_Approval_Log__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

ProdIND/ProdLWC/force-app/main/default/classes/ApprovalProposalControllerTest.cls
@isTest
public class ApprovalProposalControllerTest {
    @isTest
    public static void getProposalTest(){
        Test.startTest();
             ApprovalProposalController.getProposal();
        Test.stopTest();
    }
    
    @isTest
    public static void updateProposalRecordsTest(){
        
        Opportunity opdo1 = new Opportunity();
        opdo1.StageName = 'Qualification';
        opdo1.CloseDate = Date.newInstance(2021, 1, 11);
        opdo1.Name = 'testone';
        insert opdo1;
        
        CAM__c cam1 = new CAM__c();
        cam1.Loan_Application__c = opdo1.Id;
        cam1.BE_CVO_Remark__c = 'testbe';
        cam1.Conditional_Approval__c = 'testapprov';
    //    cam1.Proposal_Status__c = 'testproposal';
        insert cam1;
        
        Deviation__c dv1 = new Deviation__c();
        dv1.Parent_CAM__c = cam1.Id;
        dv1.Deviation_Description__c = 'testdesc';
        dv1.Deviation_Level__c = 'testlevel';
        dv1.Role__c = 'testrole';
        insert dv1;
        
        Proposal_Approval_Log__c pa1 = new Proposal_Approval_Log__c();
        pa1.Deviation_Id__c = dv1.Id;
        pa1.Parent_CAM__c = cam1.Id;
        pa1.Approval_Status__c = 'proaprv';
        pa1.Forward_Remark__c = 'testremark';
        pa1.Forwarded_By__c = 'testuser';
        insert pa1;
        
        Map<Id,Proposal_Approval_Log__c> mapVal = new Map<Id,Proposal_Approval_Log__c>();
        mapVal.put(pa1.Id,pa1);
        
        Test.startTest();
            // ApprovalProposalController.updateProposalRecords(JSON.serialize(mapVal));
        Test.stopTest();
    }
    
        @isTest
    public static void updateProposalRecordsTestNegative(){
        Opportunity opdo1 = new Opportunity();
        opdo1.StageName = 'Qualification';
        opdo1.CloseDate = Date.newInstance(2021, 1, 11);
        opdo1.Name = 'testone';
        insert opdo1;
        
        CAM__c cam1 = new CAM__c();
        cam1.Loan_Application__c = opdo1.Id;
        cam1.BE_CVO_Remark__c = 'testbe';
        cam1.Conditional_Approval__c = 'testapprov';
        cam1.Proposal_Status__c = 'testproposal';
        insert cam1;
        
        Deviation__c dv1 = new Deviation__c();
        dv1.Parent_CAM__c = cam1.Id;
        dv1.Deviation_Description__c = 'testdesc';
        dv1.Deviation_Level__c = 'testlevel';
        dv1.Role__c = 'testrole';
        insert dv1;
        
        Proposal_Approval_Log__c pa1 = new Proposal_Approval_Log__c();
        pa1.Deviation_Id__c = dv1.Id;
        pa1.Parent_CAM__c = cam1.Id;
        pa1.Approval_Status__c = 'proaprv';
        pa1.Forward_Remark__c = 'testremark';
        pa1.Forwarded_By__c = 'testuser';
        insert pa1;
        pa1.Id = null;
        
        Map<Id,Proposal_Approval_Log__c> mapVal = new Map<Id,Proposal_Approval_Log__c>();
        mapVal.put(pa1.Id,pa1);
        Test.startTest();
        String result = ApprovalProposalController.updateProposalRecords(new List<Proposal_Approval_Log__c>{pa1});
        System.assert(result.contains('The following exception has occurred'));
        Test.stopTest();
    }
    
    
    
    
    
    
    
}